### ISSUE TITLE
Question: Slim symbols assigned from fixture code are not expanded in wiki

### ISSUE THREAD

**Issue by tcnh** [unclebob/fitnesse#1007]
When setting a symbol by calling the assign() method on the StatementExecutorInterface, a symbol is added and I can use it in my tests. The wiki however, doesn't expand these symbols when a test has run.

![image](https://cloud.githubusercontent.com/assets/2232710/21640875/65620e74-d278-11e6-98f9-c8b1cc0b8b58.png)

Expected: $someSymbol to be displayed as: $someSymbol->[symbol value]

Any thoughts/suggestions? I seem to lack understanding of how the wiki and Slim cooperate. :)
Tried to use callAndAssign, but to no avail.

Context: The example above was just created to illustrate. The actual use case is a situation where large amounts of data objects are maintained in external files. We use a fixture to set the required values to symbols on a per-testcase basis, so we can use them in our tests, without the need to create large test data pages that become hard to read and maintain.
For better readability, displaying the actual symbol value would help.

**Comment by six42** [comment]
Hi Tom,

Using the script table you have already you can do:

| set symbol|someSymbol| with value| symbol value|
| $someSymbol=| value of|$someSymbol|

Any further usage of $someSymbol would then dispay as you like it.
Not nice.
 But otherwise this is not possible.

**Comment by tcnh** [comment]
Hi six42, 

This I know; The example was created to illustrate what happens. That's why I gave some context. Setting all variables by wiki pages in our situation is not viable, so I created a fixture that is able to set these slim symbols from code. We can now use this to dynamically set symbols in bulk from a file or database.

I'm trying to understand why this happens to see if I can create a fix or workaround. Either in my fixture or in fitNesse,

**Comment by ggramlich** [comment]
Hi tcnh,

as far as I understand, you are setting the value on the SLIM Executor side and not on the SLIM Runner side of the image
http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.TestSystems
The package `fitnesse.slim` refers to the SLIM Executor side, whereas the package `fitnesse.testsystems.slim` refers to the SLIM Runner side.

In order to have the symbol visible on the test page, its value must have crossed the process boundary.

**Comment by tcnh** [comment]
Thnx for the pointer!
