### ISSUE TITLE
How to get number of tests inside testsuite before running the suite

### ISSUE THREAD

**Issue by YogiKhan** [unclebob/fitnesse#1009]
Is there any way to get number of tests inside a testsuite before running the suite.

I know we can get it from pagehistory but i don't want to run the tests and get it from pagehistory.

Any help would be helpful

**Comment by keetron** [comment]
Hi YogiKhan,

Not sure if I understand the question. You mean generate a testsuite on the fly based on a random amount of available cases, running only the failed cases or a selected set of cases from a suit?
Neither of the above is possible in the current wiki.

What we do to run tests partially is with Jenkins, first run one suite and only if it is succesful, run the other suites. If your suites make sense, you can do smart stuff with this. For more details, check out Jenkins at https://jenkins.io

**Comment by YogiKhan** [comment]
@keetron  i was able to get all the list of tests inside a suites..Thanks
