### ISSUE TITLE
Fitnesse/SLiM handshake fails when using stdio

### ISSUE THREAD

**Issue by racarey** [unclebob/fitnesse#1010]
I am pretty new to Fitnesse.  Our test team recently upgraded Fitnesse to v20161106.  When they try to connect to the server via Remote Debug using the default port (which I gather is “1” meaning to use stdin/stdout for communication between fitnesse and slim) the handshake fails.

     [java] Connected to host: localhost on port: 1 timeout setting: 25
     [java] Read Slim Header: >Listening for transport dt_socket at address: 8000<

It looks like Fitnesse is expecting to see something like “Slim -- V0.5” in stdin, but instead is reading the message displayed when a java process is run with the –Xrunjdwp option.

Are we doing something wrong that is causing this?

**Comment by amolenaar** [comment]
Nice catch! It looks like we have not thought of this scenario :) As a workaround you an set the port number to something high (typically 8085), which will establish a connection over TCP.

**Comment by fhoeben** [comment]
As a workaround I suggest you set the `slim.port` number to 0, which will cause a free port to be automatically selected (instead of requiring you to hardcode a port number which must be free).
