### ISSUE TITLE
Renderer throws exception on unclosed variable definition in version 20161106

### ISSUE THREAD

**Issue by madjo80** [unclebob/fitnesse#1015]
When I define a variable, but forget the closing tag, the renderer throws an exception and Fitnesse offers a yellow screen.

for instance, I have this in my script:

`   !define var_Variable {some value`
(note the lack of } )

and when I press save, I get this error message:

`org.apache.velocity.exception.MethodInvocationException: Invocation of method 'render' in  class fitnesse.responders.WikiPageResponder$WikiTestPageRenderer threw exception java.lang.StackOverflowError at wikiPage.vm[line 1, column 10]`

This error message disappears when you properly close your variable.

**Comment by woodybrood** [comment]
This doesn't seem to be happening any longer.
