### ISSUE TITLE
Migration from v20160618 to v20161106 => "Page doesn't exist. Edit FrontPage"

### ISSUE THREAD

**Issue by staniere** [unclebob/fitnesse#1020]
Hello, 
I tried migration to last official version 20161106 and I encounter an odd thing : 
when going to http://localhost:8102/FrontPage, it display frontpage in edit mode, as if content.txt was not existing (but it exists on disk !)

In internet explorer tab, it is written "Page doesn't exist. Edit FrontPage" and wiki is open. 
Every pages are open in this wiki mode. 

I tried the last build #1033 and it has the same behavior than official release. 
I tried to see http://localhost:8102/FrontPage on internet explorer 11 and on firefox 50.1.0 but have same behavior. 

Here is dos console when launching fitnesse-standalone.jar : 

```
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance test
ing framework.
root page: fitnesse.wiki.fs.ExternalSuitePage: FitNesseRoot
logger: none
authenticator: fitnesse.authentication.MultiUserAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Unpacking new version of FitNesse resources. Please be patient...
**********************************************************
Files have been updated to a new version.
Please read the release notes on
http://localhost:8102/FitNesse.ReleaseNotes
to find out about the new features and fixes.
**********************************************************
Starting FitNesse on port: 8102
WARNING: An error occured while fulfilling user request [fitnesse.http.HttpExcep
tion: The request string is malformed and can not be parsed]
java.util.concurrent.ExecutionException: fitnesse.http.HttpException: The reques
t string is malformed and can not be parsed
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:105)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: fitnesse.http.HttpException: The request string is malformed and can
not be parsed
        at fitnesse.http.Request.checkRequestLine(Request.java:159)
        at fitnesse.http.Request.readAndParseRequestLine(Request.java:73)
        at fitnesse.http.Request.parse(Request.java:61)
        at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:102)
        at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:99)
        ... 4 more


```

Say me if you need more elements to analyse. 

Sebastien

**Comment by staniere** [comment]
In fact, it seem that error in dos console "The request string is malformed and can not be parsed]" is not displayed every time. So I am not sure it has a link with the "page doesn't exist" bug.

**Comment by keetron** [comment]
Hi Sebastien,

Check https://github.com/unclebob/fitnesse/issues/999 and see if that resolves your problem. Not recognizing content sounds about the same.

Gr,
Koen

**Comment by staniere** [comment]
Hello, 
thank you for your suggestion but I think there is no link with this issue #999. 

Indeed, current pages on my desktop are at the old format (content.txt + properties.xml)
I tried to replace CRr+LF line endings by LF in both files, but behavior does not change. 

This behavior is not coming from an update or a merge from svn. 
When migrating back to fitnesse v20160618, frontpage becomes available again. 

For information, I do not use git but subversion, on a Windows 7 desktop. 

Sincerely,
Sebastien

**Comment by keetron** [comment]
Ok, I was wrong. Hope some else has a suggestion?

Op 19 jan. 2017 2:04 p.m. schreef "Sébastien TANIERE" <
notifications@github.com>:

**Comment by keetron** [comment]
So now we are a few weeks further, I run into the same issue when wanting to migrate another project. I know we have it solved on some projects already but I am curious how you solved it yourself.
Of course I will post my solution as soon as I figure it out.

**Comment by fhoeben** [comment]
Might be related to #987 ?

**Comment by keetron** [comment]
Absolutely related, it was fixed right away when I ditched those .htmls in the folder pagesources, it is committed and uploaded to the testserver now and tomorrow I'll check if everything still operates as expected.

This is to migrate fully, by renaming the suite and somehow all it's children are saves in the new .wiki format. (this is a hidden feature)

I hope @staniere is still reading this.

**Comment by staniere** [comment]
Hello, 
thank you for your analysis, it is a great gift for me when coming back from holidays :)

I did not solved anything on my server for the moment (not time for that) and i am still in version v20160618. 

-some html are test results generated by hudson (\FitNesseRoot\files\Report\Report.html)
-some static htm pages have been put by myself for easier documentation in fitnesse server (and it would be great to be allowed to keep it !)

I tested without .htm files and fitnesse v20161106 is working ok !
**so I confirm that this is linked to #987.**

**Comment by fhoeben** [comment]
What I did for my .html files was rename them to .HTML (looks ugly, but works), I expect .htm would have been fine also...

**Comment by staniere** [comment]
it seem also that when restoring .htm files after migrating version from v20160618 to v20161106, fitnesse does not produce message "Page doesn't exist" again.

**Comment by fhoeben** [comment]
What do you mean exactly with restoring? What happens if you restart fitnesse?

**Comment by staniere** [comment]
i deleted htm files and put the new fitnesse_standalone in my folder
then i opened http://localhost in my browser and was able to see my FrontPage
then i restored my htm files with svn and FrontPage was still available
then i closed standalone and launched it again,  and FrontPage is still available

**Comment by fhoeben** [comment]
Interesting. I really noticed that each time I added a single .html below my 'files' directory all page reloads in the wiki failed.

**Comment by staniere** [comment]
ok you are right, it is because i did not restored every files. 
those with .htm does not have impact
but those with .html extension have an impact
