### ISSUE TITLE
Is there any limit set or Thread limit for the parallel execution of tests

### ISSUE THREAD

**Issue by YogiKhan** [unclebob/fitnesse#1022]
Hi ,

I have written a utility to run the tests in parallel to optimize the timings and when i ran more than 30 tests in parallel, i get connection refused error.

Is there any limit set of Thread limit for parallel execution of tests inside fitnesse?

If yes, is it configurable?

**Comment by amolenaar** [comment]
Hi,

This question would be better answered at our mailing list: fitnesse@yahoogroups.com.

There is a limit on the number of (web) request that can be handled. The values are currently hard coded (https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/FitNesse.java#L41). Feel free to send a PR :)
