### ISSUE TITLE
Is there way we can run same test for several set of test data 

### ISSUE THREAD

**Issue by sumedha1101** [unclebob/fitnesse#1027]
Lets think I have a test case to as follow
1 . Send a xml with varies data to an end point "PersistanceFixture.java"
2 . Based on the variable in xml of first step I'm validation states "Through dbfit"
3. Then I need to send another request with json to change some data in my first request "AmendFixture.java"
4. Validate some states through "dbfit"

for each of these step need to set up test data. At the moment we tend to create multiple wikis with these steps just because need to change input test data.
Is there anyway we can have all input data outside and run the same wiki for the number of different set of data set rather than creating multiple wikis. Like iterate same wiki (that define the steps ) for different set of data

**Comment by amolenaar** [comment]
Hi,

You'd better send your question to the FitNesse mailinglist: fitnesse@yahoogroups.com.

Multiple wiki's work. You could use a scenario table and a decision table. Key here is readability.
