### ISSUE TITLE
Mail notification after test execution using authentication login.

### ISSUE THREAD

**Issue by ahennar** [unclebob/fitnesse#1028]
Hello, I am looking for variable which value contains user login. Authentication is configured and works. I tried to check USER var but it gives me root. Is it a way to send a mail via fitness features or how can I get user login?

**Comment by amolenaar** [comment]
Hi,

You're probably better off sending this message to the FitNesse mailing list: fitnesse@yahoogroups.com.

To answer your question: there's no variable in FitNesse that you can use to print the user on a wiki page (I suppose that's your intent?).

**Comment by ahennar** [comment]
Could I also ask is there any documentation for writing user plugins?
