### ISSUE TITLE
Question: Fit Fixture !define calling a function

### ISSUE THREAD

**Issue by JeremyCarlsten** [unclebob/fitnesse#1031]
I have been tinkering with the idea of running my fitnesse tests in parallel, in fact I've managed to do it at a suite level using the junit runner. The next problem I was needing to solve is the data setup. Most of our tests run based off of a unique person id. I was hoping to use the [hsac-fitnesse-plugin](https://github.com/fhoeben/hsac-fitnesse-plugin) to randomly generate that personId for the individual suites(yes I know it will occasionally clash), and eventually migrate to tests. I ran into a problem with the !define calling the !randomBSN function each time I ask for the personId giving me a new id each time.  
```
!define personId { !randomBSN }

|setup data|
|create person with Id|$personId| 

|some fixture|
|search for|$personId| # not the same as setup
 ```

([Link To plugin Issue](https://github.com/fhoeben/hsac-fitnesse-plugin/issues/10)) 
The response I got from the plugin creator was to use a slim echo fixture to store off the value 
```
|script|echo fixture|
|$personId=|echo|!randomBSN|

|setup data|
|create person with Id|$personId|

|some fixture|
|search `for|$personId|
```

Is there anyway to recreate this in fit fixtures?

**Comment by woodybrood** [comment]
This is a late answer, but I think FitLibrary can offer something similar. https://sourceforge.net/projects/fitlibrary/
