### ISSUE TITLE
One way SSL configuration question

### ISSUE THREAD

**Issue by garyodonoghue** [unclebob/fitnesse#1032]
Hi, 

I was following [this guide](http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.AdministeringFitNesse.NetworkSecurity) on how to setup SSL in order to test a https protected endpoint, but still haven't had any joy. 

Im trying to run tests, whereby I am running Fitnesse locally but aiming to execute requests against a remote webservice. 
I have a truststore, for a corresponding internal HTTPS protected webservice, provided by my company which I have in a local directory. 
I have extended the SslParameters, creating a class - com.myapp.appium.CustomSslParams, and specified the location of the truststore within the class. This is available on my classpath. 

I have also modified the plugins.properties, adding the following entry - "slim.ssl=com.myapp.appium.CustomSslParams"

Fitnesse starts fine with the following command:
java -jar fitnesse-standalone.jar -p 8082", however when i click 'Test' to execute a test, it gives the following output:

"Trying to connect to host: localhost on port: 8085 SSL=true ..." and then prints a series of "Creating SSL client: localhost:8085" messages

The Fitnesse page shows a warning - "Unable to start test system 'slim': fitnesse.slim.SlimError:Error connecting to SLiM server on localhost:8085"

It seems that Fitnesse is trying to communicate securely (on port 8085) with Slim server, but all I want is to be able to tell Fitnesse is how to communicate securely with a remote webservice. Is it possible to detach these settings? 

Fitnesse version: Release v20160515
Slim v0.4
Any help would be appreciated, thanks in advance!

**Comment by JeremyCarlsten** [comment]
Is the 'Slim server' separate from the Fitnesse Jar? 
I don't use much slim we mostly use Fit and it's just included in the jar and it looks like you've started your jar on 8082. 

Have you tried using a tool like [fiddler](http://www.telerik.com/fiddler) to watch the requests?

**Comment by garyodonoghue** [comment]
As far as I understand it fitnesse will start the SLiM server. I'm starting my fitnesse-standalone jar on 8082, and in turn, Fitnesse tries to start the SLiM server on 8085. If I dont enable specify "slim.ssl" in the plugins.properties file, then Fitnesse will start the SLiM server on 8085, but will do so successfully, and is able to get the SLiM version back and everything, with the below output. The issue appears to be trying to create the SLiM server with SSL=true, it just prints out a load of "Creating SSL client: localhost:8085" messages without ever getting the SLiM version back 

Trying to connect to host: localhost on port: 8085 SSL=false timeout setting: 10
Creating plain client: localhost:8085
Creating plain client: localhost:8085
Creating plain client: localhost:8085
Creating plain client: localhost:8085
Connected to host: localhost on port: 8085 SSL=false timeout setting: 10
Read Slim Header: >Slim -- V0.4<
Got Slim Header: Slim -- V0.4, and Version 0.4

**Comment by six42** [comment]
Hi,

' but all I want is to be able to tell Fitnesse is how to communicate securely with a remote webservice.'

You don't need to configure anything described in the guide you refer to to communicate with a webservice.
The communication to the webservice must be done by your fixture code. And in your fixture code you have to configure SSL.

I can' t tell you how to do this as I don't know your fixture.

**Comment by garyodonoghue** [comment]
Would you have example of this setup or is there one available anywhere? I had tried starting Fitnesse, passing in a system property to define the location of the truststore, I.e -Djava.net.ssl.truststore=path_to_my_truststoree but, expecting Fitnesse to check this property when making a secure call, but it seems to ignore it, it seems odd to me that you would have to explicitly declare it within fixture code

**Comment by six42** [comment]
The FitNesse framework has no feature to connect to a webservice!

You need an extension, plugin or fixture to do so.
How do you call your webservice? Where do you configure the port and IP? There you have to configure SSL as well.

**Comment by garyodonoghue** [comment]
Thanks @six42 , in the end it was a case of modifying the truststore within JAVA_HOME/jre/lib/security, as Java will look here by default for truststores when establishing an SSL connection, I had tried passing the location of the truststore when starting Fitnesse, using the -Djavax.net.ssl.trustStore='path to truststore', but it seems then that property is not propagated to the SLiM server, and it is this component which is actually doing the handling the SSL communication, and so it was unaware of this files location and throwing the error. Closing this issue
