### ISSUE TITLE
Question: Can you execute Slim Test on a remote host (away from the Fitnesse web server?)

### ISSUE THREAD

**Issue by bzon** [unclebob/fitnesse#1038]
By default you Fitnesse run its test Locally.

Can I run test on a remote host? If yes, I need a simple reference on how to do it.

 I'm using Slim type fixtures. Thanks!

**Comment by keetron** [comment]
We have a setup where we run our tests remote using FitNesse in a Jenkins configuration that will point towards a Selenium Grid for the test execution. All tests are build on my local machine, submitted to Git where it is picked up by Jenkins, that will build and execute the testset on a defined environment using a remote Selenium Grid setup to enable us to test cross platform and cross machine.

So read up on Jenkins and Selenium Grid if you want to do what you ask.

I found you some links:
Jenkins in FitNesse: https://wiki.jenkins-ci.org/display/JENKINS/FitNesse+Plugin
Jenkins with Git: https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin
Selenium Grid2: https://github.com/SeleniumHQ/selenium/wiki/Grid2

Everything considerd, when setting all the above up, you are super close to CI!

**Comment by bzon** [comment]
@keetron The title seems misleading so I changed it. The tests that I want to run on a remote host are not for browser testing. What I want is for the Fitnesse Web Server to act as a Master host so that when I execute tests on a remote Slim host, results are persisted on the Master host.

**Comment by keetron** [comment]
Can't help you with that, although when looking at the current FitNesse architecture it could be possible.
May I ask you what the goal is you are trying to achieve?

**Comment by bzon** [comment]
To ensure highly available SUT and abstract the web server from running the test. It's not a big issue but is nice to have :) I'm can think of some workaround to do it but I want to know first if fitnesse slim support it out of the box.

**Comment by fhoeben** [comment]
Yes slim does support that out of the box, see http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM, the parts about the `slim.host` and `slim.port` properties. You can use these to connect your master to remote host, where you will have to start the slim manually. 

I tend to use a CI server (e.g. Jenkins, TeamCity or Bamboo) to persist test results, and have all my fixtures connect remotely to the SUT (so the cross process/host communication is done by the fixtures to SUT and not between wiki and Slim server).

**Comment by bzon** [comment]
@fhoeben Thanks, does this mean that changing the value of the slim.host will have fitnesse connect to it using the slim.port TCP/UDP and use that host like a jenkins slave?

I will have to try that!
