### ISSUE TITLE
Hiding first row with -! causes later markup to not be interpretted

### ISSUE THREAD

**Issue by brucetrask** [unclebob/fitnesse#1039]
The following table
|!-MyColumnFixture-!|
|'''col1'''|'''col2'''|
|1|2|

properly results in
![colfixtureprob](https://cloud.githubusercontent.com/assets/10885119/23399351/3c94298e-fda0-11e6-91f7-75811cc09827.PNG)

but
-!|!-MyColumnFixture-!|
|'''col1'''|'''col2'''|
|1|2|

results improperly in

![colfixtureprob2](https://cloud.githubusercontent.com/assets/10885119/23399406/61998242-fda0-11e6-886f-1c6b3ced49ca.PNG)

**Comment by ggramlich** [comment]
That is correct, because the ! prevents interpretation of the markup.
Try only - for the first row.

**Comment by brucetrask** [comment]
Ah right you are. Thanks. I had that wrong. - works just fine.
