### ISSUE TITLE
fitnesse-slim-server-fails-to-start-using-eclipse

### ISSUE THREAD

**Issue by JohnWDawson** [unclebob/fitnesse#1040]
I'm trying to get a very basic Fitnesse test to run; using Fitnesse / Slim; Java in Eclipse.

Test runs, or at least starts, but doesn't finish; get this error "Unable to start test system 'slim': fitnesse.slim.SlimError: Error SLiM server died before a connection could be established. JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]"

Fitnesse test is:

!define TEST_SYSTEM {slim} !path: C:\Users\\EclipseWorkspace\CalculatorProject | import | packageCalculator | | TestCalculator | | operand | result? | | 4 | 8 | | 2 | 4 | | 7 | 14 | | 2 | 4 |

This is a similar issue: Fitnesse: SLiM server died before a connection could be established; suggests this might be a regression bug; but I tried earlier versions of fitnesse, which made no difference

And it's not this one either: https://github.com/unclebob/fitnesse/issues/726; there is no space in the classpath

Help!!!

**Comment by six42** [comment]
Hi John

Does the test work without the debug option?
Do the solutions proposed in #1010 work?
If not it is likely a general  network problem.
Google for the error message ' JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197)'
and try one of the solutions.

Six42

**Comment by JohnWDawson** [comment]
1. Didn't use the debug option, at least not this time
2. #1010 mostly refers to using ports already in use; I've tried a few different ports, to no avail
3. Can you expand on "general  network problem" - tks

**Comment by six42** [comment]
Strange that it runs with debug. This is not the default behaviour. You say you ' fails-to-start-using-eclipse'.
What do you mean by 'using eclipse'?
If you use a fresh install and go on the wiki page and run the two minute example by pressing the test button. Does it pass? Is it also started with debug?


Did you tried a different port as below?

!define TEST_SYSTEM {slim} 
!define slim.port {0} 
!path C:\Users\EclipseWorkspace\CalculatorProject 
| import | packageCalculator | 
| TestCalculator | 
| operand | result? | 
| 4 | 8 | | 2 | 4 | | 7 | 14 | | 2 | 4 |
