### ISSUE TITLE
Fitnesse remote debug not connecting after upgrading to 20161106

### ISSUE THREAD

**Issue by chrisdlangham** [unclebob/fitnesse#1041]
I have been using fitnesse for a while now. I recently upgraded my fitnesse version to 20161106. Now I am not able to remote debug. I get this error when I click on "Remote Debug".

`Unable to start test system 'slim': fitnesse.slim.SlimError: Got invalid slim header from client. Read the following: Listening for transport dt_socket at address: 5015`

Here is my REMOTE_DEBUG_COMMAND variable, that worked in the 20160618 fitnesse version.

`!define REMOTE_DEBUG_COMMAND {java -XX:MaxPermSize=512m -XX:-UseSplitVerifier -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5015 %m}`

Am I doing something wrong? I am thinking I am missing a parameter that the new version expects.

**Comment by six42** [comment]
Look at the solution given in #1010

**Comment by chrisdlangham** [comment]
Defining slim.port to 0 did it!

**Comment by six42** [comment]
:)
