### ISSUE TITLE
Is the DoFixture available in the fitnesse_standalone.jar?

### ISSUE THREAD

**Issue by Semard** [unclebob/fitnesse#1044]
Hi,

We are using the DoFixture and it serves us very well. We have understood that the DoFixture is part of the extracted fitnesse-standalone.jar installation. Is this true, and if so, how can we access it? We cannot find any FitLibrary.jar-file from the selfextracting fitnesse-standalone installation.

The code is as follows:
package core;
import fitlibrary.DoFixture;
import fitlibrary.runtime.*;
import fitlibrary.traverse.CommentTraverse;

We are using gradle.
When we download FitLibrary.jar seperately and use it as a referenced library, it works. Today we use both fitnesse-standalone.jar and FitLibrary.jar. We would like to remove the separately downloaded FitLibrary.jar if possible.

We tried to use "import fitnesse.fixtures.DoFixture" with the hope that the DoFixture would be part of the fitnesse-standalone.jar, but we could not find it. From the self extracting fitnesse-standalone installation, the user guide list the DoFixture as a valid fixture but there is no information of where it can be found.

Regards
Semard

**Comment by jediwhale** [comment]
DoFixture and the other FitLibrary fixtures are not part of the FitNesse 
installation.  They are maintained and distributed by a separate group 
of open source volunteers.

**Comment by Semard** [comment]
Hi,
Thanks for the information!
Semard
