### ISSUE TITLE
FitNesse terminating connection if run exceeds 1 minute

### ISSUE THREAD

**Issue by ramfree17** [unclebob/fitnesse#1045]
I have posted my question in the [mailing list](https://groups.yahoo.com/neo/groups/fitnesse/conversations/messages/21728 ) but never got any response. The gist is that if the called test runs for more than 60 seconds the server terminates the connection. The sample error follows, after trying curl options to go beyond the 1 minute cut-off time:

> /usr/bin/time curl -k --keepalive-time 300 --ignore-content-length > "https://$USERNAME:$PASSWORD@.../fitnesse/SystemIntegrationTestWrapper.PrepareServices?responder=test&format=xml"
> curl: (18) transfer closed with outstanding read data remaining
> Command exited with non-zero status 18

> 0.07user 0.32system 1:01.56elapsed`

I don't see an option to specify timeouts in the command line arguments wiki. Is there any way to have the timeout extended for our long running test activities (3-10 minutes)? Or is there a way to invoke backends (via REST) in parallel to shorten the time to process a list of parameterized but individual requests so they do not reach the 1 minute timeout?

Thanks.

**Comment by fhoeben** [comment]
Are you sure its FitNesse that terminates the connection (and not curl). I've never had problems with test exceeding one minute, and I have quite a few of those. Although I run my tests either from the wiki with a browser or via Maven using the jUnit `FitNesseRunner`.

Try adding `--connect-timeout` and `--max-time` to the curl command. See https://unix.stackexchange.com/questions/94604/does-curl-have-a-timeout/94612#answer-94612
