### ISSUE TITLE
Suggestion appears to create a page when it used in slim table cells

### ISSUE THREAD

**Issue by ahennar** [unclebob/fitnesse#1047]
Moreover, It changes the cell content (it adds `<a title="create page" href="FrontPage.S9902V1?edit&amp;nonExistent=true">[?]</a>` for "S9902V1" original cell content). As a temporary workaround I have to preparse cells before using it in our tests. How can I disable this feature?

**Comment by keetron** [comment]
if you have cell content where to capitals appear in a single word, they are considered wiki-words and treated as such, like linking to a page and when that page does not exist, add a [?] with link.
To prevent this, encapsulate your cell input in `!- -!` to tell the wiki the content is not to be interpreted by the wiki formatter.
In your case, your cell input would look like this in your editor: `!-S9902V1-!` and it will be displayed in the saved page like this: `S9902V1`

**Comment by ahennar** [comment]
But in the case when I want to use variable there? encapsulation with !- -! doesn't work

**Comment by ggramlich** [comment]
You can try a "literal table" by preceding the first line of the table with a "!".
http://fitnesse.org/FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupTable
Variables and symbols still work in a literal table.

**Comment by keetron** [comment]
This is actually a really nice solution to some other issue I was having, thanks!

**Comment by ahennar** [comment]
Thanks, it really helps!
