### ISSUE TITLE
Invoking FitNesse wiki(test) from Fixture code

### ISSUE THREAD

**Issue by aquddos123** [unclebob/fitnesse#1049]
Is it possible to invoke a test/wiki from within Fixture code in Java. 

I'm working on setting up a mock web service using HttpServer which is to be started by a Wiki test. Once the service is started, I need to make an api call to the service and that is where I need to call another wiki test to get the data for the service payload and then return a JSON response.

All I need is to setup some Wiki's with different data sets and call them within the API's back end code to get specific data to process the calls. 

Any other ideas of setting up such data for API payloads without any Database are welcome. 

Thanks.

**Comment by keetron** [comment]
You can make api calls using xmlhttptest made by fhoeben, it can be found here:
https://github.com/fhoeben/hsac-fitnesse-plugin

We use it to make SOAP, Rest and Http calls, sending all kinds of data across.
