### ISSUE TITLE
.wiki format can't handle CRLF

### ISSUE THREAD

**Issue by essenius** [unclebob/fitnesse#1050]
With the old content.txt/properties.xml format, FitNesse didn't really care whether the files use LF (standard Unix) or CRLF (standard Windows). The new .wiki format only accepts LF; if you try CRLF, the properties suddenly show up as text on the page. 

I'm running FitNesse 20161106 on Windows, and have setup FitNesse with Git, which automatically does line ending translations. So all LFs are translated to CRLFs. And it also causes issues when pages are edited outside of FitNesse.

Now I can work around the Git issue by setting a Git extension rule, but that doesn't help with the external editing issue. It would be much nicer if FitNesse would simply accept both LF and CRLF.

**Comment by keetron** [comment]
same as #999

**Comment by keetron** [comment]
Oh wait, I agree it would be nicer but in the list of feature request the .gitatrributes workaround makes it low prio as far as I am concerned. There are a few things I would rather see first (such as consistency between the page formatting in the wiki editor and the intellij plugin).

**Comment by essenius** [comment]
Not a very pretty workaround though. For example, it's now impossible to quickly edit files outside of the wiki in e.g. Notepad, as that can't deal with only line feeds.

**Comment by keetron** [comment]
If you move outside the realm of the wiki editor, I would suggest as an editor Intellij Community Edition with the fitnesse plugin, this wil greatly enhance how you work on the wiki files and it can handle CR, LF, CRLF and others just fine.
If you do not want to install a full IDE, go with notepad++ as that too can handle all line endings just fine.
