### ISSUE TITLE
Start SSH script from FitNesse using Slim

### ISSUE THREAD

**Issue by keetron** [unclebob/fitnesse#1051]
Did someone write a fixture for this that is open source?

**Comment by tcnh** [comment]
I'd say the ExecuteProgram fixture in hsac fixtures should be perfectly able to do that.

**Comment by keetron** [comment]
Today I discovered the hsac documentation on the github page is covering less than the hsac documentation in the include wiki.

**Comment by six42** [comment]
You can use:

https://github.com/six42/processtesterslim
