### ISSUE TITLE
Unit test failure on Windows

### ISSUE THREAD

**Issue by essenius** [unclebob/fitnesse#1059]
I just took a copy of FitNesse and ran gradlew test to ensure all is OK before I start changing anything. Unfortunately it fails a unit test:

fitnesse.junit.FitNesseSuiteExampleTestNoDebug > FitNesse.SuiteAcceptanceTests.SuiteSlimTests.TestSystemSlimSuite.ManualStartofSlimService FAILED
    java.lang.AssertionError

2850 tests completed, 1 failed, 80 skipped
:test FAILED

FAILURE: Build failed with an exception.

I ran the acceptance test suite after gradle run, and the same test fails, see screenshot.
![image](https://user-images.githubusercontent.com/17417493/27356318-4f7580c2-560e-11e7-8461-0dd23dff1c74.png)

I have the feeling I get this error because I'm behind a firewall. Any ideas how to make this test more resilient against that? It's the only test out of 2770 that fails.

**Comment by six42** [comment]
Hi essenius,

Thanks for trying FitNesse.
your feeling is right. If you can't reach the server fitnesse.org the test will fail.
You can put any other server name instead.
Proposals which other servers should be more reachable for a person which compiles FitNesse are welcome. :)

**Comment by essenius** [comment]
A trick to make it run in FitNesse is using FitNesse itself. But that won't make the unit test run. Here is my test page that does run right in FitNesse:

```
|script               |
|$host=|echo|localhost|
|$port=|echo|${Port}  |

!| script                         |
|create page|TestPage|with content|!-
!define TEST_SYSTEM {SLIM}
!define slim.timeout {1}
!define MANUALLY_START_TEST_RUNNER (true)
!define slim.pool.size (1)
!define SLIM_PORT {$port}
!define SLIM_HOST {$host}

-! |
|check |request page   |TestPage?test                                                                         |200                                                                        |
|ensure|content matches|class="error".{0,60}SlimError: Timeout while reading slim header from client. Check that you are connecting to the right port and that the slim client is running.|

!|script                                                                                    |
|show collapsed|content                                                                     |
|check         |request page   |TestPage?executionLog                  |200                 |
|ensure        |content matches|Command.{0,20}Connection to running SlimService: $host:$port|
|show collapsed|content                                                                     |
```
