### ISSUE TITLE
Fitnesse SSL parameters class not found

### ISSUE THREAD

**Issue by gab3alm** [unclebob/fitnesse#1062]
Hello All,
Currently, I'm trying to setup fitnesse with SSL. 
I have followed the guide provided here, http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.AdministeringFitNesse.NetworkSecurity

However when I try to run my fitnesse server, the console gives the following error.
![results](https://user-images.githubusercontent.com/19417654/27875836-87d9fbee-6169-11e7-9a37-164fcbc28865.PNG)

Currently, the CustomSslParams class is within my jar file that contains all the other testing fixtures. Should I be placing the "CustomSslParams" class in a specific directory within the root?

Thanks

**Comment by six42** [comment]
Hi,

Did you added your jar to the classpath used to start the FitNesse server?

**Comment by gab3alm** [comment]
I added a "!path" to the jar file that contains the "CustomSslParams" class within the "root" page of fitnesse.
Should I be placing this "!path" in another section of fitnesse?

**Comment by six42** [comment]
It must not be added inside fitnesse.
It must be added in the commandline that starts fitnesse

**Comment by umeshchhabra** [comment]
I have tried various methods but did not get any success.

I followed the link and:

- Create JKS
- Created a custom class named mysslvalues and  complied to get .class file in (bin/mypackage) folder
- Added plugins.properies file

After doing all these, I am running fitnesse using:

java -cp bin\* -jar fitnesse-standalone.jar -p 5443

I get the same error mentioned in the original post.

Am I not following the steps?

**Comment by suchita-zade** [comment]
Did you got the solution for this? I am facing the same problem.

**Comment by fhoeben** [comment]
I have no experience running with SSL, but I believe you can't combine `-cp` and `-jar` when starting Java, https://stackoverflow.com/questions/18413014/run-a-jar-file-from-the-command-line-and-specify-classpath#answer-18413058.

So you either have to create a jar that contains the class and fitnesse's classes (I believe that is what @gab3alm did). 

OR you can use your approach but the you have to specify a classpath containing both fitnesse's jar and your custom class an explicit give the main class.
The latter approach will probably require a command line something like `java -cp bin:fitnesse-standalone.jar fitnesseMain.FitNesseMain -p 5443`

**Comment by umeshchhabra** [comment]
I ended up using Nginx on top of Fitnesse server to provide SSL access.

**Comment by kcremin** [comment]
Hi Folks,
Anyone have any luck with this? I'm using Fitnesse nslim for a .NET SUT. I downloaded the java sdk and get the following error when running javac against my custom ssl class. "error: package fitnesse.socketservice does not exist." 
I would be great if someone posted some step by step screen shots on how the get this working. The http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.AdministeringFitNesse.NetworkSecurity doc is very vague when you don't have a java background. 
I'd really appreciate some help on this. Spinning wheels now on this for ages :(.
Thanks.

**Comment by surprogrammer** [comment]
> It must not be added inside fitnesse. It must be added in the commandline that starts fitnesse

can you please share the command how to do that
