### ISSUE TITLE
OutOfMemory in Fitnesse server

### ISSUE THREAD

**Issue by Mariushrek** [unclebob/fitnesse#1064]
Hello,

We are using Fitnesse in our company with 4G heap. If it running for a some time, it is slower and we can see OutOfMemory in webbrowser:
![captureoom](https://user-images.githubusercontent.com/6495800/28062133-43cee2ac-662d-11e7-9985-45e79383e95a.PNG)

When I checked it in Java VisualVM I can see, that fitnesse.wikitext.parser.Symbol is using more than 33% of memory. Can you advise?
![jvmphoto](https://user-images.githubusercontent.com/6495800/28062399-13325588-662e-11e7-8f5f-6d6a80dc0f75.PNG)

**Comment by amolenaar** [comment]
Hi, 4Gb is a lot. Are you using any custom symbols? Those symbols should be GC'ed after a page (request) is processed. Can you trace what is keeping hold of the symbols?

**Comment by Mariushrek** [comment]
We are using our fixtures (included on classpath), so I suppose it will be translated to symbols.
Right now I increased heap to 8Gb and looking what is happening there.

For you request - I will try :)

**Comment by woodybrood** [comment]
You might also consider running suites in batches. Running really large suites of suites with very verbose tables or lots of scenario tables in a layered approach can cause a lot of memory usage.
