### ISSUE TITLE
How do I delay FitNesse from starting Slim tests on a remote server?

### ISSUE THREAD

**Issue by bobredarch** [unclebob/fitnesse#1067]
Hello
Some of our test steps can only be executed on a particular machine as a particular user.  We thought a good way to accomplish this was to establish a tunnel, and remotely execute SlimService via SSH using the COMMAND_PATTERN variable.  Here are the variables we are using:
```
!define TEST_SYSTEM {slim}
!define slim.port {2112}
!define slim.pool.size {1}
!define slim.host { localhost}
!define slim.timeout{20}
!define COMMAND_PATTERN {ssh –L2112:localhost:2112  me@remoteSlimServer sudo –u privilegedUser /usr/java/default/bin/java –cp /home/privilegedUser/FitNesse/fitnesse-20151230-standalone.jar %m}
```

The first time we execute the test, we get the error:  “Could not complete testing: fitnesse.slim.SlimError: Got invalid slim header from client. Read the following:”  The second time we run the test, it succeeds.
After the first test runs (and fails on the FitNesse machine), the tunnel is established and the SlimService is running on our remote machine.  The second time we run, we get an error sent to stdout (cannot bind to port 2112 because the SlimService is still running and listening on port 2112).  But the second test succeeds because it runs on the previously started SlimService.  The second test runs to completion, and the SlimService (started by the first run) terminates normally.  This alternating pattern continues with every run:  Test fails but starts SlimService; Test successfully connects to SlimService and passes; Test fails but starts SlimService; Test successfully connects to SlimService and passes.

I’m grasping at straws here.  My guess is that the SlimService isn’t fully up and running before FitNesse starts sending traffic.  Is there a way to delay the FitNesse side from sending the tests over to Slim?

Thank you.

**Comment by six42** [comment]
Did you tried to increase the timeout to 60.
Did it changed anything?

**Comment by bobredarch** [comment]
I tried 60 & 120 seconds.  Same problem.  First test fails, SlimService starts.  Second test passes, SlimService terminates normally.

**Comment by six42** [comment]
Two other options :

Upgrade to the latest FitNesse version and use port free slim:

!define TEST_SYSTEM {slim}
 !define slim.port {1}
 !define slim.timeout{20} 
!define COMMAND_PATTERN {ssh me@remoteSlimServer sudo –u privilegedUser /usr/java/default/bin/java –cp /home/privilegedUser/FitNesse/fitnesse-standalone.jar %m} 

Don't use ssh port forwarding (not sure if this works):
!define TEST_SYSTEM {slim}
 !define slim.port {2112}
 !define slim.pool.size {1}
 !define slim.host {remoteSlimServer}
 !define slim.timeout{20}
 !define COMMAND_PATTERN {ssh me@remoteSlimServer sudo –u privilegedUser /usr/java/default/bin/java –cp /home/privilegedUser/FitNesse/fitnesse-standalone.jar %m}

**Comment by woodybrood** [comment]
Closing this as we don't have a response to latest suggestions. Assuming issue is resolved. Certainly issue can be reopened.
