### ISSUE TITLE
NoClassDefFoundError when running fitnesse tests  on Windows server 8 machine

### ISSUE THREAD

**Issue by anjalivaswani** [unclebob/fitnesse#1069]
Hi, 

My issue is my Fitneese tests are not getting executed on Windows server 8 machine. Below I will write the steps. I have created a suite setup page where i have defined all the paths of the class files and lib files  correctly. So suppose, my lib files reside in D:\temp folder and my class files reside in D:\somefolder\workspace\myproject\out , D:\somefolder\workspace\myproject\outtest

1. Launch the fitneese server on the machine. 
2. Execute the test after setting the above paths . 

Result: Constructor  of classes not found. However class files, functions exist and also ,the lib files exist.  In my opinion class paths are not getting set but i had double made sure that paths are correct . 

Error 1 : Most frequently encountered: Unable to start test system 'slim': fitnesse.slim.SlimError: Error SLiM server startup failed. 

Error 2 : NoClassDefFoundError
!define FITNESSE_LIB {D:\temp\lib} // lib files
!define COMPILEDSRC {D:\project\workspace\out} // scr files compiled
!define COMPILEDTEST {D:\project\workspace\outtest} // test compiled files 

!* <
!path $SLIM_PORT
!path ${FITNESSE_LIB}\**.jar
!path ${JAVA}\lib\**.jar
!path ${JAVA}\lib\rt.jar
!path ${JAVA}\lib\ext\**.jar
!path ${COMPILEDSRC}\**.class
!path ${COMPILEDTEST}\**.class
*!

Can someone please help with a  fitnesse version which can solve this issue .

**Comment by six42** [comment]
Hi,

Just define the following and remove everything else you showed below:
!path {D:\somefolder\workspace\myproject\out} 
!path {D:\somefolder\workspace\myproject\outtest}

In case you have startup problems press the execution log button. It will show you the command used to start fitnesse including the classpath used.
This helps to troubleshoot such issues.

**Comment by anjalivaswani** [comment]
HI a little update on this issue, if my project is dependent on so called 1000 jars then my tests are not executed and it shows could not invoke constructors error. What i observed is that when we are have many dependencies in the system, fitnesse fails. Any update on this?

**Comment by tcnh** [comment]
There's no spaces in any file/path names? I've seen some similar behaviour in Windows if there are.

Also, check for path names longer than 254 characters. This is a limitation in Windows that causes files to be skipped.

**Comment by ggramlich** [comment]
There is a Windows limitation on the total number of characters for a comand.

https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string

Take a look at the output captured page. I would assume, that !path ${FITNESSE_LIB}*.jar causes the classpath to list every single jar, and thus the comand issued is too long.

**Comment by anjalivaswani** [comment]
Just an FYI, i have resolved this issue by making a single classpath jar using jar command in ant.. This resolves the issue and we are able to use 1000 jars in that program

**Comment by ankurtade** [comment]
Hei , 

This command should help you by 
java -cp "Test.jar;lib/*" my.package.MainClass 

You shouldn't need to add all the jars to a single jar. It will be problem with maintenance. 

For more information please see here 

https://stackoverflow.com/questions/219585/including-all-the-jars-in-a-directory-within-the-java-classpath
