### ISSUE TITLE
Format using a hotkey 

### ISSUE THREAD

**Issue by AbdElraoufSabri** [unclebob/fitnesse#1072]
Can you add **format using a hotkey** during the editing of a wiki page ?

**Comment by jdufner** [comment]
+1

**Comment by six42** [comment]
Hi jdufner and AbdElraoufSabri

The access key "f" is defined for formatting.
MAC: [CONTROL] [ALT] + f
Firefox: [ALT] [SHIFT] + f
Others: [ALT]  + f

Let me know if this was helpful for you.

**Comment by AbdElraoufSabri** [comment]
**Thanks alot** @six42 I didn't know that.
Closing issue
