### ISSUE TITLE
How to Pass an HashMaps using HashMapFixture 

### ISSUE THREAD

**Issue by anjalivaswani** [unclebob/fitnesse#1074]
![fitneesse](https://user-images.githubusercontent.com/28919672/29168003-94721fec-7dea-11e7-94c1-38b054cea53f.png)

Hi, 

Can someone guide me how to pass a hashmap[java] from wiki page and also return a hashmap from fixture to wiki page. 

Probem statement:
I have various parameters which i want to pass in an hashmap and pass it in a fixture. Then Read that hashmap in a fixture, compare it and return a boolean hashmap on the wiki page. 

Some small example would be appropriate in understanding

Wiki Page code is here : 

!contents -R2 -g -p -f -h
!define TEST_SYSTEM {slim}

!path ${java.class.path}
!path C:\Workspace\ws\HelloWorld\smartrics-RestFixture-4.1.jar
!path C:\Workspace\ws\HelloWorld\bin

!**> discs for sale 
!define discsForSale { 
|Archangel|$12||abc| 
|Stingray|$14||xyz|
|Gazelle|$8| |pqr|
|Starfire|$11| |rtw|
|Tee-Bird|$10| ||
} 
**! 

|HashMap| 
|sells|${discsForSale}| 

Fixture code is : 
package HashmapResult;

import java.util.Map;
import java.util.Set;

public class HashMap {
	
	store objstore= new store();
	public boolean sells(Map<String, String> map) { 
		  Set<String> discNames = map.keySet(); 
		  for (String discName : discNames) { 
		    Disc disc = new Disc(discName, map.get(discName)); 
		    objstore.addToInventory(disc); 
		    
		  } 
		  return true;
	}		

}

**Comment by woodybrood** [comment]
This is because you aren't using the right syntax for the decision table. The HashMap should be the input of one method. And Sells is the output. See http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.DecisionTable
