### ISSUE TITLE
Fitnesse fixture with Generics

### ISSUE THREAD

**Issue by oleg-ponomaryov** [unclebob/fitnesse#1075]
Not an issue, but rather a question.

We are going to have a fixture class with generics, something like this.

public class CacheControl<T> extends ActionWithVariablesFixture

and we hoped we could use it in that test like this:

!|CacheControl<ServerCache>           |
but something tells me this not going to work since you guys just probably use simple reflection.

Is anything I could do to achieve my goal?

**Comment by amolenaar** [comment]
Hi,

I'm not sure what you're after. The Slim system is indeed using reflection. This is not a problem since generics are only a compile time feature in Java. They do simply not exist at runtime.

BTW. User questions are better directed to the mailing list fitnesse@yahoo-groups.com.
