### ISSUE TITLE
Error executing slim fitnesse test case

### ISSUE THREAD

**Issue by psshyamvarma** [unclebob/fitnesse#1078]
I'm getting following error when executing test case in fitnesse:

The instance decisionTable_0.setFirst. does not exist

Below is the screenshot:
![image](https://user-images.githubusercontent.com/30441474/30024907-d51c6a52-916d-11e7-8e51-3a12878a4125.png)

Below is the fixture java code:
package FitnesseExamples;

public class Calculator {
	private int first, second;
	
	public void setFirst(int first){
		this.first = first;
	}
	public void setSecond(int second){
		this.second = second;
	}
	public int addition(){
		
		return(first+second);
	}

	public int minus(){
		return(first-second);
	}
	
	public int multiply(){
		
		return(first*second);
	}
	
	public float divide(){
		return(first/second);
	}
}

Below is the wiki test:

!define TEST_SYSTEM {slim}

!path C:\Shyam\Automation\Workspace\AddNumber\src\FitnesseExamples

!|Calculator|
|first|second|addition?|minus?|multiply?|divide?|
|4   |2     |6       |2     |8       |2.0   |
|10   |5     |15       |5     |50       |2.0   |
|10   |10   |20       |0     |100     |1.0   |

**Comment by psshyamvarma** [comment]
My Calculator.class file is present in the following location: 

C:\Shyam\Automation\Workspace\AddNumber\src\FitnesseExamples

**Comment by ggramlich** [comment]
As you class is not in the default package

    package FitnesseExamples;


Try this

    !define TEST_SYSTEM {slim}

    !path C:\Shyam\Automation\Workspace\AddNumber\src

    !|FitnesseExamples.Calculator|
    |first|second|addition?|minus?|multiply?|divide?|
    |4 |2 |6 |2 |8 |2.0 |
    |10 |5 |15 |5 |50 |2.0 |
    |10 |10 |20 |0 |100 |1.0 |

You can also use an import table to define the package.

**Comment by psshyamvarma** [comment]
Thanks for your reply. Now I'm getting below error:
![image](https://user-images.githubusercontent.com/30441474/30027899-c215480e-917a-11e7-80db-858238db8614.png)

**Comment by psshyamvarma** [comment]
The above issue got resolved once again i recompiled the java file and executed the Test from wiki. Thanks.
