### ISSUE TITLE
Java fixture for capturing screenshot and showing it in results in fitnesse

### ISSUE THREAD

**Issue by psshyamvarma** [unclebob/fitnesse#1080]
what is the Java fixture for capturing screenshot and showing it in results in fitnesse?

I I know how to take screenshot in selenium web driver. I'm looking on how to take a sreenshot of web application using Fitnesse Java fixture and displaying it in wiki test results.

Any sample Wiki code and Java fixture will be helpful here.

**Comment by keetron** [comment]
You can have a look at the HSAC fixture here:
https://github.com/fhoeben/hsac-fitnesse-fixtures

**Comment by fhoeben** [comment]
To be precise: https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/c3f7f5e5c30b79dbff94bc1d34967a8825ccbb92/src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java#L1677
