### ISSUE TITLE
Error "Method <method name> not found in <package.classname> while executing script in wiki

### ISSUE THREAD

**Issue by psshyamvarma** [unclebob/fitnesse#1081]
I'm getting following error while executing test script from wiki:

Method open[1] not found in demo.GoogleExp.

Below is the screenshot:

![image](https://user-images.githubusercontent.com/30441474/30169341-070efa34-93e4-11e7-8fb2-393a4e657461.png)

Below is the wiki code:

    !define TEST_SYSTEM {slim}

    !path C:\Shyam\Automation\Workspace\FitnesseTest\bin
    !path C:\Shyam\Automation\Fitnesse\Newjars\accessors-smart-1.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\asm-5.0.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\cglib-nodep-3.2.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-codec-1.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-collections-3.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-exec-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-io-2.5.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-lang3-3.4.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-logging-1.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-net-3.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\cssparser-0.9.20.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\diff-1.1.11.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\diffutils-1.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\fitnesse-20130530.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\fitnesse-standalone.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\freemarker-2.3.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\gson-2.3.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\guava-19.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hamcrest-core-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-fitnesse-fixtures-2.9.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-fitnesse-plugin-1.18.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-xebium-bridge-0.5.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmllexer-2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlparser-2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-core-js-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-driver-2.23.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpclient-4.3.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpcore-4.3.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpmime-4.3.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jcl-over-slf4j-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jna-4.1.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jna-platform-4.1.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-20090211.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-path-2.2.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-smart-2.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\junit-4.12.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\neko-htmlunit-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\netty-3.5.7.Final.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\phantomjsdriver-1.3.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\sac-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-api-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-chrome-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-edge-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-firefox-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-ie-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-java-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-java-3.4.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-leg-rc-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-remote-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-safari-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-server-standalone-3.4.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-support-3.5.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\serializer-2.7.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\slf4j-api-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\slf4j-jdk14-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\testng-6.9.4.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\velocity-1.7.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xalan-2.7.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xebium-0.12.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xercesImpl-2.11.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xml-apis-1.4.01.jar

    !|Import|
    |demo|

    !|script:GoogleExp|
    |open|http://www.google.com|
    |show|takescreenshots|Foto_1|

Below is the java fixure code:

    package demo;

    import java.util.concurrent.TimeUnit;

    import nl.hsac.fitnesse.fixture.slim.web.xebium.HsacXebiumBrowserTest;

    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.chrome.ChromeDriver;

    public class GoogleExp {

    	static WebDriver driver;
	
    	public GoogleExp(){
		
    	}
	
    	public void open(){
    		System.setProperty("webdriver.chrome.driver", "C://Shyam//Automation//ANT//chromedriver.exe");
		driver = new ChromeDriver();
		driver.get("https://www.amazon.com/");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
	}
	
	
	public HsacXebiumBrowserTest takescreenshots(String s){
		 
		HsacXebiumBrowserTest hxb = new HsacXebiumBrowserTest();
		hxb.takeScreenshot(s);
		return hxb;
		
		
	}
	
    }

**Comment by ggramlich** [comment]
Your open method does not take a parameter.

Method open[1] not found in demo.GoogleExp.

The [1] means that Slim searches for a method with 1 parameter.

You probably meant to write

    public void open(String url){
      System.setProperty("webdriver.chrome.driver", "C://Shyam//Automation//ANT//chromedriver.exe");
      driver = new ChromeDriver();
      driver.get(url);
      driver.manage().window().maximize();
      driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    }

**Comment by psshyamvarma** [comment]
Thanks this issue is resolved. But, it has another error. I will raise separate issue for that.
