### ISSUE TITLE
Error in method to take screenshot

### ISSUE THREAD

**Issue by psshyamvarma** [unclebob/fitnesse#1082]
In the first step, I have opened a new browser and opened and website. In second steps I'm calling a method to take screenshot. When running the wiki test, webbrowser is getting opened successfully but it has issue with the second method.

Error: 
    __EXCEPTION__:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Cannot use Selenium before a driver is started (for instance using SeleniumDriverSetup)

Error screenshot: 

![image](https://user-images.githubusercontent.com/30441474/30179800-9d782e16-9405-11e7-9482-0421b68f690f.png)

Below is the wiki code:

    !define TEST_SYSTEM {slim}

    !path C:\Shyam\Automation\Workspace\FitnesseTest\bin
    !path C:\Shyam\Automation\Fitnesse\Newjars\accessors-smart-1.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\asm-5.0.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\cglib-nodep-3.2.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-codec-1.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-collections-3.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-exec-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-io-2.5.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-lang3-3.4.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-logging-1.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\commons-net-3.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\cssparser-0.9.20.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\diff-1.1.11.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\diffutils-1.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\fitnesse-20130530.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\fitnesse-standalone.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\freemarker-2.3.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\gson-2.3.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\guava-19.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hamcrest-core-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-fitnesse-fixtures-2.9.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-fitnesse-plugin-1.18.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\hsac-xebium-bridge-0.5.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmllexer-2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlparser-2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-core-js-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\htmlunit-driver-2.23.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpclient-4.3.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpcore-4.3.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\httpmime-4.3.6.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jcl-over-slf4j-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jna-4.1.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\jna-platform-4.1.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-20090211.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-path-2.2.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\json-smart-2.2.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\junit-4.12.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\neko-htmlunit-2.23.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\netty-3.5.7.Final.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\phantomjsdriver-1.3.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\sac-1.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-api-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-chrome-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-edge-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-firefox-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-ie-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-java-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-java-3.4.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-leg-rc-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-remote-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-safari-driver-2.53.1.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-server-standalone-3.4.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\selenium-support-3.5.3.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\serializer-2.7.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\slf4j-api-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\slf4j-jdk14-1.7.21.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\testng-6.9.4.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\velocity-1.7.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xalan-2.7.2.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xebium-0.12.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xercesImpl-2.11.0.jar
    !path C:\Shyam\Automation\Fitnesse\Newjars\xml-apis-1.4.01.jar

    !|Import|
    |demo|

    !|script:GoogleExp|
    |open|http://www.google.com|
    |takescreenshots|Foto_1|

Below is the java fixure code:

    package demo;

    import java.util.concurrent.TimeUnit;
    import nl.hsac.fitnesse.fixture.slim.web.xebium.HsacXebiumBrowserTest;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.chrome.ChromeDriver;

    public class GoogleExp {

    	static WebDriver driver;

    	public GoogleExp(){
	
    	}

    public void open(String url){
      System.setProperty("webdriver.chrome.driver", "C://Shyam//Automation//ANT//chromedriver.exe");
      driver = new ChromeDriver();
      driver.get(url);
      driver.manage().window().maximize();
      driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    }

    public HsacXebiumBrowserTest takescreenshots(String s){
	 
    	HsacXebiumBrowserTest hxb = new HsacXebiumBrowserTest();
    	hxb.takeScreenshot(s);
    	return hxb;
    }

    }

**Comment by ggramlich** [comment]
This is not an issue for the FitNesse project, but probably refers to https://github.com/fhoeben/hsac-fitnesse-fixtures or https://github.com/fhoeben/hsac-xebium-bridge

I don't know, how the other issue watchers see it, but the issues for a github project is usually not the place to ask questions about using the project, but for reporting bugs and feature requests, especially when the project page https://github.com/unclebob/fitnesse says so (with links to the issues and the mailing list)

> **Bug tracker**
> 
> Have a bug or a feature request? Please open a new issue.
> 
> **Community**
> 
> Have a question that's not a feature request or bug report? Ask on the mailing list.
> 

I can totally understand, if you have lots of questions and problems while using FitNesse, but I would advice you to get some support from programmers around you and address the questions to the right project. And for FitNesse address them to the mailing list (or even stackoverflow.com).

To the other issue watchers: Please correct me, if you see this differently.

**Comment by keetron** [comment]
I agree with you, but in addition I would like to direct ps to this
project: https://github.com/fhoeben/sample-fitnesse-project
It is a standalone, fully functional FitNesse setup using HSAC for browser
automation. I would urge you (PS) to use this installation guide
https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/Installation-Guide
Any questions you have from there, ask in that project.

**Comment by amolenaar** [comment]
I'm closing this issue as there's nothing we can do for you with regards to the FitNesse code base.
