### ISSUE TITLE
Wiki Import replaces HTTPS with HTTP for Remote Wiki Url

### ISSUE THREAD

**Issue by eugenykravchenko** [unclebob/fitnesse#1086]
Steps to reproduce:
1. Run local FitNesse on http://localhost:8001/
2. Go to root page
3. Go to Tools/Properties/
4. On Wiki Import put remote HTTPS FitNesse url like **https**://remotedomain.com:8001/root
5. Click Update Subpages

Expected result: import started
Actual result: Import failure: The remote resource, **http**://remotedomain:8001/root, was not found.

**Comment by jsmorris** [comment]
I am also encountering this issue when trying to use https://my.server.com/WikiPage.  I am still using the content.txt and properties.xml format.  When viewing the properties page, the wiki import URL is displayed correctly, but after clicking the "Update Subpages" button, the "Source wiki" value has the converted URL, http://my.server.com:80/WikiPage

**Comment by six42** [comment]
Hi Jsmorris,

Try if changing here would help:
https://github.com/unclebob/fitnesse/blob/22330268bb5c7cb18e59afda64d8a83ab4028781/src/fitnesse/responders/WikiImporter.java#L182

**Comment by six42** [comment]
Cool,
Many Thanks Fried
