### ISSUE TITLE
Passing different VM arguments to different tests?

### ISSUE THREAD

**Issue by rdk101995** [unclebob/fitnesse#1093]
Hi. I am new to fitnesse. I need to pass different vm arguments for each test in fitnesse. How do i achieve that?

**Comment by six42** [comment]
Thanks for trying FitNesse. You made the right choice. 

Define a different COMMAND_PATTERN for each test.

See http://fitnesse.org/FitNesse.UserGuide.QuickReferenceGuide

**Comment by rdk101995** [comment]
I have defined COMMAND_PATTERN on the root page. Is there a way to dynamically change the arguments  in the COMMAND_PATTERN through a fixture? That is, if a certain test is run, the COMMAND_PATTERN arguments get modified.

**Comment by tcnh** [comment]
The command pattern is used to start the jvm that runs the test framework (and thus any fixture code). The running fixture can't change the command pattern at runtime.

What are you trying tot accomplish? If, for example, you need certain system properties to change, it should be simple enough to do so from a fixture.

**Comment by rdk101995** [comment]
I have defined VM arguments in the COMMAND_PATTERN on the root page of fitnesse. What I want to do is I want to override those arguments before running every test page on the Front page of fitnesse.
@tcnh

**Comment by tcnh** [comment]
When you run each test separately, that might be doable, but when running multiple tests as a suite, the JVM instance is only created once.

**Comment by rdk101995** [comment]
How do I do the former one? There is a single root page for fitnesse running on a particular port where I have defined all class path settings and COMMAND PATTERN. Only the COMMAND PATTERN arguments need to be changed.

**Comment by tcnh** [comment]
Just define it again before instantiating any fixture code. It will override the root setting

**Comment by ggramlich** [comment]
Do you want to switch the COMMAND_PATTERN for all the tests or do you have a group of tests where you need COMMAND_PATTERN A and another group of tests where you need COMMAND_PATTERN B?

**Comment by rdk101995** [comment]
The latter one. @ggramlich 

I tried what you suggested. Doesn't work. @tcnh

**Comment by tcnh** [comment]
I think you try overriding it after the slim/fit server  process has started then. Otherwise it should work (I use this for running tests through proxies in specific cases)

If it's groups of tests, just define separate command patterns at suite level instead of on the front page.

**Comment by amolenaar** [comment]
Have you tried setting the TEST_SYSTEM to something like `slim:testtype`? Each test system category (although all Slim servers) should execute on a new VM. In addition set the jvm arguments by adapting the COMMAND_PATTERN.
