### ISSUE TITLE
20161106 Migration renders tags unusable

### ISSUE THREAD

**Issue by torstenwieder** [unclebob/fitnesse#1106]
When migrating an existing FitNesse wiki to 20161106 on Windows, the files are converted to UTF-8 with DOS line endings. If these files contain tags or help specifications, these tags are not read properly when the pages are opened in FitNesse. Instead, at the top of the page we can see the raw file contents, with the properties crossed-out. 

To get the tags to be recognized again, the files can either be edited and saved in FitNesse, or converted to UNIX line endings in some other way. (The help still did not work after this conversion.)

Still, FitNesse should not convert the files to an unusable format in the first place, therefore I'm submitting this bug report to raise awareness.

**Comment by NicoleRauch** [comment]
This is a screenshot of one of the pages right after the migration:

![screenshot-000244](https://user-images.githubusercontent.com/436499/33435880-a570b730-d5e3-11e7-932c-815a4b79f22d.png)

**Comment by tcnh** [comment]
Ik think this one duplicates https://github.com/unclebob/fitnesse/issues/999

**Comment by NicoleRauch** [comment]
Oh, interesting, thanks for the pointer @tcnh !
So are you saying that this problem is actually caused by Git? I thought it was caused by FitNesse itself when converting to the new .wiki format. This makes a lot of sense indeeed...
