### ISSUE TITLE
Changing TEST_RUNNER special variable dynamically

### ISSUE THREAD

**Issue by fraclipe** [unclebob/fitnesse#1109]
I have been reading all the information available, but I have not been able to found how to dynamycally change the 'TEST_RUNNER' special variable in order to point to the current path where a new created executable (CSlim in my case) is located. 

The context in which I am trying to do that is from inside a Jenkins job, which is in charge of compiling and generating, among other things, the Cslim executable that needs to be run by Fitnesse. I want to, somehow, from this Jenkins job indicate to Fitnesse where the Cslim executable is located (that location changes between Jenkins builds) and aftter that, trigger the Fitnesse run. I am assuming that this information is to be stored in 'TEST_RUNNER' special variable,

I am sure I am missing some point at this. Could anybody give me any hint on this please?
Thank you all by andvance,
Best regards

**Comment by six42** [comment]
Hi

If you start FitNesse from Jenkins you should be able to pass the value for Test_runner in the command line:
 -DTEST_RUNNER=

note that any value defined on a Wiki page takes precedence over command line arguments 

See System Properties on http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.CommandLineArguments

Please use the fitnesse mailgroup for general questions in the future.
You will reach more people this way and get better help.

Hope this helps

**Comment by ggramlich** [comment]
You should first try, what @six42 suggests.
If that does not work four you, you might go with a very simple template mechanism (example not tested, but I have done similar things before)

    !define DEFAULT_TEST_RUNNER {/home/foo/bar}
    !define TEST_RUNNER {${DEFAULT_TEST_RUNNER}}

From the outside interprete `${DEFAULT_TEST_RUNNER}` as a token and replace it  with your value in that specific content.txt or .wiki file.
