### ISSUE TITLE
20171212 Changelog, PluginsClassLoader no longer visible

### ISSUE THREAD

**Issue by haroon-sheikh** [unclebob/fitnesse#1114]
Is there a full list of changes in the new release?

I've noticed that PluginsClassLoader is no longer visible.

We have this custom runner so that we can run fitnesse tests headless with maven/junit. However, with the latest release, i can no longer include plugin jars as part of this junit run.
https://github.com/sitture/fitnesse-quickstart/blob/201b227df31fed9eb0a574b10348d891a7c6ea80/src/main/resources/archetype-resources/src/test/java/FitnesseRunner.java#L75

**Comment by tcnh** [comment]
Use 20171210, same upload date, no classloader issue

**Comment by haroon-sheikh** [comment]
Thanks @tcnh

**Comment by fhoeben** [comment]
I believe there was an issue with how Java 9 support was initially built.

This problem should no longer occur on current releases
