### ISSUE TITLE
CloudBees CI server has been red for ages

### ISSUE THREAD

**Issue by NicoleRauch** [unclebob/fitnesse#1119]
I just noticed today that the CloudBees CI server has been red for a very long time:

https://cleancoder.ci.cloudbees.com/job/fitnesse/

When I searched for the cause of this failure, I came across this:

https://stackoverflow.com/questions/38967991/why-are-my-gradle-builds-dying-with-exit-code-137
(I'm referring to the second answer here)

Would you mind trying this out and modifying the build command to include the `--no-daemon` parameter to see whether this fixes the issue?

**Comment by fhoeben** [comment]
I believe the server is no longer active
