### ISSUE TITLE
Custom theme based on bootstrap no longer found using 20180127

### ISSUE THREAD

**Issue by tcnh** [unclebob/fitnesse#1124]
I have a custom theme that extends on bootstrap. Since 20180127, the theme files are no longer found.

Before 20180127 I could have a jar with the theme files in plugins and just define the theme in plugins.properties. This no longer works.

Is there a new way to make this type of themes available in the latest version?
Custom responder plug-ins  for example continued to work just fine when placed in the plugins folder.

**Comment by tcnh** [comment]
I believe this happens because plugins now have a dedicated classloader, but velocity only knows the system classloader (that no longer holds any reference to plugins/themes). Should velocity get a hold of the plugins classloader?

**Comment by fhoeben** [comment]
Is this now fixed with the 20190127 release, which includes the classloader and javascript expression PRs you made?

**Comment by tcnh** [comment]
Yes. fixed in 20190127
