### ISSUE TITLE
How does FitNesse work with Spring Test?

### ISSUE THREAD

**Issue by zzygit** [unclebob/fitnesse#1132]
Spring Test has ways work with Junit, but I really like to take advantages of FitNesse. So, I wonder if FitNesse can work with Spring Test like Junit.

**Comment by fhoeben** [comment]
I'm not sure what you envision as combination of Spring Test and FitNesse. Can you elaborate?

I run FitNesse tests from jUnit regularly. FitNesse provides a FitNesseRunner you can use for that purpose see http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.RunningFromJunit
and an example jUnit test to run FitNesse tests in https://github.com/unclebob/fitnesse/blob/master/test/fitnesse/junit/FitNesseRunnerTest.java
