### ISSUE TITLE
Slim client not able to send files of 10 MB size, connection reset happening

### ISSUE THREAD

**Issue by aritrac** [unclebob/fitnesse#1133]
This issue deals with slim client sending a 10 mb archive file to a rest end point but the connection keep gets reset. Using postman tool, we are able to submit the same file to the rest end point without issues. Any help on this regard will be a big help.

Thanks

**Comment by tcnh** [comment]
Can you provide some info on how to reproduce? What fixture are you using?
I just tried sending a 20MB zip file to a rest endpoint using a fitnesse fixture and experienced no connection reset.
