### ISSUE TITLE
inline images rendered incorrectly

### ISSUE THREAD

**Issue by Kizaemon** [unclebob/fitnesse#1135]
Version: release 20180127 fitnesse-standalone.jar

When copy paste an image from clipboard into Rich Text editor, the image is being copied and rendered correctly in the Rich Text editor.

``
!img data:image/png;base64,iVBORw0KGgoAAAA[...snip...]
``

But the page output is not rendered correctly. The resulting html is

``
<img src="data"/>:image/png;base64,iVBORw0KGgoAAAA[...snip...]
``

The html output should have been

``
<img src="data:image/png;base64,iVBORw0KGgoAAAA[...snip...]"/>
``

Many Thanks!

**Comment by djbrown** [comment]
I can confirm this bug is still reproducable in the master currently

**Comment by djbrown** [comment]
The Documentation only mentions URL based images, no inline/base64-encoded ones: [FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupPicture](http://fitnesse.org/FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupPicture)
I guess the rich text editor somehow automagically handles it correctly (some library) but it isn't a proper feature of fitnesse with tests etc.

I will look into this and try to find a fix to make inline pasted images work.
#featureNotaBug 😁
