### ISSUE TITLE
Can I include a table as a parameter to a script action?

### ISSUE THREAD

**Issue by abailly** [unclebob/fitnesse#1144]
I would like to do something like the following, e.g. include a table as an argument to an action in a script table:

<img width="453" alt="screen shot 2018-06-20 at 12 48 55" src="https://user-images.githubusercontent.com/40221/41654041-69fd6e16-7488-11e8-95de-f00298edbf0e.png">

When I run this, slim passes the HTML-formatted table, is there a way to make it pass something like `List<List<String>>` instead? 

Alternatively, what would be the "standard" way to handle the case of common data definitions that can be shared and _referenced_ as objects inside other tables?

**Comment by tcnh** [comment]
You can pass a hashtable as a parameter. Translates to a map object on the slim side.

Syntax: `!{key:Val, key:val}` etc

**Comment by abailly** [comment]
So this kind of works but not when including the table:

<img width="885" alt="screen shot 2018-06-20 at 13 38 38" src="https://user-images.githubusercontent.com/40221/41656194-7334e408-748f-11e8-94ff-7febfe45b78a.png">

**Comment by fhoeben** [comment]
I have used storing (and passing on) nested maps and lists with my [Slim fixtures](https://github.com/fhoeben/hsac-fitnesse-fixtures). Initially that didn't quite work, but recent FitNesse releases allowed me to do this without problems.

See for instance the acceptance test for my 'map fixture': https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.UtilityFixtures.MapFixtureTest.html 
Or https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/HsacAcceptanceTests.SlimTests.UtilityFixtures.MapOfMapsFixture.html

I can use hash tables, as @tcnh suggests, or define the structure in separate lines.

I use these fixtures to define maps which I store in slim variables which I can then pass on to methods of other fixtures, which will receive a Map as parameter.
