### ISSUE TITLE
RESOURCE_SIZE_LIMIT too small

### ISSUE THREAD

**Issue by youwi** [unclebob/fitnesse#1146]
public class FileResponder.RESOURCE_SIZE_LIMIT = 262144*2;

*.png,
*.min.js
may > 512K  

how can i config it?

manual patch: fitnesse.responders.files.FileResponder
line 85:
     
```
   byte[] content = reader.readBytes(RESOURCE_SIZE_LIMIT);
   while (!reader.isEof()) {
            byte[] temp = reader.readBytes(RESOURCE_SIZE_LIMIT);
            byte[] both = Arrays.copyOf(content, content.length + temp.length);
            System.arraycopy(temp, 0, both, content.length, temp.length);
            content = both;
    }
```

**Comment by amolenaar** [comment]
I don't see a problem, since this constant is only used for resources loaded from the class path. Since this is a normal question I would recommend asking those on the mailing list, instead of opening an issue.
