### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when user tries to create an empty symbolic link

### ISSUE THREAD

**Issue by orlyk** [unclebob/fitnesse#1148]
When user tries to create a symbolic link with empty fields "Name" & "Path to page" and clicks button "Create/Replace" there is an Error Occurred (java.lang.StringIndexOutOfBoundsException: String index out of range: 0)

![screen shot 2018-07-18 at 4 26 09 pm](https://user-images.githubusercontent.com/5757189/42884553-50f61474-8aa7-11e8-8e83-bb06ab28c70c.png)

![screen shot 2018-07-18 at 4 26 36 pm](https://user-images.githubusercontent.com/5757189/42884569-5dee3c7e-8aa7-11e8-9f67-8da2f3998758.png)

**Comment by fhoeben** [comment]
fixed in 20200205
