### ISSUE TITLE
COMMAND_PATTERN & !path for Fit nor working together (For RestFixture)

### ISSUE THREAD

**Issue by AditiAich** [unclebob/fitnesse#1150]
PLEASE HELP

I am writing test using RestFixture

Following is my test page which I am trying to check if RestFixture working.

#!define COMMAND_PATTERN {%m -r fitnesse.fitserver.FitServer,fitSharp\fit.dll -c FitNesse\FitnesseRoot\SuiteOdata\odata.config.xml}

!path FitNesse/Plugins/RestFixture/*.jar

|Import |
|smartrics.rest.fitnesse.fixture|

|!-smartrics.rest.fitnesse.fixture.RestFixtureConfig-!|!-OdataConfig-!|
|http.client.connection.timeout |60000 |
|http.socket.timeout |60000 |

|!-smartrics.rest.fitnesse.fixture.RestFixtureConfig-!|!-OdataConfig-!|
|http.basicauth.username |Domain\Admin1 |
|http.basicauth.password |Pass78163hn |
|restfixture.display.actual.on.right |true |

Getting exception: Cannot run program "fit.FitServer": CreateProcess error=2, The system cannot find the file specified
*******************************************************************
After looking more into the issue  and trying more options found-
---When I am commenting 'COMMAND_PATTERN', then the things are working else getting the exception.
---Please help me with the solution as I need to refer Fixture.dll's which are refered using config file and also need the RestFixture jar files for obvious reason.

**Comment by six42** [comment]
Your command pattern needs a %p parameter. This gets replaced  with  the !path defintions.

Look here for standard command patterns. http://fitnesse.org/FitNesse.UserGuide.QuickReferenceGuide

I am a bit confused as you seem to mix java and .net in one test page
This is not possible. 
You need separate pages and a command runner for each.
