### ISSUE TITLE
FitNesseRunner lacks an option to override variables

### ISSUE THREAD

**Issue by micw** [unclebob/fitnesse#1152]
When running with fitnesse-standalone, it is possible to override variables by adding url params. Internally this is done by parsing the params and creating an UrlPathVariableSource from it. Later during variable resolution, UserVariable source checkis if the page variable source is of type UrlPathVariableSource, and if so, it is used with higher priority than the other variable sources. This is an implementation that is full of implicit assumptions - maybe this should be re-written some day.

When using FitNesseRunner, there's no option to override variables this way. The reason is that FitNesseRunner does not call context.getRootPage() with a map of values.
Since all those calls are in private methods, there's also no way to create a custom FitNesseRunner that calls the method with Map arguments.

I propose to
a) refactor FitNesseRunner to allow overriding this behaviour
b) define a proper way to set custom parameters (e.g. provide a class that does it by using a annotation)

**Comment by fhoeben** [comment]
As a suggestion to 'workaround' this issue you could consider using my plugin (https://github.com/fhoeben/hsac-fitnesse-plugin, sample usage https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SymbolSamples.wiki). 

It defines a `!defineDefault` extension to the wiki language that allows you to define a variable that may be overridden by system properties. Alternatively it defines `!defineDefaultFromProperties` that allows the variables to be overridden using a .properties file.

I use this to override variables when running tests (with the jUnit FitNesseRunner) on build server.
This way the jUnit class also does not have to contain the values to use during the test run, but they can be specified externally. Specifically I use it to point my tests to the correct server.

**Comment by woodybrood** [comment]
The hsac-fitnesse-plugin option also should allow for -D vm arguments at the command line. I'm going to close this with a viable workaround.
