### ISSUE TITLE
JUnitRunNotifierResultsListener should be more verbose about exceptions

### ISSUE THREAD

**Issue by micw** [unclebob/fitnesse#1154]
in JUnitRunNotifierResultsListener.testComplete, a test failure is triggered if the number of occured exceptions is >0. The failure is always "Exception occurred on page ..." - the root cause is hidden.

The listener should expose the occured exceptions to the junit framework.

**Comment by fhoeben** [comment]
As far as I'm aware when an exception occurs it is captured as `firstFailure`, which (in the if branch before the >0 count you refer to, line 58) will be thrown as jUnit failure.
Can you elaborate what exactly happens in your pages? Does the exception not cause `testExceptionOccurred()` to be called, causing the exception to be stored?
