### ISSUE TITLE
Is it possible to disable Test and Suite buttons?

### ISSUE THREAD

**Issue by cforest** [unclebob/fitnesse#1157]
Hi there,

I am running Fitnesse on several dispathers and then copy Fitnesse history and logs from all dispatchers to a separate machine. Some other project members need access to test results on this machine but I don't want them to be able to click Test or Suite there. Is it somehow possible to disable Test and Suite buttons? I would be glad for any options: either somehow configure it in Fitnesse, or get a patched fitnesse.jar, or any other options. On the main Fitnesse site (http://fitnesse.org/StayInformed), there is the following note: "Note, the Test and Suite buttons on this site have been disabled because search engines tend to invoke them and put my server under stress. This site is actually created with FitNesse.". So I need something like that, if possible.

Could you please give me a hand with it?

Thanks,
Cedar

**Comment by youwi** [comment]
![image](https://user-images.githubusercontent.com/5918054/50430162-7db0d600-08fd-11e9-9219-8696ee5ae7cb.png)

on  other machine mark it secure-test
this maybe help. 

Plan B:
 edit    /PageFooter
> !- 
> <script>
> $(".navbar-nav").remove()
> </script>  
> -!
this will delete all buttons.

**Comment by fhoeben** [comment]
See also https://stackoverflow.com/questions/52475430/fitnesse-is-it-possible-to-disable-test-and-suite-buttons#52620660

**Comment by cforest** [comment]
Thank you, youwi and fhoeben!
