### ISSUE TITLE
Can a failed test rerun feature be added to Fitnesse

### ISSUE THREAD

**Issue by afamee** [unclebob/fitnesse#1158]
We have a great need to have a feature whereby failing or unstable tests that is part of a larger suite can be isolated and run until it passes. Most times I resort to opening this individual failure each by themselves and rerunning. Ideally, it will be nice to have some filter after test run which can filter all failed tests and present an option to run them again.

**Comment by six42** [comment]
Haven't tried myself but could be that this works for you:

https://github.com/kdabir/roft/blob/master/README.md

**Comment by fhoeben** [comment]
I recently made a new 'listener' (`nl.hsac.fitnesse.junit.ReRunSuiteTestSystemListener`) in my [fixture project](https://github.com/fhoeben/hsac-fitnesse-fixtures) to serve this purpose.
It is activated when you run your tests via the custom jUnit runner in my project (or via the docker images I created). `ReRunLastFailures.wiki` is created containing references to all failed tests in the run is created. 

After the initial run/suite is completed you can run this page to have  all failed tests re-run.

I could look into creating a PR to have this feature added to FitNesse itself if there is a wider desire to have this. In the meantime you could consider using my fixture project...

**Comment by fhoeben** [comment]
Added in version 20190417
