### ISSUE TITLE
Testing with different Jar files

### ISSUE THREAD

**Issue by VinayGitDemo** [unclebob/fitnesse#1159]
Hi,
I want to use Fitneesse for my application where I am trying to test my service with help java class.

variable defined: TEST_SYSTEM=slim 

!define TEST_SYSTEM {slim}
!path C:\Users\VMOO\Documents\Inhouse_Prjts\FitNesse_Project\workspace\New folder\wm-isclient.jar
!path C:\Users\VMOO\Documents\Inhouse_Prjts\FitNesse_Project\workspace\

!|import|
|InvokeFromFitNess|
!|InvokeFromFitNess|
|firstNum|secondNum|add?|
|9		 |4		   |13  |
|8		 |4		   |10  |

But hit with below error :
Could not complete testing: fitnesse.slim.SlimError: Error SLiM server died before Header Message could be read.

Can pointers will be appreciated.
Thanks,
Vinay.

**Comment by six42** [comment]
Hi Vinay,

You made a good choise by starting using FitNesse.

Can you share what you see when you press on the 'EXECUTION LOG' button.

And which FiNesse and OS version are you using?

**Comment by VinayGitDemo** [comment]
Hi,

Thanks for your response!! Please find the execution log details.
========================================

slim:fitnesse.slim.SlimService
Test page:	FrontPage.TestCase6
Command:	java -cp "C:\FitNesse\fitnesse-standalone.jar;C:\Users\VMOO\Documents\Inhouse_Prjts\FitNesse_Project\workspace\New folder\wm-isclient.jar;C:\Users\VMOO\Documents\Inhouse_Prjts\FitNesse_Project\workspace\" fitnesse.slim.SlimService 1
Exit code:	1
Time elapsed:	0 seconds
Standard Output:
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -client	  to select the "client" VM
    -server	  to select the "server" VM
                  The default VM is client.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
Internal Exception:
Error SLiM server died before Header Message could be read. 

=====================================================

**Comment by VinayGitDemo** [comment]
Hi Again,
Also, is there any way to test my application service URL through fitnesse.
For example, i want to post the data to below URL.
Basically,  **InvokeFromFitNess** is my application service and want to test this with FitNesse.

http://localhost:5555/invoke/sampleDefault.FitNesse:InvokeFromFitNess?firstNum=2&secondNum=2

Thanks,
Vinay.

**Comment by six42** [comment]
As you can see the created java command is not understood by java.

At a first glance the command looks ok.

Try to run the command in a dos box and see what you need to change.
Or try to run without any additional !path statements in FitNesse

Looks you have a space in the class path. 
This should have been fixed with #821 but maybe try to avoid this as well.

Do you have the latest FitNesse and java version?

**Comment by VinayGitDemo** [comment]
Yes , i have fitnesse-20180127-standalone.jar and also java

**Comment by VinayGitDemo** [comment]
Hi , did you got any chance to check about another one which i need to Post the data ?

**Comment by tcnh** [comment]
Latest Java could be an issue. I think I've seen the slim server not starting with Java 10. Can you try using 8 or 9?

**Comment by VinayGitDemo** [comment]
As six42 suggested, i have removed other path and executed successfully but i see these errors ..

The instance decisionTable_1.setFirstNum. does not exist ..
Is it mandatory to have setter methods in my Java programme(this is generated by my application) ...because am not purely from Java background ...

Thanks,
Vinay.

**Comment by six42** [comment]
You will be much quicker and have much more fun if you take the time to read the user guide once from begin beginning to end:

http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM

http://fitnesse.org/FitNesse.UserGuide

**Comment by fhoeben** [comment]
If you want to POST/GET data to your application you should check out the [web application fixtures on the plugins page](http://fitnesse.org/PlugIns#Webapplicationfixtures). There are a couple that offer pre-build java classes to do REST calls.

(I, of course, would recommend my [own fixtures](https://github.com/fhoeben/hsac-fitnesse-fixtures) that allow you to test via browser or REST. It comes with a [step-by-step guide to setup an environment](https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/Installation-Guide) based on a [sample project](https://github.com/fhoeben/sample-fitnesse-project).)
