### ISSUE TITLE
is there a plan to support  Schedule job

### ISSUE THREAD

**Issue by youwi** [unclebob/fitnesse#1163]
example ,i want run this test every hour  
 
>!schedule 1 */1 0 0 ? 
> here is my test
>| script   |my table| 
>| my arg |  
 
when using standalone.jar

**Comment by six42** [comment]
Hi Youwi,

What would be your use case for this?

To do this: Use an existing scheduler and execute your test page via the commandline 
http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.ControllingFitNesseFromTheCommandLine 

Or via calling the rest service of a running fitnesse server.

If you can't use an external scheduler write yourself a small scheduler class and start it via FitNesse. The class will the call FitNesse again itself via one of the two methods above or via the logic used in acceptance tests for FitNesse itself.

http://fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteResponderTests.SuiteTestResponders.TestResponder

**Comment by youwi** [comment]
i do not want use jenkins to Schedule my job..
so...

**Comment by jediwhale** [comment]
Developing yet another scheduling tool is not part of the FitNesse mandate, IMO.  As described above, FitNesse provides several options to interact with existing scheduling tools.
