### ISSUE TITLE
Feature request: add function to upgrade all FileSystemPage to WikiFilePage

### ISSUE THREAD

**Issue by LeiYangGH** [unclebob/fitnesse#1167]
Hi dear administrators and developers:

I'm not contributor of fitnesse but is absolutely daily(even hourly!) user, and so is our company's QA team. Recently we've **upgraded fitnesse version**(from 2013 to 2018), and the biggest change(at first glance) is wiki format change.
As the existing bug https://github.com/unclebob/fitnesse/issues/598 says, when editing pages, and save, there is **exception** and this is very time wasting. and the bug says it is caused by some **xml** parsing, so new wiki format will not reproduce this issue.

So we'd like to convert/upgrade all the FileSystemPages to WikiFilePages.

Writing some python script is my first idea, as most FileSystemPages are also generated by our python scripts from some templates. But after thinking a while, and realizing different projects teams have added **various kinds of nested pages and edited properties**,  to write such tool I must be very familiar and confident with Fitnesse's features, and it is not easy.

I've searched a lot but did not find such tool, and also download the Fitnesse souce code, but didn't found it yet.
So could you consider add a function/tool to upgrade/convert all FileSystemPage to WikiFilePage?

**Comment by fhoeben** [comment]
It's not very hard to upgrade to .wiki as I recall. I believe I just renamed my suite (all pages are converted), and then renamed it back again. 
Did you encounter any issue with this simplistic approach?

**Comment by LeiYangGH** [comment]
But how to rename them one by one with code, not manually?
I've read the fitnesse code, but still not found simple way to do this.

**Comment by fhoeben** [comment]
Sorry, no idea how to to them one by one with code.
Can you explain why you need to do that?
I just did a two renames via the wiki of my entire suite and was done.

**Comment by LeiYangGH** [comment]
Greate! I just tried renaming top suite and it worked. I never knew that, thanks!

**Comment by LeiYangGH** [comment]
problem solved.
