### ISSUE TITLE
Can't get the actual and expected content in the callback method testAssertionVerified of interface TestSystemListener

### ISSUE THREAD

**Issue by jinlxz** [unclebob/fitnesse#1169]
Hi,

I have implemented a custom test listener which implements the interface **TestSystemListener**, it can't get the actual and expected content by invoking the methods **getActual()** and **getExpected()** of an instance of class  **TestResult** in the callback method **testAssertionVerified** of the interface **TestSystemListener**, the code is as follows:
```java
public class SlimRunListener implements TestSystemListener {
        @Override
	public void testStarted(TestPage testPage) {
        }
        // omitting other inherited methods here.
        @Override
	public void testAssertionVerified(Assertion assertion, TestResult testResult) {
		// TODO Auto-generated method stub
		if(testResult!=null){
                     //the output is always empty even if an assertion in test case fails
		       System.out.println(testResult.getActual());  
                    //the output is always empty even if an assertion in test case fails
		       System.out.println(testResult.getExpected());  
		}
	}
}
```
I guess it may be a bug of Fitnesse.
the Fitness version used is 20180127.

**Comment by fhoeben** [comment]
I did a quick browse to the code, and I indeed see that the actual and expected value are not being supplied when creating the TestResult, for instance in Slim's ScriptTable.
I fear fixing this might be quite a job. (Of course a PR would be welcome.) 

Can you elaborate what you are trying to achieve, maybe I can offer a workaround?

**Comment by jinlxz** [comment]
Hi fhoeben,

I want to run fitnesse tests with maven, so I implemented a main class and the custom test listener, the test listener generates an junit format's output, the output is rendered on a jenkins job's page, the test listener works well, but it can't get the actual and expected content when a test fails, the test report only shows the test fail, it can't give more detailed information about the failure in the report, I want to get the context(the Actual and expected) when a test fails.
Do you have a workaround for my purpose?  

Thanks.

**Comment by fhoeben** [comment]
The approach I use to run tests on a build server uses the jUnit runner (FitNesseRunner, see http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.RunningFromJunit). That way there is no need to define your own main class or test listener, you can use the ones provided (which generate surefire xml and html reports).
The downside is that the content of the surefire XML, or the console output, is not very informative of what went wrong (see #1154). I only use it to ensure the build server (e.g. Jenkins) knows that a test failed. I use the generated HTML report (which I publish as an 'artifact' on the build server) to see which parts of the tests actually failed (it has the expected and actual values). A sample of a HTML test report created can be found at: https://fhoeben.github.io/hsac-fitnesse-fixtures-test-results/acceptance-test-results/ 

(My own fixture project, https://github.com/fhoeben/hsac-fitnesse-fixtures, has a [sample maven setup](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/pom.xml) to run tests in this way; it has its own subclass of FitNesseRunner, but the approach can be the same)

**Comment by jinlxz** [comment]
@fhoeben thank you, I will try it later.

**Comment by jinlxz** [comment]
@fhoeben I have tried the FitNesseRunner, it works, but I found a problem, it seems that the FitNesseRunner doesn't execute the SuiteSetup page of a test, only execute SetUp page and the test page itself, this behavior is different from the Fitnesse server

**Comment by fhoeben** [comment]
Strange to hear that the SuiteSetUp (note the uppercase U) is not executed for you. I'm quite sure it is executed in my tests using the runner.
What I have noticed is that a separate report page is created for the SuiteSetUp. If you run an entire suite you get an overview page linking to the SuiteSetUp, all test pages and SuiteTearDown. If you run a single test no such overview is generated (but the setup is run and a separate .html file is created for the SuiteSetUp). Could it be that you ran a single test and overlooked that the SuiteSetUp was also done?

**Comment by jinlxz** [comment]
Today I checked the issue, I created a separate and simple test page with SuiteSetUp, It works as you said, the issue still exists for the original tests which are in my test project, a big project which contains thousnds and hundreds of test pages and I found the issue only exists on linux which I uses as Jenkins slave, I guess It may be caused by the deep page structure or malformed page data, I will continue to debug it.

**Comment by jinlxz** [comment]
I fixed it, it is a problem of letter case, it works very well and displays beautiful result pages on Jenkins, thank you.
