### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by blling** [unclebob/fitnesse#1173]
I run into a infinite loop after upgrade to fitnesse-20181223, i found the thread is busy with method `readAndParseRequestLine`, which is changed by commit https://github.com/unclebob/fitnesse/commit/4078f4e47ff7f58b49c8e18b70aed6b8ac4125b0#diff-0e2a986db526e0ce77e3e3747199b0dbR72.   

fitnesse-20181221 is OK

jstack screenshot is here:
![image](https://user-images.githubusercontent.com/26540808/50391712-f17aa380-0782-11e9-9558-e24a8ec2278c.png)

**Comment by fhoeben** [comment]
That is unfortunate. I'll try to make a fix asap.
Anything in particular you are doing at the time this loop occurs?

**Comment by fhoeben** [comment]
What is the behaviour of FitNesse because of this loop? Does it hang, or ...?

I believe the code you refer to is only an infinite loop if there is a client that keeps sending newlines to FitNesse. That might be a browser that tries to keep a connection open. I would expect that to eventually send a real request...

**Comment by blling** [comment]
After a try use `sample-fitnesse-project`, it seems browser releated, Chrome is OK, Firefox is NG.

I reproduce it in the follow steps:  

Clone [sample-fitnesse-project](https://github.com/fhoeben/sample-fitnesse-project) -> `mvn exec:exec` ->  open http://localhost:9090 in Firfox.    

then the cpu is up, if you refresh the page n times，the cpu is up to 100*n，this is

Firfox version:
![image](https://user-images.githubusercontent.com/26540808/50393141-17a64080-078f-11e9-8f43-3137b19917b0.png)

**Comment by blling** [comment]
@fhoeben Thanks for your quick fix. :+1:
