### ISSUE TITLE
i am getting this error for ---> Unsupported major.minor version 52.0 

### ISSUE THREAD

**Issue by vikkymandoi** [unclebob/fitnesse#1185]
i am getting this error for ---> Unsupported major.minor version 52.0  this is bcz fitnesse is running on java 7 and my project is of Java 8. Kindly suggest. which all places to change when i am running java 8 on Eclipse

**Comment by tcnh** [comment]
You're using Java 7. Fitnesse no longer works in Java 7.
Make sure your java_home is set to a java 8 folder. Also check that the project JDK you're using in Eclipse is set to Java 8+

**Comment by vikkymandoi** [comment]
Thanks .. I did that all nothing worked. then i set java_home as variable while running the application in eclipse then it worked.
