### ISSUE TITLE
Changing Default Responder  page text

### ISSUE THREAD

**Issue by superherosalive** [unclebob/fitnesse#1194]
How Can I Change the below Text for Dafault Responder?  I could find any documentation for changing it.  Is it possible?

Thanks.

Default Responder
This action has been disabled.
You are seeing this page because the administrator of the FitNesse Wiki has decided that this action should be disabled.

Thanks,
The FitNesse development team.

**Comment by tcnh** [comment]
This text is in disabledPage.vm.
If you'd like to customize it, you'll need to create a custom theme containing a different version of this template file.

**Comment by superherosalive** [comment]
I did a search and could not locate disabledPage.vm.  Is there another place where it exists?

**Comment by tcnh** [comment]
https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/resources/templates/disabledPage.vm

**Comment by superherosalive** [comment]
If I understand this correctly, this change requires a rebuild of Fitnesse?  Sorry I'm new to Fitnesse.

**Comment by tcnh** [comment]
You can copy the file I linked to your project. Place it in a directory FitNesseRoot/files/fitnesse/templates and adapt it to your liking. Files in the file folder take precedence over files in the jar's resources.

**Comment by superherosalive** [comment]
I put the file disabledPage.vm in FitNesseRoot/files/fitnesse/templates and restart Fitnesse.  However, the change doesn't take place.  Is there anything else I missed?

**Comment by tcnh** [comment]
That would require a rebuild. What are you trying to achieve?

**Comment by superherosalive** [comment]
I guess I have to do a rebuild in order to remove the default phrase.  Thanks so much for your help.
