### ISSUE TITLE
FitNesse version 20190406 doesn't show version number anymore

### ISSUE THREAD

**Issue by ywevanderpol** [unclebob/fitnesse#1206]
Hello!

Version 20190406 doesn't get the right version number anymore after compiling.

`##FitNesse properties
#Tue Apr 09 13:27:06 CEST 2019
Version=vUnknown`

Thanks!

**Comment by McLFaberge** [comment]
Workaround:
Create FitNesseVersion.txt containing the text _v20190406_ and add it to fitnesse(-standalone).jar\META-INF\ (open in 7zip)

**Comment by fhoeben** [comment]
Fixed in 20190409
