### ISSUE TITLE
From a custom fixture, is it possible to access the name of the suite and test .wiki name?  Alternatively, is there a standard FitNesse symbol that contains the full test name?

### ISSUE THREAD

**Issue by violinner** [unclebob/fitnesse#1210]

**Comment by fhoeben** [comment]
I believe you can only access the current test page's name from a custom Slim table. I don't believe a fixture can access that information.

**Comment by fhoeben** [comment]
According to http://fitnesse.org/FitNesse.UserGuide.QuickReferenceGuide#GlobalVARIABLES

PAGE_PATH and RUNNING_PAGE_PATH are available, but that is not quite what you are looking for I believe.

PAGE_NAME |   | Read Only | Name of current page
-- | -- | -- | --
PAGE_PATH |   | Read Only | Fully qualified name of parent.
RUNNING_PAGE_NAME |   | Read Only | Name of current top level running page
RUNNING_PAGE_PATH |   | Read Only | Fully qualified name of the current tope level running page's parent.
FITNESSE_PORT |   | Read Only | Port number that fitnesse is using.


PAGE_NAME |   | Read Only | Name of current page
-- | -- | -- | --
PAGE_PATH |   | Read Only | Fully qualified name of parent.
RUNNING_PAGE_NAME |   | Read Only | Name of current top level running page
RUNNING_PAGE_PATH |   | Read Only | Fully qualified name of the current tope level running page's parent.
FITNESSE_PORT |   | Read Only | Port number that fitnesse is using.


PAGE_NAME |   | Read Only | Name of current page
-- | -- | -- | --
PAGE_PATH |   | Read Only | Fully qualified name of parent.
RUNNING_PAGE_NAME |   | Read Only | Name of current top level running page
RUNNING_PAGE_PATH |   | Read Only | Fully qualified name of the current tope level running page's parent.
FITNESSE_PORT |   | Read Only | Port number that fitnesse is using.


PAGE_NAME |   | Read Only | Name of current page
-- | -- | -- | --
PAGE_PATH |   | Read Only | Fully qualified name of parent.
RUNNING_PAGE_NAME |   | Read Only | Name of current top level running page
RUNNING_PAGE_PATH |   | Read Only | Fully qualified name of the current tope level running page's parent.
FITNESSE_PORT |   | Read Only | Port number that fitnesse is using.



PAGE_NAME |   | Read Only | Name of current page
-- | -- | -- | --
PAGE_PATH |   | Read Only | Fully qualified name of parent.
RUNNING_PAGE_NAME |   | Read Only | Name of current top level running page
RUNNING_PAGE_PATH |   | Read Only | Fully qualified name of the current tope level running page's parent.
FITNESSE_PORT |   | Read Only | Port number that fitnesse is using.

**Comment by violinner** [comment]
I would like to automatically log the names of Suites and Tests.

My custom fixture has a "log()" method.
From a custom fixture, is it possible to access the name of the suite and test name?
Alternatively, is there a standard FitNesse symbol that contains the full test name?

**Comment by violinner** [comment]
Perfect.  Thanks.
