### ISSUE TITLE
Fitnesse slim fails with puzzling IndexOutOfBoundsException

### ISSUE THREAD

**Issue by abailly** [unclebob/fitnesse#1221]
We are using Fitnesse/Slim with (slightly customised) pySlim server. When running `Suite` for a set of pages I got the following error: 
<img width="538" alt="Screenshot 2019-04-25 at 17 36 36" src="https://user-images.githubusercontent.com/40221/56748916-fd9e5e00-6780-11e9-89e2-03141c31c8e5.png">

I tried to debug the server but to no avail, probably because my debug-fu on Java is too rusty to be helpful. I also tried to upgrade to latest fitnesse (20190421), and to pass `-v` for more verbose debugging but to no avail. Is there way to know where/why this exception is thrown?

**Comment by tcnh** [comment]
Can you share the wiki content to reproduce this? I'm pretty sure I've seen this before with a table that was not properly formatted

**Comment by abailly** [comment]
Unfortunately not, but I came to a similar conclusion. However it's pretty much unclear _which_  page is wrongly formatted...

**Comment by abailly** [comment]
I found the culprit: It's a script table line containing a single item. `ScriptTable` fails to extract the action's name and throws this error. Would you consider a PR to fix that? What would be a more helpful error to throw?

**Comment by tcnh** [comment]
A PR with an improved exception message is always welcome!
