### ISSUE TITLE
Failed !include does not result in a failed Test

### ISSUE THREAD

**Issue by headcrab89** [unclebob/fitnesse#1226]
Tests which have an ```!include``` with a path that doesn't exist, are still marked as passed. 

![Screenshot from 2019-05-28 13-06-15](https://user-images.githubusercontent.com/23377011/58501027-b9d5b480-8183-11e9-90c0-c8db99025855.png)

In this picture the Page Include has failed but the test still has passed. Shouldn't this result in a failed test?
Because we have several includes in our tests and some of these tests have been broken after a refactoring, and we could not recognize them as failures.

Here is the code:
```
!include UtilityPage.MyUtily

!|script:fitnesse.slim.test.NullFixture|
|$NULL= |getNull                       |
|check  |getNull|$NULL                 |
```

**Comment by tcnh** [comment]
I understand the way you think, but in your example, all assertions pass and no exceptions occur. It's just a reference error in your wiki markup. The test system, however doesn't know what is markup and what is not as will just interpret the page as of the include wasn't there.

**Comment by headcrab89** [comment]
Thank you for your quick answer.

I know what you mean, but this is still a problem for us. Couldn't the information about the failed include be passed to the test system? Or a special `Fixture` which can do this?

**Comment by tcnh** [comment]
I don't think passing wiki syntax errors to slim will be easy to do..
Maybe you can use some sort of workaround by evaluating something that you have set in the include later on (i.e. in your TearDown) that would cause a failed assert or throw an exception?

**Comment by headcrab89** [comment]
Thanks for your answer. We will look for a workaround.
