### ISSUE TITLE
Multiple Symbolic Links with a same target Page are not all showed in the Page containing "Symbolic Links"

### ISSUE THREAD

**Issue by jinlxz** [unclebob/fitnesse#1234]
Hi,

I create a multiple Symbolic Links in a Suite page and all these Symbolic Links point to a same real page under this suite, but I found only one Symbolic Links was showed, e.g.
```shell
TestSuite
|__RealPage
```
I created 2 Symbolic Links in the page **TestSuite**, both of them point to the page **RealPage**, but only one Symbolic Links was displayed as the following image:
![image](https://user-images.githubusercontent.com/9611732/60959824-743c0800-a33b-11e9-8e18-fa4410aa4500.png)
the Symbolic Links were created as follows:
![image](https://user-images.githubusercontent.com/9611732/60959922-a0578900-a33b-11e9-9d2e-da829c3d9c11.png)

I think both of the symbolic Links should be showed, is it a bug?

Fitnesse version: v20180127

**Comment by fhoeben** [comment]
I believe both should be shown, but can you elaborate on why you want to have 2 symbolic links to the same page?

**Comment by jinlxz** [comment]
I created 2 symbolic links to point to a same suite page, used paths of the 2 symbolic links to run different tests with different tags, the junit test result will have test cases with different package name, we have a script to analysis the test results from multiple projects, generates a HTML report, showing number of passed tests, number of failed tests, etc., one line per project, It requires that the common part of package name of all tests for a project differs from and not contained within that of other project, in this case the script can calculate statistics for each project correctly, otherwise It fails as a test must be belonged to only one project, so I created multiple Symbolic links to the same suite page, use paths of these Symbolic links with different tags for different project.
 
Hopefully I describe It clearly.
