### ISSUE TITLE
fitnesse.org is down

### ISSUE THREAD

**Issue by JessefSpecialisterren** [unclebob/fitnesse#1240]
Trying to visit fitnesse.org gives me a connection timeout, and two external website checking tools confirm that it's down for everyone

**Comment by amolenaar** [comment]
Indeed. I can't SSH into it. I assume the machine is down.

@unclebob Can you please have a look?

**Comment by aquddos123** [comment]
Looks like FitNesse server is again down. Unable to access http://fitnesse.org/

```
Gateway Timeout
Server error - server 23.23.125.155 is unreachable at this moment.
Please retry the request or contact your administrator.
```
