### ISSUE TITLE
XML output gets jumbled and mixed rendering it invalid.

### ISSUE THREAD

**Issue by mlsomers** [unclebob/fitnesse#1242]
I don't know what exactly happens but the symptoms look like the output is written to a stack by one thread, and another thread is reading it from there. The reading thread is usually fast enough so there is only one line on the stack, but not always…
Or something similar (it sometimes breaks in the middle of lines). Maybe tests get executed in parallel and have the results merged?

Here's an example where : `</expectation>` and `</instructionResult>` are swapped:
```
<instructionResult>
	<instruction>{id='decisionTable_0_109', instruction='call', instanceName='decisionTable_0', methodName='KortingInc', args=[]}</instruction>
	<slimResult>pass(41,18)</slimResult>
	<expectation>
		<status>pass</status>
		<instructionId>decisionTable_0_109</instructionId>
		<col>4</col>
		<row>12</row>
		<type>ReturnedValueExpectation</type>
		<evaluationMessage>41,18</evaluationMessage>
	</instructionResult>
</expectation>
```
Here part of the content was split in the middle of a line (`<expectation>` and `<evaluationMessage>` ):
```
<instructionResult>
	<instruction>{id='decisionTable_0_71', instruction='call', instanceName='decisionTable_0', methodName='KortingOmscrijving', args=[]}</instruction>
	<slimResult>19,50</slimResult>
	<expectation>
		<status>ignore</status>
		<instructionId>decisionTable_0_71</instructionId>
		<col>6</col>
		<row>8</row>
		<type>ReturnedValueExpectation</type>
		<evaluationMessage>19,5
		</expectation>
0</evaluationMessage>
</instructionResult>
```

**Comment by fhoeben** [comment]
Very strange results indeed. I'm not immediately aware of any place where there might be multiple threads working that could interfere in this way.
Can you elaborate on what you were doing when this XML was written? What version of FitNesse are you using, on what platform? How are you starting the test? Are you running multiple tests in parallel? What language are your fixtures in? Is there any multi-threading in the fixture code (or application code that you call from them)?

**Comment by mlsomers** [comment]
Fitnesse v20190428
FitSharp 2.7.1 (https://github.com/jediwhale/fitsharp)
In TFS using FitNesseRun V1 (https://github.com/essenius/FitNesseRun)

I'm still trying to figure out how to generate the xml output on my local machine.
In the webbrowser my tests are working without any issues.

**Comment by mlsomers** [comment]
Ok, I figured it out. Adding "&format=xml&nochunk&includehtml" to the URL gave me the xml output.
In this case there is no issue, it is valid...
I guess it must be something in FitNesseRun after all, but it's just a powershell script, doesn't look like it's doing anything special...

**Comment by mlsomers** [comment]
It doesn't look like the problem is in FitNesseRun I did some extra testing (see [this ticket](https://github.com/essenius/FitNesseRun/issues/4)) and all the processing that is done in the powershell script seems to produce valid xml. The errors occur as soon as the powershell script tries to parse the XML, so the xml is invalid before that stage...

Is there any commandline option to output the result to std-out or a log-file (as well as the usual http) for debugging purposes?

**Comment by mlsomers** [comment]
I reverted to using NSSM and run fitnesse as a continuously running service.
Now I get correct xml in TFS...
