### ISSUE TITLE
FitNesse Flow mode not working with other fixture tables in between

### ISSUE THREAD

**Issue by JanVerstuyft** [unclebob/fitnesse#1244]
The documentation is stating that we can include a normal fixture table in between the flow mode.

> When the table is split like this, then each sub-table is first matched to an enclosing flow fixture method. If no such method exists, a fixture class is loaded as it would normally be, without the flow mode.

But when I try this, he always keep on complaining about the missing method ....
If I add these methods and instantiate the fixture like that, the flow mode is working.  But that can not be the goal of this mode, otherwise I always have to define all the possible fixture as method in my Flow fixture.  The Import fixture has the same issue btw. 

The only possible (dirty) solution I had was to define all the necessary methods.

**Comment by jediwhale** [comment]
Please post the versions of the tools you are using.

**Comment by JanVerstuyft** [comment]
Right.  I'm a bit emberrassed that I've forgot that ;).

I've had it with an older version, but I've upgraded to the latest version of FitNesse (v20190716).

In the mean time I've found the issue.  I was dragging the fitlibrary version 20080812 into my lib folder.   Without that, it is working. 

So thanks for playing my rubber duck and sorry for the inconvenience

Kind regards

Jan
