### ISSUE TITLE
[Question] - Evaluated value of a symbol wrapped `<div>` tag

### ISSUE THREAD

**Issue by ryukato** [unclebob/fitnesse#1249]
Using Rest Fixture, I defined a symbol to get specific value from JSON like following.

let | testValue| js | JSON.parse(response.body).testValue|$testValue
-- | -- | -- | --|--

And assiged the symbol to variable like below.

`!define gTestValue {$testValue}`

but I found the `$testValue` has `div` tags.
Is there anything wrong to get value using symbol and assign it to variable without the html tags?
I appreciate if you let me know.

**Comment by joroelev** [comment]
The value 'testValue' might be interpreted as a 'wikiword' word because of the casing. Sometimes this causes some problems. Try to escape it like this `!-testValue-! `  and see if that fixes the problem.

**Comment by fhoeben** [comment]
I expect you problem to be the different variable scopes in FitNesse (but I'm not familiar with RestFixture so I can't be 100% sure).
a `!define` is evaluated at wiki rendering time, before the tests are started.
a slim symbol (assignment) is done during test run

So I expect the `$testValue` too late to be usable in a define.

I don't know how/when/why you need to use `${gTestValue}`, but I expect you need to do `$testValue` in a Slim table instead, to access the value parsed from the JSON response

**Comment by ryukato** [comment]
Thanks you guys. I tried your suggestions but no luck. :(.
I tried escaping the variable like `$!-testValue-!`, but it still has `div` html tag.
And I checked the value of the symbol, which is evaluated at runtime like below but it still does with `div` html tag.

```
!|script|
|check|echo|value is {$testValue }||
```

the displayed value is like `value is <div>xxxxx</div>`
I will find and try another way.

**Comment by tcnh** [comment]
What are you trying to achieve and what is the result you're seeing? Could you maybe share a screenshot of what you're experiencing?

Is the issue that html is not being escaped?

**Comment by ryukato** [comment]
Below is the Table with RestFixture.
```
| Table: Rest Fixture | ${url} |
| setHeader | ${defaultHeader} |
| addHeaders| ${addHeader} |
| setBody   | ${payload}       |
| POST | ${path}  | 201 | | |
| let  | testValue1     | js | JSON.parse(response.body).testValue |$testValue=|

```
I expected the value of `$testValue` does NOT have any html tag like `div`, but it does like `<div>xxxxx</div>`

Anyway, I resolved the issue by add following fixture.
```
public class Utils {
    public static String removeHTMLTags(String src) {
        return Jsoup.parse(src).text().trim();
    }
}

```
and I tried 
```
|script:Utils|
|$testValue=|removeHTMLTags|$testValue|
```

so I got the result without `div` html tag. But I still don't figure out why the value has `div` tag.

**Comment by tcnh** [comment]
The div is wrapped around the value you're getting or just around a part of it?
Isn't the div just a part of the response you're parsing? I don't think Fitnesse inserts html in slim symbols, so I'd guess if the html is not in your response object, RestFixture does some magic here? (but I don't use it, because I found it made my tests competely unreadable)

**Comment by ryukato** [comment]
Well, I am not so sure RestFixture did that, but the value definitely has `div` but the response does not. I will look into the RestFixture and let you know if find something. 
Thanks,

**Comment by mikerobski** [comment]
Looks like this is an issue with Rest Fixture - see this thread: https://github.com/smartrics/RestFixture/issues/73

**Comment by woodybrood** [comment]
@ryukato Is it OK if we close this?

**Comment by ryukato** [comment]
Sorry for late response. I will close this.
