### ISSUE TITLE
References to Fitnesse Yahoo group

### ISSUE THREAD

**Issue by MMatten** [unclebob/fitnesse#1250]
Apologies, I'm no longer sure where to post issues/queries.

Some test pages still include referenes to the Fitnesse Yahoo group (https://groups.yahoo.com/) that can no longer act as a support forum.

Are there any plans to migrate to a different support site / transfer the old content?

**Comment by fhoeben** [comment]
We should update these references. Thanks for pointing it out. 

Old content will not be transferred, as far as I know.
Issues and questions believe I best placed here on GitHub or on Stackoverflow. I believe these two locations have been much more active in recent years that the Yahoo group anyway.

Any change you have the opportunity to update the references to the group you found (via a PR on https://github.com/fitnesse/fitnessedotorg)?

**Comment by MMatten** [comment]
There seems to be some kind of copy of the yahoo content at nabble.com<http://nabble.com>. E.g. http://fitnesse.996250.n3.nabble.com/DBFit-Feature-Request-for-testing-Stored-Procedure-Result-Sets-td13051.html

 Not sure how it got there or if it will stay there. Maybe we could refer to this. What do you think?

I’m sure I can find some time to work on this over the next couple of weeks.

On 20 Dec 2019, at 15:30, Fried Hoeben <notifications@github.com<mailto:notifications@github.com>> wrote:


We should update these references. Thanks for pointing it out.

Old content will not be transferred, as far as I know.
Issues and questions believe I best placed here on GitHub or on Stackoverflow. I believe these two locations have been much more active in recent years that the Yahoo group anyway.

Any change you have the opportunity to update the references to the group you found (via a PR on https://github.com/fitnesse/fitnessedotorg)?

**Comment by MMatten** [comment]
There’s the still the option to move the content. 
https://groups.io/g/GroupManagersForum/wiki/Transfer-from-Yahoo-Groups

But I’m not sure if this will still work.
