### ISSUE TITLE
Things defined in SetUp ignored in test pages

### ISSUE THREAD

**Issue by ecamaj** [unclebob/fitnesse#1256]
As you can see in image, things defined in setup is not used in test page.  (although the value is propageted correctly, as it can be seen in using ${TEST_SYSTEM})

![image](https://user-images.githubusercontent.com/1902307/72536080-e278fe80-3879-11ea-995f-fa4970de616c.png)

If I repeat !define TEST_SYSTEM {slim} in test page, everything works ok.
It is the same with !path.

![image](https://user-images.githubusercontent.com/1902307/72536233-2835c700-387a-11ea-9f64-4fbc3cfe2e5f.png)

**Comment by fhoeben** [comment]
This is by design: both `!define TEST_SYSTEM` and `!path` statements should be placed on the page itself or (preferably) on one of its _parents_ not in a SetUp sibling.
