### ISSUE TITLE
Fitnesse variables in scripts disappear

### ISSUE THREAD

**Issue by lennyg1** [unclebob/fitnesse#1258]
```
!define test {12345}

|import           |
|fitnesse.fixtures|

|script|echo fixture|
|show  |echo|${test}|
```

When running this script, the ${test} variable doesn't render in the results and doesn't produce any output.

**Comment by tcnh** [comment]
This only occurs if you name your variable `test` as far as I can reproduce. Still strange, but I can imagine that that var may have a special meaning to slim? I think the easy workaround of not naming your variable test could suffice :)

**Comment by six42** [comment]
Hi @lennyg1  

assuming you named your wiki page: TestDefineTest

Extend it:

> !define test {12345}
> !define responder {abc}
> 
> |import           |
> |fitnesse.fixtures|
> 
> |script|echo fixture|
> |show  |echo|${test}|
> |show  |echo|${responder}|

Call it in these two ways:
```

http://localhost:8001/TestDefineTest?responder=test

http://localhost:8001/TestDefineTest?test
```

Then you will understand the feature.

Code: fitnesse.http.Request.parseQueryString
