### ISSUE TITLE
Could not create class file from file

### ISSUE THREAD

**Issue by matej2** [unclebob/fitnesse#1276]
Hello, 

I am working on some tests and when i change fitnesse fixtures, i oftenly get error:

> org.givwenzen.reflections.ReflectionsException: could not create class file from file

From this, i cant know where is the error. How or where can i find more detailed information on what is actually the problem?

**Comment by fhoeben** [comment]
It looks like this is an error from [GivWenZen](https://github.com/weswilliams/GivWenZen) I think you should create an issue there.

I you believe this actually is a FitNesse issues please provide some more details on what your wiki page looks like and what kind of change you are making to the fixtures and how.
