### ISSUE TITLE
Slow parsing in whole suite tree when using specfic variable syntax containing whole tables

### ISSUE THREAD

**Issue by sqeezy** [unclebob/fitnesse#1280]
In my team we used the following syntax for defining whole tables in variables:

```
!define VariableName {|script|Adapter Name|CtorArgument|
|Method|Parameter|}
```

Every addition of such a variable slowed down the whole wiki down from the place where this was defined. The growth in parsing time seems exponential. When it got obvious (~30 s) we searched for the problem. Putting the closing curly brace on a new line fixed the problem.

```
!define VariableName {|script|Adapter Name|CtorArgument|
|Method|Parameter|
}
```

This seems like something that should either fail or work faster.

**Comment by fhoeben** [comment]
Good find. No idea why it would get that slow. And how did you ever find the workaround?

Can you give some more details on what you encountered? 
- which FitNesse version
- what JVM
- which OS
- how much memory did the machine have, any special parameters to the JVM?
- what kind of complexity made it obvious?
  - can you describe the situation in which it was ~30s?
  - did it get worse by adding more pages, or only when using the variable more? Or only when you added more variables?
  - did it matter whether the variable was used in scenario libraries or other special pages (SetUp, SuiteSetUp)?
- anything else

**Comment by sqeezy** [comment]
* **which FitNesse version**
v20160618
* **what JVM**
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
* **which OS**
Win Server 2008 R2
_Don't judge ;)_
* **how much memory did the machine have, any special parameters to the JVM?**
12 GB total
About half of that free
* **what kind of complexity made it obvious?**
* **can you describe the situation in which it was ~30s?**
* **did it get worse by adding more pages, or only when using the variable more? Or only when you added more variables?**
* **did it matter whether the variable was used in scenario libraries or other special pages (SetUp, SuiteSetUp)?**
We have a large (~700) suite of integration tests for one of our programs. It all was working well until a few days ago. First the testers thought it was a server issue and didn't think much of it. When it got to the point of it taking 30 seconds we went in and investigated.
Luckily we have version control for our suite so the point in time when it got slow was easily found. After that it was just thinking of what could be the problem and luck. After finding that moving the curly brace in one variable, I tried out moving them all. From that point on the whole app was as fast as new. The whole problem seems only to scale with number of variables with curly braces in the last line.
As for the structure:
We store the variables in a seperate page and include that page into the top level suite page, so they can be used everywhere down from there.

**Comment by fhoeben** [comment]
@sqeezy Thanks for the details.
Since 2016 the page rendering has been refactored quite a bit. Is it possible to see whether the problem persists when upgrading to 20200404?

**Comment by sqeezy** [comment]
I tried updating to latest this morning and just rechecked. Didn't help sadly.

**Comment by fhoeben** [comment]
@sqeezy Thanks for checking. Too bad it made no difference.

**Comment by fhoeben** [comment]
I've been able to reproduce this behaviour by extending the unit test `fitnesse.wikitext.parser.DefineTest`:

Locally `definesManyTablesCurlyOnEndOfLine()` takes approx 1s, `definesManyTablesCurlyAtStartOfLine()` takes 60**m**s.

When I increase the count to 20 `definesManyTablesCurlyOnEndOfLine()` does not seem to end (at least I was not patient enough > 1 min); `definesManyTablesCurlyAtStartOfLine()` takes 125ms.

```
  @Test
  public void definesManyTablesCurlyOnEndOfLine() {
    checkMultipleTables("", 10);
  }

  @Test
  public void definesManyTablesCurlyAtStartOfLine() {
    checkMultipleTables("\n", 10);
  }

  private void checkMultipleTables(String postfix, int count) {
    WikiPage pageOne = new TestRoot().makePage("PageOne");
    StringBuilder sb = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    for (int i = 0; i < count; i++) {
      if (i > 0) {
        sb.append("\n");
        sb2.append("<br/>");
      }
      sb.append(createTableDefine("x", i, postfix));
      sb2.append(MakeDefinition(createExpectedDefinition("x", i, postfix)));
      sb2.append(HtmlElement.endl);
    }
    ParserTestHelper.assertTranslatesTo(pageOne, sb.toString(), sb2.toString());
  }
```

**Comment by jediwhale** [comment]
This is great. I should be able to isolate the problem with this test.

**Comment by fhoeben** [comment]
A bit of debugging to me suggests that `Table.endsRow(Symbol symbol)` probably does not expect a table to end without a newline.

**Comment by fhoeben** [comment]
@jediwhale I was a bit clumsy and pushed my idea for possible fix to master instead of to a branch (maybe I should have a no coding before 9AM rule, not just one for during the night ;-) ).
Can you take a look at it, and let me know what you think?

**Comment by jediwhale** [comment]
I've found and fixed the problem but I'm having problems setting up to build the whole project. Probably something obvious but I haven't worked with Java for several years...

> > Task :compileJava FAILED
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:202: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:205: error: cannot find symbol
      return delegate.checkTopLevelWindow(window);
                     ^
  symbol:   method checkTopLevelWindow(Object)
  location: variable delegate of type SecurityManager
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:219: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:223: error: cannot find symbol
      delegate.checkSystemClipboardAccess();
              ^
  symbol:   method checkSystemClipboardAccess()
  location: variable delegate of type SecurityManager
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:227: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:231: error: cannot find symbol
      delegate.checkAwtEventQueueAccess();
              ^
  symbol:   method checkAwtEventQueueAccess()
  location: variable delegate of type SecurityManager
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:258: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/mikes/code/fitnesse/src/fitnesse/slim/instructions/SystemExitSecurityManager.java:262: error: cannot find symbol
      delegate.checkMemberAccess(clazz, which);
              ^
  symbol:   method checkMemberAccess(Class<CAP#1>,int)
  location: variable delegate of type SecurityManager
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ?

**Comment by fhoeben** [comment]
@jediwhale I believe you're being too 'modern'. You're working with a Java version 11 or higher, I suspect. Try compiling with a Java 8 JDK.

**Comment by jediwhale** [comment]
Passes all unit and acceptance tests. Always a chance that it might break some unusual page in the wild.
