### ISSUE TITLE
FitNesse build error "Execution failed for task ':test' "

### ISSUE THREAD

**Issue by superherosalive** [unclebob/fitnesse#1281]
I'm trying to build FitNesse and I got this error below.  Does anyone know how to fix this error?

Any help pointing me to the right direction would greatly appreciate. Thanks!

Execution failed for task ':test' 

FitNesse.SuiteAcceptanceTests.SuiteSlimTests.TestSystemSlimSuite.ErrorSituationsDuringSlimServerStartup.B_TimeoutAsSlimServerDiesBeforeConnecting

java.lang.AssertionError	at fitnesse.junit.JUnitRunNotifierResultsListener.firstFailure(JUnitRunNotifierResultsListener.java:166)	at fitnesse.junit.JUnitRunNotifierResultsListener.testAssertionVerified(JUnitRunNotifierResultsListener.java:80)	at fitnesse.testsystems.CompositeTestSystemListener.testAssertionVerified(CompositeTestSystemListener.java:55)	at fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testAssertionVerified(MultipleTestsRunner.java:220)	at fitnesse.testsystems.CompositeTestSystemListener.testAssertionVerified(CompositeTestSystemListener.java:55)	at fitnesse.testsystems.slim.SlimTestSystem.testAssertionVerified(SlimTestSystem.java:197)	at fitnesse.testsystems.slim.SlimTestSystem.evaluateTables(SlimTestSystem.java:158)	at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:131)	at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:56)	at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:93)	at fitnesse.testrunner.run.PerTestSystemTestRun.executeTestSystemPages(PerTestSystemTestRun.java:64)	at fitnesse.testrunner.run.PerTestSystemTestRun.startTestSystemAndExecutePages(PerTestSystemTestRun.java:47)	at fitnesse.testrunner.run.PerTestSystemTestRun.executeTestPages(PerTestSystemTestRun.java:30)	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:67)	at fitnesse.junit.FitNesseRunner.executeTests(FitNesseRunner.java:580)	at fitnesse.junit.FitNesseRunner.runPages(FitNesseRunner.java:497)	at fitnesse.junit.FitNesseRunner.run(FitNesseRunner.java:478)	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)	at java.lang.Thread.run(Thread.java:748)

**Comment by six42** [comment]
Are you running under Windows 10?
Looks like #1254
Just comment out the test case (skip flag in properties) to finish the build.
The test has no issues under Linux or MacOS.

**Comment by superherosalive** [comment]
Yes I'm running it under Windows 10.  Can you elaborate on which file I need to change?  Sorry I'm new to FitNesse.

**Comment by fhoeben** [comment]
Change FitNesseRoot/FitNesse/SuiteAcceptanceTests/SuiteSlimTests/TestSystemSlimSuite/ErrorSituationsDuringSlimServerStartup/B_TimeoutAsSlimServerDiesBeforeConnecting/properties.xml

to include `<Prune>true</Prune>` or just `<Prune/>`.

For instance make its contents:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<properties>
<Edit>true</Edit>
<Files>true</Files>
<LastModifyingUser>six42</LastModifyingUser>
<Properties>true</Properties>
<RecentChanges>true</RecentChanges>
<Refactor>true</Refactor>
<Search>true</Search>
<Test>true</Test>
<Prune>true</Prune>
<Versions>true</Versions>
<WhereUsed>true</WhereUsed>
</properties>

```

**Comment by superherosalive** [comment]
Thanks fhoeben.

I changed the properties.xml as suggested.  I double check it just to make sure  but I still got the same error below:

fitnesse.junit.FitNesseSuiteExampleTestNoDebug > FitNesse.SuiteAcceptanceTests.SuiteSlimTests.TestSystemSlimSuite.ErrorSituationsDuringSlimServerStartup.B_TimeoutAsSlimServerDiesBeforeConnecting FAILED
