### ISSUE TITLE
Setup and TearDown does not get included in TestCase when standalone fitnesse server is run in Linux but issue is not seen in Windows

### ISSUE THREAD

**Issue by pb1981** [unclebob/fitnesse#1284]
Setup and TearDown does not get included when standalone fitnesse server(20200404) is run in Ubuntu Linux. This issue is not seen in Windows 7 or WIndows 10.
Tried with starting the fitnesse server and launching google chrome with 'sudo' mode but no help.
Does it require some plugin or some settings change in linux?

Test case executes fine if contents of Setup and Teardown  is pasted inside Test Page but that is not what I want.  Setup and Teardown  invokes some methods which every test case need to use before and after the Test Case, does not make sense to paste contents of Setup and Teardown in thousands of Test page.

Suite Structure is as below:
<img width="277" alt="SampleSnapshot" src="https://user-images.githubusercontent.com/26858530/80515192-2dd59980-899f-11ea-9c90-6447793913ec.PNG">

**Comment by tcnh** [comment]
Rename Setup to SetUp. Windows is not case sensitive, Linux has a real filesystem ;-)

**Comment by pb1981** [comment]
Thanks @tcnh  it solved the problem.
