### ISSUE TITLE
Can we have TAG_NAME as Fitnesse ENV Variable same as we have for RUNNING_PAGE_NAME

### ISSUE THREAD

**Issue by testengage** [unclebob/fitnesse#1312]
Currently if we need to call current running page we will be using variable ${RUNNING_PAGE_NAME}. Same it will be very helpful if we have anything like ${TAG_NAME} so that we can call Tag in fitnesse page and make it useful for other purpose example running testcase on multiple accounts with a tag name.

**Comment by fhoeben** [comment]
A page (or suite) may have many tags. What value do you expect to get in `${TAG_NAME}`? 
How does the page hierarchy, and symbolic links, affect the value of `${TAG_NAME}` (if at all)?

I expect you are aiming to run the same test (or suite) against different environments/accounts and want to change some values based on the environment currently being tested. If that's the case: have you looked at using symbolic links (to create a single suite containing the test definitions and then a suite per environment that contains only the environment settings and a link to the test definitions)? See also https://stackoverflow.com/questions/64765404/can-fitnesse-page-tags-be-used-in-page

**Comment by testengage** [comment]
Thanks @fhoeben got it. will work with the symbolic link solution.
