### ISSUE TITLE
Scenarios after test execution not foldable any more

### ISSUE THREAD

**Issue by reators** [unclebob/fitnesse#1313]
After upgrading FitNesse from `20200501` to `20201213` the scenarios that are used in a test script cannot be unfolded any more.

**Steps to reproduce**
1. Run a test which calls a scenario
2. Wait for test to finish
3. Try to press the '+' sign on the line where the scenario title is shown

<img width="738" alt="grafik" src="https://user-images.githubusercontent.com/17491139/103910954-bcd9aa80-5105-11eb-8795-2672969fd17d.png">

**Expected behavior**
The content of the scenario should be visible ("Get admin token" in this case)

**Configuration:**
 - OS: OS X Catalina
 - Browser: Firefox, Chrome, Safari
 - Version 20201213 of FitNesse
 - Test System: Slim
 - Plugins in use: HSAC

**Comment by fhoeben** [comment]
Are you using hsac-fixtures 4.23.1? Does your installation include the 'bootstrap-plus' plugin (included in sample hsac project or its standalone.zip), or are you using FitNesse's standard theme? What files are present in your 'plugins' directory, what's the content of your `plugins.properties`?

Are you running the test from the wiki, or is this a jUnit run test report?

Does this problem occur when you run `FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ScenarioTestSuite.ScenarioWithOutputParametersInScripts`, or are you able to expand the scenarios there?

For me locally (using Safari on a MacOS) it works just fine (using either bootstrap-plus or the standard theme). Can you provide a small test page showing the problem?

**Comment by reators** [comment]
- The installation is based on [HSAC Archetype project](https://github.com/fhoeben/fitnesse-project-archetype).
Is 'bootstrap-plus' plugin a dependency in pom.xml?
- I tried hsac-fixtures 4.22.0 and 4.23.1. Both have same behavior.
- Content of plugins-directory:
```
kf-infi-fitnesse $ ls wiki/plugins
hsac-fitnesse-plugin-1.28.0.jar					toolchain-fitnesse-plugin-2.0.10-jar-with-dependencies.jar
hsac-fitnesse-plugin-1.29.0.jar					toolchain-fitnesse-plugin-2.0.11-jar-with-dependencies.jar
hsac-fitnesse-plugin-1.29.1.jar					toolchain-fitnesse-plugin-2.0.8-jar-with-dependencies.jar
hsac-fitnesse-plugin-1.30.0.jar					toolchain-fitnesse-plugin-2.0.9-jar-with-dependencies.jar
toolchain-fitnesse-plugin-1.20-jar-with-dependencies.jar
```
- `plugins.properties` is empty:
```
kf-infi-fitnesse $ cat wiki/plugins.properties
kf-infi-fitnesse $
```
- Tests are run from wiki
- Execution of `FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ScenarioTestSuite.ScenarioWithOutputParametersInScripts` shows the same erroneous behavior: Scenarios are not expandable.
- I saved above execution using browser and put this together into a zip-archive. Unfortunately are the '+'-signs not shown on the html page. Maybe it helps detecting the problem.
[ScenarioWithOutputParametersInScript.zip](https://github.com/unclebob/fitnesse/files/5786380/ScenarioWithOutputParametersInScript.zip)

**Comment by tcnh** [comment]
These versions are causing your issues. When upgrading hsac version, you must run mvn clean to empty the plugins directory, so that there is exactly one hsac-fitnesse-plugin and one toolchain-fitnesse-plugin, both will have the latest version.

Easiest fix now: 
- Stop FitNesse
- Delete wiki/plugins
- Start FitNesse

**Comment by reators** [comment]
Yes, this helped!
Scenarios are foldable again.
I always use `mvn clean compile dependency:copy-dependencies` to build a new version. So a `clean` is always executed which doesn't seem to be sufficient.
The manual deletion of files in `plugins` and `webdrivers` directories made the difference.

Thanks for your support 👍🏻

**Comment by fhoeben** [comment]
If your project is based on the sample/archetype I believe it's [documented in the README.md](https://github.com/fhoeben/sample-fitnesse-project#upgrading) that one should execute a special command once on upgrading:
> After upgrading one should run `mvn clean -Pdelete-hsac-fitnesse-fixtures` 

:-)

**Comment by reators** [comment]
Good to know.
Thanks for the reminder ;)
