### ISSUE TITLE
[Question] accessing the value of Name of root folder (-r parameter) in wiki

### ISSUE THREAD

**Issue by Martinay** [unclebob/fitnesse#1314]
** General Description **
Hello,
I'm using Fitnesse slim and starting the fitnesse server with the r parameter:
`java -jar Server/fitnesse-standalone.jar -r Wiki`
I found that I can use the value of the -d Parameter in my wiki page with the ${FITNESSE_ROOTPATH} variable. Is there something similiar for the -r parameter?

Thank you for your help

**Comment by tcnh** [comment]
You can use `${FitNesseRoot}` to get the root directory name

**Comment by Martinay** [comment]
It's working. Thank you :)
