### ISSUE TITLE
Error when creating SymbolicLinks: The page to which you are attempting to link, xxx, doesn't exist.

### ISSUE THREAD

**Issue by LeiYangGH** [unclebob/fitnesse#1321]
Fail to create [SymbolicLinks](http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.SymbolicLinks).

**To Reproduce**
1. Download http://www.fitnesse.org/fitnesse-standalone.jar?responder=releaseDownload&release=20210410, run locally.
2. Navigate to http://localhost/FitNesse.SuiteAcceptanceTests', open properties page.
3. Try to create symbolicLink to FitNesse.SuiteAcceptanceTests.SuiteTestHistory.SuiteTestHistoryTests. failed. Also tried various pages, but high chances of failure.
4. The error message is 'The page to which you are attempting to link, xxx, doesn't exist.' see screen shots.
5. I also tried directly editing suite content, adding some lines such as `SymbolicLinks
  SomeName: FitNesse.SuiteAcceptanceTests.SuiteTestHistory.SuiteTestHistoryTests` but still not work.
6. The above page locations are randomly chosen, they do not mean the issue only happen for specific page.

**Expected behavior**
The symbolicLinks should be created if the page path is correct.

**Screenshots**

![fitlinkcreate](https://user-images.githubusercontent.com/5386998/116514053-0e988180-a8fd-11eb-914a-f77e1396217f.JPG)
![fiterror](https://user-images.githubusercontent.com/5386998/116514054-0e988180-a8fd-11eb-94a7-9ca76fc210b6.JPG)

 
**Configuration:**
 - OS: Win10 64
 - Browser chrome
 - Version 20210410(i tried some 2018 version and found this issue, and so tried latest version and still there)
 - Test System: [e.g. Fit or Slim]

**Comment by tcnh** [comment]
To Symlink an absolute path, start the path with a dot (.). So instead of linking to `SymbolicLinks SomeName: FitNesse.SuiteAcceptanceTests.SuiteTestHistory.SuiteTestHistoryTests`, you need to link to `.SymbolicLinks SomeName: FitNesse.SuiteAcceptanceTests.SuiteTestHistory.SuiteTestHistoryTests`

If you use bootstrap-plus, the sidebar has an option to directly copy the symlinkable path to the clipboard:
![image](https://user-images.githubusercontent.com/2232710/116529280-11837a00-a8dd-11eb-8aef-a6d4d933247e.png)

**Comment by LeiYangGH** [comment]
Thanks!

I tried, this time no error, but then back to the page(FitNesse.SuiteAcceptanceTests), i cannot find the link. 
did i miss anything?

![捕获1](https://user-images.githubusercontent.com/5386998/116550447-5d5c1080-a929-11eb-89fa-e37cc9bc567a.JPG)

**Comment by tcnh** [comment]
The symbolic link is added as a child of the page you link from, so you will only see it from a table of contents `!contents` or on the filesystem.

You should be able to verify its existence by typing >SomeName on your page. It will give you a link to the symlinked child.

**Comment by LeiYangGH** [comment]
Got it . I just tried and worked. The Fitnesse wiki grammer is really comprehensive.
Thanks!
