### ISSUE TITLE
BUG: Passing a slim symbol to scenario

### ISSUE THREAD

**Issue by teunisv** [unclebob/fitnesse#1324]
**Describe the bug**
Passing a slim symbol to scenario, and then adding a number to the variable does not work like expected

**To Reproduce**
Run sample wiki.

**Expected behavior**
Sample code should turn green

**Sample Wiki Structure/content**
(I added this to FitNesse.SuiteAcceptanceTests.SuiteSlimTests.SlimSymbols.TestSymbolsDontGetTurnedToStringsInTheOutput)
```|import|
|fitnesse.slim.test|

!|script|test slim|

!|scenario|should be bill1 _|value|
|check|echo string|@{value}1|bill1|

!|script|
|$x=|echo string|bill|
|should be bill1;|$x|
```

**Configuration:**
 - OS: windows 10
 - Browser : -
 - Version: 20210410
 - Test System: slim
 - Plugins in use: -

**Comment by fhoeben** [comment]
At the moment what you want to do is indeed not possible. The symbol usage must be terminated with something that is not a letter (technically it must match regex: `\$([A-Za-z\p{L}][\w\p{L}]*)`). Practically I believe this means you should end with a whitespace before adding more actual string content. So 
```
!|scenario|should be bill1 _|value|
|check|echo string|@{value} 1|bill 1|
```

would work.

I agree it's not very nice. But I'm not sure it can be changed without breaking backwards compatibility...

**Comment by teunisv** [comment]
Unfortunately the bill1 in this example can’t change.
Lucky for me it’s used in xpath, so I could used concat.

**Comment by fhoeben** [comment]
Looking a bit closer we can probably address this, without worrying too much about backwards compatibility. On the wiki side there is a fallback mechanism that looks for the shortest known symbol if the full regex match. So inside slim we can do the same.

The fallback mechanism is in [SlimTable$SymbolReplacer#getSymbolValue()](https://github.com/unclebob/fitnesse/blob/6e5f74340c91ef945e1d6d1d7477abeef78883c8/src/fitnesse/testsystems/slim/tables/SlimTable.java#L322-L331)

**Comment by six42** [comment]
Not sure if this fits your requirement but this should work:


!|scenario|should be bill1 _|value|
|$number=|echo string|1| 
|check|echo string|@{value}$number|bill1| 

!|script|
|$x=|echo string|bill| 
|should be bill1;|$x|
