### ISSUE TITLE
Non-backwards compatible change to fitnesse.testsystems.TestSystemListener in 20210516

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#1325]
In release 20210516 `fitnesse.testsystems.TestSystemListener#testOutputChunk()` was altered to take an additional parameter (for #1322). This breaks existing custom implementations (since they implement the method with a single parameter).

Accepting the additional parameter should be made optional so existing implementations continue to work. The overload accepting a single parameter should be marked as deprecated to allow existing implementations to be migrated.

**Comment by fhoeben** [comment]
This fix was not sufficient. Classes extending `fitnesse.reporting.BaseFormatter` still did not have backwards compatibility as it overwrote `testOutputChunk(TestPage page, String output)` with a no-op operation

**Comment by violinner** [comment]
Example EchoTestSystemFactory.java "has a" CompositeTestSystemListener, which "uses a" list of TestSystemListener, which must be overloaded to work.  How can EchoTestSystemFactory do this, as a working example?

Why this question?
Not sure if this is the correct place to comment;
Asking for assistance which can be applied to upgrade unsupported JBehave-FitNesse, an old plug-in, to latest FitNesse.
This is needed to mitigate security findings with old required dependencies.
