### ISSUE TITLE
Bind error when running multiple suites at once

### ISSUE THREAD

**Issue by abpadan** [unclebob/fitnesse#1326]
**Describe the bug**

java.net.BindException: Address already in use (Bind failed) error occurs within fitnesse when running multiple suites within fitnesse. This occurs when one submits runs a suite and then a couple seconds later runs another suite.

**To Reproduce**
1. Run a suite test
2. Run another suite test
3. One of the tests may complete and show all green
4. The other test should show the yellow java.net.BindException: Address already in use (Bind failed) resulting in the test not completing

**Expected behavior**
Expected both tests to complete and give a success.

**Screenshots**
<img width="1081" alt="Screen Shot 2021-06-18 at 11 29 08 AM" src="https://user-images.githubusercontent.com/12904597/122772697-3fe25d80-d26d-11eb-8cb7-89de9fd9ab38.png">

**Sample Wiki Structure/content**
!define slim.port {0}
!define TEST_SYSTEM {slim}

Both these variables have been defined with no success. The dockerfile exposes port 8080 has the following as the entry point command:

ENTRYPOINT ["java", "-Dslim.port=0", "-cp","/app.jar", "-jar", "/fitnesse-standalone.jar", "-p", "8080"]

**Stack Trace**
I'm not sure how to view the stacktrace on the fitnesse side. Please provide details and I will provide it.

**Configuration:**
 - Using docker open jdk.
 - Running with docker compose
     ports:
      - 8001:8080
      - 7000:8000

**Comment by fhoeben** [comment]
I assume you are running the two tests in different tabs of the same browser?

When you click on the 'Execution Log' button on the top of the page after the test fails. What do you get?

Can you share the docker log of the container running the wiki server?

**Comment by abpadan** [comment]
Correct, same browser with two separate tabs.

Here is the execution log of the test that fails:

Test page: | FitNesse.SuiteAcceptanceTests.SuiteSlimTests.TestHarnessSuite.KafkaAvro
-- | --
/usr/local/openjdk-8/bin/java -cp /app.jar:/fitnesse-standalone.jar fitnesse.slim.SlimService 33607
0
14 seconds

Jun 21, 2021 10:38:58 AM fitnesse.plugins.LegacyPluginFeatureFactory registerResponders
INFO: Registered responders from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:38:58 AM fitnesse.plugins.LegacyPluginFeatureFactory registerWikiPageFactories
INFO: Registered wiki page factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:38:58 AM fitnesse.plugins.LegacyPluginFeatureFactory registerTestSystemFactories
INFO: Registered test system factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:38:58 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:38:59 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:38:59 AM fitnesse.plugins.PropertyBasedPluginFeatureFactory$6 register
INFO: Loaded custom comparator glob: fitnesse.testsystems.slim.GlobComparator
Jun 21, 2021 10:39:04 AM fitnesse.plugins.LegacyPluginFeatureFactory registerResponders
INFO: Registered responders from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:04 AM fitnesse.plugins.LegacyPluginFeatureFactory registerWikiPageFactories
INFO: Registered wiki page factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:04 AM fitnesse.plugins.LegacyPluginFeatureFactory registerTestSystemFactories
INFO: Registered test system factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:04 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:04 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:04 AM fitnesse.plugins.PropertyBasedPluginFeatureFactory$6 register
INFO: Loaded custom comparator glob: fitnesse.testsystems.slim.GlobComparator
Jun 21, 2021 10:39:08 AM fitnesse.plugins.LegacyPluginFeatureFactory registerResponders
INFO: Registered responders from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:08 AM fitnesse.plugins.LegacyPluginFeatureFactory registerWikiPageFactories
INFO: Registered wiki page factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:08 AM fitnesse.plugins.LegacyPluginFeatureFactory registerTestSystemFactories
INFO: Registered test system factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:08 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:08 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:08 AM fitnesse.plugins.PropertyBasedPluginFeatureFactory$6 register
INFO: Loaded custom comparator glob: fitnesse.testsystems.slim.GlobComparator
Jun 21, 2021 10:39:10 AM fitnesse.plugins.LegacyPluginFeatureFactory registerResponders
INFO: Registered responders from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:10 AM fitnesse.plugins.LegacyPluginFeatureFactory registerWikiPageFactories
INFO: Registered wiki page factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:10 AM fitnesse.plugins.LegacyPluginFeatureFactory registerTestSystemFactories
INFO: Registered test system factories from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:10 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:10 AM fitnesse.plugins.LegacyPluginFeatureFactory registerSymbolTypes
INFO: Registered Symbol types from: fitnesse.testsystems.slim.CustomScriptTableRenderingPlugin
Jun 21, 2021 10:39:10 AM fitnesse.plugins.PropertyBasedPluginFeatureFactory$6 register
INFO: Loaded custom comparator glob: fitnesse.testsystems.slim.GlobComparator

The execution logs don't appear to give an indication of the bind error.

Here are the docker logs:

Jun 21, 2021 10:36:47 AM fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (/plugins.properties)
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at ./FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8080

**Comment by fhoeben** [comment]
I think you can ignore my questions, I think I found the issue.

You get this error only when running tests below 'FitNesse.SuiteAcceptanceTests.SuiteSlimTests' in parallel, correct?
The problem you see is not a general FitNesse problem, it is a problem in `fitnesse.fixtures.SetUp`. This fixture class (which is used in FitNesse's own acceptance tests) does not  support concurrent runs (on line 27 it hardcodes a port number).

I do not expect you need this class in your own tests so this should not cause problems for you. 
If you plan to run tests concurrently you should take this into account and in your test and fixture setup. Each concurrent run will be run in a separate process/JVM but global machine resources (such as ports and files) will be shared.

FitNesse's own acceptance tests are not intended to be run in parallel so I don't see much value in fixing this specific issue (I expect it will just uncover the next problem). But changing the port number at line 27 to 0 is not a lot of work. :-)

If you do need this class to work please let me know how you use it...

**Comment by fhoeben** [comment]
I believe I see you have your tests in `TestHarnessSuite` below `FitNesse.SuiteAcceptanceTests.SuiteSlimTests`. Do they need to be there? I would recommend placing your test in their own independent suite. For instance by placing the `TestHarnessSuite` directory next to the `FitNesse` directory below/inside the `FitNesseRoot` directory

**Comment by abpadan** [comment]
I'm exploring moving the TestHarnessSuite into fitness-root. Is there any advantage to having the tests where they are now? Right now I'm running into this issue with echo. The instance scriptTableActor.echo. does not exist. Is this something internal to the FitNesse library and thus not able to be leveraged outside of the FitNesse directory?

A lot of our tests are built in the current directory structure inside the FitNesse directory. It would involve a big overhaul getting everything outside of it but if it doesn't fit a paradigm it would make sense to improve it. Is having the port set to 0 an option?

**Comment by fhoeben** [comment]
The advantage to where the tests are now was probably no setup required to run tests using Slim.
The entire suite your tests are in now are part of the tests for FitNesse itself, its entire structure can be used as an example but is not intended to be a container for your own test. They are subject to change without notice.
Furthermore they are quite extensive (and somewhat complex) they complicate the environment for your own tests, which is something I would recommend against in general.

I did not dig into details but I suppose you get the 'echo' error because you are no longer setting up the 'echo fixture' as a library. You could do that by importing FitNesse's own fixtures and adding`fitnesse.fixtures.EchoFixture` as a library in you own SuiteSetUp. You could also create your own class to get a similar effect without depending on a FitNesse internal fixture, but there is no real need as I don't expect that old class to change in the near future). This allows you to use the methods of this class (e.g. `echo`) in any script table.
If moving your tests really has a big impact I'm sorry to say there is all the more reason to do it quickly. Your actual tests are intertwined with FitNesse's own and that is not a good thing (even if your testing your own FitNesse plugins or fixtures)

To be able to use 'echo' do something like (in a SuiteSetUp page):
```
|import|
|fitnesse.fixtures|

|library|
|echo fixture|
```

Setting the port to `0` in the `SetUp` class would address your problem, but would break existing tests that expect to know the port number a server is started at. That could of course be fixed, but I don't believe it is worth it.

**Comment by abpadan** [comment]
@fhoeben thanks for your feedback. So far I've been able to migrate the tests outside of the Fitnesse directory and deal with the issue directly. A code doesn't make sense here like you have suggested.
