### ISSUE TITLE
Missing close anchor on FitNesse.UserGuide.AdministeringFitNesse.ApplicationArchitecture

### ISSUE THREAD

**Issue by mbucc** [unclebob/fitnesse#1330]
**Describe the bug**
Starting from "The Test system subsystem is responsible", the rest of the page text behaves as a single href.

**To Reproduce**
1. Go to 'ApplicationArchitecture' page
2. Scroll down to 'Test execution engine'
3. See error

**Expected behavior**
Half of the page text should not be a single link.

**Screenshots**

<img width="854" alt="image" src="https://user-images.githubusercontent.com/85849/127637152-68e8f441-09bd-4667-9633-44cae04fc15e.png">
**Configuration:**
 - OS: osx
 - Browser safari
 - Version v20210606
 - Test System: n/a
 - Plugins in use: the default configuration

**Comment by djbrown** [comment]
I noticed the same bug on http://fitnesse.org/PlugIns
There might be a general problem with `!anchor` in FitNesse ([docs](http://fitnesse.org/FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.LinksWithinPages)).

I dug into this issue and looked at the **response** HTML (from the server):
```html
<h2 id="1">Test execution engine <a id="testsystem"/></h2>
The Test system subsystem [...]
<h2 id="2">System under test <a id="systemundertest"/></h2>
The system under test [...]
```

The **rendered** HTML (developer tools) looks like this:
```html
<h2 id="1">Test execution engine <a id="testsystem"></a></h2>
<a id="testsystem">The Test system subsystem [...]</a>
<h2 id="2"><a id="testsystem">System under test </a><a id="systemundertest"></a></h2>
<a id="systemundertest">The system under test [...]</a>
```

I guess modern browsers render the self closing anchor-Tag `<a />` differently from back when this feature was implemented. I'll try to find the code responsible for translating `!anchor xyz` to `<a id="xyz" />` . It should instead translate the template to `<a id="xyz`></a>`.
