### ISSUE TITLE
How to join FitNesse Community

### ISSUE THREAD

**Issue by zyjin** [unclebob/fitnesse#1331]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fhoeben** [comment]
Do you want to join the Slack community? Have you tried requesting access via the 'Slack Community' link on fitnesse.org (i.e. https://fitnesse-community-inviter.herokuapp.com/)?

**Comment by zyjin** [comment]
FitNesse Community

Failed! token_revoked




欢迎关注【测试工程师成长之路】微信公众号




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "unclebob/fitnesse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [unclebob/fitnesse] How to join FitNesse Community (#1331)





 
Do you want to join the Slack community? Have you tried requesting access via the 'Slack Community' link on fitnesse.org (i.e. https://fitnesse-community-inviter.herokuapp.com/)?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fhoeben** [comment]
@zyjin try https://join.slack.com/t/fitnessecommunity/shared_invite/zt-v768ud69-vKazT5Pfga_w_ayzkXIHTA
