### ISSUE TITLE
Build hangs because SuiteResponderTest takes forever

### ISSUE THREAD

**Issue by enexusde** [unclebob/fitnesse#1332]
**Describe the bug**
A gradlew build takes forever

**To Reproduce**
1. Checkout fitnesse
2. execute gradlew build
3. wait

**Expected behavior**
Expected is a complete build.

**Sample Wiki Structure/content**
If the problem has to do with how a file handled in the wiki or how it is parsed, please add a zip file containing files that demonstrate the problem.

**Standard output**
> C:\Users\xxx\Documents\fitnesse>gradlew build
> Configure project :
Building FitNesse v20210819...
<=========----> 72% EXECUTING [45m 50s]
> :test > 1014 tests completed, 91 skipped
> :test > Executing test fitnesse.responders.run.SuiteResponderTest

**Configuration:**
 - OS: Windows
 - Version Commit 2f3124713be669e462a956073aa6f2d8f841f264 of FitNesse

**Additional context**
The system is running on an very slow machine

**Comment by tcnh** [comment]
I could not reproduce this. My build finisches in 1m26.
You say you're running on a very slow machine; could it be that gradle has insufficient memory available?
