### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by benharvie** [unclebob/fitnesse#1334]
Hey there!

I belong to an open source security research community, and a member (@noobpk) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by fhoeben** [comment]
Thanks for pointing this out.

@noobpk can email: fitnesse-security *'at'* hsac *'dot'* nl

**Comment by noobpk** [comment]
Can you see my report on hunter.dev.?

**Comment by fhoeben** [comment]
Yes I was able to access it. Thanks for submitting it.

**Comment by fhoeben** [comment]
@noobpk I believe I addressed the issue you reported. It will be included in the next release.
