### ISSUE TITLE
[Question] How do I get JUnit testresults via command line?

### ISSUE THREAD

**Issue by Fastest-Turtle** [unclebob/fitnesse#1340]
## Have you looked at possible resources for answers? 
**Yes**

## If your answer isn't out there, please describe your question
I'm looking for any solution into creating testresults in JUnit from the downloaded HSAC FitNesse fixtures. 

All available commandline options from the [Restful Services](http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.RestfulServices) have failed so far. 

`java -jar fitnesse-standalone.jar -c "HsacExamples.SlimTests.BrowserTests.Angular2CalculatorTest?test&format=junit"`

I would like to create test result files that are automatically accepted by Azure DevOps, without using Maven.

**Comment by tcnh** [comment]
> I believe https://github.com/praegus/azuredevops-fitnesse-junit-runner is a runner specifically to run tests on Azure, but I haven't used that myself.

That is merely an extension to you HsacFitnesseRunner to also report to the AzDo API's. Requirements are the same (as we us the hsac runner for the junit and html results)
