### ISSUE TITLE
SuiteContentsFinder failure

### ISSUE THREAD

**Issue by mackokasp** [unclebob/fitnesse#1345]
Line like this defined in TestPage causes failure of Tree parsing

Example:
!define variable +1 {abc}

fitnesse.wikitext.parser.SymbolType.matchesFor(SymbolType.java:142)
16094 fitnesse.wikitext.parser.ParseSpecification.contains(ParseSpecification.java:137)
16095 fitnesse.wikitext.parser.ParseSpecification.terminatesOn(ParseSpecification.java:132)
16096 fitnesse.wikitext.parser.ParseSpecification.parseSymbol(ParseSpecification.java:116)
16097 fitnesse.wikitext.parser.ParseSpecification.parse(ParseSpecification.java:88)
16098 fitnesse.wikitext.parser.Parser.parse(Parser.java:144)
16099 fitnesse.wikitext.parser.Parser.parse(Parser.java:140)
16100 fitnesse.wikitext.parser.Parser.parseTo(Parser.java:115)
16101 fitnesse.wikitext.parser.Parser.parseTo(Parser.java:111)
16102 fitnesse.wikitext.parser.Parser.parseToAsString(Parser.java:76)
16103 fitnesse.wikitext.parser.Define.parseVariableValue(Define.java:44)
16104 fitnesse.wikitext.parser.Define.parse(Define.java:25)
16105 fitnesse.wikitext.parser.ParseSpecification.parseSymbol(ParseSpecification.java:118)
16106 fitnesse.wikitext.parser.ParseSpecification.parse(ParseSpecification.java:88)
16107 fitnesse.wikitext.parser.Parser.parse(Parser.java:144)
16108 fitnesse.wikitext.parser.SyntaxTreeV2.parse(SyntaxTreeV2.java:26)
16109 fitnesse.wikitext.parser.MarkUpSystemV2.parse(MarkUpSystemV2.java:16)
16110 fitnesse.wiki.BaseWikitextPage.parse(BaseWikitextPage.java:62)
16111 fitnesse.wiki.BaseWikitextPage.getSyntaxTree(BaseWikitextPage.java:55)
16112 fitnesse.wiki.WikiPageUtil.getXrefPages(WikiPageUtil.java:87)
16113 fitnesse.testrunner.SuiteContentsFinder.addXrefPages(SuiteContentsFinder.java:113)
16114 fitnesse.testrunner.SuiteContentsFinder.addAllXRefs(SuiteContentsFinder.java:107)
16115 fitnesse.testrunner.SuiteContentsFinder.addAllXRefs(SuiteContentsFinder.java:109)
16116 fitnesse.testrunner.SuiteContentsFinder.addAllXRefs(SuiteContentsFinder.java:109)
16117 fitnesse.testrunner.SuiteContentsFinder.addAllXRefs(SuiteContentsFinder.java:109)
16118 fitnesse.testrunner.SuiteContentsFinder.addAllXRefs(SuiteContentsFinder.java:109)
16119 fitnesse.testrunner.SuiteContentsFinder.addAllXRefs(SuiteContentsFinder.java:109)
16120 fitnesse.testrunner.SuiteContentsFinder.gatherCrossReferencedTestPages(SuiteContentsFinder.java:101)
16121 fitnesse.testrunner.SuiteContentsFinder.getAllPagesToRunForThisSuite(SuiteContentsFinder.java:42)

**Comment by jediwhale** [comment]
Thanks for the excellent repro. I'll take as look.
