### ISSUE TITLE
Fitnesse site not opening

### ISSUE THREAD

**Issue by kaushik-Das** [unclebob/fitnesse#1348]
Unable to open website http://fitnesse.org/

**Comment by AlexisHenriquez** [comment]
Me neither. Is the website down? If that is the case, where can we find all the content?

**Comment by fhoeben** [comment]
I fear the server hosting the site is down, I asked @unclebob to look at it (I believe it is an AWS EC2 instance managed by him).

@AlexisHenriquez most content is included in each FitNesse installation. Just open the (local) wiki and navigate to the 'FitNesse' page (e.g. http://localhost:8081/FitNesse).

_All_ content can be found in: https://github.com/fitnesse/fitnessedotorg. For instance the standalone.zip for the latest (20111030) release is at: https://github.com/fitnesse/fitnessedotorg/blob/master/releases/20211030/fitnesse-standalone.jar

**Comment by unclebob** [comment]
Someone took over managing the server about a decade ago.  I've been looking through old emails to find out who manages it now.  I suspect they are on holiday and will bring it up soon.  I'll keep looking through my emails in the mean time.

**Comment by unclebob** [comment]
Well, this is embarrassing.  While other people _had_ taken over the maintenance of fitnesse.org; I still had control of the server.  It's just that FitNesse is just such a solid system that I haven't had to touch that server in years.  But I finally checked my EC2 inventory and there it was.  So I rebooted it.  It seems to be up and working again.

**Comment by AlexisHenriquez** [comment]
Thank you very much!

**Comment by kaushik-Das** [comment]
Thank you @unclebob!
