### ISSUE TITLE
Variable content being interpreted while we want raw text

### ISSUE THREAD

**Issue by briceparmentier** [unclebob/fitnesse#1351]
Hello there,

I've googled a lot about this but couldn't find any answer. Also I don't know if this could be a bug or a feature request, so please be kind if I'm in the wrong section 😛 

I want to use for example existing FitNesse variable like ${RUNNING_PAGE_NAME} which gives me the current test page name.
This gives something like "MyPageName", which will be interpreted by the renderer as it is camel case syntax, so on the page it will be replaced by an HTML link like "<a href="blablabla">MyPageName</a>".
But in our case we want to use this "MyPageName" as raw text (without the HTML stuff around) to pass it along to the fixture code (C++ code using CSlim in our case).

I've tried a lot of combinations using !- -! to have markup literal text, but none worked. Always getting "${myVar}" (or "${RUNNING_PAGE_NAME}" in my example) as raw text, not the content of the variable.

Any thoughts on this one?
Thanks a lot in advance.

Brice

**Comment by jediwhale** [comment]
I couldn't find a way to do what you want! I think we might need a new predefined variable, e.g. RUNNING_PAGE_NAME_TEXT that is defined as literal text rather than the wiki name.

**Comment by tcnh** [comment]
You can do this using the (new-ish https://github.com/unclebob/fitnesse/pull/1310)  no links prefix (^) on your table. This will prevent the wiki from messing with your inputs by creating links on wiki words or e-mail addresses, but will still stranslate symbols like ${RUNNING_PAGE_NAME} or !today (as oppoed to using a ! as table prefix)

Example that sets the plain text value to a slim symbol:
```
|import           |
|fitnesse.fixtures|

^|script   |echo fixture             |
|$pageName=|echo|${RUNNING_PAGE_NAME}|
```

Outputs:
![image](https://user-images.githubusercontent.com/2232710/154237158-819f8d15-9809-4ad6-924d-de86aa706abb.png)

**Comment by six42** [comment]
Hi Bruce

Did you tried the table flags described here: http://fitnesse.org/FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupTable

**Comment by jediwhale** [comment]
I forgot about the table prefix flags!

**Comment by briceparmentier** [comment]
Hmmm thanks for this link, I will have a deeper look at and test it !
