### ISSUE TITLE
Unclosed collapsible sections make page rendering insanely slow.

### ISSUE THREAD

**Issue by renaudcepre** [unclebob/fitnesse#1371]
The usage of collapsible sections make page rendering insanely slow, exponentially if several sections are not closed.

**To Reproduce**
Write a test page with several unclosed  collapsible sections, and some long text (starts to be really long with hundreds of lines)
```
!**> section
Some long text ...
!**> section2
Some long text ...
```

**Expected behavior**
Maybe a warning or a timeout ?

**Configuration:**
 - OS: Windows
 - Version FITNESSE_VERSION=v20211030
 - Test System: Slim
 - Java 8

**Comment by mikestockdale** [comment]
Thanks. I should be able to fix the parser to handle this.

**Comment by woodybrood** [comment]
Keep in mind that the collapsed section could contain tables that need to be processed. Sometimes people don't want to show all of how the data is set up, so it's in a collapsed section.
