### ISSUE TITLE
The result xml  content is lost  <instructions>

### ISSUE THREAD

**Issue by cmaster007** [unclebob/fitnesse#1377]
Connecting to [http://XX.XX.0.XX:80/Access.BAutoDrmTestCase?suite&format=xml&includehtml
When  the testcase is t three hundred The  result  xml  content is lost instructions struct
error：
</content>
  </result>

right：
</content>
    <relativePageName>001</relativePageName>
    <instructions>
      <instructionResult>

**Comment by cmaster007** [comment]
error：
`</content>
  </result>`
right：
`</content>
    <relativePageName>001</relativePageName>
    <instructions>
      <instructionResult>`

**Comment by fhoeben** [comment]
To me it is unclear what you are doing and what the problem is.

> When the testcase is t three hundred The result xml content is lost instructions struct
