### ISSUE TITLE
What's wrong with fitnesse?

### ISSUE THREAD

**Issue by cmaster007** [unclebob/fitnesse#1379]
*D:\fitnesse\fitnesse20190119>java -jar -Xms16384M -Xmx16384M -Xmn512M -Xss1024K
-XX:MetaspaceSize=1024m  -XX:MaxMetaspaceSize=1024m fitnesse-standalone.jar  -a
password.txt -p 80
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
å…«æœˆ 04, 2022 12:56:18 ä¸‹åˆ fitnesse.ConfigurationParameter loadProperties
ä¿¡æ¯: No configuration file found (D:\fitnesse\fitnesse20190119\plugins.proper
ties)
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance test
ing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.MultiUserAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 80
Test system terminated with exception [fitnesse.testsystems.TestExecutionExcepti
on: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive
 data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionExcepti
on: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive
 data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionExcepti
on: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive
 data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionExcepti
on: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive
 data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionExcepti
on: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive
 data with SUT]

**Comment by fhoeben** [comment]
What are you doing when `Test system terminated with exception [fitnesse.testsystems.TestExecutionExcepti
on: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive
data with SUT]` is added to the console? I don't believe that is done immediately on startup, but only when some test is started.

Are you tests using test system 'slim' or 'fit'? Are your fixtures written in Java or some other language? Can you share the 'execution log' of the test runs that do not work?

**Comment by cmaster007** [comment]
My tests using test system 'slim'.  My fixtures writtern in Java

**Comment by fhoeben** [comment]
It looks like initially the test starts and then you have an error from RestFixture. Why FitNesse is then unable to communicate with the SUT is unclear to me, but it doesn't look like that immediately happens after the stack trace you posted as subsequent rows seem to get processed and the last row in your image seems to report an error coming from the SUT again.

Have you tried asking for assistance from RestFixture? To me this doesn't look like a FitNesse error...

(Looking at the error message I get the impression the response you receive does not have a `data` property and that is causing the stack trace you posted. But I have no experience with RestFixture so I could be completely wrong)
