### ISSUE TITLE
FitNesse.org needs a new home.

### ISSUE THREAD

**Issue by unclebob** [unclebob/fitnesse#1387]
I've been hosting fitnesse.org for twenty  years or so; but the time is coming when this should change.  I suggest that the contents of fitnesse.org be moved to a github static website.  Also, at some point, fitnesse deserves it's own github account.

**Comment by fhoeben** [comment]
@unclebob an account was created some time time ago (https://github.com/fitnesse). I think an easy step for the Git repo would be if you transferred ownership of the repo to that account. Would that we a good idea?

Currently the site is, of course, served using FitNesse itself. Technically I suppose we could have FitNesse itself generate a static site (although that would be a new feature to create) is that what your thinking of for serving it using GitHub?

**Comment by jediwhale** [comment]
FYI, I have a need for generating a static site from FitNesse, for another project of mine. If that's the way we want to go, I can raise my priority for that feature and start working on it.

**Comment by unclebob** [comment]
I'm happy to transfer ownership of the github site to github.com/fitnesse.  Does anyone know how to do that?  They have the concept of a "successor" which apparently would transfer ownership in the event of my death or incapacity.  Anyway, I'll keep looking into this.  

As for the static site, fitnesse.org is still running fine in one of my EC2 servers; but it would be better if the fitnesse community took this over somehow.  A static site is likely the best option.  God known how long that ancient version of FitNesse that powers fitnesse.org will continue to run.

**Comment by unclebob** [comment]
Hmmm.  Transferring ownership looks like it could be complicated.  We'd have to coordinate pretty closely to get it done.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by fhoeben** [comment]
It doesn't seem that complicated. But I just scanned quickly.

(And just to make it explicit: fitnesse.org is running the latest FitNesse as far as I'm aware. Although it's HTTP server features are no match for the latest static servers, of course)

**Comment by jediwhale** [comment]
I will get going on publishing a FitNesse site to a set of static HTML files. Then we can decide where to host them.

**Comment by jediwhale** [comment]
Just noticed the FrontPage at fitnesse.org is different from the FrontPage here in github. Anyone know where the fitnesse.org version came from?

**Comment by fhoeben** [comment]
fitnesse.org is served using the content from https://github.com/fitnesse/fitnessedotorg

When I release a new version of FitNesse:
 *  I run the `build-release.sh` script from https://github.com/fitnesse/fitnesse-release (I just noticed the description of the process in the `RELEASE.md` is a bit outdated, as Bintray no longer exists)
 * then I switch to my local copy of https://github.com/fitnesse/fitnessedotorg,
 * pull the latest changes from GitHub,
 * merge these into a separate branch that is tracking an 'ec2' remote (which is the server actually serving the site in production)
 * when I push these changes to the remote it stops the currently running process serving fitnesse.org and starts a new one using the latest content

**Comment by jediwhale** [comment]
I have a publish feature working and I want to test it on the fitnesse.org content. I looked in https://github.com/fitnesse/fitnessedotorg and I didn't find the user guide. I looked at the `build-release.sh` script but I didn't see how the user guide from https://github.com/unclebob/fitnesse gets copied - maybe I'm missing something?

**Comment by jediwhale** [comment]
I've published the fitnessedotorg content at https://jediwhale.github.io/fitnessedotorg The download links don't work because they use a DownloadResponder in the FitNesse server. So far, everything else looks good.

**Comment by jediwhale** [comment]
Option 3 looks good - I think github even counts the downloads :)

**Comment by jediwhale** [comment]
Back to work on this...  Playing a bit with github releases, looks like a good way to go. It generates release notes from the commit history.  I'm going to redo the publisher to use the velocity engine, since it's already being used and generating the html by hand is getting too complicated...

**Comment by jediwhale** [comment]
Please note a copy of the http://fitnesse.org site is now available at https://fitnesse.github.io/fitnessedotorg/ At this time, it only has a link to the latest version available for download.Let me know if you see any other differences or missing information in the github.io site. I'll add some of the older versions to the download page, and if everything else looks OK, we can point fitnesse.org to the github.io site.

**Comment by mh182** [comment]
I just want to mention that it would make sense to redirect requests from http://fitnesse.org/ and https://fitnesse.org to https://fitnesse.github.io/fitnessedotorg/.

I just read a book which provided the a link to http://fitnesse.org. My Firefox redirects http://fitnesse.org to https://fitnesse.org which shows an "Unable to connect" error.

**Comment by fhoeben** [comment]
@mh182 I believe there was an issue with the server of http://fitnesse.org/, but that is fixed now. For me that link now works again. Is your Firefox still taking you to a https url automatically (which indeed does not exist)?

@unclebob to me transferring the repo to the fitnesse organization on GitHub does not seem that complex. Can we maybe discuss the issues you see in further detail?

One thing I do see we need to do to take over fitnesse.org is that we would have to change the DNS registration for fitnesse.org to point to the GitHub static site instead. I believe there is some documentation at https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by mh182** [comment]
http://fitnesse.org/ is working now.

**Comment by aquddos123** [comment]
It looks like http://fitnesse.org broke again.

**Comment by fhoeben** [comment]
Back up

**Comment by aquddos123** [comment]
Thanks @fhoeben. Its working now.

**Comment by djbrown** [comment]
fitnesse.org seems broken again (Firefox and Chrome).
also docs.fitnesse.org doesn't work neither.
fitnesse.github.io/fitnessedotorg works fine though.

**Comment by fhoeben** [comment]
I believe the setup using GitHub pages to serve https://fitnesse.org works quite well.
And I am under the impression that you are not quite ready to transfer the repository to the `fitnesse` GitHub organization yet, @unclebob. 

Closing this issue
