### ISSUE TITLE
[Question] Can a wiki page NAME/PATH be parameterized to include in other wiki pages?

### ISSUE THREAD

**Issue by aquddos123** [unclebob/fitnesse#1400]
We have a scenario where we would like to dynamically change the included page name and/or path using other variables or system properties. For example:

`!define ENVIRONMENT1 {<values coming from command line arguments>}`

And then later in SuiteSetUp we want to use in to include specific pages. 

`!include .ParentPage.ChildPage.${ENVIRONMENT1}`
Or
`!include .ParentPage.${ENVIRONMENT1}.ChildPage`

Please note that SymbolicLinks feature is out of question. That does not serves our purpose. Thanks!

**Comment by aquddos123** [comment]
Never mind. I got it working.

**Comment by six42** [comment]
Hi Aquddos123,

Can you share how it works?
Will help others with the same question.

**Comment by six42** [comment]
Many Thanks Aquddos123 for taking the time to write and share your experience.
Your clear description will be beneficial for others.
