### ISSUE TITLE
Release process failure

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#1404]
I tried to upload release version 20221219 using the `build-release.sh` script in https://github.com/fitnesse/fitnesse-release and then publish that to fitnesse.org via https://github.com/fitnesse/fitnessedotorg

This did not go as expected:
 * the contributors and git changes were no retrieved correctly
 * the created version did not have FITNESSE_VERSION set correctly causing fitnesse.org to look like:
<img width="605" alt="Screenshot 2022-12-19 at 09 50 16" src="https://user-images.githubusercontent.com/5467859/208389907-e5edf77e-78f5-4e8f-aa93-d42bee33f95d.png">
<img width="1046" alt="Screenshot 2022-12-19 at 09 50 02" src="https://user-images.githubusercontent.com/5467859/208389928-82928724-f2aa-4689-9c31-2c905a4a5b53.png">

In the standalone.zip the FITNESSE_VERSION seems to be ok, `META-INF/FitNesseVersion.txt` is present and contains `v20221219`

@jediwhale can you publish the new release (which is [present in Maven Central](https://repo1.maven.org/maven2/org/fitnesse/fitnesse/20221219/)), via the new approach, to GitHub releases and update the generated static site?
Can we switch the release process to just use that approach? What should the process look like (manually) and can we automate that process using a shell script of (preferably) using a GitHub action?

**Comment by jediwhale** [comment]
I'll fix it

**Comment by jediwhale** [comment]
fitnessedotorg is updated. I'll update the build-release script.

**Comment by fhoeben** [comment]
@jediwhale can you setup a GitHub action to publish the updated site? 

Something like described in https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

Once we have to build process fully controlled once again we can check with @unclebob whether we can have fitnesse.org point to the GitHub pages. Then the EC2 site is no longer required I suppose

**Comment by jediwhale** [comment]
Updated build-release.sh to generate static pages. Added instructions to create release page on GitHub. Removed creation of release page on fitnesse site.

I tried to push to the fitnesse.org site but I don't have permission.

I haven't used github actions before, so I will look at publishing with github actions but it might take a while.

**Comment by fhoeben** [comment]
@jediwhale I've pushed your changes to fitnesse.org. Thanks for making the updates.

With your updated descriptions I believe using GitHub actions to publish a new release (in Maven Central and GitHub) and updating the GitHub.io pages should not be very hard. Let me know if I can assist in any way.
