### ISSUE TITLE
[Question]The fit  response GMT time ,how to set local time?

### ISSUE THREAD

**Issue by cmaster007** [unclebob/fitnesse#1417]
![image](https://user-images.githubusercontent.com/35914039/219589773-ddbcad5c-b3e4-4613-9ead-d667981f6b2a.png)

**Comment by fhoeben** [comment]
This is a question for the [rest fixture project](https://github.com/smartrics/RestFixture).

Furthermore it looks like the fixture is just showing the response the server sent. In that case it is up to the server what it sends exactly (and which time zone is used). Maybe you can first extract the timezone and use a dedicated fixture to convert to another (local) timezone from whatever the server sent.

**Comment by cmaster007** [comment]
ok，thanks
















在 2023-02-17 16:22:15，"Fried Hoeben" ***@***.***> 写道：

Closed #1417 as completed.
