### ISSUE TITLE
[Question] OAuth2/OIDC support

### ISSUE THREAD

**Issue by mellmann-dtit** [unclebob/fitnesse#1421]
Hello guys at FitNesse,

are there any future plans to support OAuth2/OIDC with FitNesse?

Thanks and regards
Sebastian

**Comment by fhoeben** [comment]
There are no plans at the moment as far as I'm aware.

I assume you want to have this for a 'central wiki server' to do authentication and authorization?

I have to admit I always use FitNesse either locally or on a build server and in neither case authentication (to FitNesse) is of any importance. Access to the tests (i.e. the wiki files) is controlled based using version management (Git). And test results are retrieved, as job artifacts, from the CI server (which has its own access control).

I know there is [an LDAP integration](https://github.com/timander/fitnesse-ldap-authenticator) that might be a starting point to build authentication using OAuth2 if you would want to look into building it. But it is not actively maintained as far as I can tell.
