### ISSUE TITLE
Convert content.txt to .wiki

### ISSUE THREAD

**Issue by denkist** [unclebob/fitnesse#1430]
Within my company we use Fitnesse in 'the old way' i.e. with a properties.xml and a content.txt file. We are in the process of converting to .wiki format. We do this by renaming the suites/pages to TMP and back again to its original name. This way the properties.xml and content.txt are automatically converted to .wiki format by Fitnesse itself

## The isssue:
We use a lot of Powershell code to orchestrate our nightly test process which we have to change so we can utilize our existing code base. The properties.xml and content.txt files are in a windows format, i.e. with a Carriage Return/Line feed (CRLF) at the end of each line. When converting to .wiki format the CRLF pairs are changed in unix Line Feeds (LF).

## The question:
Is there a way to automatically use CRLF instead of LF while converting? Using a property in plugins.properties for instance?

Thanks in advance
Peter

**Comment by fhoeben** [comment]
I don't believe there is (I am not even sure CRLF .wiki files work properly to be honest).
But if it works I see no harm in supporting this, so you could try to make a PR to allow this.

An alternative might be (assuming you are using version control to store your tests) to have your version control system automatically update line endings to the platform specific format on checkout. That way you don't have to worry about it either way.
