### ISSUE TITLE
Example FitNesse plug-in EchoTestSystemFactory requires a TestSystemListener.

### ISSUE THREAD

**Issue by violinner** [unclebob/fitnesse#1431]
**Describe the bug**
In FitNesse version 20221219 source, the
Example plug-in fitnesse.testsystems.example.EchoTestSystemFactory is missing a workable example fitnesse.testsystems.TestSystemListener .

**To Reproduce**
EchoTestSystemFactory refers to TestSystemListener.
TestSystemListener.testOutputChunk() throws "UnsupportedOperationException("This overload is deprecated..."

**Expected behavior**
Please provide an example TestSystemListener overload which writes output to a working formatter.

**Screenshots** - n.a.

**Sample Wiki Structure/content** - n.a.

**Stack Trace** -
outputChunk throws UnsupportedOperationException.

**Configuration:** - n.a.

**Additional context**
Attempting to upgrade the 2015 FitNesse JBehave FitNesse plug-in from version 20191229 to 20221219.
After refactoring, I am missing the communication between the CompositeTestSystemListener and formatters to write output back to the FitNesse report.

**Comment by fhoeben** [comment]
I have to admit I haven't looked at test systems in a while.
A quick first glance suggest callers should use `testOutputChunk(TestPage testPage, String output)` and that is also what I see being done in `EchoTestSystem` (line 55 of fitnesse/testsystems/example/EchoTestSystemFactory.java), and multiple other places in the code base.

What exactly are you looking for?

**Comment by violinner** [comment]
I am unable to create a project due to company rules.

Is it possible to get the EchoTestSystem to work with the most recent version of FitNesse?
It appears to have the same problem that JBehave has.

**Comment by violinner** [comment]
The default listener outputs report "chunks" as expected to the final report (html/text/xml/etc.)

The only change is to avoid "outputChunk(message)" without a TestPage argument.
