### ISSUE TITLE
Will there be a release to fix security vulnerability in json?

### ISSUE THREAD

**Issue by danio** [unclebob/fitnesse#1432]
There is a vulnerability in org.json:json 20220924 that is fixed and dependabot has updated  on Feb 27th : #1420 

Are there any plans to make a release with this (and the other improvements since last December)?

**Comment by fhoeben** [comment]
https://github.com/unclebob/fitnesse/releases/tag/20230503

**Comment by danio** [comment]
Thanks @fhoeben !
