### ISSUE TITLE
Unicode WikiWord Parse problem

### ISSUE THREAD

**Issue by woodybrood** [unclebob/fitnesse#144]
I upgraded fitnesse today, and got a problem that might be a bug. A wiki-page with a wikiword containing Unicode fails, for example a context.txt with 

DennaDör

renders
java.lang.IllegalArgumentException: Can't parse path: DennaDör
fitnesse.wikitext.parser.WikiSourcePage.makeFullPathOfTarget(WikiSourcePage.java:68)
...

My workaround so far is search-replacing to !-DennaDör-! which works. But since the previous version was fine, I'm guessing this is a bug, but I am grateful for any input on this.

All wiki-files are in UTF-8.

Cheers Jonas

**Comment by caiofbpa** [comment]
I would like to reopen this since I've tried to use any char from this list `çãõáéíóúôêâ` in WikiWords and it didn't work. The test created in the commits referenced here isn't present in the latest releases.
