### ISSUE TITLE
The java process memory of fitnesse keeps growing

### ISSUE THREAD

**Issue by cmaster007** [unclebob/fitnesse#1441]
I had a problem. When I deploy the jenkins on the window server 2016.
 Trigger multiple tasks to access the fitnesse with the pipeline parallel on the jenkins. The java process memory of fitnesse keeps growing. After the task, the memory is not released, and the memory is exhausted. I access the fitnesse with the fitnesse plug-in of jenkins. Is there a solution for this situation? Can you give you some directions? thanks very much.

**Comment by fhoeben** [comment]
I have no experience using the Jenkins plugin, sorry.

I've always just set up jUnit tests (using maven or docker) with the HTML reports published using Jenkins. (But it has been a while.)
Have you tried that approach, does that work for you? In my experience it was very simple to setup and maintain and that just worked (also when updating FitNesse versions). (I also liked it as it worked on all CI/CD servers: GitLab, TeamCity, Jenkins, etc.)

In that setup each task has each own (completely independent) process so there couldn't possible be memory leaks between tasks.
I wrote a small utility to combine the reports of all separate processes into a single overall HTML report, which I run as a final task after all test tasks have finished.
The required setup in Maven's `pom.xml` and source files can be found in: https://github.com/fhoeben/hsac-fitnesse-fixtures. The README of this project has a [description on how to run the tests](https://github.com/fhoeben/hsac-fitnesse-fixtures#to-run-the-tests-on-a-build-server).

**Comment by fhoeben** [comment]
Closed due lack of activity
