### ISSUE TITLE
Java-11 compatible version of FitNesse is in Maven Central

### ISSUE THREAD

**Issue by violinner** [unclebob/fitnesse#1459]
Maven Central has available (gradle specification): 'org.fitnesse:fitnesse:20231029'
Where was this created?  It is not listed in the Releases section of this project.

Reference: https://mvnrepository.com/artifact/org.fitnesse/fitnesse/20231029

**Comment by fhoeben** [comment]
It was created by us (me actually) we have an issue on the server hosting fitnesse.org preventing us from using the new version there. Therefore it is also not yet displayed there.
But the FitNesse version itself should be fine: give it a try!
