### ISSUE TITLE
Running test suite with format XML stops at first date field in result

### ISSUE THREAD

**Issue by essenius** [unclebob/fitnesse#1483]
**Describe the bug**

I am running FitNesse in automated builds, and I use the XML format to be able to transform it via XSLT. I ran into a similar symptom 
as https://github.com/unclebob/fitnesse/issues/1440 but I think it has a different cause.  

I've created a GitHub Action that shows the problem. I have a hunch it was introduced with https://github.com/unclebob/fitnesse/pull/1406. I'm thinking that because it was running fine when I ran FitNesse v20220319, and now I moved to the latest version 20231203 I see the issue. 

Check out https://github.com/essenius/FitNesseAction. I get the issue when running https://github.com/essenius/FitNesseAction/blob/main/.github/workflows/fitnesse-run.yml  

**Expected behavior**
I was expecting to get a complete XML document, but the test process got killed prematurely. 
The output came no further than this:

```
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20231203</FitNesseVersion>
  <rootPath>DemoSuite</rootPath>
  <date>
```

**Screenshots**
No screenshots, but here are the log/result files that got generated.

[fitnesse-demosuite.zip](https://github.com/unclebob/fitnesse/files/14202447/fitnesse-demosuite.zip)

**Sample Wiki Structure/content**
See the repo

**Stack Trace**

Here is the error message: 
```
Executing command: DemoSuite?suite&format=xml&nochunk&includehtml
Test system terminated with exception [Invocation of method 'getDateString' in  class fitnesse.reporting.history.SuiteExecutionReport threw exception java.lang.NullPointerException at suiteXML.vm[line 5, column 31]]
```

**Configuration:**
 - OS: Linux (GitHub hosted)
 - Browser N/A
 - Version  of FitNesse: 20231203
 - Test System: Slim
 - Plugins in use: None, but using FitSharp 2022.11.13 as test runner.

**Additional context**

**Comment by fhoeben** [comment]
@essenius  Thanks for the complete setup to show the issue. But there are quite a few moving parts to the issue. Is it maybe possible to produce a simpler setup that also shows the issue?

For instance, does the problem also occur when your GitHub action runs one of FitNesse's own Slim-based acceptance tests (or suite), for instance FitNesse.SuiteAcceptanceTests.SuiteSlimTests.TestScriptTable. That would remove FitSharp, and the whole .Net part, of out of scope. Based on the error message it seems the error occurs inside FitNesse own processing of test results in it's Java process so the test runner might not be relevant.

**Comment by fhoeben** [comment]
@essenius I've been doing some debugging and I believe I found the following:

- The problem only occurred in you FitSharp workflow, the pure Java one worked fine
- There is a problem in FitNesse where no start time was recorded if the test system failed to started, leading to the error you observed so the actual problem was completely obscured.
- In your workflow the FitSharp system fails to launch. When I bypassed the faulty error processing I got the following XML. I hope this can help you figure out what the real problem is (to me it seems like the runner only has .Net 6 installed and .Net 5 is needed). I hope when this is addressed even the current FitNesse version because usable with you action again.

```
<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20240214</FitNesseVersion>
  <rootPath>DemoSuite</rootPath>
  <date>$suiteExecutionReport.dateString</date>
  <pageHistoryLink>DemoSuite?pageHistory&amp;resultDate=$suiteExecutionReport.resultDate</pageHistoryLink>
   <executionLog>
    <testSystem>slim:dotnet</testSystem>
    <command>dotnet /home/runner/work/FitNesseActionTest/FitNesseActionTest/fitsharp/net5.0/Runner.dll -c ./config.xml 8475</command>
    <exitCode>150</exitCode>
      <stdOut></stdOut>
      <stdErr>You must install or update .NET to run this application.

App: /home/runner/work/FitNesseActionTest/FitNesseActionTest/fitsharp/net5.0/Runner.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: /home/runner/.dotnet/

The following frameworks were found:
  6.0.27 at [/home/runner/.dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&amp;framework_version=5.0.0&amp;arch=x64&amp;rid=ubuntu.22.04-x64
</stdErr>
      <exception>Error SLiM server died before a connection could be established. https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&amp;framework_version=5.0.0&amp;arch=x64&amp;rid=ubuntu.22.04-x64</exception>
   </executionLog>
  <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>-1</totalRunTimeInMillis>
</testResults>

```

**Comment by essenius** [comment]
Thanks @fhoeben - I'll do some more digging.
