### ISSUE TITLE
Can a template template access a markup variable whose name is argument to the table template ?

### ISSUE THREAD

**Issue by pvbemmelen62** [unclebob/fitnesse#1484]
I have multiple markup variables, XML_BODY_1 and XML_BODY_2, and want to tell a table template which one to use, using a table template argument.
I can't get it to work.

<pre>
!define url {http://whatever/someservice}

!define XML_BODY_1  { {{{
  soap body one
  multiline
}}} }

!define XML_BODY_2  { {{{
  soap body two
  multiline
}}} }

|script|xml http test|

|table template|send request              |
|post          |${@{body}}     |to |${url}|
|check         |response status|=~/20[02]/|
|show          |request                   |
|show          |response                  |

|send request|
|body        |
|XML_BODY_1  |

</pre>

Running the above script, in the run log shows for the post line:

`post    ${XML_BODY_1}   to      http://whatever/someservice`

Thus: the value for XML_BODY_1  is not substituted in the line.

I've tried
`$@body`
and
`$@{body}`
but they didn't give the desired result.

I did get it to work if instead of markup variables (!define)  , I use slim symbols :
<pre>
!define url {http://whatever/someservice}

|script      |xml http test|
|$XML_BODY_1=|echo         |{{{
  soap body one
  multiline
}}}|
|$XML_BODY_2=|echo|{{{
  soap body two
  multiline
}}}|

|table template|send request              |
|post          |$@{body}       |to |${url}|
|check         |response status|=~/20[02]/|
|show          |request                   |
|show          |response                  |

|send request|
|body        |
|XML_BODY_1  |
</pre>

It's just that the syntax for the slim variable definitions , is not as simple and elegant as the markup variable definitions.
So it would be nice if I could get it to work using markup variables.

**Comment by fhoeben** [comment]
I think the following should work, sending the wiki variable as input to the table template. Have you tried that already?
```
!define url {http://whatever/someservice}

!define XML_BODY_1  { {{{
  soap body one
  multiline
}}} }

!define XML_BODY_2  { {{{
  soap body two
  multiline
}}} }

|script|xml http test|

|table template|send request              |
|post          |@{body}       |to |${url}|
|check         |response status|=~/20[02]/|
|show          |request                   |
|show          |response                  |

|send request |
|body         |
|${XML_BODY_1}|
```

**Comment by pvbemmelen62** [comment]
Yes, that works! And it looks nice in the editor.
In the run log the xml body is shown twice, though, as result of passing the value of the variable, and not its name:

![image](https://github.com/unclebob/fitnesse/assets/11163367/c03815a2-8c20-499a-a021-eb51bb88906a)

That xml body may be large.
That's the tradeoff, I guess.
