### ISSUE TITLE
When run Suite test, cannot read test history is not saved

### ISSUE THREAD

**Issue by JGProg** [unclebob/fitnesse#1489]
**Describe the bug**

**To Reproduce**
1. Go to 'Suite test'
2. Click on 'Suite'
3. Go to 'One test on Suite test'
4.  Click on 'Tools'
5.  Click on 'Test history'
6. Click on 'Lest result'
7. No "execution log" button appear

**Expected behavior**
Possible to see console ouput
![screen](https://github.com/unclebob/fitnesse/assets/1257401/1d281102-f6f5-4abe-b643-a3b875113e91)

**Configuration:**
 - OS: Windows
 - Browser edge
 - Version [e.g. 20240217] of FitNesse
 - Test System: [e.g. Fit ]

**Comment by JGProg** [comment]
The problem came Fitharp

**Comment by fhoeben** [comment]
@JGProg can you elaborate what was happening in FitSharp? I'm looking into #1483 and there I also see that running test with FitSharp creates an issue in the test reporting that does not occur with Java Slim
