### ISSUE TITLE
fitnesse  compile error how to  fix it?

### ISSUE THREAD

**Issue by cmaster007** [unclebob/fitnesse#1497]
F:\sourcecode\fitnesse-20230503>gradlew.bat standaloneJar
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :buildSrc:test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

> Configure project :
Building FitNesse v20240316...

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\sourcecode\fitnesse-20230503\build.gradle' line: 56

* What went wrong:
A problem occurred evaluating root project 'fitnesse'.
> Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by cmaster007** [comment]
Execution failed for task ':jar'.
> Cannot fingerprint input file property 'rootSpec$1$1$1': Failed to create MD5 hash for file content.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by six42** [comment]
Reboot your windows pc and retry.
There are some processes running blocking writing a file.

**Comment by cmaster007** [comment]
[compile.txt](https://github.com/unclebob/fitnesse/files/14633894/compile.txt)

**Comment by cmaster007** [comment]
java version "1.8.0_191" + gradle 7.6.3

**Comment by cmaster007** [comment]
![Uploading 捕获.PNG…]()

**Comment by cmaster007** [comment]
hi:
    i see，The issue persists  even after i switched to a new computer ,and it has been bothering me quite some time.
Can you inform which version of Gradle can successfully compile with java 8 in a Windows 10 environment,or any other successul compilation scenarios ?
















At 2024-03-16 23:05:05, "six42" ***@***.***> wrote:

Reboot your windows pc and retry.
There are some processes running blocking writing a file.

**Comment by fhoeben** [comment]
You state that you are trying to compile with Java 8, that will no longer work. FitNesse switched to Java 11 (end of October last year, commit `389bb593`)
