### ISSUE TITLE
Slim GracefulNaming, misleading documentation in the UserGuide

### ISSUE THREAD

**Issue by alexejSchwarz** [unclebob/fitnesse#1499]
## Problem encountered

While learning about FitNesse and more concretely about Slim, I stumbled upon this [Wiki page](https://fitnesse.org/FitNesse/UserGuide/WritingAcceptanceTests/SliM/GracefulNames.html) from the UserGuide on the topic of GracefulNames in Slim. There is the following table provided:  

![gracefulNameFromDoc](https://github.com/unclebob/fitnesse/assets/160615784/f95e802c-d608-44a8-99f5-33e5b9dffd1a)  

From my understanding the table implies that one could use **_"slim test"_** or **_"slim test."_** in a test table column to define the method to be used. However, when doing so in a test the program assumes this column to be a field rather than a method (as the "?" postfix is absent). In addition the description above the table:  

"_A graceful name looks like it is written in human language rather than computer language. It has spaces that separate the words and **may have a period** at the end_."...    

...further implies to me, that such naming of methods in FitNesse front end is possible.  

In the end a quick real test scenario will disprove this implication, but none the less it does lead to confusion in my opinnion. Maybe a disclaimer above or an addition of the correct postfix in the table could prevent any confusion. Or the table could be split up in three. One for the graceful naming of methods, one for fields and one for for fixture naming.

**Comment by six42** [comment]
Hi Alexej,
 
Which kind of table you tested and what didn't worked as expected? 
Can you post your example? 

You are right that the graceful naming is rather a general concept and might slightly vary based on the table type. 
The individual table descriptions should make this clear:

<https://fitnesse.org/FitNesse/UserGuide/WritingAcceptanceTests/SliM.html>

If you want more flexibility look at the hybrid decision table:


<https://fitnesse.org/FitNesse/SuiteAcceptanceTests/SuiteSlimTests/HybridDecisionTable.html>

**Comment by alexejSchwarz** [comment]
@six42   

I have used this [table](https://fitnesse.org/FitNesse/UserGuide/WritingAcceptanceTests/SliM/DecisionTable.html):  

![initTest](https://github.com/unclebob/fitnesse/assets/160615784/112c2100-f45c-4aef-93e4-0e6e1c4be56f)  

I changed the method name to "go to store"  

![gracefulMethodName](https://github.com/unclebob/fitnesse/assets/160615784/d9e0f824-3eee-41f1-9edc-9dd5018cfa30)  

FitNesse thinks that goToStrore is now a field rather than a method.  

In the doc for Slim [GracefulName](https://fitnesse.org/FitNesse/UserGuide/WritingAcceptanceTests/SliM/GracefulNames.html) There is the Implication that "go to store" would also be a graceful name for a goToStore(...) method.  

![implication](https://github.com/unclebob/fitnesse/assets/160615784/e2b29e1b-a231-465f-9dd1-85c814524e73)

**Comment by fhoeben** [comment]
@alexejSchwarz you are indeed right that the description given for graceful names is not correct when it comes to the column headers in a decision table. It could be made much more clear on this graceful names page that this is a strategy and the exact implementation depends on the  type of table being executed.

I believe the listed method names listed are correct for a "script table" but a decision table doesn't actually work with methods, it works with properties. The decision table first determines the property name and then based on that (using the standard Java convention to go from property to either 'getter' or 'setter') determines a method name.

If you then look at a [dynamic decision table](https://fitnesse.org/FitNesse/UserGuide/WritingAcceptanceTests/SliM/DynamicDecisionTable.html) there are only 2 methods (`get()` and`set()`) and the column names are passed directly to these methods (no graceful naming involved at all)

And a [query table](https://fitnesse.org/FitNesse/UserGuide/WritingAcceptanceTests/SliM/QueryTable.html) also doesn't use method names, but the columns map to 'columns' in the result.

**Comment by alexejSchwarz** [comment]
@fhoeben I see. Thanks for the clarification. Should I close the Issue or what is the further procedure?

**Comment by fhoeben** [comment]
I think we can leave the issue open for now, since we agree the documentation could be improved.

If you have the time we would appreciate you making a PR with improved content for [this page](https://github.com/unclebob/fitnesse/blob/master/FitNesseRoot/FitNesse/UserGuide/WritingAcceptanceTests/SliM/GracefulNames/content.txt) to make it more clear for future readers

**Comment by alexejSchwarz** [comment]
@fhoeben I am pretty new to collaborative work on GitHub and I do not know exactly how to do a proper PR. However, I do have a modified Version for the specific page: [content.txt](https://github.com/unclebob/fitnesse/files/14667915/content.txt)

**Comment by fhoeben** [comment]
Do you think this is solved by #1506? Then please close this issue

**Comment by alexejSchwarz** [comment]
@fhoeben I think the new description is more fitting now. Thanks to you and @GiorgosMarkogiannis.
