### ISSUE TITLE
When will a new Version be released?

### ISSUE THREAD

**Issue by AlexNetcare** [unclebob/fitnesse#1515]
Hello,
I just wanted to ask when a new Version of Fitnesse will be released? I could not find anything about a release interval, so I was wondering how it works.

**Comment by fhoeben** [comment]
No set date, just when we have a nice set of PRs merged (and we have some time). 

For the next release I think we should have #1510 and #1512 included.
Actually addressing #1514 would be nice as well, and I think should not be too hard. But I just haven't gotten around to looking into the details and the styling of the pages isn't something I've worked with a lot so I will have to dive into (unless someone else finds some time and creates a PR...)

**Comment by fhoeben** [comment]
Released 20240707 this weekend
