### ISSUE TITLE
Version 20241026 throwing Exception at startup

### ISSUE THREAD

**Issue by eireglas** [unclebob/fitnesse#1547]
Hi, just wondering if anyone else is seeing this issue when running version 20241026 of Fitnesse. When I try to access the fitnesse url its throwing this error:
![image](https://github.com/user-attachments/assets/812f4feb-fd43-4b08-a24f-39cca2ddb4d8)

Previous versions are all fine. I'm trying to upgrade to this version and I'm running it in a docker container.

**Comment by fhoeben** [comment]
Doesn't ring a bell, could it be that something more changed in the docker image?

Can you share the Dockerfile creating the image and the startup command?

**Comment by eireglas** [comment]
I resolved the issue. It was related to a dependency version issue but it's now resolved. Thanks
