### ISSUE TITLE
Setup a second job in CI to run using JDK 1.7

### ISSUE THREAD

**Issue by woodybrood** [unclebob/fitnesse#212]
We're seeing some issues with running with Java 7.  To address this, we will create a second Jenkins job to run the build process with the 1.7 JDK. Initially this will run in series.  Later after some refactoring we will try to run in parallel, assuming we can run two executors in parallel with the cloudbees account.

**Comment by amolenaar** [comment]
I'd like to move the Java dependency up to Java 8. This would fail the build on CloudBees.

**Comment by amolenaar** [comment]
Since we require Java 1.7 now we can close this issue.

Java 8 is tested on Travis-CI, triggered by updates on https://github.com/fitnesse/fitnesse.
