### ISSUE TITLE
Prevent System.exit() calls in SUT to exit the SLiM runner

### ISSUE THREAD

**Issue by mgaertne** [unclebob/fitnesse#233]
One of the larger problems with some systems is that System.exit() calls end up having the unpleasant side effect, that the whole test runner from SLiM also exits. I just came across a workaround in a JUnit book, and thought that we might want to incorporate that into the SLiM runner, and maybe even the FIT runner. 

Here is a sketch to do that:
- Before executing the real test, invoking any fixture code, save the SecurityManager, and replace the system's SecurityManager with an own one.
- After executing the real test, restore the original SecurityManager.

The own Security Manager needs to subclass SecurityManager, and override the checkExit(int) function to prevent calls to System.exit(). Instead we might throw an exception with a descriptive text and how the programmer can prevent something like this.

In the example code from that book, the methods checkPermission are delegating to the old security manager, if it was not null. I am not sure, whether we might want to use an own SecurityManager for FitNesse access. We might also handle authorization with that, I don't know too much about that.

**Comment by fhoeben** [comment]
@mgaertne the system security manager interface changed for Java 11, keeping this support in is causing some headaches. 

I actually consider SUTs calling `System.exit()` quite a code smell. I would like to drop out of the box prevention of system exit prevention from FitNesse. I would think that adding a custom security manager to prevent then would be a small task to add to a test environment's fixtures. Am I overlooking something?
