### ISSUE TITLE
Suggestion: Add Validation of Test pages (SLIM?)

### ISSUE THREAD

**Issue by KoenVerheyen** [unclebob/fitnesse#340]
Please add an extra function on a test page to validate it.
This means that you only check if every line in your test has a valid scenario/fixture.
But the actual tests are not run.

We have test cases which can take + 1 minute, and thus it takes a lot of time to fix small typos at the end of your script which cause the tests to fail.

We use slim...

**Comment by amolenaar** [comment]
Have you tried the FitNesse plugin for IntelliJ recently?
