### ISSUE TITLE
Flow Mode in older FitLibrary is not working with FitNesse 20131110

### ISSUE THREAD

**Issue by javornikolov** [unclebob/fitnesse#359]
The [Flow Mode Example](http://fitnesse.org/FitNesse.UserGuide.FixtureGallery.ImportantConcepts.FlowMode) fails with errors like:

```
Could not find fixture: PreparePlayers.
....
Could not find fixture: ListPlayers.
```

The issue has been reproduced with:
- FitNesse: **20131110**
- FitLibrary: 20081102, 20090628, 20091020
- Test System: Fit
- Test Runner: FitServer

Same example works fine with the previous FitNesse version (20130530).

---

Seems switching to **FitLibraryServer** runner makes above example work OK (I tried with FitLibrary 20091020 and 2.0). However:
- This requires changing the test runner
- Requires newer FitLibrary versions which are breaking code which relies on stuff like overriding `Fixture.interpretTables`, e.g.: [DatabaseTest#interpretTables](https://github.com/benilovj/dbfit/blob/master/dbfit-java/core/src/main/java/dbfit/DatabaseTest.java#L18...#L36)

---

This discovery emerged when tried DbFit with latest version of FitNesse: https://github.com/benilovj/dbfit/issues/179

**Comment by hendryluk** [comment]
Could you please confirm whether this is still working now? Flow mode doesn't seem to work on Fitnesse 20150814, with FIT test system. It's complaining about 'Could not find fixture: foo', even though I have foo() method on my DoFixture.

**Comment by jediwhale** [comment]
Yes, flow mode is working.  Can you post your test and results.

On 2015-09-10 02:38, hendryluk wrote:
>
> Could you please confirm whether this is still working now? Flow mode 
> doesn't seem to work on Fitnesse 20150814, with FIT test system. It's 
> complaining about 'Could not find fixture: foo', even though I have 
> foo() method on my DoFixture.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/unclebob/fitnesse/issues/359#issuecomment-139168535>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>

**Comment by hendryluk** [comment]
Yea sorry it wasn't working because I had a (hidden) import table above it (which doesnt do anything on FIT anyway). Is there any slim equivalent of flow-mode? Cheers
