### ISSUE TITLE
Best way for CI Integration

### ISSUE THREAD

**Issue by Turambar1** [unclebob/fitnesse#410]
Hi *,

What is the preferred way to include FitNesse in an Continuous-Integration build?
Is there any doku available? All google results are 5 years and older.

**Comment by 2xmax** [comment]
Brilliant! https://github.com/unclebob/fitnesse/pull/642. IMHO it can be closed

**Comment by tomasbjerre** [comment]
I was also looking for this. Wrote a blog post on how I solved it:
https://bjurr.com/fitnesse-with-maven-and-jenkins/

I use Maven and Maven Antrun Plugin. In Jenkins I use the Lockable Resource Plugin to avoid ip port collisions. It allows me to:
* Run all tests from command-line to produce a junit report.
* Start the wiki locally to edit/run tests. Any changes are under version control and are committed.

It is now a part of a pipeline where I verify merge requests in GitLab! =)
