### ISSUE TITLE
Query Table is not able to recognize Lists in the cells.

### ISSUE THREAD

**Issue by richardjaldin** [unclebob/fitnesse#441]
I'm not sure if this is a bug or a new feature request.

The scenario is:
When I have Objects like ```User``` its fields show great in the Query Table.

```
public class User {
    private String name;
    private String dni;

    //getter and setter methods.
}
```

When I have "complex" objects like these ```Country```, I get and exception saying that an "ArrayList cannot be cast into a String".

```
public class Country {
    private String name;
    private List<City> cities;

    //getter and setter methods.
}

public class City {
    private String name;

    //getter and setter methods.
}
```

If I use a Script Table to show only one ```Country``` object, it shows correctly all the fields even the inner List, but Query Tables are not able to do the same task.

Please let me know if you need additional information or if I can help in any way.

Best Regards.

**Comment by amolenaar** [comment]
You can add a custom Converter in the upcoming release.
