### ISSUE TITLE
EnumConverter toString uses '.name()'

### ISSUE THREAD

**Issue by raboof** [unclebob/fitnesse#470]
.. which is pretty much guaranteed to be an all-uppercase 'technical' identifier.

Should we perhaps return the '.toString()' of the enum constant? It has a reasonable default (the .name()) and isn't likely to contain anything other than the 'friendly' name of the enum...

Not sure how to do this without breaking backwards-compatibility though... :(

**Comment by amolenaar** [comment]
Can I close this issue?
