### ISSUE TITLE
No converter for fit.Parse when using Rest Fixture (config)

### ISSUE THREAD

**Issue by tcnh** [unclebob/fitnesse#476]
In fitnesse versions higher than 20111025, I cannot use the configuration fixture from rest fixture. 

Fitnesse logs the following exception: 'no converter for fit.Parse'. I have raised this issue at smartrics, but the project seems to be somewhat dead. Anyone here with a possible workaround or push in the right direction?

**Comment by amolenaar** [comment]
Closing issue, since there's no apparent action to be taken and issue is idle for 6+ months.
