### ISSUE TITLE
A scenario name with an uppercase letter in the middle combined with semicolon call syntax fails

### ISSUE THREAD

**Issue by six42** [unclebob/fitnesse#537]
There are three ways how you can call a scenario from a script. But the calculation of the scenario name is not consitent over these three ways.The below page demonstrates the behaviour:
--------------------------------------------------------------------------------------------------------------
Use the Division class from the eg library to implement the scenario
|Library|
|eg.Division|

|scenario | bAr _ _ _|numerator, denominator, quotient|
|setNumerator| @numerator|
|setDenominator| @denominator|
|check | quotient| @quotient|

This Syntax works
|script|
|bAr 35 5 7.0|
|bAr |6|| 3|| 2.0|

Fail: The scenarion name is not identified
|script|
|bAr; |35 |5| 7.0 |

No other name works neither :(
|script|
|BAR; |35 |5| 7.0 |
|B Ar; |35 |5| 7.0 |
|BAr; |35 |5| 7.0 |
|Bar; |35 |5| 7.0 |

Using the same scenario with upper case only in the first letter works
|scenario | Bar _ _ _|numerator, denominator, quotient|
|setNumerator| @numerator|
|setDenominator| @denominator|
|check | quotient| @quotient|

|script|
|Bar; |35 |5| 7.0 |

**Comment by mwarhaftig** [comment]
Created pull request #574 with suggested fix.  Semi-colon is causing Script Table to camel-case scenario name. 

Thanks for noticing this and providing good test scenarios.

**Comment by six42** [comment]
Hi Wahrhaftig

Thanks for taking the time to fix this.
