### ISSUE TITLE
!contents -p not showing symbolic link attribute, as documented

### ISSUE THREAD

**Issue by ALuckyGuy** [unclebob/fitnesse#541]
Running both an August 24th and October 6th build, the symbolic link attribute, default '>', is never displayed when a !contents -p option is used. Not sure if it ever worked, and checking the Acceptance tests, I can't see that there are any tests to verify the behavior. 

Additionally, I don't see tests for verifying that the global variable PROPERTY_CHARACTERS works, and it doesn't seem to either.

**Comment by amolenaar** [comment]
Closing issue. A fix has been merged a while back already.
