### ISSUE TITLE
How To Prevent Create new Fitnesse Page

### ISSUE THREAD

**Issue by liviamota** [unclebob/fitnesse#546]
Hello,

I'm searching for some way to protect my fitnesse environment. I'm using LDAP plugin, but it's not enough.
There are any way to protect my fitnesse enviroment for no-authorised user create a new page? I'd like to implement the same fitnesse website behavior in my environment. Eg: http://www.fitnesse.org/LiviaMota 
Thank you in advance.

Livia.

**Comment by amolenaar** [comment]
Should adding new pages require "write" permission on the (to-be) parent page?

**Comment by amolenaar** [comment]
I checked with

    java -jar fitnesse-standalone.jar -a arjan:test -p 8000

and I was able to set security permissions on the root page (http://localhost:8000/root). After that I was no longer able to create a new page as an anonymous user. The authorisation logic is checking the page and (in absence of a security property) the parent page up to the root.

**Comment by six42** [comment]
I would say: yes.
Alternative would be a dedicated "AddPage" right.

**Comment by six42** [comment]
I would say: yes.
Alterantive would be a dedicated "AddPage" right.

Am 27. Juli 2015 17:40:43 MESZ, schrieb Arjan Molenaar <notifications@github.com>:

**Comment by amolenaar** [comment]
Is this still an issue?
