### ISSUE TITLE
Enhancement:  Color Test Table Columns & Rows

### ISSUE THREAD

**Issue by mwarhaftig** [unclebob/fitnesse#558]
Our in-house test cases tend to be 300+ line ActionFixtures.  To make tests more readable we use custom JavaScript and CSS to add color-coded row background colors to the html (colored based on the action name):
![image](https://cloud.githubusercontent.com/assets/1711265/5151996/d896e2b0-71b4-11e4-9872-e70ddb21bac4.png)

The color coding greatly improves test readability but the in-house implementation is inflexible as it assumes all test tables have a vertical test flow.  For a better (and community shared) solution, at the fitnesse.wikitext.parser.Table.toTarget() level I believe it is possible to fairly accurately decide whether a test table has vertical or horizontal test flow and then add column or row coloring (and/or hooks for coloring via CSS).  For example here is a mockup of how some basic tables would look:
![image](https://cloud.githubusercontent.com/assets/1711265/5151999/e4704554-71b4-11e4-94cc-31201862f066.png)
![image](https://cloud.githubusercontent.com/assets/1711265/5152002/e66a42b0-71b4-11e4-9869-8c3e9985072d.png)

Please let me know if I can add table coloring logic to the codebase.  Suggestions or concerns are appreciated too.

**Comment by amolenaar** [comment]
PR has been merged
