### ISSUE TITLE
Documentation: SLIM protocol still mentioning fixed 6 digits length encoding

### ISSUE THREAD

**Issue by Kosta-Github** [unclebob/fitnesse#564]
The documentation still mentioning a hard-coded 6 digits length encoding of strings and lists: http://fitnesse.org/FitNesse.UserGuide.SliM.SlimProtocol

And it also only mentions the SLIM protocols version `0.1` and `0.2`; no word about `0.3`.

And is version `0.3` still the most recent version? Or was the version bumped to `0.4` with the recent changes to the more variable number of digits for the length encoding?

**Comment by Kosta-Github** [comment]
This change hasn't been deployed to this page http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.SlimProtocol yet, right?

BTW, it looks like this page is not reachable by a link from the parent page. I only reached it be asking `Google`...

**Comment by amolenaar** [comment]
I forgot to update the FitNesse version that runs the site. It has been upgraded now.
