### ISSUE TITLE
Wildcard imports?

### ISSUE THREAD

**Issue by swanson** [unclebob/fitnesse#578]
It would be nice if `ImportTable` could have support for wildcard imports, we've got some fixtures in multiple packages and it seems we have to import each package manually.

Something like:

```
|import|
|com.megacorp.utils|
|com.megacorp.fixtures.*|
```

Is this something feasible? Would you accept a PR for this?

**Comment by amolenaar** [comment]
Currently wildcard imports are not possible, not sure how easy it would be to implement, since the server has to look for package names itself.
I would expect the package to map to one level (e.g. `com.megacorp.fixtures.foo`, not `com.megacorp.fixtures.foo.bar`)?

**Comment by swanson** [comment]
In our case, there are a large number of fixtures - so they are grouped by function (`com.megacorp.fixtures.sales`, `com.megacorp.fixtures.customers`, `com.megacorp.fixtures.products`, etc) and also product version (`com.megacorp.fixtures.legacy.reports`, `com.megacorp.fixtures.v2.reports`).

Is there a mechanism in FitNesse to hook in a custom table? From a quick glance it seems like we could subclass `ImportTable`, expand wildcard paths, and add a list of `ImportInstructions`.

**Comment by ggramlich** [comment]
There is a plugin mechanism. Take a look at

http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.ConfigurationFile
(Section Slim Tables)

This is, how it gets registered then
https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/PluginsLoader.java#L151

**Comment by ryber** [comment]
One thing to consider with it. We had a large number of import packages and while profiling to figure out why our fitnesse tests seemed so slow we noticed that the mechanism to find a fixture in a package was a big drag. We were importing packages rather than each fixture. So basically for each fixture fitnesse was going into each import package, attempting to find the fixture and then throwing an exception if it couldn't find it. Because there were 53 import packages this took quite a bit of time.

We flattened all of our packages into one and dropped the import fixture down to the one package and we reduced our total fitnesse suite run from 12 minutes to 7 minutes.

**Comment by phgr100x** [comment]
A workaround I use :

Create a custom Slim Table that extends ImportTable, and [register it](http://www.fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.WritingPlugins):
```
public class ListImportTable extends ImportTable {
	
	public ListImportTable(Table table, String id, SlimTestContext testContext) {
		super(table, id, testContext);
	}

	@Override
	protected String getTableType() {
		return "list import";
	}

	@Override
	public List<SlimAssertion> getAssertions() throws SyntaxError {
		int rows = table.getRowCount();
		List<SlimAssertion> instructions = new ArrayList<SlimAssertion>(rows);
		if (rows < 2)
			throw new SyntaxError("Import tables must have at least two rows.");

		for (int row = 1; row < rows; row++) {
			String importString = replaceSymbols(table.getCellContents(0, row));
			
			table.substitute(0, row, importString);
			
			if (!importString.isEmpty()) {
				Instruction importInstruction = new ListImportInstruction(makeInstructionTag(), importString);
				instructions.add(makeAssertion(importInstruction, new ImportExpectation(0, row)));
			}
		}
		return instructions;
	}
}
```

a custom ImportInstruction that can import list of path:
```
public class ListImportInstruction extends ImportInstruction {
	
	private String listPath;
	
	public ListImportInstruction(String id, String path) {
		super(id, path);
		listPath=path;
	}

	@Override
	protected InstructionResult executeInternal(InstructionExecutor executor) throws SlimException {
		
		if (listPath.contains("[")) {
			String[] paths=listPath.replaceAll("\\[", "").replaceAll("\\]", "").split(",");

			for (String path:paths) {
				executor.addPath(path.trim());
			}

		} else {
			executor.addPath(listPath.trim());
		}
		return new InstructionResult.Ok(getId());
	}
}
```
and a Slim Fixture that can list all sub package of package with wildcard (use Guava library):
```
import com.google.common.collect.ImmutableSet;
import com.google.common.reflect.ClassPath;
import com.google.common.reflect.ClassPath.ClassInfo;

public class ImportWildcardFixture {

	private static ImmutableSet<ClassInfo> classInfos;

	private final static Logger LOG = Logger.getLogger(ImportWildcardFixture.class);
	
	public List<String> listImportPackage(String wildcardPath){
		
		List<String> result = new ArrayList<String>();
		
		wildcardPath=wildcardPath.trim();
		
		if (wildcardPath.endsWith(".*")) {
			if (classInfos == null) {
				final ClassLoader loader = Thread.currentThread().getContextClassLoader();
				try {
					//Limit packages to scan, it can be very slow...
					classInfos = ClassPath.from(loader).getTopLevelClassesRecursive("my.company.package.for.better.performance");
				} catch (IOException e) {
					LOG.error(e.getMessage(),e);
				}
			}
			String parentPath = wildcardPath.substring(0, wildcardPath.lastIndexOf('.'));
	
			for (final ClassPath.ClassInfo info : classInfos) {
				if (info.getPackageName().startsWith(parentPath) && !result.contains(info.getPackageName())) {
					result.add(info.getPackageName());
				}
			}
		}else{
			result.add(wildcardPath);
		}

		return result;
	}
}
```

Then, in your wiki:
```
First, import package where is ImportWildcardFixture:

|list import                                            |
|package.of.my.import.wildcard.fixture|

Call ImportWildcardFixture with a path that contains wildcard:

|script            |Import Wildcard Fixture                                    |
|$listImports=|listImportPackage|my.package.with.wildcard.* |

Then, import list of packages returns by the fixture:

|list import     |
|$listeImports|
```

**Comment by amolenaar** [comment]
Does this issue require any further action?
