### ISSUE TITLE
Failure Navigation don't work in the test history

### ISSUE THREAD

**Issue by bjornpalmqvist** [unclebob/fitnesse#579]
When checking the test history for a test that contains errors, the failure navigator does not find any failed tests. Hence the navigator can't be used to jump to the failures/errors/exception. This makes it hard to navigate to the failures directly when entering large tests.

To recreate this issue:
1. Create a test that will go wrong
2. Run it
3. Go into the test history for the failed test
4. Try to use the failure navigator

I will state that it can't find any failures, and navigates to test 1 och 0.

**Comment by bjornpalmqvist** [comment]
Created pull request #580 for the changed that we used to fix this issue. I understand that i may need some more work when I'm not familiar with the FitNesse code base.

**Comment by amolenaar** [comment]
By default the failure navigator is only enabled for test pages. Are you using a custom template that enables the Failure navigator in history pages?
