### ISSUE TITLE
Test links in Search do not work

### ISSUE THREAD

**Issue by InspiredIdealist** [unclebob/fitnesse#581]
This is occurring in the latest version (20150114)

The test links next to each test that is found as part of a search are missing the beginning part of the path. I have only tested this for tests that appear on the FrontPage so far, since all of our tests essentially stem from the FrontPage.

Example:
Actual Path: FrontPage.SomeSuite.OtherSuite.RealTest
Path Linked: SomeSuite.OtherSuite.RealTest

Exception shown when clicking the "Test" link, in addition to the address being wrong:
java.lang.NullPointerException fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:109) fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70) fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25) fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100) fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51) fitnesse.FitNesseServer.serve(FitNesseServer.java:28) fitnesse.FitNesseServer.serve(FitNesseServer.java:21) fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:109) java.lang.Thread.run(Unknown Source)

**Comment by amolenaar** [comment]
Hi,
I tried searching in the FitNesse page and it seemed to work just fine. Have you been using symlinks maybe?
What I did was:
1. Open Tools -> Search
2. Enter a search criteria "slim", hit Search Titles
3. Click on a Test link (first column) of a page found and see the test execute.

Did I miss anything?

**Comment by InspiredIdealist** [comment]
Was the test you tried to execute under the FrontPage?

**Comment by amolenaar** [comment]
I tried with FitNesse.SuiteAcceptanceTests. But that shouldn't make a different (famous last words... ).

I appreciate your feedback.

**Comment by InspiredIdealist** [comment]
I just tried it again locally, once with a test NOT on the FrontPage, and one ON the FrontPage.
Although this may seem strange, here are the results:

Non-FrontPage Test: ("Test" link works) 
Name of Test: FitNesse.SuiteAcceptanceTests.SuiteResponderTests.AddChildResponderSuite.AddTestPageTest

FrontPage Test: ("Test" link leaves out the "FrontPage", so the test cannot run) 
Name of Test: FrontPage.TestingRestful

**Comment by simonvanderveldt** [comment]
Can confirm that the test link on the search result page for pages that are a (sub)child of the FrontPage don't work as explained by @InspiredIdealist (i.e. FrontPage is omitted from the URL).

**Comment by amolenaar** [comment]
Found it :). It broke when searching from a sub-wiki. The link to the test page was a relative link from the page the search was initiated from.

**Comment by InspiredIdealist** [comment]
Excellent! Thanks for looking into this!
