### ISSUE TITLE
Strange exception when running a Search (Titles or Content)

### ISSUE THREAD

**Issue by InspiredIdealist** [unclebob/fitnesse#587]
I get the following exception when I run a search (either Title or Content):

java.lang.RuntimeException: Unable to parse XML from stream fitnesse.wiki.WikiPageProperties.loadFromXmlStream(WikiPageProperties.java:54) fitnesse.wiki.fs.FileSystemPage.loadAttributes(FileSystemPage.java:250) fitnesse.wiki.fs.FileSystemPage.getDataVersion(FileSystemPage.java:169) fitnesse.wiki.fs.FileSystemPage.getData(FileSystemPage.java:128) fitnesse.wiki.fs.FileSystemPageFactory$FileSystemSubWikiPageFactory.getSymlinkChildren(FileSystemPageFactory.java:134) fitnesse.wiki.fs.FileSystemPageFactory$FileSystemSubWikiPageFactory.getChildren(FileSystemPageFactory.java:114) fitnesse.wiki.fs.FileSystemPage.getChildren(FileSystemPage.java:117) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:123) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:124) fitnesse.wiki.PageCrawlerImpl.traverse(PageCrawlerImpl.java:116) fitnesse.wiki.search.WikiPageFinder.search(WikiPageFinder.java:23) fitnesse.responders.search.SearchResponder.traverse(SearchResponder.java:43) fitnesse.html.template.TraverseDirective.render(TraverseDirective.java:49) org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207) org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342) org.apache.velocity.runtime.directive.Parse.render(Parse.java:260) org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207) org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342) org.apache.velocity.Template.merge(Template.java:356) org.apache.velocity.Template.merge(Template.java:260) fitnesse.html.template.HtmlPage.render(HtmlPage.java:81) fitnesse.responders.search.ResultResponder.doSending(ResultResponder.java:48) fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70) fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25) fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100) fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51) fitnesse.FitNesseServer.serve(FitNesseServer.java:28) fitnesse.FitNesseServer.serve(FitNesseServer.java:21) fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:109) java.lang.Thread.run(Unknown Source)

Does anyone know what this might be related to?

**Comment by amolenaar** [comment]
Hi,
Do you know which page you were on when this error occurred? Can you share the properties.xml file of that page?

**Comment by InspiredIdealist** [comment]
This happens in every single search I run, title or content based, whenever the search is complete (that seems to be the pattern). This does not occur when doing a properties based search, which I thought was kind of peculiar.

**Comment by mithunbalyada** [comment]
Currently search operation in fitnesse is including the search in error logs as well. Since the error logs is growing in my project, is there any way I can exclude search in error logs. 
I am thinking of writing a wrapper to make the seach in the fitnesse to be really fast and customize the search based on my project requirement. Could you please help me on how to write a new servelet which will do the search operation and respond with Json data so that I can parse this data on my custom HTML and render the result.

**Comment by amolenaar** [comment]
@InspiredIdealist Is this still an issue?

mithunbalyada In the last few versions, no ErrorLog files are created anymore. the execution log information is not part of the test history. There is also a special controller for showing the execution log stuff.

**Comment by InspiredIdealist** [comment]
I haven't tried this issue in a while... Perhaps it was fixed in a recent release?

**Comment by amolenaar** [comment]
I'll close this issue until further notice.
