### ISSUE TITLE
Enhance SLiM "Library" fixture to allow constructor arguments

### ISSUE THREAD

**Issue by InspiredIdealist** [unclebob/fitnesse#591]
In my tests, there are certain instances where I'd like to take advantage of the Library feature that FitNesse has, but not being able to introduce constructor arguments causes me to have to break some of the patterns that we have established.

**Comment by amolenaar** [comment]
Hi, can you give an example?

**Comment by InspiredIdealist** [comment]
Sure,

We have a custom database fixture that can take arguments such as environment (QA, DEV), and Database Type (Oracle, MySQL, Microsoft SQL). It is quite inefficient for us to create/destory an instance of this fixture every time it is used, and we can't switch to another fixture without doing exactly that. However, there is never a need to switch environment & database types during the test. So using the library table seemed like a good way to mitigate the cost of opening/closing database connections.

The sample wiki page table (wanted future state):
|library|
|database fixture|QA|MySQL|

Using Library as it exists today:
|library|
|database fixture|

|script|
|set environment|QA|
|set database|MySQL|

**Comment by six42** [comment]
Hi @InspiredIdealist 

have a look at the pull request I created if this solves your problem.

**Comment by InspiredIdealist** [comment]
There are no code changes in the commit you are referencing... This does not resolve my problem.

**Comment by InspiredIdealist** [comment]
Please re-open this issue, it is still not addressed.

**Comment by six42** [comment]
Did you tried it:

|script|
|database fixture|QA|MySQL|
|$df= |get fixture |

|library|
|$db |


What was the result?

**Comment by InspiredIdealist** [comment]
@six42, I've been playing around with the page you created, and it looks to me like FitNesse already supports what I'm looking for, at least for the most part.
It is starting to look like the fitSharp runner that I'm using may not support library constructor arguments...
