### ISSUE TITLE
Update entry for ScenarioTable in usage guide to mention output parameters

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#596]
The user guide for Slim's ScenarioTable explicitly states it does not support outputs this is not correct as one of the entries in the release notes was about better support for output parameters.

From http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ScenarioTable:
> Notice that there is no concept of an output header; i.e. there is no '?' in any of the column headers. A Decision Table that calls a Scenario Table does not make any assertions of its own. Rather it relies on the Scenario table to do the asserting. If you look at the Scenario Table above, it uses the check keyword to make the assertion. Again, this is important. When you call a Scenario, you only pass data into it. You don't get data back out of it. Scenarios have no return value.

Can this page be updated so people will be made aware of ScenarioTable's output parameter capability?

**Comment by six42** [comment]
In github its updated already.
Is the website not updated after every release?

Am 25. Januar 2015 20:31:17 MEZ, schrieb Fried Hoeben <notifications@github.com>:

**Comment by fhoeben** [comment]
Now I see that the documentation inside my installation is indeed updated. And that probably means that fitnesse.org is not using the latest release.

But I have to say that compared to the rest of the page the paragraph on output columns is very minimal. It only points to the suite that tests the behavior, which itself has no documentation on output columns at all (only in its children). 
In the user guide I would expect at least a basic description of output columns: how do you define one in a scenario and what is the difference between an output and input column for the caller.

**Comment by six42** [comment]
Go ahead and change it.
I wrote this page about output parameters but I am sure there are always things which can be improved.
