### ISSUE TITLE
How to debug fixtures executed through FitNesseRunner 

### ISSUE THREAD

**Issue by senips** [unclebob/fitnesse#599]
I thought FitNesseRunner will work with in process to debug my fitnesse table but it never go to my code instead it uses again that socket mechanism.  For example,  how do i set a break point to my fixture code and seamlessly debug with Junit?

**Comment by amolenaar** [comment]
You can set the `@DebugMode` annotation on the code, that will make the code be loaded in-process.

**Comment by amolenaar** [comment]
Did this work for you? (please re-open if you need more info/code change)

**Comment by senips** [comment]
Good to know but I haven't tried yet.
