### ISSUE TITLE
[Import] - Wiki import fails when the page to import contains CDATA tags

### ISSUE THREAD

**Issue by pizzqc** [unclebob/fitnesse#601]
Our FitNesse structure is the following:
 * We have 1 "integration-fitnesse" package that includes ~10 other FitNesse wiki
 * The imported Wiki are for specific services components

The "integration-fitnesse", usually update the content properly... but there are some exceptions where it fails even if the result of the sync says otherwise.

The only visible error are in the FitNesse console:
``` Logs
[Fatal Error] :157:59: The element type "content" must be terminated by the matching end-tag "</content>".
```

Another strange behavior is the "Updating imported wiki" status page:
* There seems to be a phantom page as per the results.  See screenshot below:
![image](https://cloud.githubusercontent.com/assets/3100777/5923122/f7e1cc5e-a61e-11e4-8646-ff3422ae35c9.png)

Is this a known issue with "imported wiki"?

Note: I have tried the following: deleting the page not updating, deleting the entire imported tree and re-importing and same problems.

Thanks
/Antoine

**Comment by pizzqc** [comment]
I went by elimination and turns out the IMPORT of external wiki fails as soon as the content of the page contains CDATA blocks (i.e.: <![CDATA[]]> )  

Hope this helps resolving the issue
Thanks
/Antoine

**Comment by mwarhaftig** [comment]
Hi Antoine,  

Can you please provide the full page contents for a failing import?  My attempts at importing wiki pages that contained CDATA did not encounter any errors and imported correctly.

Thanks,
Matt

**Comment by pizzqc** [comment]
Hi Matt,

I was able to reproduce with the following page content.  The entire content.txt is the following :

```
!define STUB_RESPONSE {!-<?xml version="1.0" encoding="utf-8"?>
                <Metadata>
                    <passThroughDataObjects><![CDATA[]]></passThroughDataObjects>
                    <passThroughDataElements><![CDATA[]]></passThroughDataElements>
                </Metadata>-!}
```

Hope this helps,

Thank you,
/Antoine

**Comment by mwarhaftig** [comment]
Sorry Antoine, I was unable to recreate.  Hopefully another contributor has better luck.

**Comment by pizzqc** [comment]
Hmm..  I have installed two new FitNesse instance and trying to reproduce it with those and couldn't either ... I will try to hunt it down from our original wiki what could cause this.

Thanks for your effort and will hopefully be able to give you a tarball with all the required stuff to reproduce it.

/Antoine

**Comment by pizzqc** [comment]
I was able to reproduce and also resolve my problem.  My remote FitNesse was running version "20140901" while my integration FitNesse instance (the one importing) was running version "20150114"...  I am not sure exactly why it was failing but those two version were not compatible together when using "imports".

After updating the two FitNesse instances to the same version, it solve the issue and all the pages gets properly synced ... and no more [Fatal error] inside the SAX parser either.

Not sure if you are interested in looking into this issue cross version or we simply close the bug?

**Comment by amolenaar** [comment]
I think we can close it, until further notice.
