### ISSUE TITLE
Size increase for test results since version 20140901

### ISSUE THREAD

**Issue by floppyrom** [unclebob/fitnesse#603]
Hi 

Is there any way to control the size of the test results which are generated by Fitnesse? Ever since we updated to version 20140901 the size of the test results exploded by 60% (what was 9MB before now is 15 MB). Indeed some of our tests may not very optimized (we use a lot of hashmaps with big queries) but even so, this increase in the log size from version before 20140901 is not good.

**Comment by amolenaar** [comment]
At that time the output HTML (which is part of the page history) has been changed from using CDATA to escaped HTML. That's probably why. It can be changed back to CDATA, but escaped HTML is saver when it comes to reading data.

**Comment by floppyrom** [comment]
Thanks. This is probably it. Can you please tell me how can I change it?

The problem is that for now in our environment we are stuck with an old Jenkins, which is running Fitnesse Plugin 1.4, which is quite old - last version is 1.11. Jenkins thus chockes when running suites with many tests that have logs over 20 MB. We cannot update the fitnesse plugin as Jenkins is too old and there is no plan to update it soon. Yet we want to use the latest Fitnesse and we're looking for some quick solutions to unblock us.

**Comment by stefanhendriks** [comment]
A quick solution would be to revert back one version of Fitnesse. Unless you're missing out on some important feature there?

**Comment by amolenaar** [comment]
What you can do is extract the file `fitnesse/resources/templates/testResults.vm` from fitnesse.jar and put it in FitNesseRoot/files/fitnesse/templates. Then change the line that writes the content (line 14) to

    <content><![CDATA[$result.Content]]></content>

The file in the files section will take precedence over the one in the jar file.

**Comment by denisko** [comment]
How much effort would it be to always zip the testresults ? 

I got complaints from Sysadmin, because these logfiles increased to over 1 GB in a few hours. We use a set of FitNesse scripts for monitoring. Approx 15 scripts are run every five minutes from Nagios. The output is used for alerting.

**Comment by amolenaar** [comment]
We might want to limit the history size (e.g. a retention of 30 days by default).

See #28.

**Comment by amolenaar** [comment]
PR #636 allows you to limit the stored history.
