### ISSUE TITLE
Using symbols in Slim TableTable

### ISSUE THREAD

**Issue by jplambert** [unclebob/fitnesse#604]
Hello everybody,

I am using some custom tables with TableTable but got stuck about the handling of symbols.

My question is that TableTable do not substitute symbols with their values, but the Slim fixtures do not have to the store of symbols.

To me it looks like something is missing or has been forgotten there. If you agree, I can share a patch that performs the substitution before passing the text to the Slim fixture.

Do you agree? Did I missed something?

Thanks in advance,

Jean-Pierre Lambert

**Comment by ggramlich** [comment]
Are you talking about assigning values to Slim symbols or only about using them in a TableTable? Just using them should be possible, storing them is an issue that came up before and has not been solved.

Please have a look at

https://github.com/unclebob/fitnesse/pull/469, https://github.com/unclebob/fitnesse/issues/91, https://github.com/unclebob/fitnesse/issues/369, https://github.com/unclebob/fitnesse/pull/525

**Comment by jplambert** [comment]
I am talking about both.

So far from my experience:
- using symbol values is not working/not implemented
- assigning values works (the result provided by the call to doTable(...) for this cell is put in the symbol) but still forwards the "$V=" text to the doTable(...) call which is kinda weird

I have something working locally, by doing that:
1. Substitute all symbols by their values before sending the table to doTable(...)
2. Substitute symbol assignment text by an empty String

That's actually very simple and works, to the extent of doTable(...) not making any pretty-printing since this will be part of what is assigned into the symbol.

I'll have a closer look at the issues you reference, thanks.

**Comment by amolenaar** [comment]
This has been resolved by #644, right?

**Comment by jplambert** [comment]
Sure! Thanks.
