### ISSUE TITLE
Nested scenario table not working.

### ISSUE THREAD

**Issue by alvillaflor** [unclebob/fitnesse#609]
Is nested scenario table not working?

Ex.
|scenario| add number _ | a,b,c|
|start|add two numbers| @a | @b |
| check | get sum | @c |

|scenario | add more _ | e,f,g |
|add number | @e | @f | @g |

'Add more' scenario is called by a decision table.

The example is from this doc too.  http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ScenarioTable

**Comment by mwarhaftig** [comment]
Hi Alvillaflor, Thanks for reporting, I'll look into a fix. 

Trying to test FitNesse.UserGuide.WritingAcceptanceTests.SliM.ScenarioTable is failing because ColoredSlimTable.toTarget (table coloring) is calling fitnesse.fixtures.TearDown's constructor and causing teardown to run prematurely.

I believe this issue covers your example too.

     [java] Caused by: java.lang.NullPointerException
     [java] 	at fitnesse.fixtures.TearDown.<init>(TearDown.java:15)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
     [java] 	at java.lang.Class.newInstance(Class.java:379)
     [java] 	at fitnesse.wikitext.parser.ColoredSlimTable.toTarget(ColoredSlimTable.java:80)

**Comment by jediwhale** [comment]
Some serious problems with ColoredSlimTable? 100 line method, no unit test that I could find?

**Comment by ggramlich** [comment]
The issue was discussed and solved on the mailing list

https://groups.yahoo.com/neo/groups/fitnesse/conversations/topics/21082

**Comment by mwarhaftig** [comment]
Thanks Gregor! - this nested scenario ticket turning out to be a non-issue is good news. When I am back at my desk I will open a new ticket for the table coloring class instantiation issue. - have a fix already in mind. 

@Mike dedicated unit tests for table coloring is a good idea. Will include that with the TearDown instantiation fix. 

-Matt

**Comment by alvillaflor** [comment]
Should probably need to update the docs with correct syntax to make it work
