### ISSUE TITLE
ER: Junit responder

### ISSUE THREAD

**Issue by konstantinvlasenko** [unclebob/fitnesse#612]
Hi all,
Can we have the junit reponder (**format=junit**)? It will help us to integrate with TeamCity w/o converting XML to Junit results by our-self.
Or maybe we already have it in Fitnesse?

**Comment by amolenaar** [comment]
We do not have it yet. Sounds like a useful addition.

**Comment by amolenaar** [comment]
Serge made a nice patch (#642). Would that suffice?

**Comment by amolenaar** [comment]
merged #642.
