### ISSUE TITLE
Hash table editing within rich text editor

### ISSUE THREAD

**Issue by brucetrask** [unclebob/fitnesse#614]
Hello,
I am looking for a feature of editing embedded tables (hash tables) from within the rich text editor.  
I have looked at https://github.com/unclebob/fitnesse/issues/364 but I need to take it a bit further.  I have modified the javascript to bring the table creation toolbar member up in to the in_table view and so I can click within a cell and press that button and get the table to appear and can edit it then.  The problem happens when I save it and I lose the embedded table part of it and that table gets interpreted as only new cells in the row of the cell where I would like the embedded table

I am thinking that upon save I would like to have the tool persist an embedded table added in by way of the rich text editor as the usual !{} format.

Any pointers for me on continuing with this?  I am almost there but may need a few suggestions.

A couple of screen shots are attached.

Regards,
Bruce

![screen shot 2015-02-06 at 5 10 43 pm](https://cloud.githubusercontent.com/assets/10885119/6082821/5b2ea00e-ae24-11e4-9d7f-2e230e28900a.png)
![screen shot 2015-02-06 at 5 11 46 pm](https://cloud.githubusercontent.com/assets/10885119/6082823/5e674fb4-ae24-11e4-82c6-eae02f9a6b9c.png)

**Comment by ALuckyGuy** [comment]
Any plans to enhance the editor to support nested tables?  It's ***so*** close with the hash table support:

![image](https://cloud.githubusercontent.com/assets/3267060/6606767/4880ce04-c810-11e4-9371-030db47c9c93.png)

Nested tables are a real hassle to maintain currently. Using defines is kludgey and tedious if each row in a table has a different set of nested data, and embedding them directly using !( )! makes it virtually impossible to format meaningfully without huge amounts of whitespace. They're a big stumbling block for new users too. Proper rich text support would be a godsend for us.

**Comment by brucetrask** [comment]
Agreed on that.  I did open and issue  #669 which I think embraces what you are asking.  Would be a godsend for us as well.

**Comment by brucetrask** [comment]
I would love this as well. I did open https://github.com/unclebob/fitnesse/issues/669 for this.
