### ISSUE TITLE
Add parameter for logging stdout/stderr in file

### ISSUE THREAD

**Issue by mswz** [unclebob/fitnesse#616]
Hi all,

it seems like recently I ran into a quite unique issue, since I couldn't find anything that seemed to be related here or anywhere else on the web. I'm running the latest official release (20150114) of the fitnesse-standalone.jar as a Windows service and perform nightly test runs which are executed by Jenkins, i.e. Jenkins executes the test suite via restful services. At first this went pretty well, but once my test suite reached a certain size, Jenkins failed to complete reading the XML results from FitNesse. Jenkins just ran into some http timeout and then published what it got before the stream stopped. It turned out that FitNesse ran out of heap space every time the suite was executed by Jenkins and failed to give any response to Jenkins anymore, while it was still possible to startup new tests or even to create new ones. So there wasn't any indication that FitNesse ran into an error at all.
After starting FitNesse via the command line and executing the Jenkins job again, I found the Java Out Of Memory (out of heap space) exception in the stdout. So I just raised the heap space up to 1024MB (512MB which I tried first, weren't enough either). Now it seems to behave fine again.

Unfortunately since I was running FitNesse as a Windows service, the stdout which included the out of heap space exception was redirected to NUL, so it was quite hard to figure out what was going on. For that reason it would be nice if it where possible to redirect the output streams to a logfile to be able to investigate such issues a bit more straight forward.

**Comment by amolenaar** [comment]
Hi,
FitNesse is using java.util.logging to do it's logging. This log system is configurable.

You can start Fitnesse with the system property `java.util.logging.config.file` pointing to your logging configuration, e.g. `-Djava.util.logging.config.file=mylogging.properties`. The properties file should adhere to the `java.util.logging` configuration style.

FYI, the default (console) configuration looks like this:

```
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter = fitnesse.logging.LogFormatter
```

**Comment by mswz** [comment]
Thanks a lot, this works great for me!

**Comment by pilpo** [comment]
> 
> 
> Hi,
> FitNesse is using java.util.logging to do it's logging. This log system is configurable.
> 
> You can start Fitnesse with the system property `java.util.logging.config.file` pointing to your logging configuration, e.g. `-Djava.util.logging.config.file=mylogging.properties`. The properties file should adhere to the `java.util.logging` configuration style.
> 
> FYI, the default (console) configuration looks like this:
> 
> ```
> handlers = java.util.logging.ConsoleHandler
> java.util.logging.ConsoleHandler.formatter = fitnesse.logging.LogFormatter
> ```

Thanks @amolenaar , it works like a charm, you helped me alot!
