### ISSUE TITLE
Make MemoryVersionsController constructor public

### ISSUE THREAD

**Issue by reprive** [unclebob/fitnesse#623]
I'm working on creating a versions controller plugin for FitNesse version 20150114, and I use the Git plugin as a basis. The GitFileVersionsController uses fitnesse.wiki.fs.MemoryVersionsController internally. When I try to do the same thing, I get an error. My plugin isn't allowed to create a MemoryVersionsController instance because the MemoryVersionsController constructor is not public.

I've already patched a local version of FitNesse, and then it works fine. However I can't commit the change because I can't get all the tests to run in my environment. 

So, the request is to make the MemoryVersionsController constructor public.

**Comment by amolenaar** [comment]
You can send a pull request. I suppose it's not a problem. (As a bonus you get mentioned in the release notes :) ).
