### ISSUE TITLE
"insert-image" html code prevents ie9 from editing fitnesse pages in wiki mode

### ISSUE THREAD

**Issue by staniere** [unclebob/fitnesse#629]
Hello, 
since installing Release v20150130, I can't anymore edit page in wiki mode with Internet Explorer 9 (9.0.8112.16421). 
Indeed, I can't anymore select text or click on Cancel or Ok button. 
When activating "compatibilty mode" on ie, it appears a modal window which seems to be the source of problem.

Problem disappears when reverting .jar to release v20140630. 

it seems due to a block of html added to the end of html page : 
'
<div id="insert-image" class="modal-dialog">
 <div>
  <h2>Insert image</h2>
  <fieldset>
  <p>1. From the files section:</p>
  <pre></pre>
  <ul></ul>
  </fieldset>
  <fieldset>
  <p>2. Provide a URL:</p>
  <input type="text" size="50" value=""></input><button value="Add">Add</button>
  </fieldset>
  <a href="#" class="button">Cancel</a>
 </div>
'

I think this code has been added in this object : 
 fitnesse/src/fitnesse/resources/templates/editPage.vm

hoping I have put all needed information (be comprehensive with me, it is my first issue commited on github !)

Regards, 
Sébastien

**Comment by amolenaar** [comment]
Thanks for the report. Indeed the modal window was the cause of the error.
