### ISSUE TITLE
Install DataTables jQuery plugin for tables

### ISSUE THREAD

**Issue by DmitriyKartashov** [unclebob/fitnesse#630]
http://www.datatables.net/ - poverfull jQuery plug-in for decorating html tables. The plugin allows to perform searching inside the tables, filtering the data and other useful features.
I suggest to install it by default. It will simplify work with the tables.

**Comment by woodybrood** [comment]
What does this actually get a FitNesse user? It's some pretty powerful
table functionality, but what does the user actually do with this in a
typical setup?

Keep in mind that "Big Tables" are often unhealthy in FitNesse tests, as
they are slow and consume a lot of memory when processed/executed.

So, how does it simplify work with the tables?

Daniel A. Woodward
-------------------------
FitNesse using Slim and Java
@woodybrood
http://whotestedthis.co

**Comment by DmitriyKartashov** [comment]
The user gets sorting, better style, filtering and searching. I suggest this list as a default set of features.

In fact it really helps already with 8+ rows tables.
I'm a FitNesse user too. Sure, most of our tables have less than 6 rows of data. Here the features might be superfluous. I agree. But we have to work with 10, 16 and even 50 (in extreme cases up to 100) rows table. I'm not sure that they aren't "Big Tables" but I really miss filtering when I'm btw checking test cases.

I'd also suggest to disabled the features for tables with less than N rows. N = 8 by default. Sorry that I didn't mention it in the origin issue.

**Comment by woodybrood** [comment]
Can it be done in a way that would be compatible with the coloring changes
that folks have implemented?

How would it work with ScriptTable or TableTable?

**Comment by DmitriyKartashov** [comment]
>>Can it be done in a way that would be compatible with the coloring changes
that folks have implemented?
What do you mean? If you are talkng about test results highlighting - answer is yes. Does FitNesse have some other coloring?

As far as I remember tables have no html classes.
I hope it will be possible to define separate class for every type of table. In that case user will be able to configure witch types of tables will have DataTables support.
By default it can be On for DT, DDT and Off for other.

**Comment by amolenaar** [comment]
I don't feel comfortable with this. It would make for a nice plugin. I think it's better to make the UI more pluggable.
