### ISSUE TITLE
Install CodeMirror plugin for page editing

### ISSUE THREAD

**Issue by DmitriyKartashov** [unclebob/fitnesse#631]
http://codemirror.net/ - jQuery plugin for highlighting text in textarea.
It provides a lot of features such as code folding, bracked matching , multiline editing and so on.
Example of the plugin work can be found here: http://runnable.com/UmGTLn0iIYljAAEu/codemirror-example-change-theme

**Comment by amolenaar** [comment]
You want to use this as a replacement for the plain text area? Sounds like a plan, but a custom syntax is needed I suppose(?)

**Comment by DmitriyKartashov** [comment]
Yes, replacement for the plain text area.
You're right. The custom syntax is a part of installation process. Actually the main one.
If you don't mind later I'll discribe which features of FitNesse will be supported in the text editor. I'm only started to work with it.
Btw.
This IDEA plugin will be used as an example of code highlighting: https://plugins.jetbrains.com/plugin/1143
And code folding will be provided for collapsible blocks in the first version as well.

**Comment by amolenaar** [comment]
merged
