### ISSUE TITLE
Test Table Coloring Should Not Instantiate Fixtures

### ISSUE THREAD

**Issue by mwarhaftig** [unclebob/fitnesse#633]
fitnesse.wikitext.parser.ColoredSlimTable.toTarget() instantiates a test page's fixtures in order to call instanceof on them and categorize them as comment tables, import tables, etc for table coloring.  Instantiation is a problem for fixtures like fitnesse.fixtures.TearDown because the constructor calls context.fitNesse.stop() and stops the test prematurely.

This issue can be seen when trying to test the page FitNesse.UserGuide.WritingAcceptanceTests.SliM.ScenarioTable and getting the below error.  Fix will be to not instantiate but calculate superclasses via reflection.

     [java] WARNING: Unable to handle request [Invocation of method 'render' in  class fitnesse.responders.WikiPageResponder$WikiTestPageRenderer threw exception java.lang.NullPointerException at wikiPage.vm[line 1, column 10]]
     [java] org.apache.velocity.exception.MethodInvocationException: Invocation of method 'render' in  class fitnesse.responders.WikiPageResponder$WikiTestPageRenderer threw exception java.lang.NullPointerException at wikiPage.vm[line 1, column 10]
     [java] 	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
      ...
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at fitnesse.fixtures.TearDown.<init>(TearDown.java:15)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
     [java] 	at java.lang.Class.newInstance(Class.java:379)
     [java] 	at fitnesse.wikitext.parser.ColoredSlimTable.toTarget(ColoredSlimTable.java:80)

**Comment by amolenaar** [comment]
> Fix will be to not instantiate but calculate superclasses via reflection.

Or give the TestSystemFactory a method that provides the table type (as a string). If the table is provided a class we can do the column/row colouring just via CSS (via `:first-child`, `:nth-child()`, etc.).

**Comment by mwarhaftig** [comment]
@Arjan - I could only see TestSystemFactory methods being called during a test run (and not during a wiki page load).  Also, if using CSS :first-child, :nth-child() wouldn't we still need to "mark" tables (via html class attributes) in order for the correct CSS rules to action on the correct test table?

Proposed pull request is my approach to avoiding fixture instantiation (to avoid the NPE).  Also included are dedicated test cases for table coloring. 

I can revisit TestSystemFactory & CSS if you don't like its current approach.

**Comment by amolenaar** [comment]
My bad. I should have referred to the SlimTableFactory, instead of TestSystemFactory. We still need to mark the tables, indeed.

I checked the PR. Just wondered why it's checking Fit fixture classes. I think I overlooked that on the initial PR. It should only deal with Slim, right?

**Comment by arjan** [comment]
@mwarhaftig wrong @arjan :p

**Comment by mwarhaftig** [comment]
>Just wondered why it's checking Fit fixture classes. I think I overlooked that on the initial PR. It should only deal with Slim, right?

Yes, there is no Fit table coloring.  Might be overkill but the new acceptance test's Fit fixture class check is to confirm no coloring got added.

**Comment by amolenaar** [comment]
Then what about the references to `fit.ImportFixture`, `fit.Comment`, etc.?

**Comment by mwarhaftig** [comment]
A Slim test ColumnFixture fixture can extend fit.ColumnFixture (for example eg.Division does this) so I assumed was possible for all Slim fixtures to extend their Fit equivalent.
  
Let me double-check this tonight...

**Comment by mwarhaftig** [comment]
Ah, so in Slim a test table will be a Decision Table if type is not specified (via DDT:, Import:, etc).  You are then correct that the table coloring reflection logic is unnecessary. - If SlimFactory.getTableType() does not calculate a table's type but it is a valid class then it must be a decision table.

Updated the commit, simplified code.

**Comment by amolenaar** [comment]
I think you fixed it pretty well :)
