### ISSUE TITLE
Is it possible to restrict a Fitnesse test's time execution?

### ISSUE THREAD

**Issue by cforest** [unclebob/fitnesse#641]
Hello,

Is it somehow possible to restrict a Fitnesse test' time execution? Say, I want to stop the test if it takes more than N minutes. I would be glad to have the corresponding value in properties.xml of a given test. It would be even more convenient if all child processes that were created by the test were terminated, as well.

Is it doable?

Thanks.

**Comment by amolenaar** [comment]
For Slim tests it's possible to set a property `slim.timeout`. This property is the timeout in seconds.

There is no overall timeout property for a complete test/suite.

**Comment by fhoeben** [comment]
What is the slim.timeout exactly. I believe it to be the time for the Slim server to an individual command/function call. Correct?

**Comment by amolenaar** [comment]
Yup. Global timeout's can normally be set on your CI server.

**Comment by cforest** [comment]
Thanks for the answer. Global timeouts specified in CI server might be helpful, but I would vote for a similar parameter in Fitnesse - on the test and the suite levels. If a given test runs more than a test timeout, Fitnesse would stop it and go to the next test in the suite. If a given suite runs more than a suite timeout, Fitnesse stops the suite.

**Comment by amolenaar** [comment]
Closing issue, since there's no apparent action to be taken and issue is idle for 6+ months.
