### ISSUE TITLE
Better message on slim.timeout

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#656]
When the slim.timeout period is exceeded an error is sent to the log of the wiki process
`SEVERE: Killing slim client as exception occurred:java.net.SocketTimeoutException: Read timed out`

And in the wiki page no results of the current table are shown, but 'Errors Occurred' is shown on the top of the page. Clicking on that shows the execution log where an 'Internal Exception:' is shown: `Read timed out`

This is not very helpful (as indicated in #653). 

* The message should mention the `slim.timeout` property as a way to address this, and the current timeout value. 
* Furthermore I would prefer the resulting wiki page to be similar to what happens on a 'StopTest'  or 'StopSuite' exception. Meaning that all the tables are rendered, and all results that were obtained are shown and all assertions not executed marked as such. This also gives the user an indication when exactly the timeout occurred.

**Comment by amolenaar** [comment]
I think the web interface is a lot more informative now, with #660 merged in.
