### ISSUE TITLE
slim.timeout default value

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#657]
The current default value for Slim timeout is 10 seconds. This is quite short, can this be set to 30 seconds or a minute?

**Comment by six42** [comment]
The slim.timeout parameter is old but looks it never worked during test execution. 
With the refactoring I did for SSL this is now working during test execution. But it seems to break many tests.

We have three options:

1 - Restore the previous - not working - timeout implementation. => Timeout will never happen even if a user wants it.

2 - Change the timeout default to 0 = no timeout
=> Individual users which need a timeout can set one.

3 - Do nothing. Ask each user to set a timeout value suiteable for his tests.

I prefer option 2. What are your thoughts?

Long term we might need two timeout settings
A - During the initiation of the socket connection
B - During test execution.

**Comment by amolenaar** [comment]
See also #653.

**Comment by fhoeben** [comment]
I also prefer option 2 for test execution.

For initiation of the connection I do think we need a timeout (I believe I have seen that work in the past). For that 10 seconds seems quite reasonable, although in debug mode I would think it would need to be much larger (say 1 or 2 minutes).

**Comment by six42** [comment]
In debug mode you can set variable: slim.debug.timeout
