### ISSUE TITLE
Do not create a `.gitignore` when unpacking wiki pages

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#658]
When FitNesse is started (I used finesse-standalone.jar) it unpacks the latest version of the wiki pages in `FitNesseRoot`. The latest release also unpacks a file called `.gitignore`, previous versions did not.

This is not very desirable for people not using Git...

**Comment by linquize** [comment]
But it is useful for people using git, nowadays very popular.
If you run Linux, the dot files are normally hidden to you.

**Comment by fhoeben** [comment]
I understand that it is useful, but why does it need to be there by default. Can't people who use Git just add it as part of their own efforts to bring their wiki pages under version control?

I myself have the root of my Git repository one level higher (the level where I also have finesse-standalone.jar, plugins.properties and both the plugins and FitNesseRoot directory). I already have a .gitignore there. 

The point of this issue was just to not place the file there: there (still) are people not using Git or running on Windows. Why should they be burdened with an extra meaningless file that is not even useful to all Git users?

**Comment by clobob** [comment]
agree with fhoeben. 
No need to create a file there by default. All Git users should know how to manage the Git rep by themself if they really need.

**Comment by linquize** [comment]
But there are some fitnesse specific folders patterns to ignore

**Comment by fhoeben** [comment]
And Git users are quite capable of ignoring these themselves. If you feel it is hard to recognize what to ignore I feel a better solution would be to add a description to the Reference Guide, where users of other version management tool can also see what can/should be ignored.

**Comment by amolenaar** [comment]
Superseded by #727.
