### ISSUE TITLE
Tests execute twice after pressing 'test' on wiki page.

### ISSUE THREAD

**Issue by clobob** [unclebob/fitnesse#664]
Hi,
I'm using Fitnesse to test web api.

Here is the case: 
1. create 3 test cases in wiki;
2. press 'Test' on wiki , 3 Get request is expected.
3. these 3 test cases are excuted twice, actually 6 Get request occured.

in my test, one Get method , which is implemented with httpclient, is needed in one case.

can you help on this? thanks!

**Comment by amolenaar** [comment]
Hi,

I assume http-client is called from your fixture, hence the problem should be in your fixture code somewhere.

**Comment by clobob** [comment]
Hi,
after comparing 2 way to execute tests, it's a really bug in fitnesse.
1. use this way 'http://myfitnesseHost.mytest?test'. No problem here
2. use 'test' button on wiki page, the problem occurs.

hope this info can help trace the problem, thanks!

**Comment by amolenaar** [comment]
Can you start FitNesse with the `-v` option and share the console output? I expect the log line starting with "Starting process" to be printed once per test system that will be started.

**Comment by clobob** [comment]
![image](https://cloud.githubusercontent.com/assets/10508051/6679350/5a6c6bd0-cc81-11e4-96fc-aff6e53be799.png)

the log is too long, hope it's the useful part. 
BTW, is it fine there are so many 'socket write error' in the log?

**Comment by amolenaar** [comment]
There shouldn't be any `Output stream closed` messages in the logs, unless you killed the test execution.

I think it's a problem in your setup. I think it's best to remove any theming, plugins and what else. Maybe start with a fresh copy of FitNesse, see if that works.

I got a hunch #666 is also a manifestation of the errors you're facing.

**Comment by clobob** [comment]
Hi,
Sorry, but I try to start it in an empty folder with default setup.
the problem still exist. 
I feel the problem is much related to 'pressing test/suite button on wiki page'.
compare to execute test or suite by using URL(eg: http://myfitnesseserver/mytest?test) directly.

BTW, test execute twice is obviously. 
![image](https://cloud.githubusercontent.com/assets/10508051/6745185/c20e2aac-ceee-11e4-8a29-0e6a1e28d965.png)
depending on above log, 2 distances are started after pressing 'suite' on wiki page. 
so please check this point for the problem. thanks!

**Comment by ggramlich** [comment]
Just to confirm: We also have

    Output stream closed unexpectedly

regularly on our console under linux since around http://www.fitnesse.org/.FrontPage.FitNesseDevelopment.FitNesseRelease20140418
but I am not sure, if that release introduced it.
Apart from that, FitNesse works as expected for us.

**Comment by amolenaar** [comment]
I close this issue since there's no apparent action to be taken and issue is idle for 6+ months.
