### ISSUE TITLE
Page history need provide username and password to access.

### ISSUE THREAD

**Issue by clobob** [unclebob/fitnesse#665]
username and password are needed when trying to access page history. 
After setting a page as secure-write.
i'm trying to lock a test page or suit page to avoid someone to edit, but not avoid to read it's page history. so this should be changed. thanks!

**Comment by mwarhaftig** [comment]
I agree, TestHistory and PageHistory don't seem to be able to do any write or test operations so secure-all (require authentication if any secure flag exists) seems like overkill.  Pull request only requires user authentication if secure-read is set on for page.

**Comment by amolenaar** [comment]
Merged #696, so we can close this issue

**Comment by clobob** [comment]
thanks!
