### ISSUE TITLE
Chinese words display incorrect in execution log.

### ISSUE THREAD

**Issue by clobob** [unclebob/fitnesse#666]
chinese words including in execution log display as messy code.

**Comment by amolenaar** [comment]
Hi,

In order to fix this I need a little more information:
 - Can you provide an example of a test result file (xml file in the files/testResults/*MySuite* folder) with Chinese output? (pref. with an image attached, as my Chinese is a little rusty lately)
 - I need to know if the Chinese words are stored correctly in this file?

**Comment by clobob** [comment]
![image](https://cloud.githubusercontent.com/assets/10508051/6659384/29488830-cbbf-11e4-8d88-3ef4d5b54b6c.png)

**Comment by clobob** [comment]
it is a screenshot from .xml file which was found in \files\testResults\mysuit\*

**Comment by amolenaar** [comment]
Thanks. So the proper words do not end up in the xml file. Then I know where to look.

**Comment by amolenaar** [comment]
I can not reproduce the error. My test is green:

![screen shot 2015-03-19 at 20 55 38](https://cloud.githubusercontent.com/assets/96249/6739657/66f50f60-ce7a-11e4-8632-2d06e2b91cf7.png)

And the execution log output states the same:

![screen shot 2015-03-19 at 20 55 52](https://cloud.githubusercontent.com/assets/96249/6739663/73a74e08-ce7a-11e4-9e54-62f1cc953f68.png)

Are you running FitNesse on the same machine (user account) you're working on? What encoding are you using? You can find that out by adding `${file.encoding}` to a page. For me it says `UTF-8`. What's the encoding used on the SUT? 

BTW. I tried the tests with Slim.

**Comment by clobob** [comment]
In my page it says GBK. 
how can I change it to 'UTF-8'?

**Comment by clobob** [comment]
i'm trying to fix my problem in fixture code:
![image](https://cloud.githubusercontent.com/assets/10508051/6744743/fd1df1a6-cee7-11e4-8b5c-ce84507bb72c.png)
stdout result is changed:
![image](https://cloud.githubusercontent.com/assets/10508051/6744756/1a8f3402-cee8-11e4-8449-8fd672d98394.png)

i wonder if there is a way to fix this problem which don't need to add code in fixture.
thanks!

**Comment by amolenaar** [comment]
I looked through the code. The server is expecting UTF-8 to be printed on stdout/stderr of the SUT.
Apart from that, all byte conversions translate to UTF-8. I added a few extra lines that enforce UTF-8 for template rendering.

Maybe you can provide the JVM option `-Dfile.encoding=UTF-8` to the SUT?
Like this:

    !define COMMAND_PATTERN {java -Dfile.encoding=UTF-8 -cp fitnesse.jar:%p %m}

(replace the column by a semi-column if you're running windows)

**Comment by amolenaar** [comment]
Completely off topic, but what does "这是中文" mean?

**Comment by clobob** [comment]
i'll try this later, since my computer is damaged by accident. :-(
BTW, "这是中文" means 'this is chese word'. :-) thanks a lot!
