### ISSUE TITLE
FileUtil.buildPath() on Unix platform

### ISSUE THREAD

**Issue by mullar** [unclebob/fitnesse#667]
Hi,

It looks like this method was modified which is no longer behaving the way it used in release 20140901.
Before this release it used to return the path for example {"opt","myfolder"} as "/opt/myfolder", due to the later to change to this method it is now returns relative path "opt/myfolder". This method is used by UpdaterImplementation that writes resource files on start up. It appears that now root-path set with -d command line parameter no longer consistently used since update uses it as relative path while other parts of the system using it as absolute path, In Windows because we specify drive letter this is not an issue. What was the reason for the change in behavior? Feels to me this should be fixed.

Thank You

**Comment by amolenaar** [comment]
I checked out that bit of code. It feels like there's some unnecessary processing going on there.

**Comment by mullar** [comment]
Should the method be fixed to previous behavior? I feel that the way it is now is not consistent across platforms.

**Comment by amolenaar** [comment]
I’m diving into that. It seems to me it can be made more consistent with less code.

**Comment by amolenaar** [comment]
I removed FileUtil.buildPath() (98f2e1ee810). It seems to work fine now on both Mac and Windows.

**Comment by mullar** [comment]
Great!!!. We see will have the next release?

Thanks

**Comment by amolenaar** [comment]
Have you checked it for yourself? :) Just to be sure I did not miss anything...

**Comment by mullar** [comment]
Looks good. BTW is there any way we can add custom list of resources to be added/replaced on fitnesse startup/install? It appears not. We repackage fitnesse with custom fixtures and would like to add help wiki with it such that it installs out of the box shipped list of wiki plus custom list that we make available in jar. At the moment as workaround we replace shipped lists with our own by adding it in front of fitnesse jar.

Thanks

**Comment by amolenaar** [comment]
Hi,

You can append files to the file `Resources/updateList` or `Resources/updateDoNotCopyOverList` if you do not want them to be overridden if they already exist. Those files will be extracted on start and when a version has been updated (`META-INF/FitNesseVersion.txt`).

... but you figured that out already ...

I had a discussion with @fhoeben on the subject as well. Maybe the updater should not just check those files, but check for all occurrences of those files across jar files (Java has API calls for that). That way every plugin can add it's own documentation and have it published.

**Comment by mullar** [comment]
Yes that's what we did. Handling all found occurrences sounds like the best option.

**Comment by amolenaar** [comment]
I opened issue #685 for dealing with the documentation. Closing this issue.
