### ISSUE TITLE
Fitnesse Installation problem 

### ISSUE THREAD

**Issue by Tejaswini2** [unclebob/fitnesse#671]
I have downloaded latest Fitnesse jar (fitnesse-standalone) and installed with the command ( java -jar fitnesse-standalone.jar).Found Fitnesse is started on port 80 but it got stuck in between and Fitness page is not getting launched properly.

![fitnesse_page](https://cloud.githubusercontent.com/assets/11366084/6542132/e791afac-c515-11e4-8d7f-cc2824feea18.png)
![fitness_installation_commandline](https://cloud.githubusercontent.com/assets/11366084/6542133/f123b5d8-c515-11e4-8ac7-165f8250bac5.png)

**Comment by ggramlich** [comment]
Your screenshots look fine to me. What exactly are you missing?

**Comment by Tejaswini2** [comment]
yes it is fine.I was confused because I have not found the buttons to create Test case on Fitnesse Welcome page. So how can I create the test cases on this.

**Comment by clobob** [comment]
1) you can simply create Test case by pressing 'edit' button on front page.
2) the other way to create test by pressing 'add' button to create a new page

**Comment by Tejaswini2** [comment]
Thanks for the reply
