### ISSUE TITLE
HASH Maps not working for scenario tables

### ISSUE THREAD

**Issue by WicusG** [unclebob/fitnesse#673]
hash maps are not correctly translated in scenario tables.

!|scenario|my scenario|
|this is a map|!{fname:Bob, lname:Martin, dob:5-Dec-1952}|

!define myHasMap {!{fname:Bob, lname:Martin, dob:5-Dec-1952}}

!|scenario|my scenario|
|this is a map|${myHasMap}|

!define myHasMap2 {
!{
fname:Bob, 
lname:Martin, 
dob:5-Dec-1952
}}

renders key values as <br/>fname, <br/>lname, <br/>dob

**Comment by amolenaar** [comment]
You are escaping your scenario.

If you remove the ! symbol before the table, its contents will be interpreted properly. The exclamation mark ensures that the content of a table is treated as is. The only thing that will be replaced are variable assignments.

E.g.
```
|scenario|my scenario|
|this is a map|!{fname:Bob, lname:Martin, dob:5-Dec-1952}|
```
will render fine.

**Comment by WicusG** [comment]
The problem with that is, that when you have data that need to be in camel case, is then interpreted as by the SLIM to be links.

|scenario|my scenario|
|this is a map| UserMap1| |!{fname:Bob, lname:Martin, dob:5-Dec-1952}|

Are interpreted as
|scenario|my scenario|
|this is a map| UserMap1[?]| |!{fname:Bob, lname:Martin, dob:5-Dec-1952}|

**Comment by ALuckyGuy** [comment]
You can protect the camel-case text from being turned into a link via !- -!: !- UserMap1 -!

Personally I wish there was an option to disable this behavior because for us it's more trouble than it's worth.
