### ISSUE TITLE
Hidden table heads not rendered correctly after spreadsheet to fitnesse import

### ISSUE THREAD

**Issue by WicusG** [unclebob/fitnesse#674]
Create table
-!|Comment|
|Beta|gamma|Delta|
|1|2|3|

Click Fitnesse to Speadsheet
Click Speadsheet to Fitnesse
table now renders as follow
!|-!|Comment|
||Beta|gamma|Delta|
||1|2|3|

**Comment by markhop** [comment]
I have pushed up a fix for this issue in pull request #678.  I think the original behaviour was flawed as it always added a ! to the beginning of the first line even if the original FitNesse format table did not have one.

**Comment by amolenaar** [comment]
Fixed by #678
