### ISSUE TITLE
Problem in creating test case in Fitnesse tool

### ISSUE THREAD

**Issue by Tejaswini2** [unclebob/fitnesse#675]
![fitness_testcase_1](https://cloud.githubusercontent.com/assets/11366084/6581097/b6b6a6be-c77a-11e4-9273-ef775e0c7bfa.png)
![fitness_testcase_2](https://cloud.githubusercontent.com/assets/11366084/6581110/c7731564-
Hello,
I am newly using Fitnesse tool. Created first sample test case and wrote the  fixture code as -
variable defined: TEST_SYSTEM=slim 
classpath: F:\Fitnesse\SampleExample

Simple Cal
first	second	sum?
4	5	9
3	5	9
 while executing found some exception. Could help me where I am wrong.

sample code

package Player;

public class SimpleCal {
	private double first,second;
	
	public void setFirst(double first) {
		this.first=first;
	}
	
	public void setSecond(double second) {
		this.second=second;
	}
	
	public double sum(){
		return first+second;
	}
	
![Uploading sampleFitnessTestcase.png . . .]()

	public double diff(){
		return first-second;
	}
	public double quotient(){
		return first/second;
	}

}

Screenshot is attaching
![fitness_testcase_1](https://cloud.githubusercontent.com/assets/11366084/6581179/50b98146-c77b-11e4-9d34-612ce3c4124f.png)
![fitness_testcase_2](https://cloud.githubusercontent.com/assets/11366084/6581184/574b2ece-c77b-11e4-9e93-09454a0ea7d9.png)

**Comment by Tejaswini2** [comment]
Could not find fixture: SimpleCal message is coming

**Comment by Tejaswini2** [comment]
Also getting exceptions for this fixture code.Screen shot attached for your reference
![fitness_exception](https://cloud.githubusercontent.com/assets/11366084/6589822/bf82ebb6-c7cc-11e4-8ae7-3c71e123fcbd.png)

**Comment by clobob** [comment]
wrong definition in wiki:
pls change it to below style ==>
!path path/to/your/class/files

**Comment by Tejaswini2** [comment]
I have updated the table as for the above sample code then also getting some exception( Screenshot attached)
![samplefitnesstestcase](https://cloud.githubusercontent.com/assets/11366084/6590245/90b0128a-c7d3-11e4-9b82-b362962973a2.png)


!define TEST_SYSTEM {slim}
!path F:\Fitnesse\SampleExample

!|Simple Cal|
|first|second|sum?|
|4|5|9|
|3|5|9|

**Comment by clobob** [comment]
1) make sure the path is where your .class files stored in.
2) add below table after that, the second row is your package name.
|import|
|Player|  

and then try to run again.

**Comment by Tejaswini2** [comment]
I have written 
|import|
|Player|

then also facing the same issue ( Screen shot attached)
![fitness_exception2](https://cloud.githubusercontent.com/assets/11366084/6590920/6f3cdbd2-c7de-11e4-98d8-d2974c168385.png)

**Comment by clobob** [comment]
Oops!
try this. 
===========================
!define TEST_SYSTEM {slim}
!path F:\MyWorkspace\Test\bin
|import|
|Player|
===========================

**Comment by Tejaswini2** [comment]
Thanks a lot . Now it is working

**Comment by janakijayasree** [comment]
!path C:\Users\Jayasree\workspace\Selenium\bin\Sample
!| import |
|Selenium.src.Sample.add|

!| add |
| a| b| sum? |
| 10 | 2 | 12 |
| 3 | 5 | 8 |

i am getting same error

**Comment by Anandkcd08** [comment]
how can i call overloaded Methods?
Ex: public int add(int a, int b){
return a+b;
}
Please help me...

**Comment by clobob** [comment]
@Anandkcd08 , you can refer to this link http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.FixtureCode 
I think this is info you need.
