### ISSUE TITLE
Related to Testing on Fitnesse

### ISSUE THREAD

**Issue by Tejaswini2** [unclebob/fitnesse#676]
Hello,
I need to do some API testing. If I will use Fitnesse tool. Do I need to take the source code from Development team and put the Class path in Fitnesse page as fixture code and write the test table for this.
Or I have to do any changes in source code to make it fixture code for Testing purpose .

**Comment by clobob** [comment]
in my opionion, the fixture code is sufficient.
fixture code should be included into class path in Fitnesse page. 
it support to execute table in wiki.
hope this can help your problem.

**Comment by Tejaswini2** [comment]
Please correct me if I am wrong-

I will take the API from development team ( Class file) and put in the class path in Fitnesse Tool. Then I will create  a table and execute . If I need to do any change in the source code to make it as fixture code  then please let me know

**Comment by clobob** [comment]
fixture code is not the API itself. it should be code to implement or execute the API. it also provide method to return data or message from API for verification in wiki table.

**Comment by Tejaswini2** [comment]
ok.Thanks

**Comment by woodybrood** [comment]
In the future, please use the FitNesse yahoo group for questions.
https://groups.yahoo.com/neo/groups/fitnesse/conversations/messages

The issues list should really be for bugs and feature requests.

Thanks

**Comment by Tejaswini2** [comment]
Hello,

I have written fixture code as -

package Test1;

public class sum {
	public int a;
	public int b;
	          public static int mysum (int a, int b) {
			  int  c=a+b;
			return c; 
		  } 
		} 


and created Fit test case but getting error ( Error screen shot is attached)

Test case 

!define TEST_SYSTEM {slim}
!path D:\Fitness\Workspace\Test\bin

|import|
|Test1|

!|Sum|
|a|b|Sum?|
|2|4|6|
|5|3|7|

Do I need to change Fixture code . If so then what I need to change and what is the approach to write fixture code.

Thanks in Advanced,
Tejaswini
![fitness_testcase_error](https://cloud.githubusercontent.com/assets/11366084/6651932/78371824-ca81-11e4-8143-82c780f33100.png)

**Comment by ggramlich** [comment]
Try renaming your class from "sum" to "Sum"

Package name are lower case in Java. So

package test1;

public class Sum {...


and

|import|
|Test1|

Then you should get different error messages, like that you need setX and setY and getSum Methods.

**Comment by Tejaswini2** [comment]
I modified as per your comment and now I getting the error

variable defined: TEST_SYSTEM=slim 
classpath: D:\Fitness\Workspace\Test\bin

import
test1

Sum
a	b	Sum?
2 Method setA[1] not found in test1.Sum.	4 Method setB[1] not found in test1.Sum.	6 Method Sum[0] not found in test1.Sum.
5 Method setA[1] not found in test1.Sum.	3 Method setB[1] not found in test1.Sum.	7 Method Sum[0] not found in test1.Sum.


How to resolve the issue ?

**Comment by ggramlich** [comment]
You implement the methods setA, setB and Sum.

http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.DecisionTable

**Comment by Tejaswini2** [comment]
Thanks a lot for the answer.
