### ISSUE TITLE
Question on Import wiki

### ISSUE THREAD

**Issue by WicusG** [unclebob/fitnesse#677]
How do I re-import/link from remove wiki if the remote suite has been refactored?  There doesn't seem to be option to remove / re link / re add imports.

**Comment by amolenaar** [comment]
I do not understand your question. Can you provide steps to reproduce your situation?

**Comment by mgaertne** [comment]
Please refer to the mailing list (https://groups.yahoo.com/groups/fitnesse/) for general advice. This is a bug tracker, and should be used to track bugs.

Closed.

**Comment by WicusG** [comment]
Let me explain the issue.
CI.Fitnesse (our core regression fitnesse instance)
local.Fitnesse (developers use for new development)

In CI.Fitnesse we have 
- App1
   -> Suite 1
- App2
  -> Suite 1

We use the wiki import functionality to link CI.Fitnesse/App1 to local.Fitnesse/App1.

in CI.Fitnesse we refactor App1 to Application1
local.Fitnesse/App1 can't find CI.Fitnesse/Application1 ... there is no way under the current setup to fix the "wiki import" under the properties option
