### ISSUE TITLE
Allow plugins to publish their own documentation

### ISSUE THREAD

**Issue by amolenaar** [unclebob/fitnesse#685]
This issue is a spin-off of issue #667.

@mullar asks: 

> Is there any way we can add custom list of resources to be added/replaced on fitnesse startup/install? It appears not. We repackage fitnesse with custom fixtures and would like to add help wiki with it such that it installs out of the box shipped list of wiki plus custom list that we make available in jar. At the moment as workaround we replace shipped lists with our own by adding it in front of fitnesse jar.

@amolenaar replied: 

> You can append files to the file Resources/updateList or Resources/updateDoNotCopyOverList if you do not want them to be overridden if they already exist. Those files will be extracted on start and when a version has been updated (META-INF/FitNesseVersion.txt).
> 
> ... but you figured that out already ...
> 
> I had a discussion with @fhoeben on the subject as well. Maybe the updater should not just check those files, but check for all occurrences of those files across jar files (Java has API calls for that). That way every plugin can add it's own documentation and have it published.

**Comment by amolenaar** [comment]
I think plugins need the same (or similar) mechanism than fitnesse for publishing documentation: check if the version is different from the published version.

For this we need to:

1. scan all jar files for a particular file, containing a version number and an artifact name
2. Let the plugin class publish a version number and point to the documentation. 

That version number is matched with the published version (in `FitNesseRoot/properties`?).

We also need to make the newly added documentation known to the user. How to do that? Add it to the FrontPage?

**Comment by six42** [comment]
This would be a nice feature,

I would propose that all plugins publish their documentation in the Wiki under .plugins.PLUGINNAME

The Frontpage can then have a link to .plugins

.plugins should have a link to fitnesse.org/plugins to show all available plugins and !contents to show all installed plugins


Each plugins.PLUGINNAME page should have a helptext which describes the main features of the plugin and a tag vXX.YY.ZZ that gives the version of the plugin.

As you mentioned under point 2 the plugin class should gives the name of the plugin and the version. 
if these are newer the documentation should be updated at startup.

Open questions / special cases:
Fitnesse has a startup option to suppress the update of the wiki. Is this needed for a plugin as well and how to do this? Maybe a special tag on each plugins.PLUGINNAME page

How can plugins add further special pages like templates or acceptance tests?

**Comment by fhoeben** [comment]
Yes this would be a good feature, but would it only work for plugins? Or would it also provide some feature/support to install fixtures?

What I do at the moment, in my [hsac-fitnesse-fixtures](https://github.com/fhoeben/hsac-fitnesse-fixtures)  is distribute my own 'baseline installation'. It contains: FitNesse, two plugins, some fixtures (with example/documentation pages and acceptance tests) and Selenium drivers. This can of course be cloned from GitHub to get the (fixtures') sources, but I also release it as a 'standalone' zip, which users can just download, unzip and run. 

What I would really to have is a way I could create a customized finesse-standalone.jar that upon first launch does not only extract the standard wiki pages, but also the other elements described above.

**Comment by six42** [comment]
I would expect it to work for fixtures as well if the jar from the fixtures is added to the fitnesse wiki classpath.
