### ISSUE TITLE
Need to test C++ code using Fitnesse tool

### ISSUE THREAD

**Issue by Tejaswini2** [unclebob/fitnesse#690]
Hello,

Few queries :
1. I have to test C++ code . Do I need to install any plug in after from Fitneese jar. I have tried for java code.Now I want to test for C++ code.
2. Need to test C++ code in Linux machine.For this ,How I will proceed.
3. I have class which is opening the file in read only mode . There is no input parameter.Can I test it through Fitnesse tool

Please help me for these queries

**Comment by woodybrood** [comment]
I'm pretty sure you need https://github.com/dougbradbury/cslim to do that.

**Comment by Tejaswini2** [comment]
Some where I found to use fitSharp.Do I need it.

**Comment by woodybrood** [comment]
I don't use FitNesse with C or C++.  If you are going to be in a linux
environment, you probably want to lean towards CSlim. There has been
progress recently getting the .Net platform to run on other OSs, but I
don't know that it would be the solution you are looking for.

**Comment by Kosta-Github** [comment]
Or have a look here: https://github.com/Kosta-Github/fitnesse-cppslim

**Comment by woodybrood** [comment]
Thanks.  I didn't remember that.

**Comment by linquize** [comment]
good hint

**Comment by Tejaswini2** [comment]
Thanks. Let me try...

**Comment by jediwhale** [comment]
fitSharp works with .NET, usually C#.  It does not support C++.

On 2015-03-24 12:37, Tejaswini2 wrote:
>
> Some where I found to use fitSharp.Do I need it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/unclebob/fitnesse/issues/690#issuecomment-85636069>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>

**Comment by Tejaswini2** [comment]
Need one more help. I need to run tests for c++ code in Fitnesse tool in window.So I need to create a fixture .cpp and then what will be code for path and decision table 
Note - Need to run in window

**Comment by Tejaswini2** [comment]
Any update

**Comment by mgaertne** [comment]
Please refer to the mailing list (https://groups.yahoo.com/groups/fitnesse/) for general advice. This is a bug tracker, and should be used to track bugs rather than individual problems with finding a tutorial.

Closed for the purpose of transferring the communication to the proper channel to have it.
