### ISSUE TITLE
Unit tests  fitnesse.FitNesseContextTest.testGetRootPagePath(FitNesseContextTest.java) fails in Windows 

### ISSUE THREAD

**Issue by sergebug** [unclebob/fitnesse#691]
Windows 7 64bit latest FitNesse as of 3/24/2015. AFAIK issue exists at least from 17th of March.
    [junit] junit.framework.AssertionFailedError: expected:<...e1968692532786396932[\]RooT> but was:<...e1968692532786396932[/]RooT>
    [junit] 	at fitnesse.FitNesseContextTest.testGetRootPagePath(FitNesseContextTest.java:16)

Did someone experienced/solved this one?

**Comment by amolenaar** [comment]
Nice. I built on Windows XP a short while ago. I suppose XP is not that picky...

**Comment by amolenaar** [comment]
Closed as #692 has been merged.
