### ISSUE TITLE
what will be code for path and decision table for c++ code for Fitnesse tool

### ISSUE THREAD

**Issue by Tejaswini2** [unclebob/fitnesse#693]
I need to run tests for c++ code in Fitnesse tool in window.So I need to create a fixture .cpp and then what will be code for path and decision table 
Note - Need to run in window

Also what will be the code for path and decision table while creating decision table in linux machine for c++ code

**Comment by mgaertne** [comment]
Please refer to the mailing list (https://groups.yahoo.com/groups/fitnesse/) for general advice. This is a bug tracker, and should be used to track bugs rather than individual problems with finding a tutorial.

Closed as invalid issue.
