### ISSUE TITLE
could the decision table or any other table distinguish mathematical expression？

### ISSUE THREAD

**Issue by HuHeng** [unclebob/fitnesse#694]
example, if I input a "10" on a table cell, the slim could convert it to a number 10. if I input a string “5+5” on a table cell, could slim convert it to a number "10" ?

**Comment by mgaertne** [comment]
FitNesse does not support this out of the box. You can probably write a custom type converter for strings that is capable of that, though.

Best Markus

-- 
Dipl.-Inform. Markus Gärtner
Author of ATDD by Example - A Practical Guide to Acceptance
Test-Driven Development

http://www.shino.de/blog
http://www.mgaertne.de
http://www.it-agile.de
Twitter: @mgaertne

**Comment by six42** [comment]
Yes, have a look at 

http://www.fitnesse.org/FitNesse.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupExpressions

**Comment by HuHeng** [comment]
thanks mgaertne and six42.
        the MarkupExpression is first converted by wikipage language, then the result calculated will be displayed on the page, so slim converts can read the result.
        but i want the mathematical expressions could  be displayed on the page, and the slim convert can distinguish it. because I want test output changes relative to input, while the input may be a dynamic variables. Anyway, I browsed the src of fitnesse slim, and coudn't find the function.

**Comment by mgaertne** [comment]
Take a look at this: http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.CustomTypes

-- 
Dipl.-Inform. Markus Gärtner
Author of ATDD by Example - A Practical Guide to Acceptance
Test-Driven Development

http://www.shino.de/blog
http://www.mgaertne.de
http://www.it-agile.de
Twitter: @mgaertne

**Comment by six42** [comment]
If you have dynamic input you get normally also dynamic output. This is something which can't be easily automated, except if you reimplement the logic you want to test.

But maybe I didn't got your point. Can you give an example of a decision table you want to test.

**Comment by HuHeng** [comment]
the offical dynamic table is
![Uploading image.png . . .]()

**Comment by six42** [comment]
Custom comparators can do the job as @mgaertne wrote already. Or redefine the function "total cents?". You control this function in a real world case.

**Comment by amolenaar** [comment]
Has this issue been resolved?

**Comment by HuHeng** [comment]
I changed my requirement, anyway,this issue could be closed
