### ISSUE TITLE
how can I debug fitnesse with eclipse?

### ISSUE THREAD

**Issue by HuHeng** [unclebob/fitnesse#697]
I creat a new project and use location fitnesse-master after I "ant run" and "ant acceptance_tests".now the project is in my workspace, but i don't konw how to debug fitnesse, when I set a breakpoint then run fitnesse-main as a java application?  it seems doesn't work;

**Comment by linquize** [comment]
I also want to know too!

**Comment by HuHeng** [comment]
it work, the program stop in the fitnesse-main, and i try to know how slim work, but the program cann't stop in the code of slim package .

**Comment by mgaertne** [comment]
Please read the available documentation on this: http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.DebuggingFixtureCode

Closed as this does not appear to be an issue needing fixing.

**Comment by linquize** [comment]
But it does not specifically mention Eclipse...
