### ISSUE TITLE
Customization via FitNesseRoot/files - Security Risk? 

### ISSUE THREAD

**Issue by six42** [unclebob/fitnesse#702]
FitNesse can be customized by placing files in the below folders. These folders are read and writable via the Wiki by any FitNesse user.
Is this not a security leak?

Customization is good. But should this not better be limited to users which can access the folders directly on the server?
  

FitNesseRoot/files/fitnesse/javascript
FitNesseRoot/files/fitnesse/templates
FitNesseRoot/files/fitnesse/css

See also: FitNesseRoot/files/fitnesse/README.txt

**Comment by amolenaar** [comment]
Good point. Previously all CSS and javascript was stored in the files section.

**Comment by amolenaar** [comment]
It would probably help to make the folder files/fitnesse read only via the wiki. We need it to be read from, since we need to serve its content.

**Comment by six42** [comment]
Many thanks @amolenaar for fixing this.
