### ISSUE TITLE
SystemExitSecurityManager is responsible for massive performance problems

### ISSUE THREAD

**Issue by benhamidene** [unclebob/fitnesse#703]
the commit 195a5c6d64bf6b9bf239069c8fa4492e37994ff1 tries to block exiting the virtual machine from any test being executed. That´s why a special SystemExitSecurityManager  is set before any Instruction is run.
This results in a massive perfomance leak mainly in applications with heavy IO operations ike spring applications.

I suggest to replace the solution of the given commit with another way. As a matter of fact a test is not allowed to exit the VM and we can force that by process not by implementation.

**Comment by benhamidene** [comment]
I have committed a pull request for this issue:

https://github.com/unclebob/fitnesse/pull/707

**Comment by bknobloch** [comment]
I'm also interested in a fix for this issue. Thanks for committing a pull request, benhamidene.

**Comment by benhamidene** [comment]
Commit merged https://github.com/unclebob/fitnesse/pull/707
