### ISSUE TITLE
Wiki variable referring to other variable broken

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#709]
Wiki variables are not able to reference other variables, as can be seen in the user manual at http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupVariables

The value of `x` should be `The value of y is y-value` (as the page states), but above that we can see that the value of `x` is actually `The value of y is ${y}`. So the value of `y` is not inserted into `x`.

![image](https://cloud.githubusercontent.com/assets/5467859/7084609/51f52a40-df6f-11e4-95ab-4def03df77c7.png)

**Comment by ggramlich** [comment]
I don't consider it broken. If you take a look at the wiki source, you will see, that

    ${x} is expressed as: The value of y is y-value

is not fake. It is generated by

    !style_code{!-${x}-!} is expressed as: ${x}

https://github.com/unclebob/fitnesse/blob/master/FitNesseRoot/FitNesse/UserGuide/FitNesseWiki/MarkupLanguageReference/MarkupVariables/content.txt

**Comment by fhoeben** [comment]
My bad, I just looked at the 'variable defined' message, and forgot to actually output the content

**Comment by jediwhale** [comment]
The value of y is not rendered until x is rendered.

${x} is rendered as: The value of y is y-value


On 2015-04-10 02:53, Fried Hoeben wrote:
>
> Wiki variables are not able to reference other variables, as can be 
> seen in the user manual at 
> http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupVariables
>
> The value of |x| should be |The value of y is y-value| (as the page 
> states), but above that we can see that the value of |x| is actually 
> |The value of y is ${y}|. So the value of |y| is not inserted into |x|.
>
> image 
> <https://cloud.githubusercontent.com/assets/5467859/7084609/51f52a40-df6f-11e4-95ab-4def03df77c7.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/unclebob/fitnesse/issues/709>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>
