### ISSUE TITLE
-d option doesn't work with absolute paths under Linux

### ISSUE THREAD

**Issue by phauer** [unclebob/fitnesse#712]
Hello,

I like to start Fitnesse from command line. Assume my working directory is /my/dir/.

I use for starting fitnesse:
 java  -cp /home/user/.m2/repository/org/fitnesse/fitnesse/20150226/fitnesse-20150226.jar:/home/user/.m2/repository/org/fitnesse/fitnesse/20150226/fitnesse-20150226-standalone.jar fitnesseMain.FitNesseMain -p 8383 -d /my/dir/

I would expect that Fitnesse creates _only_
/my/dir/FitNesseRoot 
and places all files there (files, properties, updateListe as well as FitNesse, FrontPage, PageFooter etc).

However, Fitnesse creates two directories:
/my/dir/FitNesseRoot  (contains files, properties, updateDoNotCopyOverList, updateList - that's fine)
AND
/my/dir/my/dir/FitNesseRoot (with FitNesse, FrontPage, PageFooter, PageHeader, TemplateLibrary, .gitignore)

Using "-d ." works, but I want to use an absolute path.

**Comment by six42** [comment]
Try to add -r option :
-d /my/dir -r /my/dir

**Comment by sergebug** [comment]
You also may want to use -o key to prevents (omit) updating FitNesseRoot content. 
This is to avoid auto-creation of files under FitNesseRoot

**Comment by phauer** [comment]
I further investigated this issue and it seems to be an Linux specific problem.

Running the command under Linux (Red Head Enterprise Linux; Bash Shell)

java -jar fitnesse-standalone.jar -p 8888 -d /home/user/Downloads/test
(executed from /home/user/Downloads/test)
creates the folder FitNesseRoot and home (with user/Downloads/test/FitNesseRoot).

But under Windows I can't reproduce this issue.

Using -o is not an option, because in this case my tests are failing (Read time out). Some files within FitNesseRoot are not under version control (e.g. files, content.txt, properties, update*) and need to be recreated.

**Comment by phauer** [comment]
As of FitNesse Version 20150424 this issue doesn't appear anymore. Thanks!
