### ISSUE TITLE
SlimTestSystem does not inform its listener of test completion when an exception occurs during execution of a test

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#713]
,At the moment `SlimTestSystem.runTests()` only invokes `testComplete()` only if `processAllTablesOnPage()` returns normally, not if an exception occurs (for instance because a slim timeout occurred).

This means that listeners do not get notified of the fact the test is finished (aborted actually), only of the fact an exception occurred.

This may be a problem for listeners that always expect complete to be invoked if start is invoked for a test (for instance `JUnitRunNotifierResultsListener` does not report on a page where `processAllTablesOnPage()` threw an exception).

I think `testComplete()` should be invoked in a finally-block so the listener is informed of test completion, even if it is with a horrible exception.

I will submit a pull request shortly...

**Comment by amolenaar** [comment]
Has this one been resolved?

**Comment by fhoeben** [comment]
Yes
