### ISSUE TITLE
JUnitRunNotifierResultsListener should inform RunNotifier of the fact testing was aborted because of an exception 

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#714]
If a Slim test run aborts (for instance due to a slim timeout) this is not reported to jUnit by `JUnitRunNotifierResultsListener`. This means that in the jUnit results the fact that pages are skipped because the testSystem was stopped is NOT REPORTED at all.

I think its `testSystemStopped()` implementation should be extended with a call to the notifier reporting a problem while running `mainClass`. 

I'm not sure whether `fireTestAssumptionFailed` or `fireTestFailure` is the most appropriate method of jUnit's `RunNotifier` to call. I'm leaning towards `fireTestAssumptionFailed`.

**Comment by fhoeben** [comment]
I believe a good fix should include `JUnitRunNotifierResultsListener` implementing `TestsRunnerListener`, and tracking how many tests were completed, so that on testSystem abort it can report how many tests were not executed.

**Comment by fhoeben** [comment]
I just looked up [jUnit's documentation on assumptions](http://junit.org/apidocs/org/junit/Assume.html), and now I think we should use `fireTestFailure`

**Comment by amolenaar** [comment]
Closing this issue since #716 has been merged.
