### ISSUE TITLE
Error-prone exception handlung in MethodExecutor 

### ISSUE THREAD

**Issue by benhamidene** [unclebob/fitnesse#722]
The metod __callMethod__ in __fitnesse.slim.MethodExecutor__ does not consider the case where a cause is null and that causes problems:
protected Object callMethod(Object instance, Method method, Object[] convertedArgs) throws Throwable {
    FixtureInteraction interaction = SlimService.getInteractionClass().newInstance();
    try {
      return interaction.methodInvoke(method, instance, convertedArgs);
    } catch (InvocationTargetException e) {
      __throw e.getCause()__;
    }
  }

Actually according to the following JavaDoc , the Target exception should be thrown instead:

http://docs.oracle.com/javase/7/docs/api/java/lang/reflect/InvocationTargetException.html

**Comment by amolenaar** [comment]
Did you have a particular situation where this failed? Or was it an old Java version you were running on?

**Comment by benhamidene** [comment]
Yes The error occurred in our tests and we are using Java 1.6

Sent from iPhone. Please ignore typing errors.

Best Regards
Anis Ben Hamidene

**Comment by amolenaar** [comment]
Can be closed since #723 has been merged.
