### ISSUE TITLE
Move Git integration to a separate module

### ISSUE THREAD

**Issue by amolenaar** [unclebob/fitnesse#727]
The GIT integration is pretty big and adds some dependencies to FitNesse, including common libraries like Apache HttpComponents. This can potentially cause clashes with SUT dependencies.

JGit is also a big library (about 2Mb).

It adds to following dependencies:

     \--- org.eclipse.jgit:org.eclipse.jgit:3.6.2.201501210735-r
          +--- com.jcraft:jsch:0.1.50
          +--- com.googlecode.javaewah:JavaEWAH:0.7.9
          \--- org.apache.httpcomponents:httpclient:4.1.3
               +--- org.apache.httpcomponents:httpcore:4.1.4
               +--- commons-logging:commons-logging:1.1.1
               \--- commons-codec:commons-codec:1.4

**Comment by denisko** [comment]
+1

**Comment by hansjoachim** [comment]
Somewhat unrelated, but I noticed that if you try to update to jgit 3.7 a lot (all?) of the git-related test cases break. I haven't investigated more, though I guess that might become easier if the related functionality is split out more.

**Comment by amolenaar** [comment]
Done.
