### ISSUE TITLE
ScenarioLibrary auto include fails when a page has an invalid wiki named parent

### ISSUE THREAD

**Issue by eamonnfaherty-productmadness** [unclebob/fitnesse#733]
I had a test in the following location

MyProductName.Versions.One.RegistrationTest

My ScenarioLibrary file failed to include when placed at:
MyProductName.Versions.One.ScenarioLibrary
MyProductName.Versions.ScenarioLibrary

The ScenarioLibrary file was successfully included when placed at 
MyProductName.ScenarioLibrary

I know my intermediate page names are invalid Wiki names and that is why the include failed.  It would be great to raise an error telling the user this include is failing as it failed silently and the includes on the test page showed strange results.

**Comment by amolenaar** [comment]
I loosened the page name rules, so also non-wiki-word page names can be chosen. This looks like something that needs solving.

**Comment by eamonnfaherty-productmadness** [comment]
Thanks :+1:

**Comment by amolenaar** [comment]
Might be related to #770 (or the other way around :) ).
