### ISSUE TITLE
When -Dslim.timeout of 0 specified (command line or via plugins.properties), receive fitnesse.slim.SlimError on all tests other than those on 1st port in pool

### ISSUE THREAD

**Issue by ALuckyGuy** [unclebob/fitnesse#734]
I've had problems with this since the slim.timeout feature was activated and haven't been able to use releases past Jan 9th, 2015.  Finally today to take some time to try and figure out what was happening.

Basically I don't want the timeout parameter in use because we have a number of long running tests. However when I specify -Dslim.timeout=0 or any other value on the FitNesse command line, all but the first test fails with the error:
Could not complete testing: fitnesse.slim.SlimError: Error connecting to SLiM server on localhost:8088

What I've realized is that it fails on every test except the first port in the pool. So when I run the first test, port 8085 is used and it works. The rest of the tests start incrementing the port though, and even though my slim server comes up on the specified port, FitNesse doesn't appear to recognize it. I assume FitNesse tries to communicate using 8085. If I keep testing until the port loops back to the first in the pool, that test will succeed but then all that follow fail again and it loops back through the pool.

This only happens if I change the timeout parameter on the command line however. And it doesn't help anything if I add the other parameters to the command line too, such as -slim.port or Dslim.pool.size. If I change the time-out, the port pool feature doesn't seem to work.

By the way, I'm not using the java slim client, but PowerSlim instead. Also, I'd be happy to try to use a plugins.properties file, but I don't have one currently and not exactly sure how one would look.

**Comment by six42** [comment]
Hi Lucky Guy,

If you only have this problem when you add the slim.timeout parameter why do you use it?

Can you please try the latest FitNesse build and don't specify a timeout value. This should work. Previous timeout issues have been fixed.

If  this should still not work start Fitnesse with option -v and share the output from stdout. Also share the exact command line used to start PowerSlim and stdout and stderr  during startup of PowerSlim for the first (working test) and second (failling test). You can see all this on the test result page when pressing the ""Error Occured"" or "output captured" button.

**Comment by ALuckyGuy** [comment]
First off, testing with the latest build, May 6th. 

Second, the problem is I don't want a timeout parameter, but a long non-functional default timeout of 10 seconds was fixed back in January or February I believe and now it kicks in. Since we have some tests that run long, I need to now specify a value to override the default, or actually just disable the timeout entirely by specifying a value of 0. However, that's when the problems occur. Once I specify it on the command line, I have problems as I described. The slim server starts up but the FitNesse server doesn't talk to it unless it just so happens to be the first port in the pool.

I'll try it with the verbose output and post back.

**Comment by ALuckyGuy** [comment]
Ok, tested with Verbose output. This is my command line: 
"C:\Program Files (x86)\Java\jre7\bin\java.exe" -Dfile.encoding=UTF-8 -Dslim.timeout=0 -Dslim.port=9000 -Dslim.pool.size=10  -jar .\fitnesse-standalone.jar -p 8080 -v

As I mentioned before, if I don't set the slim.timeout on the command line, things are fine, but when I set the timeout to any value, the pooling doesn't work. The first test, and any others that go to the first port in the pool work fine, all others fail. The slim server is started up on the correct port, but FitNesse doesn't talk to it.

Here's example output:
May 21, 2015 2:33:46 PM fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (C:\FitNesse-Test\plugins.properties)
Configured verbose logging
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8080
Creating plain socket on port: 8080
Socket class: class java.net.Socket
   Remote address = /29.2.102.164:58589
   Local socket address = /10.25.71.15:8080
   Closed = false
   Connected = true
   Bound = true
   isInputShutdown = false
   isOutputShutdown = false
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9000]
Trying to connect to host: localhost on port: 9000 SSL=false timeout setting: 0
Creating plain client: localhost:9000
Connected to host: localhost on port: 9000 SSL=false timeout setting: 0
Read Slim Header: >Slim -- V0.3<
Got Slim Header: Slim -- V0.3, and Version 0.3
WARNING: Could not detect death of command line test runner.
WARNING: Could not detect death of command line test runner.
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9001]
Trying to connect to host: localhost on port: 9001 SSL=false timeout setting: 0
Creating plain client: localhost:9001
WARNING: Could not detect death of command line test runner.
WARNING: Could not detect death of command line test runner.
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9002]
Trying to connect to host: localhost on port: 9002 SSL=false timeout setting: 0
Creating plain client: localhost:9002
WARNING: Could not detect death of command line test runner.
WARNING: Could not detect death of command line test runner.

You can see in the screenshot PowerSlim starts up with the port specified on the command line. Unfortunately it never receives a request from the FitNesse server.
![5-21-2015 2-37-15 pm](https://cloud.githubusercontent.com/assets/3267060/7756210/d1d92a4a-ffc7-11e4-9e13-c953380a9bec.png)

This is how FitNesse reports the problem to the user.
![5-21-2015 2-35-46 pm](https://cloud.githubusercontent.com/assets/3267060/7756224/02cc5c8a-ffc8-11e4-93c8-5b1a680792ee.png)

Again, works fine when I don't specify a slim timeout value on the command line, but I don't want the default 10 second timeout.

**Comment by six42** [comment]
Hi Lucky Guy
Could you also share what is shown when you press the "Errors Occured" button.

**Comment by six42** [comment]
And can you also send the output as before but without the slim.timeout option and with -v

**Comment by ALuckyGuy** [comment]
Here's the server output when the timeout option is not specified on the command line.

May 22, 2015 8:45:00 AM fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (C:\FitNesse-Test\plugins.properties)
Configured verbose logging
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8080
Creating plain socket on port: 8080
Socket class: class java.net.Socket
   Remote address = /29.2.124.53:59717
   Local socket address = /10.25.71.15:8080
   Closed = false
   Connected = true
   Bound = true
   isInputShutdown = false
   isOutputShutdown = false
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9000]
Trying to connect to host: localhost on port: 9000 SSL=false timeout setting: 10
Creating plain client: localhost:9000
Creating plain client: localhost:9000
Creating plain client: localhost:9000
Creating plain client: localhost:9000
Creating plain client: localhost:9000
Creating plain client: localhost:9000
Connected to host: localhost on port: 9000 SSL=false timeout setting: 10
Read Slim Header: >Slim -- V0.3<
Got Slim Header: Slim -- V0.3, and Version 0.3
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9001]
Trying to connect to host: localhost on port: 9001 SSL=false timeout setting: 10
Creating plain client: localhost:9001
Creating plain client: localhost:9001
Connected to host: localhost on port: 9001 SSL=false timeout setting: 10
Read Slim Header: >Slim -- V0.3<
Got Slim Header: Slim -- V0.3, and Version 0.3
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9002]
Trying to connect to host: localhost on port: 9002 SSL=false timeout setting: 10
Creating plain client: localhost:9002
Creating plain client: localhost:9002
Connected to host: localhost on port: 9002 SSL=false timeout setting: 10
Read Slim Header: >Slim -- V0.3<
Got Slim Header: Slim -- V0.3, and Version 0.3

And when I run with the timeout option, here are the details for the error as reported in the browser:
![5-22-2015 8-48-46 am](https://cloud.githubusercontent.com/assets/3267060/7770721/807b03d8-005f-11e5-9932-3cf7f18a5fe6.png)

**Comment by ALuckyGuy** [comment]
FYI, after discovering a plugins.properties example file in the root repository directory, I specified the same slim parameters with the plugins.properties file and found the same error occurs. 

Here's the verbose output:
Configured verbose logging
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8080
Creating plain socket on port: 8080
Socket class: class java.net.Socket
   Remote address = /29.2.63.238:60749
   Local socket address = /10.25.71.15:8080
   Closed = false
   Connected = true
   Bound = true
   isInputShutdown = false
   isOutputShutdown = false
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9000]
Trying to connect to host: localhost on port: 9000 SSL=false timeout setting: 0
Creating plain client: localhost:9000
Connected to host: localhost on port: 9000 SSL=false timeout setting: 0
Read Slim Header: >Slim -- V0.3<
Got Slim Header: Slim -- V0.3, and Version 0.3
WARNING: Could not detect death of command line test runner.
WARNING: Could not detect death of command line test runner.
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9001]
Trying to connect to host: localhost on port: 9001 SSL=false timeout setting: 0
Creating plain client: localhost:9001
WARNING: Could not detect death of command line test runner.
WARNING: Could not detect death of command line test runner.
Starting process [PowerShell, -NonInteractive, -ExecutionPolicy, unrestricted, -file, .\slim.ps1, 9002]
Trying to connect to host: localhost on port: 9002 SSL=false timeout setting: 0
Creating plain client: localhost:9002
WARNING: Could not detect death of command line test runner.
WARNING: Could not detect death of command line test runner.

Previously I figured it was a only problem with the command-line option since I'd seen others suggest setting the default timeout via the properties file and no one had complained. I'm going to change the subject to reflect this now if I can.

**Comment by ALuckyGuy** [comment]
More info. It's not so much that any timeout specified doesn't work, it's that a 0 time-out doesn't work. 

I think in my original testing I might have ran into trouble because I was thinking of a timeout in milliseconds instead of seconds, and I ended up specifying a timeout too large.  Since timeout is an INT and it's multiplied by 1000, that's not hard to do and when you do so I believe it throws an exception which gets caught. End result is the default of 10 seconds and that's too fast for our system in many circumstances.

Next, when a timeout of 0 is specified, I think it's used as a delay in waiting for slim to start, and with no delay the system tries to communicate with the slim server before it actually starts up and thus fails.

**Comment by amolenaar** [comment]
Does this issue require a patch or can it be closed?

**Comment by ALuckyGuy** [comment]
As far as I know it's still a bug. I haven't tried another release since the May 6th version however. For me I was able to set the timeout high enough that it's not really bothering me now, but a slim.timeout value of 0 definitely exhibits the problem on my system.

**Comment by six42** [comment]
As there is a workaround for ALuckyGuy I propose to close the issue for the moment.

Am 27. Juli 2015 23:02:01 MESZ, schrieb ALuckyGuy <notifications@github.com>:

**Comment by ALuckyGuy** [comment]
It may not be the highest priority, but I'm not sure why we'd close the issue without a fix, especially since the system's behavior is so unexpected and intermittent. The first test after restart will work and then after that, only 1 of slim.pool.size after that. 

With a default timeout now of 10 seconds, it shouldn't be a surprise that at least some people need to adjust it, and disabling the timeout entirely with a value of 0 is a special but not-uncommon case that will immediately cause confusion and frustration.

**Comment by amolenaar** [comment]
@ALuckyGuy you want to make a point for a special `slim.timeout=0` case? With no timeout value set. Are you using 20150426?

In the latest release the use of `slim.timeout` has been limited to only the time it takes for the Slim server to initially connect to FitNesse.

I think I'm missing something here...

**Comment by ALuckyGuy** [comment]
I just tested with the latest edge build - 2015-07-28 - and the same problem occurs: with the slim.timeout = 0, all tests not on the 1st port of pool fail. However I did learn there's a little more to it.  It does NOT happen with the current Java slim server, but it does occur with the PowerSlim server I'm using. 

Not sure if it's a spec issue - the PowerSlim server uses v3 instead of the newer v4 - but I'll do more digging to determine the root cause.

**Comment by amolenaar** [comment]
The protocol has no part in this. `slim.timeout` just says how many seconds FitNesse should wait for the Slim server to come on-line. I tried a few times using the acceptance suite and got this error message after my third attempt:

    Could not complete testing: fitnesse.slim.SlimError: Error connecting to SLiM server on localhost:9088

It's still not clear to me why you want to set `slim.timeout` to 0. 10 or maybe 60 seconds are more reasonable values. Having such a timeout avoids FitNesse to wait forever for the SUT to start.

**Comment by amolenaar** [comment]
Addressed in 20150814.

**Comment by tinybluefish** [comment]
Hello!

 

New message, please read <http://totalexecutivemgmt.com/weather.php?b>

 

admin@tinybluefish.com

**Comment by ShawnWang6** [comment]
I test to run parallel test using multiple executors with PowerSlim, the  script just like below. When  $parallel_max_num is greater than 10,  there is always one or two process  failed to complate, but the parallel tests are successful when  $parallel_max_num is lower than 10. It's strange and has been bothering me.  Can you give some advice?

##################################################################
$parallel_max_num = 12
$testCmd = "RootSuite.HttpDownload?responder=suite&format=text"
$process_array = New-Object -TypeName System.Collections.ArrayList 
for ($num = 0;  $num -lt  $parallel_max_num; $num++)
{
   $port          = Get-FreePort
   $FitPath     = "C:\workspace$num\Fitnesse"
   $commandLine = " -Xmx512m -Dslim.timeout=10810 -Dslim.port=0 -jar c:\fitnesse-standalone.jar -d $FitPath -c $testCmd -p $FitPort -o"
   $process = start java $commandLine -PassThru -NoNewWindow    
   $process_array.Add($process)	
 }

 $timeout = 3600
 Wait-Process -InputObject  $process_array  -Timeout $timeout -ErrorAction SilentlyContinue
 foreach ($p in $process_array)
 {
    if (-not $p.HasExited)
    {
        Write-Host "Process $($p.Id) (start from $($p.StartTime)) hasn't exited for $timeout seconds"
    }
 }

**Comment by ggramlich** [comment]
@ShawnWang6 
You can try to increase the slim.pool.size, which is 10 by default. See http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM

I don't know, what your -Dslim.port=0 might cause. Why do you use it like this?

**Comment by ShawnWang6** [comment]
@ggramlich 
I'll try it and tell you the result.

**Comment by tinybluefish** [comment]
Hi, 

After  a month of   journey I went back  home, it was a  lovely journey, take a  look at some  photos of it  <http://set.taxwino.com/e7oww/5>

admin
