### ISSUE TITLE
Using FIT with Word, Excel and Markdown

### ISSUE THREAD

**Issue by kasajian** [unclebob/fitnesse#735]
I've used FitNesse over the years.   In fact, several years ago I wrote an experimental "PhraseFixture" ( http://www.codeproject.com/Articles/22060/The-Case-for-PhraseFixture-a-better-DoFixture-for ) fixture.

I'm now in an environment where we author our specs in Word documents.   What I would like to do is use FitNesse but have the data come from Word instead of the wiki files.   Interestingly, this smells more like the original FIT project, on which FitNesse is based.

But I don't think it makes sense to start with FIT because it's so old.  Besides, what I'd really like is for the code reads the word documents to use the newer docx APIs (Open XML), i.e..   It's just a zip file with XML inside it.

Unless someone convinces me this is a bad idea, I think what I would like to do is fork off of FitNesse, so I can leverage all it's goodness, but provide a means of feeding the data from a source other than the wiki-files.   Having discuss the FitNesse / SLIP architecture with Bob years ago, I have a feeling things are likely to be relatively well abstracted for to be able to do that without all that much pain.   A little pain would be okay.

Does anyone here who is more familiar with the codebase that I am willing to respond with some guidelines as to where to start first.   You might spend 5/10 minutes and save me a few days of effort trying to get started.

Any feedback (including if/why you think this is a bad idea) is welcome.

Thank you.

**Comment by amolenaar** [comment]
Hi,
I think you should give it a try. I've been working a lot to separate the wiki for the test system bits over the past few years. I think it would be awesome if you can put that to the test.

**Comment by amolenaar** [comment]
That said, I think this topic belongs on the mailing list, instead of the issue tracker :)
