### ISSUE TITLE
Breadcrumbs are unable to render pages which are not WikiWord

### ISSUE THREAD

**Issue by sergebug** [unclebob/fitnesse#737]
In recent FitNesse new pages are no longer required to be a Wiki Word.
One can create a new page named "Bob" and it will be acceptable.
It appears that breadcrumbs will be generated up to Bob page in the path
RootTestSuite>TestSuite>Bob>MyTest 
would render as (note that Bob is no longer part of breadcrumb):
RootTestSuite>TestSuite
Bob 
MyTest

**Comment by mwarhaftig** [comment]
Hi Serge, I was not able to recreate using master.  Can you give more detail on how you created the pages (from the 'Add' menu item or by editing the browser url), let me know the page types of the path pages (Suite, Test or Static) and if you could share a screenshot of the breadcrumb it would be helpful.

**Comment by sergebug** [comment]
@mwarhaftig - You are right. Rebuild with latest master and issue has gone. Looks like it was resolved. I'm closing it now.
