### ISSUE TITLE
fitnesse-standalone.jar corrupt

### ISSUE THREAD

**Issue by davidmagill** [unclebob/fitnesse#741]
fitnesse-standalone.jar on fitnesse.org for the latest release(20150424) is corrupted. Wasn't sure of best way to make this aware. Old version still downloads properly.

**Comment by amolenaar** [comment]
Are you sure? I just downloaded a copy from fitnesse.org and it seems to be working fine. I could even execute the acceptance suite via the browser.

**Comment by amolenaar** [comment]
Crappy wire maybe?

**Comment by davidmagill** [comment]
Ha, no... it wasn't working at the time. It is working now.
