### ISSUE TITLE
Reading test progress path from plugins.properties

### ISSUE THREAD

**Issue by appsetup** [unclebob/fitnesse#743]
Currently in FitNesse we can canfigure in plugins.properties test.history.path , similarly why cant we have a property to set test.progress.path ? If the FitNesseRoot folder is created as a read only folder then none of the test cases can run

**Comment by amolenaar** [comment]
I actually wonder if TestProgress is used at all. FWIK FitNesse itself does not look at it.

**Comment by amolenaar** [comment]
PageInProgress formatter has been removed, as there is no direct use for it.
