### ISSUE TITLE
JAVA_TOOL_OPTIONS causes unit test to fail

### ISSUE THREAD

**Issue by linquize** [unclebob/fitnesse#744]
When `JAVA_TOOL_OPTIONS` environment variable is defined, java will print something to stderr.
`Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar `
so unit test will fail
CommandRunnerTest.testBasics()

CommandRunnerTest.java Line 24
It fail because stderr is not empty

**Comment by mwarhaftig** [comment]
Hi Linquize,  I believe that the failure is specifically due to the behavior of jayatanaag.jar as an agent.  CommandRunnerTest.testBasics() runs correctly with JAVA_TOOL_OPTIONS specifying another agent.

Can you please investigate if jayatanaag.jar is outputting to STDERR regardless of whether Fitnesse is being used?

**Comment by linquize** [comment]
Yes, when I run `java -version`, the same message is printed to stderr.

**Comment by mwarhaftig** [comment]
Ok, cool.  Fixing jayatana's error should resolve your Fitnesse issues.

**Comment by linquize** [comment]
I have to `unset JAVA_TOOL_OPTIONS` in bash, and the problem goes away.
If I `export JAVA_TOOL_OPTIONS=`, the problem still persists.

**Comment by mwarhaftig** [comment]
Ok, can you give the command line output from running `java -version` with JAVA_TOOL_OPTIONS defined.

**Comment by linquize** [comment]
```
user@Ubuntu1204-2:~$ export JAVA_TOOL_OPTIONS=
user@Ubuntu1204-2:~$ java -version
Picked up JAVA_TOOL_OPTIONS: 
java version "1.7.0_25"
OpenJDK Runtime Environment (IcedTea 2.3.10) (7u25-2.3.10-1ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
user@Ubuntu1204-2:~$ 
```

**Comment by hansjoachim** [comment]
I've run into the same problem on Ubuntu 15.04, and have resorted to `unset JAVA_TOOL_OPTIONS` before building FitNesse. It looks like this line printed from jayatana has caused problems for some other applications as well, see the bug reports at https://bugs.launchpad.net/ubuntu/+source/jayatana.

**Comment by linquize** [comment]
Yes, I was running Ubuntu 15.04, with JAVA_TOOL_OPTIONS set when bash starts.

**Comment by hansjoachim** [comment]
With version 2.7-0ubuntu3.1 of jayatana on Ubuntu 15.04 (and 2.7-0ubuntu4 on Ubuntu Wily), it no longer sets JAVA_TOOL_OPTIONS. After installing the update and logging in again I was able to successfully build FitNesse without having to unset the variable.

Could you check whether this resolves the issue for you as well? If it does, I believe this issue can be closed.

Here's the whole changelog entry:
```
jayatana (2.7-0ubuntu3.1) vivid; urgency=medium

  * Do not export JAVA_TOOL_OPTION session file for now. It seems jayatana
     breaks some tools which are running java -version to grep for the runtime
     version. Openjdk hardcode though some outputs "Picked up <variable name>"
     that can't be suppress and isn't willing to remove it as they see it as
     a security vulnerability. Remove session variable export until java
     upstream get a proper upstream solution for Gnome Shell and Unity global
     menu. (LP: #1441487)
     Meanwhile, people who wants to keep this functionality enabled (or
     programs which knows are working well with it) can reexport
     JAVA_TOOL_OPTIONS="-javaagent:/usr/share/java/jayatanaag.jar
     $JAVA_TOOL_OPTIONS" in their session environment on a per program by
     program bases.
```

See https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1441487 for more information.

**Comment by amolenaar** [comment]
There's not much we can do, right? Can this issue be closed? (closed, pls reopen if more action is required)

**Comment by hansjoachim** [comment]
>Can this issue be closed?

I believe so. It should be fixed on the Ubuntu-side (see above), and I haven't run into any problems with this since my previous comment.
