### ISSUE TITLE
Equals() which doesn't take type into consideration

### ISSUE THREAD

**Issue by hansjoachim** [unclebob/fitnesse#747]
I've mentioned the SonarQube instance at http://nemo.sonarqube.org/dashboard/index/390646 before. I looked at the history for the last month, and there was a small spike due to new checks in the code analyzer. Among others, it found two cases of equals()-methods which  doesn't look at the type of the object it is being compared to. See http://nemo.sonarqube.org/component_issues?id=org.fitnesse%3Afitnesse#resolved=false|severities=BLOCKER|rules=squid%3AS2097 for details.

For Delta, it looks like actually does verify type, it just does it by looking at the class name so it might just be the check missing this case. (I haven't double checked whether this is the fully qualified name including package path or just the class name.)

The other one, ScientificDouble, I'm not all that sure about. I briefly tried to add a check to verify the other object was of the same type, but in the test suite for this class it does several comparisons with a regular Double. 

Thus I'm not quite sure how to proceed. Does anyone know the intention for these classes, and whether the equals()-check should become stricter by also looking at type?

**Comment by amolenaar** [comment]
It looks like I introduced those issues in a pursuit of fixing some different ones mentioned by Sonar. I'll look into this, if it's fine by you.

**Comment by hansjoachim** [comment]
>It looks like I introduced those issues in a pursuit of fixing some different ones mentioned by Sonar.

Don't think so. :) If you look at the previous diff, it doesn't affect the equals() method, so it has been that way a long time. I guess SonarQube either added to or refined their rules which made it possible to catch it.

>I'll look into this, if it's fine by you.
No problem. :+1:

**Comment by amolenaar** [comment]
This seems fixed now :)
