### ISSUE TITLE
Getting EXCEPTION__:java.lang.NoClassDefFoundError: com/wm/data/IDataFactory

### ISSUE THREAD

**Issue by vasavinr** [unclebob/fitnesse#749]
I am getting the above mentioned exception when i tried to run Fitnesse test.For this i tried to place the 
jar for com/wm/data/IDataFactory in the classpath.
!path C:\Fitness\wm-wsclient.jar
Also tried to place the jar in systempath..
But still facing same error.Can you please help me on this

**Comment by amolenaar** [comment]
Hi, We have a mailing list where issues like these can be handled. 

Please ask that on the dedicated mailing list (fitnesse@yahoogroups.com) rather than filling the bug tracker that is intended to track bugs. You'll receive more help there.
