### ISSUE TITLE
WYSIWYG (rich text) breaks inlinecode in table.

### ISSUE THREAD

**Issue by szczurmys** [unclebob/fitnesse#756]
Hi.

I wrote the text in plain text, 
![001a_before_plain_text](https://cloud.githubusercontent.com/assets/4983958/8326654/d5e66354-1a62-11e5-8ceb-7392f3ad51a3.png)

this works fine
![001b_parse_plain_text](https://cloud.githubusercontent.com/assets/4983958/8326657/db068878-1a62-11e5-9af6-1da6c668edbf.png)

but when I switched to rich text
![002_rich_text](https://cloud.githubusercontent.com/assets/4983958/8326661/de130726-1a62-11e5-8d97-22fb8edf17f0.png)

then WYSIWYG breaks inlinecode.
![003_breaks_down_plain_text](https://cloud.githubusercontent.com/assets/4983958/8326662/e0f9c31c-1a62-11e5-945e-8ce7bc6ab24a.png)

That is an error, whether inlinecode in table can not be multiline?

**Comment by amolenaar** [comment]
I think it's a limitation of the current rich text editor implementation.
A.k.a. a bug :)

**Comment by szczurmys** [comment]
In the file **fitnesse\resources\wysiwyg\wysiwyg.js**,
in function **handleLine**,
in line **2435**,

I added  **&& !inCodeBlock()** condition in if statement
```
        if (inTable() && !inEscapedText() && !inHashTable() && !inCodeBlock()) {
            handleTableCell(-1);
        }
```	
and now inlineCode looks fine.

![inlinecodelooksfine](https://cloud.githubusercontent.com/assets/4983958/8339701/b2c0041e-1ab9-11e5-8663-417b93bb8c28.png)

**Comment by amolenaar** [comment]
Thanks for investigating. I added a test along with the fix, so it remains working.
