### ISSUE TITLE
Save in the richText isn't working (build #858).

### ISSUE THREAD

**Issue by szczurmys** [unclebob/fitnesse#760]
Hi, again.

In build https://cleancoder.ci.cloudbees.com/job/fitnesse/858/ 

Save in the richText isn't working (saves the document, but without changes). 
Probably, CodeMirror doesn't copy changes.

![saveintherichtext](https://cloud.githubusercontent.com/assets/4983958/8396430/04495d42-1da5-11e5-91cf-d85b2f01cbcc.png)

**Comment by DmitriyKartashov** [comment]
Hi! Thank you for finding the issue.
Pull request with the fix is created.
Please, let me know if you find any other problems with new editor.

**Comment by amolenaar** [comment]
Fixed by #760. I also added a line so the text in CodeMirror is updated when switching from rich text to plain text.
