### ISSUE TITLE
Rich text, combines multiple lines into one line.

### ISSUE THREAD

**Issue by szczurmys** [unclebob/fitnesse#761]
Rich text, combines multiple lines into one line.

![multiline](https://cloud.githubusercontent.com/assets/4983958/8396504/e7e19026-1da8-11e5-867a-fb1e66802848.png)

**Comment by DmitriyKartashov** [comment]
HI! Is it a new issue or an old one?

**Comment by amolenaar** [comment]
This has been this way ever since I built the rich text editor. Back then there was a discussion we might want to use more semantic HTML (e.g. paragraphs).

It makes sense to support newlines better, though.
