### ISSUE TITLE
java.util.ConcurrentModificationException when writing test results

### ISSUE THREAD

**Issue by cedclement** [unclebob/fitnesse#768]
Hello,

I am running fitnesse (v20150226) with FIT (C++ implementation, if that matters).
From time to time I have an incomplete test executions in a suite : for instance, the report indicates 4 tests executed for a suite with 10 tests, no error, no exception.
It happens rarely, on random tests.
So I did a little digging by myself, adding logs and backtraces, and found the test execution was stopped because of a test sytem internal exception : 

Exception : java.util.ConcurrentModificationException at:
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
java.util.ArrayList$Itr.next(ArrayList.java:851)
org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:393)
org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
org.apache.velocity.Template.merge(Template.java:356)
org.apache.velocity.Template.merge(Template.java:260)
fitnesse.reporting.history.TestXmlFormatter.writeResults(TestXmlFormatter.java:188)
fitnesse.reporting.history.TestXmlFormatter.writeResults(TestXmlFormatter.java:175)
fitnesse.reporting.history.TestXmlFormatter.close(TestXmlFormatter.java:162)
fitnesse.reporting.history.SuiteHistoryFormatter.testComplete(SuiteHistoryFormatter.java:87)
fitnesse.reporting.history.SuiteHistoryFormatter.testComplete(SuiteHistoryFormatter.java:28)
fitnesse.testsystems.CompositeTestSystemListener.testComplete(CompositeTestSystemListener.java:40)
fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testComplete(MultipleTestsRunner.java:205)
fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testComplete(MultipleTestsRunner.java:187)
fitnesse.testsystems.CompositeTestSystemListener.testComplete(CompositeTestSystemListener.java:40)
fitnesse.testsystems.fit.FitTestSystem.testComplete(FitTestSystem.java:94)
fitnesse.testsystems.fit.FitClient$FitListeningRunnable.testComplete(FitClient.java:153)
fitnesse.testsystems.fit.FitClient$FitListeningRunnable.attemptToListenToFit(FitClient.java:145)
fitnesse.testsystems.fit.FitClient$FitListeningRunnable.listenToFit(FitClient.java:125)
fitnesse.testsystems.fit.FitClient$FitListeningRunnable.run(FitClient.java:119)
java.lang.Thread.run(Thread.java:745)

I think that the problem is located in TestXmlFormatter.:
The object TestExecutionReport testResponse is accessed concurrently by two threads (from my output traces):
method writeResults : Thread is: FitClient fitOutput
method stdErr Thread is: CommandRunner stdErr

So it seems that fitnesse is trying to append logs on stderr while the velocity engine is rendering the stderr section of the xml output ?

Finally, I checked against the edge build (v20150707), the issue is still present.

**Comment by ufroehling** [comment]
I have the same experience with our nightly suites (v20150424). I was so happy that bug https://github.com/unclebob/fitnesse/issues/514 was fixed which destroyed several suite results per week. But now we have several incomplete suite runs per week and my colleagues are still unhappy with FitNesse

**Comment by amolenaar** [comment]
I'll look into this.

**Comment by amolenaar** [comment]
The issue should be something list related (because the foreach directive is involved).

There are a few places where lists are involved: the test results, the execution logs and the list of exceptions (also instructions and expectations, but those are only used for Slim). 

However, that would mean that there are either exceptions or new test rest results being added. The latter seems unlikely, since the listener is closed.

Each of these are being printed from the template (testResults.vm). I updated the ExecutionReport classes to copy the lists in their respective getters. Does this resolve the issue?
