### ISSUE TITLE
WikiWords and !include

### ISSUE THREAD

**Issue by davidmagill** [unclebob/fitnesse#770]
Not too long ago fitnesse was changed to allow pages that are not formatted as Wiki words.  I noticed that if you try to use "!include .FrontPage.01NonWikiWord" this syntax will not work.  It will get stuck at FrontPage because 01NonWikiWord is not a wiki word.  Are there plans to make !include work with Non wiki words?  I was trying to number certain pages to maintain some type of order, but they are not recognized as wiki words.  So i reverted to AaTestSuite, BbTestSuite... which just doesn't look very clean.

**Comment by amolenaar** [comment]
Fixed by #777.
