### ISSUE TITLE
Provide better feedback on technical failures of SUT

### ISSUE THREAD

**Issue by amolenaar** [unclebob/fitnesse#782]
As discussed in #772, it might be worthwhile improving the feedback in case of an error. You can think of:

 - timeouts when trying to connect to the Slim server
 - errors that occur when launching the SUT (e.g. application crashes due to class path misconfigurations)
 - rename the Execution Log button to "Execution Log..." for consistency
 - refer to execution log from error messages

As @six42 puts it:
> I like your idea to extend the error message with the text:
>  "check the execution log for details".
> I would also propose to change the text on the button to "Execution Log…". I have the feeling that new users are not aware that this is a button as it looks like a Status Indicator. Think it is fine to change the colour of the button based on the test result but the text should not change.

Follow up by @alexkogon:
> Hi Arjen,

> My problem was that the underlying Java process couldn't launch because the classpath wasn't set properly when the Java process was spawned. This is a similar problem to issue #726 which I commented on, though it was happening for a different reason. I added this code so that when the Java process won't launch you see the output in the UI; I wasn't really thinking that the Java process could also just die for whatever reason, and this would also be output.

> I think in the instance where the underlying process is not working (granted, the reason was I had been hacking on the codebase, but this is happening to others too) it is great to have a multi-line output that shows the java command line run, and the error message. In the case where it just died after running for a while, the output is probably still helpful but the java command line may not be that interesting.

> Perhaps we could make FitNesse smart enough to know that the server died on startup and have two different messages if so?

> Let me know if you want me to help on this, I'm not so familiar with the browser code but could probably figure it out or at least collaborate with someone to finalize it. From our point of view the problem was that the java process was dying when we launched it, I figured out why so it is not such a pressing need but having the better error message would have saved us a lot of headaches.

**Comment by alexkogon** [comment]
As said be in touch later on whether you want my help

**Comment by amolenaar** [comment]
Some has been improved. 
@alexkogon Is this fine with you?

**Comment by alexkogon** [comment]
It's better than before because you know what happened. We could make it multi-line in the UI and also display the command run, but it is probably a non-issue for 99% of the users anyhow.

**Comment by amolenaar** [comment]
Let's close this one and open a more actionable one when need arises.
