### ISSUE TITLE
jGit IllegalArgumentException: One of setGitDir or setWorkTree must be called (Windows)

### ISSUE THREAD

**Issue by marcelstuder** [unclebob/fitnesse#785]
We have an existing git repository and want to run fitnesse-standalone.jar from a \wiki subdirectory using git integration.

If the repository directory (.git folder) is not on the same directory level as the fitnesse-standalone.jar, jGit throws an exception when modifying fitnesse pages.

![dirstructure](https://cloud.githubusercontent.com/assets/10497964/9657353/80035dc8-5240-11e5-997b-10c7dcac29b9.png)
![exception](https://cloud.githubusercontent.com/assets/10497964/9657354/818927b8-5240-11e5-876d-4896e1795b98.png)

Steps to reproduce:
* create a folder "repo"
* call "git init" in this directory
* add a file with git and commit (to init git object store)
* make a subdirectory "wiki"
* copy fitnesse-standalone.jar into wiki folder
* Modify plugins.properties to use git VC:
VersionsController=fitnesse.wiki.fs.GitFileVersionsController
RecentChanges=fitnesse.wiki.fs.GitFileVersionsController
* run fitnesse
* modify front page

Expected: 
* Page gets saved, git log shows an additional message due to modifying the page

Actual:
* IllegalArgumentException: One of setGitDir or setWorkTree must be called

Notes:
* if fitnesse-standalone.jar is in the same folder as the repository (.git directory) no exception occurs and git integration works
![repoonsamelevel](https://cloud.githubusercontent.com/assets/10497964/9657420/34895e0a-5241-11e5-873b-19beeaefbb66.png)
![integrationworks](https://cloud.githubusercontent.com/assets/10497964/9657424/37d1e5dc-5241-11e5-9c12-cf90d36a7556.png)

* if GIT_DIR environment variable is set to the location of the .git folder then no exception gets thrown but the git log does not contain any updates and integration does not seem to work (but maybe I'm missing something here...)

**Comment by amolenaar** [comment]
Sorry for the late response.
I'll look into this.

**Comment by amolenaar** [comment]
I created version 1.0.1 of the fitnesse-git-plugin (for use with 20151230). It contains a fix.

The problem is that the `.git` directory is outside the relative path that FitNesse takes into account. If called from within the `wiki` directory, as in the example above, FitNesse takes into account the working directory (`.`) and the root directory (`FitNesseRoot`). Therefore it won't check the parent folder.

**Comment by marcelstuder** [comment]
Sorry for putting this issue in the wrong place. I should have posted the issue on https://github.com/timander/fitnesse-git-plugin ...

I've just tried version 1.0.1 with FitNesse 20151230 and it works as expected, so thank you for investing your time and for your great work.

**Comment by amolenaar** [comment]
It's in the right place :). When you opened the issue, Git support was still in FitNesse.

Thanks a lot for verifying. I'm happy I helped you out.
