### ISSUE TITLE
Lotus notes link does not work anymore

### ISSUE THREAD

**Issue by staniere** [unclebob/fitnesse#786]
Hello, 
In older version of fitnesse (=~ 6-12 month ago), i was able to add some "lotus note" links such as : 
[[fiche anomalie lotus notes][notes://venus/C1256C090046CD44/2CE10BE2B6B54C8D80256B35006093EE/0A9C78096549316AC1257DDA005F3CEF]]

It does not work anymore as now it displays : 
fiche anomalie lotus notes[?]

It seem it now work only with "http://" links

**Comment by amolenaar** [comment]
Do you by any change recall which FItNesse version that was?

**Comment by staniere** [comment]
Hello, 
I can say that it was working great with release 20140901. 
It was no longer working with version 20150114.

**Comment by amolenaar** [comment]
Related to #820.
