### ISSUE TITLE
"Remote Debug" socket timeout prevent any attempt to debug fixtures when running test

### ISSUE THREAD

**Issue by tmontane** [unclebob/fitnesse#790]
Hi,

Since I have upgraded to one of the latest build of FitNesse (20150426 and 20150814). I previously used a 2011 release.

If I look quickly in the code changed between 2011 and 2015 (a lot of changes), I notice that 2015 version has an hardcoded timeout in the socket connection (SlimCommandRunningClient.connect), and log this line : "Trying to connect to host: localhost on port: 8085 SSL=false timeout setting: 10"

The problem here, is that 10s, is way too short to attach the debugger and step into fixtures (using fitsharp), the consequence is FitNesse server drops the connection before we can actually step in the code. Same thing for any breakpoints in fixtures.

Is it possible when using "Remote Debug" to have no timeout and make it wait for ever ?
Is it possible to set a timeout value from the command line, or something similar to make it able again to debug the fixtures and code in the debugger without losing the connection (like before in 2011) ?

Or maybe you have a better way to debug the tested code ?

Regards.

**Comment by six42** [comment]
You can define the timeout length on your test page. Below sets the timeout to 60 seconds

!define slim.timeout {60}

**Comment by amolenaar** [comment]
Hi,

It might be an idea to use IntelliJ with the FitNesse plugin. You can execute FitNesse test pages and debug them straight from the IDE. Works also with the Community edition of IntelliJ.

That said, those questions are better asked on the mailing list at fitnesse@yahoogroups.com.

**Comment by tmontane** [comment]
@six42 
"You can define the timeout length on your test page. Below sets the timeout to 60 seconds !define slim.timeout {60}"

No you can't (I already tried both, slim.timeout and slim.debug.timeout)... the code is fully hardcoded in server side, no parameters:

src\fitnesse\testsystems\slim\SlimCommandRunningClient.java
(...)
  @Override
  public void connect() throws IOException {
    final int sleepStep = 50; // milliseconds
    long timeOut = System.currentTimeMillis() + connectionTimeout * 1000;
    LOG.finest("Trying to connect to host: " + hostName + " on port: " + port + " SSL=" + useSSL + " timeout setting: " + connectionTimeout);

(...)

**Comment by tmontane** [comment]
@amolenaar 

I don't see your point, what could I do with IntelliJ ? All fixtures are in C#, code targeted by fixtures is C or C++ running on Windows7-64. So I don't understand what IntelliJ will do for me ? We have no Java developers in-house.

**Comment by six42** [comment]
What is hardcoded here? Connectiontimeout is a parameter.

When you set the timeout to 60 do you see the number 60 in the error message?

**Comment by tmontane** [comment]
@six42 

I always see "10"

But I will re-do the test and let you know (maybe a typo or something).

**Comment by jplambert** [comment]
Hi,

I should check the code again but I remember that when I did, I saw that the variables looked up by the code do not bear the name stated in the doc.

So, setting the timeout in FitNesse using !define works, but you should check in the code what are the actual variable names to use. Do not trust the doc on this.

(I know, I know, I would be better providing a PR to fix it)

Will let you know if I find the answer again in the code.

**Comment by jplambert** [comment]
Me again,

It looks I was saying dumb things. We can see in SlimClientBuilder, in determineTimeout method : https://github.com/unclebob/fitnesse/blob/7c177ed033c693a62c566e11eb9851f673bf3a86/src/fitnesse/testsystems/slim/SlimClientBuilder.java

That the looked up variables are indeed slim.timeout and slim.debut.timeout

My previous comment was related to other variables I think, about setting the Slim port and things like that. Things that most people do not use, unless you run the Slim Server in daemon mode, which is kind of half-deprecated from what I see in the code.


Soooooo to get back to the point.

Either the bug in FitNesse is much nastier, or there is some mismatch on your side. Let us know how goes your further investigations.

Thanks! And sorry for the bad hope, and bad mouth about FitNesse!

**Comment by amolenaar** [comment]
@tmontane Indeed, then it makes little sense. Better leave the true help to @six42 and @jplambert :)

**Comment by tmontane** [comment]
Seems to work fine, I've set in the front page before the classpath setup:


>variable defined: TEST_SYSTEM=slim 
>variable defined: COMMAND_PATTERN=%m -r >fitSharp.Slim.Service.Runner,"${FITSHARP_HOME}\fitsharp.dll" %p 
>variable defined: TEST_RUNNER="${FITSHARP_HOME}\Runner.exe" 
>variable defined: slim.debug.timeout=600 


And now I have all the time I need to attach and set breakpoint, analyze code... so far so good ...

Thanks for your help.
