### ISSUE TITLE
Time values in junit output directly generated by fitnesse are incorrect

### ISSUE THREAD

**Issue by mpendas** [unclebob/fitnesse#794]
When running a test via REST using a URL such as the one below:

http://localhost:8086/FrontPage.NewFitnessePOC?suite&format=junit&nochunk

The following output is produced:

<?xml version="1.0"?>
<testsuite name="FrontPage.NewFitnessePOC" tests="1" failures="0" disabled="0" errors="0" time="3673">
      <testcase name="FrontPage.NewFitnessePOC.NewFitnessePOCTestPage" assertions="10" time="2018">
		      <system-out>FrontPage.NewFitnessePOC.NewFitnessePOCTestPage?pageHistory&amp;resultDate=20150917183344</system-out>
    </testcase>
  </testsuite>

The two time values are in milliseconds. They should be in seconds i.e.:
time="3.673"
time="2.018"

**Comment by sergebug** [comment]
When I did junit format I was under impression that jUnit supposed to use milliseconds, was it not? That being said someone already did a check-in to convert it to seconds a while ago. Specifically https://github.com/unclebob/fitnesse/pull/769
Are you sure you are using latest?

**Comment by mpendas** [comment]
I believe I am using the latest version:
[root@cilsdbxd4098 FitNesseRoot]# cat properties
##FitNesse properties
#Mon Jun 22 10:57:58 EDT 2015
Version=v20150424

Re junit - I think it is a common misconception. junit wants millisecond precision. The actual format is in seconds with three digits after the decimal place. That is how jenkins, at least, interprets the time fields.

**Comment by mpendas** [comment]
I see that it is not the latest release. I will grab the new and check again.

**Comment by mpendas** [comment]
This is better:

<?xml version="1.0"?>
<testsuite name="FrontPage.NewFitnessePOC" tests="1" failures="0" disabled="0" errors="0" time="6">
      <testcase name="FrontPage.NewFitnessePOC.NewFitnessePOCTestPage" assertions="10" time="2">
		      <system-out>FrontPage.NewFitnessePOC.NewFitnessePOCTestPage?pageHistory&amp;resultDate=20150921131614</system-out>
    </testcase>
  </testsuite>

**Comment by mpendas** [comment]
Unfortunately, it looks like the millisecond precision was dropped.

time="6"
