### ISSUE TITLE
Dynamically resolving a variable name using a defined variable is not currently possible

### ISSUE THREAD

**Issue by InspiredIdealist** [unclebob/fitnesse#800]
Consider the use case:
```
!define SOME_VARIABLE {100}
!define VARIABLE_NAME {SOME_VARIABLE}
!define OTHER_VARIABLE {${$[VARIABLE_NAME]}}
```
I would expect that `OTHER_VARIABLE` resolves to: 100
Instead, it resolves to the text: $[SOME_VARIABLE]

**Comment by InspiredIdealist** [comment]
This is an enhancement request

**Comment by six42** [comment]
Hi @InspiredIdealist,
 
You can do this with the below:

!define SOME_VARIABLE {100}
!define VARIABLE_NAME (${SOME_VARIABLE})
!define OTHER_VARIABLE (${VARIABLE_NAME})

All variables return 100
S ${SOME_VARIABLE}
V ${VARIABLE_NAME}
O ${OTHER_VARIABLE}

**Comment by InspiredIdealist** [comment]
Fascinating, if not a little hacky :P. I'll give that a try. Thanks!

**Comment by InspiredIdealist** [comment]
Ah yes, good point. I'll just use that.

**Comment by amolenaar** [comment]
Can this issue be closed?
