### ISSUE TITLE
Junit example for version 20150814

### ISSUE THREAD

**Issue by JeremyCarlsten** [unclebob/fitnesse#814]
I am trying to run fitnesse tests in my maven build using version 20150814 but I am having troubles picking out which example would be best. It appears as though there are a few different ways to configure the test. 
currently in my pom I am running the maven-failsafe-plugin 
and my junit file 
```
@RunWith(FitNesseSuite.class)
@Name("FrontPage.FunctionaL.BackEnd")
@FitnesseDir(systemProperty = "../fitnesse")
@OutputDir(pathExtension = "target")
@ConfigFile("plugins.properties")
class FitnesseBackendTestsIT {

    @Test
    void runFitnesseTests() {}
}

```

although I have tried a few different variations. I can't seem to make it acutally run the tests. We are attempting to upgrade from version 20140418 which is horribly outdated.

**Comment by JeremyCarlsten** [comment]
We were also trying to get the tests setup to run a few suites in parallel. I guess one of my peers had this code working 

 ```

@RunWith(FitNesseRunner.class)
@FitNesseRunner.Suite("FrontPage.FunctionaL.BackEnd")
@FitNesseRunner.FitnesseDir("../fitnesse")
@FitNesseRunner.OutputDir("target")

````

**Comment by amolenaar** [comment]
That looks okay to me. Actually, in the line

    @FitnesseDir(systemProperty = "../fitnesse")

the value should contain a system property (looked up via `System.getProperty()`, instead of a directory reference. That should have fixed your first version, which is deprecated, but should still work.

**Comment by amolenaar** [comment]
Is this issue solved?

**Comment by JeremyCarlsten** [comment]
Go ahead and close it, If i remember correctly I got junit working; however, I didn't get the junit tests to run fit in parallel. It's been pushed into our backlog anyway. Thanks!
