### ISSUE TITLE
Execution logs missing from suite reponder output with xml format

### ISSUE THREAD

**Issue by cedclement** [unclebob/fitnesse#816]
Hello,
It seems that execution logs (stdout, stderr, exit code, ...) are available from all xml outputs (including history) except when using the suite responder with the xml format.

Then maybe this is done on purpose, but I can't see why...

My guess is that the appropriate section is missing in the suiteXML.vm template?

**Comment by amolenaar** [comment]
Hi,

It had not been available via the XML responder before. Indeed, it makes sense to add the output to the XML format as well. (PR anyone?)
