### ISSUE TITLE
Problems with non-WikiWord pages and symbolic links

### ISSUE THREAD

**Issue by ALuckyGuy** [unclebob/fitnesse#820]
FitNesse allows a user to create page names that aren't camel case but these cause problems with Symbolic links. For instance, you can create pages named "Databases" or "Environment1". However if you do this, in several scenarios FitNesse will not work properly.

First, consider the following:
![fitnesse - test suite](https://cloud.githubusercontent.com/assets/3267060/10465940/7de949dc-71bf-11e5-80f7-7254da99fb35.jpg)

and the following pages setup with environment variables defined and symbolic links to the test suites:
![fitnesse - env links](https://cloud.githubusercontent.com/assets/3267060/10465973/a454ccea-71bf-11e5-85ba-417b2369f177.jpg)

SuiteSetUp works when testing Env A.
![fitnesse - symlink camelcase works 1](https://cloud.githubusercontent.com/assets/3267060/10466000/c3f33a78-71bf-11e5-8d57-ddbb726890fd.jpg)

It does not work when testing Env 1:
![fitnesse - symlink camelcase issue 1](https://cloud.githubusercontent.com/assets/3267060/10466007/cfb5d74e-71bf-11e5-97a4-11bdc3294f00.jpg)
Notice too that the content of Test Page 1 actually gets pulled into the failed link.  The page should have the content "Test Page 1", but instead it's just "Page 1" and the word "Test" appears at the end of the Suite Set Up link. It works fine in Env A

Additionally, if you name symbolic links without camelcase names, those fail too.
![fitnesse - symlinks wo camelcase fail too](https://cloud.githubusercontent.com/assets/3267060/10466099/62ce48f4-71c0-11e5-85a2-247f8d9bef87.jpg)
Results in this failure:
![fitnesse - symlinks wo camelcase fail too 2](https://cloud.githubusercontent.com/assets/3267060/10466134/9bdd4fdc-71c0-11e5-935d-b6c111a0ed01.jpg)

These problems aren't new - they've existed for quite a while.

One other problem I am seeing today with the Oct 10th release and appears new is related to creating SymLinks.  I've noticed that if I create new links with a non-WikiWord name, as soon as I click "Create Link" the Properties page refreshes and the link is gone. In practice, the link has been created and if I force a refresh on the normal page, the symlink shows up. Re-opening the Properties page it does not show up, at least not initially. Eventually it does in fact appear on the properties page - it seems to be a caching problem. ~~However I've only noticed this particular caching problem occuring with symlinks named as non-WikiWords - others seem to be working fine. That might be a coincidence because I've only been working with the Oct 10th release a few hours and most of the time has been spent documenting the other issues above.~~ Edit: Scratch that - I've now seen it happen with WikiWord symlinks too. It just seems to be a general caching issue and not related to non-wikiword support.

**Comment by amolenaar** [comment]
I added some fixes for the October, will dig into this.

**Comment by ALuckyGuy** [comment]
Just be clear, this problem didn't just start occurring. It happens with the Aug 14th release and was occurring before that too. I just never got around to documenting it.
