### ISSUE TITLE
Broken link on page FitNesse.UserGuide.AcceptanceTests

### ISSUE THREAD

**Issue by axmbo** [unclebob/fitnesse#822]
Link "Running, Tested Features" on page FitNesse.UserGuide.AcceptanceTests is broken. Apparently, the correct URL is http://ronjeffries.com/xprog/articles/jatrtsmetric/. There are at least other link in the same page to the same broken URL.

**Comment by axmbo** [comment]
Duplicate of issue #789, already fixed.

**Comment by amolenaar** [comment]
Yes. It will be fixed once the next FitNesse release is out.
