### ISSUE TITLE
Progressbar for Sleep fixture

### ISSUE THREAD

**Issue by tschroeder13** [unclebob/fitnesse#826]
Hi all,

is there a known solution to display a bootstrap progress bar along with a slim fixture call 
|Sleep|10000| ?
I wonder how to start both in parallel the fixture and the bootstrap stuff, or maybe integrate the progressbar into the sleep fixture.
Any help or even ideas would be great. Some first lines of code below ;-)

Thanks in advance and best regards!

Tobi

The Bootstrap part may be similar to this
Javascript:
```javascript
$(function () {
  var timerId = 0;
  var ctr=0;
  var max=10;
  
  timerId = setInterval(function () {
    // interval function
    ctr++;
    $('#blips > .progress-bar').attr("style","width:" + ctr*max + "%");
    
    // max reached?
    if (ctr==max){
      clearInterval(timerId);
    }
    
  }, 500);


  $('.btn-default').click(function () {
    clearInterval(timerId);
  });

});
``` 

HTML:
```html
<div class="progress-bar" role="progressbar" style="width: 100%;">
     ctr
</div>
```

**Comment by amolenaar** [comment]
For the progress bar to update, test results have to be received from the SUT. This is where the Sleep is execute, hence the only way to communicate is to finish the sleep (if you catch my drift).

I don't see this work.

As a side note: don't you want your tests to execute as fast as possible?

**Comment by tschroeder13** [comment]
Hej Arjan,

I (miss)use fitnesse for testing across a lot of diffrent server systems. Something like: changes in  database A somehow triggers  a process with influence on Active Directory (system B) and some results in system C. But all these steps need time, and i don't have implemented any retry mechanism.
Sleep is mean of choice.

maybe I have to do some more dev on my fixtures...

Thanks

**Comment by six42** [comment]
Hi Tobias,

the way you use FitNesse sounds interesting. Can you share how you run FitNesse on three servers. Do the tests run in parallel? Any communication or synchronisation? 
Your input would be appreciated best in #806 

To reduce your waiting time a smart sleep with a retry can be very helpful.
Look at jdbcSlim it supports this for database commands.

Sample page here:
https://github.com/six42/jdbcslim/tree/master/FitNesseRoot/PlugIns/JdbcSlim/UserGuide/2KeyBenefits/1WaitingForAsynchronousResults 


If you want to implement it for other fixtures one class with two methods does the job: 
https://github.com/six42/jdbcslim/blob/master/src/main/java/six42/fitnesse/jdbcslim/RetryManager.java

**Comment by tschroeder13** [comment]
Hey six42,
I run one instance of fitnesse on my Workstation and LDAP request to the engaged systems. The test is a sequence of !include pages. no inter test communication no syncing. sorry. 
Thanks for the hint with retryManager.

Have a nice christmas holiday

Tobi
