### ISSUE TITLE
problems in imports lines

### ISSUE THREAD

**Issue by Samarelagouz** [unclebob/fitnesse#831]
i have many problem with imports line when i import fitnesse project like:
import static fitnesse.wiki.PageType.SUITE;
import static org.mockito.AdditionalAnswers.returnsFirstArg;
......
please help me to find the way to solve all this problem
thanks

**Comment by amolenaar** [comment]
The "issues" section is about problems, bugs and issue requests with regards to fitnesse. Your problem sounds more like a general programming problem. You can either direct your question to the FitNesse mailing list (fitnesse@yahoogroups.com) or a forum on programming. If you do so, please also state what you want to achieve, what goes wrong and how you try to achieve it.
