### ISSUE TITLE
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]

### ISSUE THREAD

**Issue by nikoudel** [unclebob/fitnesse#834]
Getting lots of those messages when navigating between pages (eg. simply clicking http://localhost/FitNesse and back). Version v20150814, fresh install on Windows 7.

```
PS C:\temp> java -jar .\fitnesse-standalone.jar -v
marraskuuta 21, 2015 2:15:32 IP. fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (C:\temp\plugins.properties)
Configured verbose logging
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 80
Creating plain socket on port: 80
Socket class: class java.net.Socket
   Remote address = /0:0:0:0:0:0:0:1:52871
   Local socket address = /0:0:0:0:0:0:0:1:80
   Closed = false
   Connected = true
   Bound = true
   isInputShutdown = false
   isOutputShutdown = false
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
```

**Comment by MaximeArnstamm** [comment]
I have the same problem on a fresh install, i tried two versions v20150814 and v20140201
I run fitnesse locally with fitnesse-launcher-maven-plugin

In my console i have these messages, always by 4 : 
déc. 21, 2015 11:07:13 AM fitnesse.FitNesseExpediter send
INFOS: Output stream closed unexpectedly (Stop button pressed?)
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
	at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:70)
	at fitnesse.http.SimpleResponse.sendTo(SimpleResponse.java:22)
	at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:98)
	at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:50)
	at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
	at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
	at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:110)
	at java.lang.Thread.run(Thread.java:745)

I can't reproduce them easily, i don't know yet what is the cause. It's usually after some modifications, but not everytime.

It may be related to another issue i have, but i doubt it :
I have a remote fitnesse and a local fitnesse with the maven plugin. Usually, with this stack, when i set the wiki import, the files are imported in my project, not only the target folder. At the moment, the files aren't saved so each time i clean my project, so i have to specify the wiki import and download the pages again.

**Comment by amolenaar** [comment]
This normally happens if the browser terminates the connection before all data was sent.

What browser + version are you using?

**Comment by amolenaar** [comment]
I've seen this behaviour occur. I think it has something to do with pre-fetching of pages by the browser.
