### ISSUE TITLE
Script Fixture - Can we remove "Or if the first cell is blank." feature for note ?

### ISSUE THREAD

**Issue by suratdas** [unclebob/fitnesse#842]
I am trying to organize my tests so that the execution steps are easily recognizable starting in the same column. I am using a script table for that per below table screenshot and I want first steps to be blank to format my table. As it stands today, if the first cell is blank, the cells in that row are ignored. Is it possible to remove this feature?

![image](https://cloud.githubusercontent.com/assets/9042580/11491823/55154cd0-979a-11e5-94e0-c8d6ad10f117.png)

**Comment by amolenaar** [comment]
This would be a change in protocol. Quite some tests may rely on this feature, so I'd rather keep it as is.

**Comment by jplambert** [comment]
Which protocol are you taking about? The SLIM protocol? I'd find it suspicious if comment lines are sent to the SUT...

**Comment by amolenaar** [comment]
Comment lines are not sent to the SUT. I do not like to change this because that will change the script table convention which will potentially impact many users.

**Comment by jplambert** [comment]
I understand your point.

Is this feature documented? I wasn't aware of it; I have always used the "note" keyword to write comments on Script Tables.

**Comment by six42** [comment]
Hi @suratdas,

I agree with @amolenaar that the script fixture should not be changed.
On the other hand  I like your idea as an alternative.

If you want this feature you can add a new fixture type to Fitnesse as a plugin.Similar to the Dynamic Decision table and the normal Decision Table.
