### ISSUE TITLE
result comparison fail when first column has no value to check

### ISSUE THREAD

**Issue by staniere** [unclebob/fitnesse#849]
hello, 
it seem result comparaison has changed of behavior as fitnesse are no more able to match lines if first column has no value to compare. 
When first column has no value to compare, every lines are considered as missing, and we have equal number of line considered as surplus. 

saw in build #912
![fitcomparison](https://cloud.githubusercontent.com/assets/10977030/11711430/a4566ff2-9f26-11e5-962d-f96baad2f94b.png)

**Comment by amolenaar** [comment]
Is this due to #787?
