### ISSUE TITLE
CheckBox Option on Wiki page

### ISSUE THREAD

**Issue by swaroop1991** [unclebob/fitnesse#850]
Can Wiki Page have an additional feature to provide the user to enable/ Disable a particular test case in a suite. Currently fitnesse has tag's to run specific cases which is not too user friendly.

**Comment by ggramlich** [comment]
Hi swaroop1991,

have you tried the "Skip (Recursive)" checkbox on the page properties?
If you have, what other functionality to disable a test case are you looking for?

**Comment by swaroop1991** [comment]
Hi ggramlich,
Yup the skip(Recursive) feature works fine, but I was looking if we have any scope for adding a checkbox next to the test cases, which would help the user to check few test cases in a suite and run them.

**Comment by amolenaar** [comment]
You can also add a tag to the pages you want to execute and run the suite with `?suite& suiteFilter=mytag`.

**Comment by amolenaar** [comment]
I think this issue can be closed, right?
