### ISSUE TITLE
is there a way to pass a separate properties file?

### ISSUE THREAD

**Issue by haroon-sheikh** [unclebob/fitnesse#855]
I'd like to pass some variables (root urls, etc) to fitnesse, similar to what plugins.properties does.

**Comment by six42** [comment]
Hi Haroon,

There are many ways to customise FitNesse.
To best help you can you describe what your problem is that you want to solve. What extra urls you want to add and in which part of FitNesse (wiki, test system, fixture) you need the extra url information?

**Comment by haroon-sheikh** [comment]
@six42 For example, if Im testing a list of apis using the RestFixture, I'd like to pass a root urls using a properties file so that they're all in one place.

**Comment by six42** [comment]
I am sorry, 
I never worked with the RestFixture so can't give good advice.

Maybe ask your question at https://github.com/smartrics/RestFixture

**Comment by haroon-sheikh** [comment]
It's not really a rest fixture question, more to do with me passing properties to fitnesse

**Comment by six42** [comment]
You can have a look at 
https://github.com/six42/jdbcslim/blob/master/FitNesseRoot/PlugIns/JdbcSlim/UserGuide/3HowtoConfigureTheDatabaseConnection/FeatureOverviewOfPropertyFilesAndTables/content.txt

This is how JdbcSlim manages properties.

The question I can't answer is how you link this data with the RestFixture.

Did you considered using variables or symbols to store your data?

**Comment by amolenaar** [comment]
You can define a configuration file to load. Use the `-f` option:

```
Usage: java -jar fitnesse.jar [-vpdrlfeoaicb]
	-p <port number> {80}
	-d <working directory> {.}
	-r <page root directory> {FitNesseRoot}
	-l <log directory> {no logging}
	-f <config properties file> {plugins.properties}
	-e <days> {14} Number of days before page versions expire
	-o omit updates
	-a {user:pwd | user-file-name} enable authentication.
	-i Install only, then quit.
	-c <command> execute single command.
	-b <filename> redirect command output.
	-v {off} Verbose logging
```

I think it's perfectly valid to use the properties file for this purpose. It's hooked up to the property lookup chain for that reason.

**Comment by haroon-sheikh** [comment]
Yes sorry I meant, passing multiple files using the -f option

**Comment by amolenaar** [comment]
FitNesse does not support that. That might become confusing: how would you deal with the same property being defined in multiple files? Does one take precedence or would properties be merged?

You can combine a configuration file with system properties (passed to the JVM with the `-D` option).

**Comment by amolenaar** [comment]
I think we can close this issue, right?
