### ISSUE TITLE
How to get green SuiteSlimTests.ChainTest with new NodeJS SliM server

### ISSUE THREAD

**Issue by noamtcohen** [unclebob/fitnesse#858]
Hi, maybe you can help with a NodeJS SliM server I'm developing: [SlimJS](https://github.com/noamtcohen/SlimJS/)
If you download the repo and run `npm install`, start fitnesse and navigate to [http://localhost:8080/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ChainTest?test](http://localhost:8080/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ChainTest?test)
I'm not sure how to make the test pass from the documentation [SlimProtocol](http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.SlimProtocol)
You can see my first tests passing here: [http://localhost:8080/FrontPage?test](http://localhost:8080/FrontPage?test)
Thanks, N

**Comment by ggramlich** [comment]
Hi Noam,

I can take a look at it, probably over the weekend.

I assume, you are aware of https://github.com/limadelic/decaf ,
but I am not sure, how complete the implementation of decaf is and I understand, that you are implementing a solution that works with async callbacks.
(I would suggest, that in addition to callbacks, you support normal return values which might then be promises as well, but that is a different story.)

Just to get me started: I followed your instructions, cloned the repo, ran `npm install` and started the fitnesse server from your bundled `fitnesse-standalone.jar`. I ran node v0.10.30, java 1.7.0_79 (OpenJDK).

When running Test on the FrontPage, it fails. The first exception looks like this:

![image](https://cloud.githubusercontent.com/assets/69276/12163658/dac39584-b50f-11e5-8a7c-ce67151bddf9.png)

The captured output is

```
/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/sandbox.js:37
            theType = theType[ns[i]];
                             ^
TypeError: Cannot read property 'Division' of undefined
    at Object.sandbox.make (/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/sandbox.js:37:30)
    at Object.module.exports.make (/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/sandbox.js:9:20)
    at Instructions.proto.make (/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/instructions.js:51:27)
    at doInstruction (/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/slimjs.js:35:22)
    at onReceivedInstructionSet (/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/slimjs.js:29:5)
    at Socket.<anonymous> (/home/gregor/projects/fitnesse_stuff/jsslim_experiment/SlimJS/src/tcp-server.js:28:21)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
```

**Comment by noamtcohen** [comment]
Hi and thanks for the support!

Please update your node version, also what is your working directory?

N

**Comment by ggramlich** [comment]
Hi Noam,

I think, we should move this issue over to your repository.

I was able to run the tests now.

The logic for the `make` method should be:
If a symbol is stored and it points to a string, this string should be used as the name of the Class/Constructor function. (somthing like clazz=Symbols[clazz.substr(1)]
If a symbol is stored and it is an object instance (not string), it should directly be used (you already had s.th. like that).

I will send a pull request and close this issue.
