### ISSUE TITLE
Problem parsing !include statements

### ISSUE THREAD

**Issue by stephenhand** [unclebob/fitnesse#864]
Some of my includes are working as expected, however, with others the parser seems to incorrectly identify the include name and assume that the entire rest of the document is the name of the page I am trying to include.

It seems to be something to do with the number of dot separators in the name, though this is just guesswork on my part.

Doing

!include .MyCompany.IncludePage

works fine, but doing something like 

!include .MyCompany.MyProduct.IncludePage results in the following:

![fitnesse-inclue-error](https://cloud.githubusercontent.com/assets/1694716/12641931/8dbb8b1a-c5aa-11e5-8301-2ef48d53c3c7.png)

This issue occurs on explicit !include statements, but also if I try to specify SetUp or TearDown pages too far down my hierarchy I get the same issue.

I should say that this issue is occuring when I try to run the tests in process using a JUnit runner, I haven't tried to reproduce it on a web server.

**Comment by amolenaar** [comment]
Hi Stephan,

What version of FitNesse are you using? Can you provide an example (test) that reproduces the problem (page layout is fine as well)? I noticed the page that fails to be included is all lower case (hence not a wiki word), some issues have been fixed in the last release.

**Comment by ALuckyGuy** [comment]
This reminds me of an issue I opened a while back about non-wiki words being included in symbolic links. !include commands then fail to work correctly. In the example above, "target" is a non-wiki word.

https://github.com/unclebob/fitnesse/issues/820

**Comment by amolenaar** [comment]
Yes, I thought I nailed it :)

**Comment by stephenhand** [comment]
Ok, I thought I had tried different casing with no success but I will try again, it's possible something else was broken when I tried upper case the first time.

**Comment by ALuckyGuy** [comment]
It's not the casing that's the problem, it's the fact that it's one word. While it should work just having "target" or "Violations", it technically doesn't match the wikiword pattern. Try "TestTarget" or something like that.

I find it annoying that two word page names are required, but I found includes and symbolic links work much better if you avoid one-word page names.

**Comment by stephenhand** [comment]
That did the trick, many thanks
