### ISSUE TITLE
Documentation: Maven information out of date

### ISSUE THREAD

**Issue by Frobitz66** [unclebob/fitnesse#865]
http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.RunningFromMaven

The referenced maven plugin is no longer accessible via the links on this page.
Updated instructions for having maven drive testing would be very helpful.

**Comment by amolenaar** [comment]
I'm not using Maven. Who can help out here?

**Comment by woodybrood** [comment]
Well, this was based on the trinidad plugin written by Gojko a while back. It looks like the maven repository it was shared from is not accessible.

I've imported the source code from Google Code to github (https://github.com/woodybrood/trinidad), but I have no idea if I can do anything about it. It seems to have been abandoned. I'll update here if I can figure anything out.

**Comment by Frobitz66** [comment]
Thanks for the update !
