### ISSUE TITLE
Do you plan to improve Symbolic Links?

### ISSUE THREAD

**Issue by sbellus** [unclebob/fitnesse#868]
Hi

I have more less psychological problem with usage of Symbolic Links as described in http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.SymbolicLinks.

The cause of my problem is to create two level structure of static pages (one is ignored) as described on http://www.fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteVersionsControllerTests.BusinessCase.
Also on the page is stated that the structure has to be created only for technical reason (Because of limitation of Fitnesse).

Is it possible to get rid of this technical structure? The benefit would be that documentation will look more natural.

Because I don't know implementation details, please take following lines only as inspiration.

Fitnesse will provide new page type Bussiness Rules/Tests Template/Examples Template/Bussiness Examples/Parametrized Examples/... I don't know correct name within Fitnesse domain.

The page can be new type (as Test/Suite page) or new special page (http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SpecialPages)

The page will have no Test/Suite button (same as static page)
The tests under page will be not executed during parent suite execution (different as static page)
The tests under page will be executed when the page is linked under the suite page
The undefined variables will be accentuated (may be same layout as for tags can be used)

What do you think about it?
Best regards

**Comment by six42** [comment]
Hi Stefan,

Thanks for the detailed description.
But I got lost. 
Can you descibe your objectives further, best with actual example pages?

Why do you want to test the same pages multiple times?
What would be the differences in each run and how do you plan to configure them?

**Comment by sbellus** [comment]
Yes, I want to run same group of tests more times. I guess, my scenario is same as your one on page http://www.fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteVersionsControllerTests. 

In our case the test cases describe the requirements. We delivers for more architectures PowerPc and Arm. The same requirements are valid on both. 

We have two suites PowerPc and Arm that defines necessary variable for "Test templates" stored under Specification/Examples. See our current structure [FitNesseRoot.zip](https://github.com/unclebob/fitnesse/files/119306/FitNesseRoot.zip).

My wish is to get rid of  Specification/Examples pages and replace them with new page that will be not executed within suite, because it contains only test templates, those have to be configured by suites those links the new type of page.

**Comment by six42** [comment]
Hi Stefan

Thanks for sharing your setup. Always nice to see how others use fitnesse.

There are three options I am aware of:

1. As you did with the purge/skip intermediate page.
2. Move the specification outside the test suite (in a seperate user guide) then you don't need the purge page. 
3. Make arm your reference specification and powerpc a symlink into arm.






Am 5. Februar 2016 16:18:12 MEZ, schrieb Stefan Bellus <notifications@github.com>:

**Comment by sbellus** [comment]
Thanks for your suggestions.

I want to achieve readable documentation. Regarding to content and also form.
I feel uncomfortable with all your suggestions.
1. I already explain
2. I feel that the solution disconnects things that belongs together
3. Why arm should be more special as powerpc :)?

I feel uncomfortable when I have to explain that strike through doesn't mean that scenarios are not valid, but it has to be so because of technical reason.

I am OK with closing the issue, if you are also fine with that.

**Comment by amolenaar** [comment]
This is an interesting subject. I can see that skipping a page can lead to discussion based on the way it's shown in the table of contents.

I think the second option is not as bad as you think, it's basically just another layer:

    root
      + BusinessRules
      + AcceptanceTests
           + PowerPc (contains !defines and settings)
                 + Tests -> .BusinessRules
           + Arm
                 + Tests -> .BusinessRules

When executing the AcceptanceTests the BusinessRules are not directly in scope, hence, they need not be explicitly skipped. I can see some challenges pop up with variables: default/placeholder values need to be defined on a common root page as you do not want to duplicate them.

Regarding point 3: I can see you want to have the architecture (PowerPC/Arm) sections as similar as possible.

There is a fourth option: define the ToC by hand, kind of what I did on the UserGuide main page: http://www.fitnesse.org/FitNesse.UserGuide. The `!contents` can be put in a collapsible section, only available to the tech folks.

**Comment by six42** [comment]
Hi Stefan,

if your users are iritated by the strike through and you don't use prune in other situations you can change the formatting in the TOC:
 https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/resources/css/fitnesse_pages.css line 286

/** Table of Contents **/
.contents a.pruned {
  text-decoration: line-through;
}

**Comment by amolenaar** [comment]
Does this issue require more attention? Or can it be closed?

**Comment by sbellus** [comment]
Thanks for your time.
