### ISSUE TITLE
Is it possible to add a shortcut (preferably 'd' ) for remote debugging of a test page

### ISSUE THREAD

**Issue by suratdas** [unclebob/fitnesse#873]
I am required to frequently debug the fixture run by fitnesse. I use "?responde=test&remote_debug=true" at the end of the test page url for this purpose for every test page I want to debug. Is it possible to create a shortcut key (preferably 'd' ) which does this on the test page. That will be really very handy and will save a lot of time.

**Comment by ggramlich** [comment]
There was a bookmarklet link on a previous version of the user guide, which worked really well for me and would probably fit your desire for a shortcut:

https://github.com/unclebob/fitnesse/blob/756f8c5a840d9fcc291c002e907a267e321ad8c8/FitNesseRoot/FitNesse/UserGuide/WritingAcceptanceTests/DebuggingFixtureCode/content.txt

@amolenaar removed this part in favor of the sentence
The Tools menu contains a Remote Debug action that can be used to start a test run in debug mode.

**Comment by suratdas** [comment]
Okay. If it can be added under Tools menu, it should be possible to add a keyboard shortcut also.

**Comment by amolenaar** [comment]
@suratdas: If you use Java you can debug in IntelliJ with the FitNesse plugin installed.

@ggramlich: Should the bookmark link be reinstated?

**Comment by ggramlich** [comment]
@amolenaar I think, it wouldn't hurt, if the link was there again. It works really well for me and some colleagues.
