### ISSUE TITLE
No longer stopp the process when accessing /?shutdown

### ISSUE THREAD

**Issue by hansjoachim** [unclebob/fitnesse#875]
To reproduce :
1. Run `java -jar fitnesse-standalone.jar`
2. Visittkort localhost to verify it is running. 
3. Locate the process. For gnu/Linux,  run `ps -ef | grep fitnesse`. For Windows, open task manager ()

**Comment by hansjoachim** [comment]
Sorry  about the split.
Task manager (Ctrl +alt+Esc ) and go to the process tab.
4. Visit localhost/?shutdown. 

Fitnesse itself will stop, but the process remains.  This happens with 20151230 and latest snapshot, but with older releases the process stopped too. Looks like a regression.

**Comment by amolenaar** [comment]
Indeed. It also happens on Mac.

**Comment by amolenaar** [comment]
The problem started when I changed FitNesse to use a thread pool instead of spawning threads in the wild (e9accb3).
