### ISSUE TITLE
Running suites does not show the tests summaries

### ISSUE THREAD

**Issue by briceparmentier** [unclebob/fitnesse#876]
Hi,

I just upgraded my FitNesse instance to latest one (v20151230), and got a strange behaviour.
Running a test suite, I have a title named "Test Summaries", under this title, the name of my runner is shown, here "**slim:FitSharp\Runner.exe**".

Inside HTML code of this page, under the tag containing the runner name, there is an "ul" tag that should receive each test recap. But its name (its HTML id) contains the same "\" as in "slim:FitSharp\Runner.exe", that is to say the id of the tag is "**test-system-slim:FitSharp\Runner.exe**", so that the Javascript code can not target the tag to add each test summary.

The Javascript console logs a "**document.getElementById(...) is null**".

For more details see the screenshot attached.
I tried to use the latest release from your Jenkins CI server, but the issue is still present. It was not present on previous official release, v20150814.

Thanks !

![untitled](https://cloud.githubusercontent.com/assets/10654140/13179240/4d200100-d723-11e5-9125-8859be1f7085.png)

**Comment by amolenaar** [comment]
Something has changed there. The escaping of html for javascript has been extended in 696dddb5b67b9024e0b77bd6fee41c558d2c0761. Apparently I missed one case.

**Comment by briceparmentier** [comment]
Thanks !
