### ISSUE TITLE
How to put testcases "outside" fitnesse?

### ISSUE THREAD

**Issue by Semard** [unclebob/fitnesse#881]
I want to be able to update my fitnesse code without having to copy all my testcases into the directory FitNesseRoot.

I've tried to move my testcases and put them directly under C: but when doing this, I'm not able to get the SetUp page included. SuiteSetup is there but not SetUp.

This is how my classpath looks like:
!*****> Classpath references
!path C:\SAFT\fitnesse\*.jar
!path C:\SAFT\fitnesse\lib\*.jar
!path C:\SAFT\fitnesse\lib\saftjars\*.jar          # saftjars are my own developed methods.
!path C:\                                                         # This made no difference
!path C:\testspace\TestCasesMoved\             # This made no difference
!define TEST_RUNNER {fitlibrary.suite.FitLibraryServer}
**********!

**Comment by jediwhale** [comment]
You can use the -d option on the fitnesse command line to specify where your wiki files are located.  The path option is only for locating executable files.  See http://www.fitnesse.org/FitNesse.UserGuide.QuickReferenceGuide#FitNesseCommandLINE

**Comment by Semard** [comment]
Thanks for your prompt answer. We tried what you suggested but with that we couldn't find the FrontPage. I now see that I've not explained my complete problem. I want to have FitNesseRoot with FrontPage, SuiteSetup, ReferenceTestCases et al. in my Fitnesse delivery. And then outside be able to find other "customer" testcases.

**Comment by mgaertne** [comment]
In your case, what I understood, you would have the FitNesseRoot with FrontPage etc. under C:\testspace\ and start FitNesse with -d C:\testspace\. The code is included differently, and you may use full paths to your jars, and your fixture classes.

There is basically no other way, as the default pages are delivered within the jar, and extracted upon first start up of FitNesse. So you need to have the full FitNesseRoot somewhere.

**Comment by TiborVyletel** [comment]
Semard,
I would suggest to use symbolic links in the properties.xml of the "root" page - the content.txt/properties.xml pair placed directly in the FitNesseRoot directory. 

You can reference wiki/tests pages outside the root directory this way:
`<properties>`
...
`<SymbolicLinks>`
  `<CustomerTestCases>file:///full/path/somewhere/on/disk/CustomerTestCases</CustomerTestCases>`
`</SymbolicLinks>`
`</properties>`

We used to 'prepare' this root properties.xml file during maven build process (using  resource filtering functionality)

**Comment by Semard** [comment]
Now I have added this in my properties.xml
<?xml version="1.0"?>
<properties>
	<SymbolicLinks>
	<CustomerTestCases>file:///C:/RefTestCasesScGxAMoved</CustomerTestCases>
	</SymbolicLinks>
	<Files/>
	<RecentChanges/>
	<Search/>
	<saveId>1272448529479</saveId>
	<ticketId>4728227119693878491</ticketId>
</properties>
But I still don't get a link on my FrontPage. I also tried to find CustomerTestCases on the FrontPage, but found nothing. Do I have to make a link in the windows explorer? Since I also tried this and nothing got better.
In my FrontPage content.txt file:
 * [[!-Customer TestCases -!][.CustomerTestCases]]

**Comment by TiborVyletel** [comment]
Cannot really see what's the content of you properties.xml - please reference a gist or something...
ad windows explorer links: no such thing is needed

I tried minimal example myself and it works:
1) in c:\_fitnesse downloaded latest standalone fitnesse (20151230)
2) started (java -jar)
3) stopped
4) added file c:\_fitnesse\FitNesseRoot\[properties.xml](https://github.com/unclebob/fitnesse/files/153313/properties.txt)
5) added directory c:\_externalPages with simple wiki content (see [zip](https://github.com/unclebob/fitnesse/files/153318/_externalPages.zip))
6) started fitnesse again 
7) http://localhost/ExternallyPlaced renders fine...

**Comment by Semard** [comment]
Thank you so much! This solved our problem!

**Comment by amolenaar** [comment]
Nice work. I'll close this issue then.
