### ISSUE TITLE
Format button busts nested tables

### ISSUE THREAD

**Issue by ALuckyGuy** [unclebob/fitnesse#887]
Clicking **Format** on a page with nested tables adds extra whitespace between the open parenthesis and verticle bar when these characters are found: !(|  The result: a busted nested table with messed up formatting.

Example - Paste the following into a page:
```
| Key   |     Nested Data          |
| Test  | !(| Key2 | Example   |
|             1    | Number 1  |)! |
```

Save and note the table. Next, click Edit and then Format. Whitespace is added after !( and before the | - when the page is then rendered, the nested table format is broken.

**Comment by ALuckyGuy** [comment]
By the way, while this issue is only requesting that Format play nicely with nested tables, it would sure be nice if the Format button actually supported them. The example shows how I try to format nested tables manually - lining all the columns up, with the exception of the first columns |, which of course must always be the first character.

Even better would be the system recognizing the nested table and then not requiring the first char to always be | - but instead to allow white space in front of the verticle bar within the nested table structure. This would be ideal:

```
| Key   |     Nested Data          |
| Test  | !(| Key2 | Example   |
            |   1  | Number 1  |)! |
```

**Comment by amolenaar** [comment]
I fixed it in a way nested tables do not break, keeping the current table logic (table rows should start at the beginning of a line) in place. I hope that's fine with you.

**Comment by ALuckyGuy** [comment]
Seems to be working well... thank you!
