### ISSUE TITLE
TwoMinuteExample fails

### ISSUE THREAD

**Issue by b5white** [unclebob/fitnesse#897]
Fitnesse server is up and running.
My tests work, but I'm trying to demo it and TwoMinuteExample fails.

On further review, the CleanCode tests pass but most of the fitnesse acceptance tests I tried failed.
Both Slim and Fit tests are failing.

Running the TwoMinuteExample, I get
"Could not complete testing: fitnesse.slim.SlimError: Timeout while reading slim header from client. Check that you are connecting to the right port and that the slim client is running. You can increase the timeout limit by setting 'slim.timeout' in the fitnesse properties file."

Occasionally I get "Output stream closed unexpectedly: Software caused connection abort: socket write error (Stop button pressed?)" in the cmd window.
My tests continue to work even after that.

Watching the port with TCPView and everything seems to be operating as expected.

Command is:
	fitsharp\Runner.exe -r fitnesse.fitserver.FitServer,fitsharp\fit.dll classes;C:\Users\DOR10186\Fitnesse\lib\annotations-2.0.1.jar;C:\Users\DOR10186\Fitnesse\lib\commons-codec-1.10.jar;C:\Users\DOR10186\Fitnesse\lib\commons-io-2.4.jar;C:\Users\DOR10186\Fitnesse\lib\commons-lang3-3.4.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-core-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-db2-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-derby-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-docs-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-hsqldb-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-mysql-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-netezza-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-oracle-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-postgres-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-sqlserver-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-teradata-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\fitlibrary-20091020.jar;C:\Users\DOR10186\Fitnesse\lib\fitnesse-20150424-standalone.jar;C:\Users\DOR10186\Fitnesse\lib\fitnesse-20151230-standalone.jar;C:\Users\DOR10186\Fitnesse\lib\guava-15.0.jar;C:\Users\DOR10186\Fitnesse\lib\hsqldb-2.3.2.jar;C:\Users\DOR10186\Fitnesse\lib\javassist-3.18.2-GA.jar;C:\Users\DOR10186\Fitnesse\lib\mysql-connector-java-5.1.36.jar;C:\Users\DOR10186\Fitnesse\lib\postgresql-9.3-1101-jdbc41.jar;C:\Users\DOR10186\Fitnesse\lib\reflections-0.9.9.jar;fitsharp\dbfit.dll;fitsharp\dbfit.sqlserver.dll;Fixtures\CleanCodeFixtures.dll;fitsharp\fit.dll 8090

Stdout starts with
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\DOR10186\Fitnesse\classes' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Users\DOR10186\Fitnesse\classes'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

I loaded a virgin copy and most of the acceptance tests pass.

Looking at ProcMon, I can't see anything that it is trying to load from classes and failing.
I don't have a 'classes' directory, but neither does the virgin copy.
I do see that it seems to be finding all the dlls.

I can't see anything in the content of the virgin copy that I'm missing in my running version.

Any ideas?
Thanks for any help.
Brad.

**Comment by jediwhale** [comment]
Are you working in .NET?  I assume you are because you're using 
fitsharp\Runner.  In this case, you don't need any classes or jar files 
in the path - these are for Java only.

On 2016-03-22 17:46, b5white wrote:
>
> Fitnesse server is up and running.
> My tests work, but I'm trying to demo it and TwoMinuteExample fails.
>
> On further review, the CleanCode tests pass but most of the fitnesse 
> acceptance tests I tried failed.
> Both Slim and Fit tests are failing.
>
> Running the TwoMinuteExample, I get
> "Could not complete testing: fitnesse.slim.SlimError: Timeout while 
> reading slim header from client. Check that you are connecting to the 
> right port and that the slim client is running. You can increase the 
> timeout limit by setting 'slim.timeout' in the fitnesse properties file."
>
> Occasionally I get "Output stream closed unexpectedly: Software caused 
> connection abort: socket write error (Stop button pressed?)" in the 
> cmd window.
> My tests continue to work even after that.
>
> Watching the port with TCPView and everything seems to be operating as 
> expected.
>
> Command is:
> fitsharp\Runner.exe -r fitnesse.fitserver.FitServer,fitsharp\fit.dll 
> classes;C:\Users\DOR10186\Fitnesse\lib\annotations-2.0.1.jar;C:\Users\DOR10186\Fitnesse\lib\commons-codec-1.10.jar;C:\Users\DOR10186\Fitnesse\lib\commons-io-2.4.jar;C:\Users\DOR10186\Fitnesse\lib\commons-lang3-3.4.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-core-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-db2-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-derby-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-docs-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-hsqldb-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-mysql-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-netezza-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-oracle-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-postgres-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-sqlserver-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\dbfit-teradata-3.2.0.jar;C:\Users\DOR10186\Fitnesse\lib\fitlibrary-20091020.jar;C:\Users\DOR10186\Fitnesse\lib\fitnesse-20150424-standalone 
> .jar;C:\Users\DOR10186\Fitnesse\lib\fitnesse-20151230-standalone.jar;C:\Users\DOR10186\Fitnesse\lib\guava-15.0.jar;C:\Users\DOR10186\Fitnesse\lib\hsqldb-2.3.2.jar;C:\Users\DOR10186\Fitnesse\lib\javassist-3.18.2-GA.jar;C:\Users\DOR10186\Fitnesse\lib\mysql-connector-java-5.1.36.jar;C:\Users\DOR10186\Fitnesse\lib\postgresql-9.3-1101-jdbc41.jar;C:\Users\DOR10186\Fitnesse\lib\reflections-0.9.9.jar;fitsharp\dbfit.dll;fitsharp\dbfit.sqlserver.dll;Fixtures\CleanCodeFixtures.dll;fitsharp\fit.dll 
> 8090
>
> Stdout starts with
> System.IO.FileNotFoundException: Could not load file or assembly 
> 'file:///C:\Users\DOR10186\Fitnesse\classes' or one of its 
> dependencies. The system cannot find the file specified.
> File name: 'file:///C:\Users\DOR10186\Fitnesse\classes'
> at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, 
> String codeBase, Evidence assemblySecurity, RuntimeAssembly 
> locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, 
> Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean 
> suppressSecurityChecks)
>
> I loaded a virgin copy and most of the acceptance tests pass.
>
> Looking at ProcMon, I can't see anything that it is trying to load 
> from classes and failing.
> I don't have a 'classes' directory, but neither does the virgin copy.
> I do see that it seems to be finding all the dlls.
>
> I can't see anything in the content of the virgin copy that I'm 
> missing in my running version.
>
> Any ideas?
> Thanks for any help.
> Brad.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/unclebob/fitnesse/issues/897>
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>

**Comment by b5white** [comment]
Yes, .NET.

I found
!path lib/*.jar
!path classes
in "C:\Users\DOR10186\Fitnesse\FitNesseRoot\FitNesse\content.txt"

That's the only reference to "classes" that might affect the TwoMinuteExample.
There are others further down in the acceptance tests.

Removing those lines gives a different error.
Command: fitsharp\Runner.exe -r fitnesse.fitserver.FitServer,fitsharp\fit.dll fitsharp\dbfit.dll;fitsharp\dbfit.sqlserver.dll;Fixtures\CleanCodeFixtures.dll;fitsharp\fit.dll 8088

StdErr: Usage: FitServer [-v] [-c config] <assemblies> <host> <port> <socket-token>
	-v	verbose: print log messages to stdout
	assemblies:	';' separated list of assembly filenames

Internal Exception: Error SLiM server died before a connection could be established. 	assemblies:	';' separated list of assembly filenames

**Comment by b5white** [comment]
I also noticed that dbfit looks like it has a hard coded reference to fitnesse-20150424-standalone.jar. I think that is why it is referenced in the command line quoted above. I renamed fitnesse-20151230-standalone.jar to fitnesse-20150424-standalone.jar and changed my reference.
That didn't seem to make any difference.

**Comment by b5white** [comment]
My start command is:
java -cp "lib\dbfit-docs-3.2.0.jar;lib\fitnesse-20150424-standalone.jar" fitnesseMain.FitNesseMain

Fitnesse\FitNesseRoot\content.txt is
!note .NET References
!path fitsharp\dbfit.dll
!path fitsharp\dbfit.sqlserver.dll
!path Fixtures\CleanCodeFixtures.dll
!path fitsharp\fit.dll

!note .NET Fitnesse runner
!define COMMAND_PATTERN {%m -r fitnesse.fitserver.FitServer,fitsharp\fit.dll %p}
!define TEST_RUNNER {fitsharp\Runner.exe}
!define PATH_SEPARATOR {;}

!note global directives -- default to true in latest version
!define COLLAPSE_SETUP {true}
!define COLLAPSE_TEARDOWN {true}

**Comment by b5white** [comment]
There is a Runner.exe.config, but it only contains
<configuration><runtime><loadFromRemoteSources enabled="true"/></runtime></configuration>

**Comment by b5white** [comment]
What else is there to configure?
Seems like the example and the acceptance tests should just run without any other changes.

**Comment by jediwhale** [comment]
For SLIM tests, your COMMAND_PATTERN should be: !define COMMAND_PATTERN {%m -r fitSharp.Slim.Service.Runner %p}
See http://fitsharp.github.io/Slim/GettingStarted.html

**Comment by b5white** [comment]
Wow. That seems completely broken.
The acceptance tests are a mix of fit and slim tests.
According to that page, each slim page should have that line to set the command pattern.
But none of them do.
And my virgin site doesn't have them and runs fine.

**Comment by b5white** [comment]
@jediwhale Getting closer.
Your comment led me to go the other direction.
I removed 
!note .NET Fitnesse runner
!note define COMMAND_PATTERN {%m -r fitnesse.fitserver.FitServer,fitsharp\fit.dll %p}
!note define TEST_RUNNER {fitsharp\Runner.exe}
!note define PATH_SEPARATOR {;}

from FitnesseRoot/content.txt and that fixed it.
Still have one issue, but the TwoMinuteExample runs.

Now the command is
java -cp lib\fitnesse-20151230-standalone.jar;fitsharp\dbfit.dll;fitsharp\dbfit.sqlserver.dll;Fixtures\CleanCodeFixtures.dll;fitsharp\fit.dll fitnesse.slim.SlimService 8086

I'll take up the other issue in a new thread.

Thanks for the help thinking through it,
Brad.

**Comment by mgaertne** [comment]
I think you are confusing a thing or two.

Suites are organized in tree like structures. When you run a test on the leaf level, the tree will be walked upwards until the nearest parent with a definition of the test system is found. That's what picks the test runner in charge of the test. When you execute a higher level suite, tests for the different test systems are grouped together and executed in a batch for each test system.

The same goes with the COMMAND_PATTERN variable.

The acceptance tests for FitNesse are to my knowledge in Java, thus when you execute the TwoMinuteExample as well as the acceptance tests, then the java runner will be used with class files that ship together with FitNesse for the fixtures.

Now, when you define the variables on the top level (FitNesseRoot), FitNesse will try to execute the whole suite with the fitsharp command pattern and test runner. I doubt that works (unless jediwhale included the same fixtures as those that ship with the standard java distribution).

**Comment by b5white** [comment]
Thanks for the clarification.
