### ISSUE TITLE
FitSharp Suite configuration file requires empty path specification

### ISSUE THREAD

**Issue by reprive** [unclebob/fitnesse#900]
This issue was posted before at https://github.com/jediwhale/fitsharp/issues/144, but was considered not FitSharp but FitNesse related.

I'm using a FitSharp suite configuration file to specify fixture assemblies, and I expected that I would not need `!path` statements anymore since the config file specifies the assembly. 

This is the plumbing I use:
` !define COMMAND_PATTERN {%m -c ExcelFixture\config.xml -r fitsharp.Slim.Service.Runner,${FitSharp}\fitsharp.dll %p} `

Here is the config file:
```
<?xml version="1.0" encoding="utf-8" ?>
<suiteConfig>
    <ApplicationUnderTest>
        <AddAssembly>ExcelFixture\ExcelFixture.dll</AddAssembly>
        <AddNamespace>ExcelFixture</AddNamespace>
    </ApplicationUnderTest>
</suiteConfig>
```
However when I run the test, all tests show `Test not run` .
![test not run](https://cloud.githubusercontent.com/assets/5294830/14134412/681702d0-f657-11e5-84b6-0eef496cbe6e.JPG)
After quite some trial and error, I found out that I needed to add  `!path ""`  to make the test work:
![test run](https://cloud.githubusercontent.com/assets/5294830/14134430/7c26ecae-f657-11e5-8ce8-fb0b210b9282.JPG)

Would it be possible to fix this so path statements are no longer required when suite configuration files are used?

I'm using FitNesse 20151230 and FitSharp 2.4.

**Comment by six42** [comment]
Hi Reprive,

can you try once with the below command (without %p) and let us know if this works:
!define COMMAND_PATTERN {%m -c ExcelFixture\config.xml -r fitsharp.Slim.Service.Runner,${FitSharp}\fitsharp.dll}

**Comment by reprive** [comment]
That did the trick. Thanks!
