### ISSUE TITLE
RssResponder

### ISSUE THREAD

**Issue by boredland** [unclebob/fitnesse#901]
Hi there,
before trying to write my own responder I wanted to understand for an example, how the RssResponder (as mentioned here http://www.fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.ConfigurationFile), that already is in the release package (https://github.com/unclebob/fitnesse/tree/master/src/fitnesse/responders) can be used. I think it's a working version, the one that is used on fitnesse.org.
However: Even including it via "Responders=rss:fitnesse.responders.RssResponder" in my plugins.properties gives me no "not found" errors on fitnesse-startup, it still doesn't work but instead give me (for example on /RecentChanges?responder=rss) some "Error Occurred java.lang.NullPointerException" (and nothing more to track it down). Logs are, besides mentioning an Err 400, empty - even in verbose.
What did I miss?
Yours
Jonas

**Comment by amolenaar** [comment]
I'm not sure why it's not working for you. The RSS responder relies on the RecentChanges page. How is your FitNesse instance configured?

**Comment by amolenaar** [comment]
Can I close this issue?
