### ISSUE TITLE
Is there a way we can add an anchor tag on the Test Page?

### ISSUE THREAD

**Issue by kadimulam** [unclebob/fitnesse#902]
Is there a way we can add a HTML anchor tag on the Test Page so that i can open my custom page in a new window? I read the documentation and looks like we can only specify a http path to a resource. 

Basically, i am trying to create a custom HTML form that user can fill in so that i can create all the wiki code and the test case programmatically. So when user wishes to edit a particular test case (i would like to provide a link (anchor tag that i am talking above), which user can use to edit. Is that possible?

**Comment by amolenaar** [comment]
To answer your question: you can just add chunks of HTML to the wiki page by escaping the (`!-<a target="_blank" href="...">...</a>-!

But... Why are you using a form to create test cases? Wouldn't that restrict the users in creating the tests they need?

**Comment by amolenaar** [comment]
No further action needed. Closing the ticket.
