### ISSUE TITLE
What are best possible ways to test Restful web services?

### ISSUE THREAD

**Issue by kadimulam** [unclebob/fitnesse#903]
What are best possible ways to test Restful web services, with a minimal wiki code that a BA/QA user can write? With the RestFixture, the user currently needs to write the HTTP methods, Headers, URI, Request and Response which might not be that user friendly for BQ/QA user. Moreover, this has to be repeated for every HTTP verb they are willing to test. Do you have any suggestions?

**Comment by fhoeben** [comment]
I use scenarios (and sometimes custom subclass fixtures) of my `[JsonHttpTest](https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/2.-Slim-Fixtures#httptest)` fixture to make the wiki content easier to write/maintain and the resulting test report easier to understand (allowing drill down to all technical detail when things fail, but only showing top level information when all is well).

But, as always, the real answer is 'it depends': what it the level of abstraction your BA/QA people are reasoning about the services? If you figure that out you can probably configure the wiki to use those concepts to test with.

**Comment by isparkes** [comment]
We use Smartrics RestFixture:

[https://github.com/smartrics/RestFixture](https://github.com/smartrics/RestFixture)

Look at the "Live Documentation" (link on the README page) in order to see what it can do.
