### ISSUE TITLE
fitnesse.slim.SlimError: Timeout while reading slim header from client

### ISSUE THREAD

**Issue by bruijnri** [unclebob/fitnesse#906]
We are running a Fitnesse server running Release v20150814 
We are using Slim protocol. Slim service is also running on the same server.
Test team size is 10+ and Fitnesse is used for almost all projects on a daily basis.

We are encountering Fitnesse Slim errors every once in a while. It is not always reproducable, meaning when the issue is applicable we have to run the same test a couple of times before it will run. Sometimes we dont have the issue for 1 or more days.

The issue is that after a random test is started, a Slim timeout error appears in Fitnesse fron-end:
```
Could not complete testing: fitnesse.slim.SlimError: Timeout while reading slim header from client. Check that you are connecting to the right port and that the slim client is running. You can increase the timeout limit by setting 'slim.timeout' in the fitnesse properties file
```

When aborting the test before the timeout the following error appears in Front-end:
```
Unable to start test system 'slim': java.net.SocketException: Socket is closed
```

In Fitnesse logfile the following error appears:
```
Can not bind to port 8092. Aborting.
java.net.BindException: Address already in use
```
Note: 8092 is not the only port where the error appears. It could be the case on 8085-8095.

Restarting the Fitnesse server or slim service results in less errors but do not avoid them. 
Slim configuration is default (slim.host, slim.port, slim.pool.size).
If more information is needed please let me know.

**Comment by six42** [comment]
Hello Bruijnri,

thanks for the detailed problem description.
Please increase the slim.pool.size. Maybe try a value twice or three times your team size. This should reduce the frequency of the problem significantly. Also check that no other program uses the port 8085-8115.

Please let us know if this helped.

P.S. Great to see that Fitnesse adds value and is used by your whole team.

**Comment by bruijnri** [comment]
Thanks for the advice. We have increased the pool size. Lets find out that the error occurs less from now :-).

In my opinion increasing the pool is an action to decrease the chance that the error occurs, it is not the real fix.
Is it possible to build an extra feature where Fitnesse checks if the next Slim port is available or not before making the connection?
For example: In our situation Fitnesse tests are part of a Jenkins pipeline. When a test failes due to the Slim error the whole Jenkins pipeline is terminated. We need a 100% score on starting Fitnesse tests.

**Comment by amolenaar** [comment]
Question: is everyone working on one central Fitnesse server?

FitNesse already does some checking, but still race conditions can occur (e.g. if tests are started simultaneously).

One alternative way to fix it is to run in "debug" mode, which will run the Slim server in-process and does not require a socket to communicate (as of 20162131).

**Comment by bruijnri** [comment]
Yes we do have a central Fitnesse server. I'm beginning to understand the issue. Some of our suites run for 30/40 minutes. Meanwhile Fitnesse cycles through the Slim ports and at a certain moment the Slim port is already tried the be used while the previous testsuite is still running. This port should be skipped since it is already in use. Or should is situation handled properly by Fitnesse?

This also clarifies our feeling that the Slim issues occur when Fitnesse is used by more people.

With debug mode: are you referring to the property "manually.start.test.runner.on.debug"?
Where can i find some more info? I am lokking at http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM.

We are running v20150814, is it available here? I guess you made a typo with "20162131".

**Comment by amolenaar** [comment]
Indeed, that should be 20151230 :)

With debug mode, I mean you run the suites with the `debug` parameter added to the suite URL (`SuiteName?suite&debug`, see also http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.DebuggingFixtureCode). This works fine if you automatically start the tests, but is less handy if you start the test suites via the web interface.

**Comment by amolenaar** [comment]
Does this issue still require some action/change?

**Comment by bruijnri** [comment]
Setting pool size to 100 did the trick for us.
