### ISSUE TITLE
JUnitRunNotifierResultsListener should fireTestFinished even when fireTestFailure is called.

### ISSUE THREAD

**Issue by sgo** [unclebob/fitnesse#908]
I've been having issues using the FitNesseRunner with the Gradle build tool as it was simply ignoring any test failures reported by the JUnitRunNotifierResultsListener.

At first I thought this was a bug with Gradle but they claim to support a strict interpretation of the RunNotifier contract meaning you should call fireTestFinished after every fireTestFailure.
See: https://discuss.gradle.org/t/with-custom-junit-runner-failures-are-ignored/2496

After I read this I modified JUnitRunNotifierResultsListener locally and sure enough the test failures are now being picked up by Gradle.

I'd submit a patch but I noticed the JUnitRunNotifierResultsListenerTest is a bit sparse and I'm still having trouble getting IvyIDEA to work properly so I'll try again later.

**Comment by amolenaar** [comment]
#909 merged
