### ISSUE TITLE
Ability to use symbol in a Query table

### ISSUE THREAD

**Issue by EricD2** [unclebob/fitnesse#91]
Currently, the documentation states that symbols are only supported in "a Decision Table, Script Table, or any other kind of table that can call functions", sadly this doesn't seem to include Query table. 

I want to have something like this

<pre>
|Query: list foo by name|
|name |property |id     |
|foo1 |prop1    |$foo1= |
|foo2 |prop2    |$foo2= |
|foo3 |prop3    |$foo3= |

|Query: list bar with foo|
|name |idFoo |property52 |
|bar1 |$foo1 |1          |
|bar2 |$foo1 |2          |
|bar1 |$foo2 |4          |
</pre>

**Comment by amolenaar** [comment]
This is kind-of resolved I'd guess? (if not, please reopen)

**Comment by DmitryKonev** [comment]
It is partly resolved. #525 provides ability to assign symbol values in Query tables. But using symbols for asserts is still unavailable.

    |Query: list bar with foo|
    |name |idFoo |property52 |
    |bar1 |$foo1 |1          |

In this case $foo1 symbol is interpreted as a string.
