### ISSUE TITLE
Change build system to Gradle

### ISSUE THREAD

**Issue by amolenaar** [unclebob/fitnesse#910]
I'd like to change the build system to Gradle. Ant served us well over the years, but Gradle provides some advantages over Ant nowadays.

By using Gradle we can:

* Create a multi-module build, so Fit, Slim and the web server can be built separately.
* Slim can be built against Android libs, to ensure it works.
* Upload to Bintray is easier. Bintray is easier to upload to than Maven Central, this can ease the release process somewhat. Maybe move away from Cloudbees/Jenkins.
* The Gradle wrapper script will prevent the need for separate installation of a build tool.
* The code used to create the updateList and doNotCopyOverList can be moved to a plugin.
* Incremental builds are faster.
* Better integration with IDE's. IntelliJ has proper support for Gradle, and I think Eclipse has the same, alternatively project files can be generated from Gradle.

Am I missing out on something? Would it be better to stick with Ant?

**Comment by six42** [comment]
Hi Arjan,

Good idea!

My experience with Gradle was positive.

**Comment by amolenaar** [comment]
Fixed by #916.
