### ISSUE TITLE
can FitNesse be configured to use Electron (NodeJs/Chromium)?

### ISSUE THREAD

**Issue by violinner** [unclebob/fitnesse#915]
Is there a known configuration of FitNesse which can control Electron (a NodeJs desktop application), through the Chromium WebDriver?

**Comment by amolenaar** [comment]
Hi,

This is a typical question you're better of asking on the mailing list: fitnesse@yahoogroups.com.

You can use SlimJS (https://www.npmjs.com/package/slimjs) to hook NodeJS up to FitNesse. Although I have not tried this myself.
