### ISSUE TITLE
How to debug "Error SLiM server died"

### ISSUE THREAD

**Issue by b5white** [unclebob/fitnesse#918]
Everything was working this morning until just before my demo.

All my FIT tests run, but the Two-Minute example fails against SLiM.
I haven't changed anything with the example pages or the slim server that I know of.
The only change I know of was perhaps a Windows Update last night.
I've rebooted the machine.

ProcMon shows it finding all the DLLs.
Fails with the same error from the command line.

Details:
My command that works:
`fitsharp\Runner.exe -r fitnesse.fitserver.FitServer -v Fixtures\Effort.dll;Fixtures\CashFlow.Fitnesse.dll;C:\Projects\NDOR\controllerApplications\CashFlow\DEV\CashFlowReporting\WebApplication\bin\CashFlow.Model.dll;fitsharp\dbfit.dll;fitsharp\dbfit.sqlserver.dll;fitsharp\fit.dll;Fixtures\CleanCodeFixtures.dll drbtsd66 1262 3863`

Two minute example command that fails:
`fitsharp\Runner.exe -r fitnesse.fitserver.FitServer -v fitsharp\dbfit.dll;fitsharp\dbfit.sqlserver.dll;fitsharp\fit.dll;Fixtures\CleanCodeFixtures.dll 8090`

Error result:

```
     Usage: FitServer [-v] [-c config] <assemblies> <host> <port> <socket-token>
             -v      verbose: print log messages to stdout
             assemblies:     ';' separated list of assembly filenames
```

Reported internal exception:

```
Error SLiM server died before a connection could be established.    assemblies: ';' separated list of assembly filenames
```

That message looks garbled. Don't know if that is a clue.

Runner does start up and run for a bit, per ProcMon.
How else do I debug this?
What specifically is this slim server that it is trying to connect to?

Version:
fitnesse-20151230-standalone.jar
Windows 10

**Comment by jediwhale** [comment]
Try this: http://www.asoftwarecraft.com/2010/01/troubleshooting-with-fitsharp-and.html

**Comment by amolenaar** [comment]
Can we close this issue?

**Comment by b5white** [comment]
Yes.
