### ISSUE TITLE
WhereUsed for pages under a Symbolic Link

### ISSUE THREAD

**Issue by cedclement** [unclebob/fitnesse#925]
Hello, the last release (20160515) seems to have greatly improved the symbolic links management, however I think there is still an issue with the WhereUsed responder : pages located under a Symbolic Link are not beeing found.

For instance, FitNesse.UserGuide.FitNesseWiki.SymbolicLinks?whereUsed shows 2 results, whereas the same page under a Symbolic Link FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.SymbolicLinks?whereUsed the references are not found.

**Comment by amolenaar** [comment]
I think this commit solves it. At least to the extend that you'll find the pages the symlink is related to.
