### ISSUE TITLE
 Login failed for user 'DEV\abc'. ClientConnectionId:a12f7cab-7261-4fa7-8064-ea355f03f883

### ISSUE THREAD

**Issue by maheshrecr** [unclebob/fitnesse#927]
0
down vote
favorite
	

I am trying to coonect sqlserver from dbfit, and getting below error:

com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'DEV\abc'. ClientConnectionId:a12f7cab-7261-4fa7-8064-ea355f03f883 at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216) at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:254) at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:84) at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:2908) at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:2234) at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:41) at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:2220) at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696) at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715) at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1326) at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:991) at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:827) at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1012) at java.sql.DriverManager.getConnection(DriverManager.java:664) at java.sql.DriverManager.getConnection(DriverManager.java:208) at dbfit.api.AbstractDbEnvironment.connect(AbstractDbEnvironment.java:51) at dbfit.environment.SqlServerEnvironment.connect(SqlServerEnvironment.java:53) at dbfit.api.AbstractDbEnvironment.connect(AbstractDbEnvironment.java:78) at dbfit.fixture.DatabaseEnvironment.connect(DatabaseEnvironment.java:52) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at fitlibrary.closure.MethodClosure.invoke(MethodClosure.java:35) at fitlibrary.closure.MethodClosure.invokeTyped(MethodClosure.java:28) at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:77) at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:95) at fitlibrary.closure.CalledMethodTarget.invokeAndWrap(CalledMethodTarget.java:358) at fitlibrary.traverse.workflow.caller.ActionCaller.run(ActionCaller.java:37) at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretRow(DoTraverseInterpreter.java:176) at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretAfterFirstRow(DoTraverseInterpreter.java:66) at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretInFlow(DoTraverseInterpreter.java:151) at fitlibrary.DoFixture.interpretAfterFirstRow(DoFixture.java:47) at fitlibrary.FitLibraryFixture.doTable(FitLibraryFixture.java:83) at dbfit.fixture.DatabaseEnvironment.doTable(DatabaseEnvironment.java:22) at fit.Fixture.interpretFollowingTables(Fixture.java:121) at fit.Fixture.interpretTables(Fixture.java:107) at fit.Fixture.doTables(Fixture.java:81) at fit.FitServer.process(FitServer.java:81) at fit.FitServer.run(FitServer.java:56) at fit.FitServer.main(FitServer.java:41)

is anyone facing similar issue?

Apprecaite your help.

Thanks

**Comment by woodybrood** [comment]
Please ask questions like this on the Yahoo FitNesse group: https://groups.yahoo.com/neo/groups/fitnesse/conversations/topics. That is the place to ask questions about using FitNesse and debugging things about your setup. The community there includes users of more than just the core, which is what this github account is for. When you do, please indicate the OS, the versions of java, FitNesse and dbFit that you are using, as that will help people help you.
