### ISSUE TITLE
Single file page format

### ISSUE THREAD

**Issue by amolenaar** [unclebob/fitnesse#931]
FitNesse is using a directory (the page name) and two files: `content.txt` and `properties.xml` to store a wiki page to disk.

While this works fine if you're only using FitNesse from the wiki, this structure has some downsides when used from IDE's. Version control is also somewhat more laborious with those many files.

I'd like to propose a single file format: `<page-name>.wiki` for a single wiki page.
## Nesting of pages

~~I think here the folder should have the page name and it should contain a default file: `content.wiki`.~~

Do as Gregor says.
## Page properties

Page properties (if it's a test page, symlinks, etc.) will be stored in a "front-matter", just like Jekyll does it (https://jekyllrb.com/docs/frontmatter/). So a wiki page, when opened in a text editor, may look like this:

```

---
Edit
Test

---
Page content comes here
```

To do list:
- [x] Use old and new style pages interchangeably
- [x] Parse Front mapper with current wiki parser
- [x] Create page properties from front matter
- [x] Create page data
- [x] Remove pages and sub pages
- [x] Pages should be listed in the contents section
- [x] Store new file versions
- [x] Create (zip) backup files -> support `VersionsController` interface
- [x] Use new page format as default for new pages

**Comment by ggramlich** [comment]
In general, I think this is a good idea.
Do you think of a single migration step or should it be able to read pages in a backwards compatible way and do an ad hoc conversion?

Concerning the **Nesting of pages** part: As you don't know in advance, whether a page might have subpages, the format you are proposing could cause frequent changes from page-file to folder. What happens, when the last subpage is deleted?
I think, a more consistent solution might be:
Normal <page-name>.wiki file, but as soon as a subpage exists, you add a folder <page-name> and leave the <page-name>.wiki file untouched.

```
|- PageA.wiki
|- PageA (folder)
|  |- PageAA.wiki
|  |- PageAA (folder)
|     |- PageAAA.wiki
|  |- PageAB.wiki
|-PageB.wiki
```

**Comment by amolenaar** [comment]
Thanks for your suggestion on the nested pages. Indeed that makes things a lot simpler.

Regarding migration: I thought of making a new WikiPage type (rename the old one to `OldFileSystemPage` or something), and create new pages using this new structure. One reason to change the extension is to make a clear distinction between the old format (`content.txt`) so that both files can coexist next to each other. Just like we do with `ExternalSuitePage`.

I think that doing migration is tougher since we have to mix the old `FileSystemPage` with the new implementation.

**Comment by jediwhale** [comment]
Great idea - I've been thinking about this for years...

**Comment by woodybrood** [comment]
I’m in favor as well. The boon for users to work in an IDE is huge. The
wiki is valuable, but I was always faster in Vim (though I prefer Sublime
Text now). But having to supply the XML files is a pain.

Also I like the front-matter idea. I’ve started using Jekyll myself and
it’s quite easy to learn. Much easier on the diff tools too.

**Comment by six42** [comment]
Nice idea.

How do you do setup and teardown for a single page?

What naming convention would you use for versions of the files?
Would the front matter still be xml?


I would propose a phased approach and first make the current xml file optional.

Already now the security information is inherited from the parents. So it is optional. 
I would propose the same for the navigation buttons: edit, test, ...

The page type can be deducted from the page name or could be TEST by default. Help text is likely empty anyway. And tags are likely also not used on every page.

This would give you 80 % of the benefit with 20% of the effort.

**Comment by amolenaar** [comment]
Hi @six42,

SetUp and TearDown will be no different.
File versions will be the same as they are now I assume. It's up to the VersionsController implementation to handle that.
The front matter will be yaml(-ish). I think we'll start with a default and enable/disable features via the front matter.

Should the front matter be visible when editing a page through the wiki web interface? I assume not, so the experience for users of this interface is not changed and we have the properties page for that.

**Comment by six42** [comment]
Hi Arjan,

Given the below pages:
Root.page1
Root.page1.child1
Root.page1.SetUp
Root.page2
When you test page1 or child1
Then SetUp will be executed

But When you test page2
SetUp must not be executed

This is the current behaviour.
To keep it every page with a SetUp, TearDown, PageHeader or PageFooter must stay in a folder and can't be converted in a single file page format.

Adding one of these special pages to an existing single file page requires the page to be transitioned in folder format.

I was wondering what the effort would be to support this in the wiki or from an IDE.

**Comment by amolenaar** [comment]
I don't see how this behaviour would change? Only the way pages are stored on disc will change. Apart from that, the page behaviour should be completely the same as with the current file format.

The sub-page will be in a directory with the same name as the wiki page (as @ggramlich outlined above). That way we do not touch the wiki file when adding a sub-page :).

**Comment by six42** [comment]
You are right.With the proposal from @ggramlich this is straightforward. :)

What happens if a folder exists without an identical named .wiki file?
Would the folder be 
- ignored 
- or be part of a test run as a suite page and for the Wiki a html page with a TOC be generated?

I would prefer the second option.

**Comment by woodybrood** [comment]
I like the suite page with automatic table of contents. Click edit and you
get the TOC markup and you can enter text. If you do, a .wiki page will be
created.

**Comment by amolenaar** [comment]
That would be the fancy solution :). But how do you determine it's a folder that can be presented as a suite page? FitNesse should traverse into the folder (only one level or multiple levels?) and think it's okay as soon as it finds a .wiki file (or a folder with a `content.txt`?) somewhere? 

The ExternalSuitePage is actually doing something like that for `.html` pages.

**Comment by amolenaar** [comment]
BTW. I made some progress in this branch: https://github.com/amolenaar/fitnesse/tree/single-file-wiki.

**Comment by six42** [comment]
Any folder would do which has not a content.txt inside and no .wiki file with the same name at the same level.

I follow the layout fitnesse has in git and there are only fitnesse pages under my FitNesseRoot.

Clear segregation of requirements and implementation. :)

I understood you use a different layout. But even if you have code and fitnesse tests in the same folder. Every code should have a test and the suite folders would not be empty ;)

**Comment by amolenaar** [comment]
> I understood you use a different layout. But even if you have code and fitnesse tests in the same folder. > Every code should have a test and the suite folders would not be empty ;)

I do not understand. Do you mean that it's okay to treat empty folders as suite pages?

**Comment by ggramlich** [comment]
@amolenaar Just one small thing that came to my mind, but I am quite sure you already do so:
Please make sure, that the order in the frontmatter is stable.

With the properties.xml it was sometimes a PITA, because the order of tags differed, after creating a page and after editing it; It was hard to see in version control, whether something actually changed.

**Comment by six42** [comment]
Hi Arjan,

Yes you got me right: it's okay to treat empty folders as suite pages!

I did a quick test and it seems that the current implementation of the test system would ignore these.

But in general you are right this is a fancy feature. Not required for a first version.

**Comment by amolenaar** [comment]
I have a working example that reads wiki files like this:
```
---
Suite
Help: help me here
WhereUsed: false
Files: no
SymbolicLinks:
  PageName: .FitNesse
  AnotherPage: .FrontPage
---
!contents
This is a wiki page written with the new file format
```

The front matter contains only the settings that differ from the default set of properties for a page. Therefore this section can be kept small, which is handy if you do a lot of editing outside FitNesse.

**Comment by amolenaar** [comment]
@ggramlich: the entries in the front matter are ordered :).

I wonder if it's useful to do a transformation from the old page format to the new for the pages that we provide (FrontPage, PageHeader, - Footer, TemplateLibrary and FitNesse).

Should there also be an option to stick with the old format? For example when you have some custom scripts that handles wiki content.

**Comment by six42** [comment]
Given I have  a page in the old format
When I save it
Then What happens? It sticks to the old format are is saved in the new?
If it is saved in the new format than the history must be converted as well.

 
Is there not a global flag/property which decides in which format new pages are generated? So people can choose between old and new format?
Similar flag could be there for saving pages.

Long term the old format should be depreciated so that one day the code can be removed.

**Comment by amolenaar** [comment]
> Given I have  a page in the old format
> When I save it
> Then What happens? It sticks to the old format are is saved in the new?
> If it is saved in the new format than the history must be converted as well.

The format of the file is preserved. If the file is already in old format, it will remain in old format. If it's in new format it will remain in new format.

>  Is there not a global flag/property which decides in which format new pages are generated?

I was thinking of implementing this. If you've written some custom scripts that work on the wiki pages it might be desirable to retain that format.

> Long term the old format should be depreciated so that one day the code can be removed.

I suppose. I have no plans for that in the short term.
