### ISSUE TITLE
Option to stop test on any error (Slim)

### ISSUE THREAD

**Issue by mgurov** [unclebob/fitnesse#935]
I would like to be able to instruct the slim server to stop the test on any error/exception that happens during the test run. 

**Motivation.** 

We found that failing tests fast drastically improves maintainability of our large battery of Fitnesse-based integration tests. The problem is that wrapping every Fixture method to propagate the Slim's  [StopTestException](http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ExceptionHandling) is cumbersome and mundane task. It gets extra inconvenient when dealing with standard or fixtures not under your control. Would be nice to have a more sustainable solution.

**Comment by mgurov** [comment]
Would be nice to combine with #684 eventually

**Comment by amolenaar** [comment]
#911 adds the possiblity to tweak method invocation behavior. I think a solution could be to make an `FixtureInteraction` that throws a StopTestException (or StopSuiteException) if an exception is thrown.

I think it's currently not possible via FixtureInteraction.

**Comment by mgurov** [comment]
@amolenaar thank you for the feedback. In fact even the current version of the `FixtureInteraction` helps me to fulfill most of my needs: 
*  I can catch an exception thrown by any fixture method (also not under my control) and wrap it with a `StopTestException`
* I can catch and wrap an exception on instantiation of a constructor-abusive fixture
* #911 will also allow me to wrap a missing error exception eventually

I will still miss ability to stop test on failed checks (say DecisionTable expected/actual mismatch), which will probably be additional motivation to push as much as possible logic to the fixtures. 

The only serious blocker remaining for me is #684 as there are cases when the teardown is very much desired. 

I still feel like an option to stop tests on any exception or error would be a nice out-of-the-box feature, but at the moment my experience with the Fitnesse is not wide enough to keep insisting on that. Feel free to close this ticket.
