### ISSUE TITLE
How to pass or fail a test from custom ColumnFixture written in Java?

### ISSUE THREAD

**Issue by kadimulam** [unclebob/fitnesse#936]
I am writing a custom **ColumnFixture** using Java Class and based on certain results i need to either **pass** or **fail** the test. I should be able to highlight it as **Red** or **Green** and should be able to view the same under **Test History**. How do we achieve this with custom ColumnFixture written in Java?

**Comment by jediwhale** [comment]
In a custom fixture, you pass or fail by marking a cell as right or wrong:

     right(cell);

or

     wrong(cell);

I can't give any more detail without more information about your custom 
fixture.

On 2016-06-15 09:26, kadimulam wrote:
>
> I am writing a custom *ColumnFixture* using Java Class and based on 
> certain results i need to either *pass* or *fail* the test. I should 
> be able to highlight it as *Red* or *Green* and should be able to view 
> the same under *Test History*. How do we achieve this with custom 
> ColumnFixture written in Java?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/unclebob/fitnesse/issues/936>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AACXY8Lm5jGRmyIND9Lu04gA9TgmrvVYks5qMBmhgaJpZM4I2ez3>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>

**Comment by kadimulam** [comment]
Ok...so right and wrong methods are predefined? Where are these methods defined? Also, how can I get cell object? My fixture will be straight forward which will extend ColumnFixture and will define a method which obtains a string from back end. Based on the string response I need to pass or fail a test.

Please advice.

**Comment by six42** [comment]
Hi Kadimulam,

Any specific reason that you use fit and not slim?

Effort to write fixtures in slim is less than in fit.
If you are new to FitNesse then use slim.

The decision table allows to do what you want by writing just two methods without calling or depending on any predefined functions.

http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.DecisionTable

**Comment by jediwhale** [comment]
Can you give an example of a test using your fixture?

right and wrong are defined in Fixture class so will be available in 
your fixture that extends ColumnFixture (which extends Fixture).

There are methods you can override to get a cell object but I need to 
know what your test table will look like.

On 2016-06-15 22:00, kadimulam wrote:
>
> Ok...so right and wrong methods are predefined? Where are these 
> methods defined? Also, how can I get cell object? My fixture will be 
> straight forward which will extend ColumnFixture and will define a 
> method which obtains a string from back end. Based on the string 
> response I need to pass or fail a test.
>
> Please advice.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/unclebob/fitnesse/issues/936#issuecomment-226382806>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AACXY33R4oOYfQ3pHJ8QSLUwEQA0aE5Uks5qMMp2gaJpZM4I2ez3>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>

**Comment by kadimulam** [comment]
My fixture code and test is simple as shown below:

public class FileComparisonFixture extends ColumnFixture{

    private String expectedFileName;
    private String actualFileName;

    public String getExpectedFileName() {
        return expectedFileName;
    }

    public void setExpectedFileName(String expectedFileName) {
        this.expectedFileName = expectedFileName;
    }

    public String getActualFileName() {
        return actualFileName;
    }

    public void setActualFileName(String actualFileName) {
        this.actualFileName = actualFileName;
    }
    
    public List<String> deviationsExists() throws FileNotFoundException, IOException{
        return ComparisonService.compareDataInBackend(expectedFileName, actualFileName);
    }
}


|FileComparisonFixture|
|expectedFileName|actualFileName|deviationsExists?|
|E:/expected.txt      |E:/actual.txt         |   []     |
