### ISSUE TITLE
docs: two minute example refers to old location of Test button, not current

### ISSUE THREAD

**Issue by binkley** [unclebob/fitnesse#937]
The `FitNesse.UserGuide.TwoMinuteExample` page refers to "See the Test button in the upper-right corner?" but with 20160515 (earlier?) Test is actually in the menu bar directly next to the FitNesse logo, not in the upper right.

(I'd fix this myself, but for good reasons there's no Edit for me, Mr. J Random Public.)

**Comment by amolenaar** [comment]
It's easy to fix: just add '?edit' to the url and you'll open up an edit screen :)

**Comment by amolenaar** [comment]
Fixed. Thanks :)

**Comment by binkley** [comment]
Thanks @amolenaar for the `?edit` tip -- I'll try it next time I spot a typo.
