### ISSUE TITLE
hidden directories are shown with !content

### ISSUE THREAD

**Issue by mike-lam** [unclebob/fitnesse#941]
Hidden directories are shown on the wiki pages when using !content.

We recently upgraded fitnesse from version 20111026  to version 20151230 which we used on Windows 7 with CVS for versioning the fitnesse wiki. The !content on version 2011 would not show the cvs directories that but now on 2015 our fitnesse wiki pages contains references to cvs pages.

**Comment by amolenaar** [comment]
Indeed, pages names are less restrictive, therefore files like `CVS` are supported.

Just maybe we should allow to blacklist such files. 

(Subversion `.svn` files are not a problem, since they start with a dot, which is not considered a valid wiki page name).

**Comment by mike-lam** [comment]
I believe the method list in class DiskFileSystem  
could be changed with 

    return path.isDirectory() ? path.list(filter) : new String[] {};

where filter is a FilenameFilter that checks for the hidden attribute.



Also, if I were to make such a change and distribute the new jar strictly within my organisation would that be against the license agreement?

**Comment by amolenaar** [comment]
That sounds okay. Only looking for a hidden flag is not sufficient, as Unix does not have such a file attribute
