### ISSUE TITLE
Possibility to launch Table fixtures from script and scenario

### ISSUE THREAD

**Issue by testgae** [unclebob/fitnesse#942]

**Comment by amolenaar** [comment]
Can you please add a description for this issue? What do you want to achieve?

**Comment by testgae** [comment]
The idea is to have like a routine that aggregates several Table fixture usages.

**Comment by woodybrood** [comment]
How about an example? Can you show us what you would want that to look
like? And what you would want the outcome to be like?

Potentially the same thing can be done with script tables and existing
functionality.

**Comment by testgae** [comment]
So that we can have declared a scenario
|scenario|scenario1 _ _|arg1,arg2|
|begin fixture|
|Table: Fixture1|@arg1|
|Cell11|@arg2|
|Cell21|Cell22|
...
|end fixture|
|begin fixture|
|Table: Fixture2|@arg2|
|Cell11|@arg1|
|Cell21|Cell22|
...
|end fixture|

and then call it
|scenario1|
|arg1|arg2|
|10|20|
|30|40|
...

Instead of copy pasting Fixture1 and Fixture2

**Comment by testgae** [comment]
> Potentially the same thing can be done with script tables and existing
> functionality.

Sure, but I wasn't able to call a Table fixture from within script or scenario table. I would appreciate if you can show the example. :-)

**Comment by woodybrood** [comment]
It’s been a while since I’ve done it and I can’t dig in during working
hours, but it is possible to layer things kinda deep. So you are calling
scenarios from scenarios. So there might be a way, but I can’t try until
later.

**Comment by amolenaar** [comment]
I'm not sure I get what you mean. In a table you would normally put some (key-) examples that describe a feature of the application your building. This allows you to easily communicate the intent of a feature and discuss it (e.g. with non-programmer people).

It looks to me like you want to do something in FitNesse, that comes close to programming. You're better of doing in a programming language like Java or C#. (The same thing happens when you use scenario's extensively, btw.)

You may want to look at scenario tables. Nesting arbitrary tables in one another is not possible.

**Comment by woodybrood** [comment]
@amolenaar I generally agree with you. At my previous employer we had a rather unique system of scenario tables that we called either in decision table or script table style. Sometimes we got a few layers deep and it did approach being more programmers-esque, but it worked in that context. So not saying the approach is ideal in most cases.

**Comment by testgae** [comment]
> It looks to me like you want to do something in FitNesse, that comes close to programming.

Exactly :-) I want to be able to create fully reusable scenarios in Fitnesse. It's a kind of scripting and sometimes it's more flexible than programming.
And I see no problem with that as there is already a scenario fixture. It just needs to be enhanced.

So, do you have any idea how this can be done ? If no, can I implement a pull request for this ?

**Comment by testgae** [comment]
> You may want to look at scenario tables. Nesting arbitrary tables in one another is not possible.

Yes. I want to be able to nest arbitrary table into scenario fixture. Can I implement a pull request for this ?

**Comment by amolenaar** [comment]
I still think you should keep the fitnesse pages clean and descriptive and do the code in a programming language, not in FitNesse and not in scenario tables.

FitNesse is not an IDE and you'll create yourself a maintenance nightmare.

Of course you're free to create a table like that. You can add custom tables to FitNesse. You can keep it as a plugin. I'm not inclined to add it to FitNesse's core: it adds complexity that (I hope) most people do not need.

For an example of how such a plugin could work I'd recommend looking at @fhoeben's FitNesse plugins: https://github.com/fhoeben/hsac-fitnesse-plugin, esp. the table types.

I'm more than happy to add a reference on the plugins page on the website.
