### ISSUE TITLE
FitNesse-project fails to build in Eclipse (due to ant dependency?)

### ISSUE THREAD

**Issue by hansjoachim** [unclebob/fitnesse#946]
I followed the instructions in the readme for importing FitNesse into Eclipse (Neon). First impression is that it was a lot more straight-forward to import the gradle project compared to earlier. Things are mostly working as expected, but some files fail to build. The affected files are all located in the package fitnesseMain.ant. 

For instance `ExecuteFitnesseTestsTask` fails to find the `org.apache.tools.ant.*` imports. The same file is able to resolve apache commons lang imports, and the other files in the project don't seem to have any import problems, so it looks like these files fails to find the ant dependency.

Am I missing a step, or might something in the dependency configuration be causing the problem? I'll be happy to provide any additional information or output if needed.

I also set up the project in IntelliJ, but didn't run into similar issues there.

**Comment by amolenaar** [comment]
That's odd. Ant is listed as a dependency.

**Comment by hansjoachim** [comment]
I did some more testing, with latest master on an Ubuntu Yakkety vm with a clean install of Eclipse 4.6 (Neon). When importing FitNesse as per the readme, this is the depencies listed in the Eclipse project:
![dependencies](https://cloud.githubusercontent.com/assets/3002493/16896752/e2708962-4b9c-11e6-8621-394463430dcc.png)

I assume the gradle cache they are located in is the local repo, so I tried to see if I could find any ant jars close to for instance `.gradle/caches/modules-2/files-2.1/org.apache.velocity/velocity/1.7/2ceb567b8f3f21118ecdec129fe1271dbc09aa7a/velocity-1.7.jar`. I'm not sure how to interpret the results, since I found a couple of matches but they are either an older version number or located in a different directory;
```
$ find .gradle/  | grep -e "ant.*jar.*"
.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-ant-tasks/2.1.3/b09be554228d66d208e5fef5266844aacf443abc/maven-ant-tasks-2.1.3.jar
.gradle/caches/modules-2/files-2.1/org.apache.ant/ant-launcher/1.8.0/8b53ba16fa62fb1034da8f1de200ddc407c8381/ant-launcher-1.8.0.jar
.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.8.0/7b456ca6b93900f96e58cc8371f03d90a9c1c8d1/ant-1.8.0.jar
.gradle/wrapper/dists/gradle-2.13-all/1b9wlm73elu4cqnbc0rk7r7qn/gradle-2.13/lib/plugins/gradle-antlr-2.13.jar
.gradle/wrapper/dists/gradle-2.13-all/1b9wlm73elu4cqnbc0rk7r7qn/gradle-2.13/lib/ant-1.9.6.jar
.gradle/wrapper/dists/gradle-2.13-all/1b9wlm73elu4cqnbc0rk7r7qn/gradle-2.13/lib/ant-launcher-1.9.6.jar
.gradle/wrapper/dists/gradle-2.13-all/1b9wlm73elu4cqnbc0rk7r7qn/gradle-2.13/samples/userguide/ant/useAntType/libs/test.jar
```

I haven't experimented with it, but I see that ant is marked as an optional dependency in `build.gradle`. I don't know why, but maybe that has something to do with it? (Though on the other hand, JUnit is optional too and that one is listed...)

**Comment by amolenaar** [comment]
Can you give it a try with the current master?

I did some changes to the way the build dependencies were structured. Now Ant and jUnit should be added as compile dependencies in IDE's.

**Comment by hansjoachim** [comment]
Checked again with latest master and it works as expected now.

**Comment by amolenaar** [comment]
Cool! Thanks for the feedback.
