### ISSUE TITLE
Graceful naming - Ignore wiki pages

### ISSUE THREAD

**Issue by dacoder1987** [unclebob/fitnesse#963]
Hi,

We have a requirement where we would like to ignore the graceful naming for suite/test pages in FitNesse. I see the below comment in the GracefulNamer class and wanted to understand if this would be fixed anytime soon?

`//todo OH FRATZ!  Graceful names was for java method and instance names, not wiki page names!  Get all this wiki page name stuff out of here.`

Thanks.

**Comment by amolenaar** [comment]
By default names are not printed "gracefully".

The comment is old (2009) and I think it can be removed. E.i. we can keep the graceful naming. you can steer this variable with the variable `REGRACE_LINK`.

I committed cec6edf52f347086fd8b1b1be1f5c857eca45391, which removes the comment.

**Comment by dacoder1987** [comment]
Thanks for the reply closing the issue.
