### ISSUE TITLE
SliM execute fixture constructor based on parameters types

### ISSUE THREAD

**Issue by george-toma** [unclebob/fitnesse#966]
Hi folks,

While using FitNesse SliM protocol, I encountered a "nice to have feature", the fixture constructor call should be based on the parameters types.
E.g. : 
- |Query:my business fixture|Michael|5|
  -- should execute the constructor "trigger X "
- |Query:my business fixture|20120210|Adela|
  -- should execute the constructor "trigger Y"
- |Query:my business fixture|20120210|10|
  -- should execute the constructor "trigger Z"

And the Java class : 
class MyBusinessFixture{

public MyBusinessFixture(String s, String p){
...trigger X....
}
public MyBusinessFixture(Date date, String p){
...trigger Y....
}

public MyBusinessFixture(Date date, Integer i ){
...trigger Z....
}
...my methods...
}

In the current code, an iteration is done over all class constructors, and the first match on the number of parameters is picked up.

**I would like to implement this fix** by reusing the current code, mostly ConverterRegistry.java, and the fix should always pick up the constructor based on the parameters types ( e.g. 1 can be mapped to a String and to an Integer, but would seems logical to pick up the constructor with an Integer parameter).

Can someone provide me a feedback regarding the fix I want to do ?

Regards,
George

**Comment by six42** [comment]
Hi @george-toma ,
I think this would be a nice and useful feature.
I am not familiar with this part of the code base so I can't comment on your approch.
Go ahead.

Six42
