### ISSUE TITLE
Override String Converter

### ISSUE THREAD

**Issue by dacoder1987** [unclebob/fitnesse#975]
Hi,

I am trying to override the Slim String converter in ConverterRegistry so the Fitnesse UI displays the given string value as hyperlink if it contains a specific keyword.Though the registry overrides the default String converter with mine I don't see the values being converted as expected. Please let me know what I am missing here?

Thanks.

**Comment by amolenaar** [comment]
Can you elaborate a little more? e.g. show code examples, configuration.

**Comment by dacoder1987** [comment]
Hi,

I achieved what I wanted by using a custom Symbol Type as I was dealing with a List and read in the documentation later that Converters are not applied for List.

Thanks.
