### ISSUE TITLE
Random Defines

### ISSUE THREAD

**Issue by JeremyCarlsten** [unclebob/fitnesse#986]
I'm not sure if it's possible, but I would imagine it working a lot like the today() function currently works. 
What if we had a random function available in the defines? So in your markup you can provide 

!define randomInt(5)  and it would generate five random digits
!define random("one", "two","Three"...)  and it would randomly pick from the list. 

Adding functions like this would allow e2e testing to randomly insert data into our database but reference it later in our test, perhaps an AccountID that we need to later search by?

Additionally, (in my case) it would allow me to setup fitnesse tests to run in parallel with, almost always, unique ids for my data.

I haven't taken a look at the code but I suspect it would be relatively easy to implement by doing something similar to the 'today()' code. 

What do you all think?

**Comment by keetron** [comment]
The HSAC plugin does this and some other neato stuff:
https://github.com/fhoeben/hsac-fitnesse-plugin
We use it in our implementation exactly how you mention.

**Comment by JeremyCarlsten** [comment]
Perhaps I'll check it out monday, thanks! If it's not quite what I'm looking for I can always fork it and tweek it to my liking. If there is anything that fitnesse it's self needs  feel free to shoot me an email, I'd love to help.

jeremy@jeremycarlsten.com

**Comment by JeremyCarlsten** [comment]
@keetron , after installing the plugin it appears to be generating multiple values. 

$define personId { !randomBSN }

|setup data|
|create person with Id|${personId}|

|some fixture|
|search for|${personId}|

In this case the personId's printed on the wiki are entirely different. Is this the behavior you would expect? 

p.s. I posted the same question in their [issues](https://github.com/fhoeben/hsac-fitnesse-plugin/issues/10).

**Comment by keetron** [comment]
And it seems there is an extensive answer there :-)

**Comment by JeremyCarlsten** [comment]
He beat you to it!, I posted them about the same time. Thanks again.
