### ISSUE TITLE
Presence of .html files in 'files section' breaks wiki

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#987]
When I have .html files in my files section, start FitNesse version 20161106, the root page (and no other pages) can be displayed.
All pages accessed via my browser give "Page doesn’t exist"...

If I first start FitNesse without the .html files all works perfectly. If I then add a single .html file, FitNesse reports "Page doesn’t exist" for all pages. When I rename the file to .HTML normal functionality is restored.

**Comment by staniere** [comment]
Hello, 
will it be possible to keep static html pages in \FitNesseRoot\files\ folder in next release milestone ?
or we will have to clean it to migrate ? (I have lot of html, pages in my folder and it would be great to be able to keep it)
I did not understand what is the new .wiki mode and how it could have an impact on html pages.

**Comment by keetron** [comment]
Hi Staniere,

As you can see in fhoebens reply, when renaming those to .HTML as opposed to .html, everything works fine.
Don't ask me why it works, but can you check if this is a method for you to keep all your documents in place? 

Quick rename can be done using the idea plugin for intellij:
https://plugins.jetbrains.com/idea/plugin/3774-idea-file-rename
But this is only one tool of course.

**Comment by amolenaar** [comment]
@staniere This still needs some work indeed. I haven't found inspiration yet to look into it. It should be fixed somewhere in the area of the `FileSystemPageFactory` I suppose.

**Comment by staniere** [comment]
hello, 
thank you @keetron for your tool. 
@amolenaar, for information, my static pages named *.htm work fine (as *.HTML).
but i have still some *.html one (which are automatically generated, so it will take a little more time to be able to migrate for me)
i will try to have a look to FileSystemPageFactory  (if i find some time to download git and to understand something to fitnesse sourcecode :) )

**Comment by amolenaar** [comment]
The "problem" here is that the FileSystemPageFactory is not aware of how deep it is in the wiki tree. In itself that's a good thing, but it should refuse to dive into the `files` folder -- if on op level.

It only looks for `.html` files (lowercase), because of the `ExternalSuitePageFactory`.

**Comment by keetron** [comment]
Quick comment on how to look into the sourcecode superfast:
download intellij community edition here: https://www.jetbrains.com/idea/download/
in the welcome screen, checkout from sourcecontrol, github, past this link: https://github.com/unclebob/fitnesse.git
now use ctrl-shft-f to find whatever phrase you want.

Not sure if you need git installed, if yes, grab from here: https://git-scm.com/downloads

**Comment by fhoeben** [comment]
Looking at the source I believe I found another (simpler) workaround: ensure a `_root.wiki` file exists in your FitNesseRoot. (This is actually the location linked to by the 'root' link at the bottom of each FitNesse page.) It may be empty.

@amolenaar maybe just add this file to the standard Root created when FitNesse extracts its pages?

This will cause the `RootWikiFilePageFactory` to be used, which is also the default if no other factory is considered a match (which seems 'normal' behaviour in a fresh installation's FitNesseRoot)

**Comment by amolenaar** [comment]
@fhoeben Can it really be that simple? :D

**Comment by fhoeben** [comment]
Seems to work for my installation....
Not sure whether we should have content.txt/properties.xml, or _root.wiki....
