### ISSUE TITLE
Slim process dies without any error in log with FitNesse 20161106

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#989]
I have a test, using Slim, which works with the previous version of 20160618. It also works with version 20161106 if I run it via jUnit using `FitNesseRunner` with Slim in-process. It does not work when started from the wiki (separate Java process for Slim), on Windows 7.

I just get a message that the communication with the Slim process was lost, and in the execution log I see no indication of what went wrong. The Slim process just seems to die, without any error output.
A part of the test is executed, the SuiteSetUp and SetUp, but Slim dies on the real test page. 
I've placed logging (to standard error) in my fixture code and I see that in the output of my SetUp pages, but the constructor of the fixture of the first (script) table never seems to be called. So I assume something happens in the code between the wiki and the Slim process before my fixture is even created.

I have no clue what the cause is, but processes stopping without any indication of what went wrong are very annoying....

**Comment by fhoeben** [comment]
It turns out there was 'something' in the execution log. I found that the slim process died with exit code 98. Which I tracked in the source to mean that an exception occurred. Unfortunately the logging of the exception did not work (as I did not see that in the execution log).

When I configure the connection to the slim process to be done on a random free port (i.e. I added `!define slim.port {0}` to the root of my suite, where I also configure the test system to be slim). The test works again.

My conclusion is that something is going wrong with the 'pipe based' connection between FitNesse and Slim. And logging on exception at the level does not end up in the execution log.

**Comment by amolenaar** [comment]
Can we replay this scenario?

**Comment by fhoeben** [comment]
I haven't been able to make a short sample that shows the problem. I have encountered the problem in multiple test sets in my current projects. All tests only show the problem on Windows 7 when started from the wiki (i.e. not when run on a build server using the jUnit runner on Linux).
The problem goes away on downgrade of FitNesse or when I set the slim.port variable.

**Comment by fhoeben** [comment]
I just checked #995 is the same problem as this issue. Adding the `!define slim.port {0}` also fixed the problem with the euro symbol

**Comment by keetron** [comment]
Gonna do that right away on Saturday night so I wont have to remember until Monday...

**Comment by fhoeben** [comment]
I believe the problem comes from the new 'default usage of console input/output' to communicate between wiki and Slim. On Windows the console does not support Unicode, at least not by default (see for instance http://stackoverflow.com/questions/20386335/printing-out-unicode-from-java-code-issue-in-windows-console). 
Maybe Slim should only use console on non-windows platforms (e.g. check via `System.getProperty("os.name")` or use Apache Commons' [`SystemUtils.IS_OS_WINDOWS`](http://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/SystemUtils.html#IS_OS_WINDOWS)), or wrap ome print writer/reader with explicit encoding around the console streams.

**Comment by amolenaar** [comment]
The Stackoverflow item suggested adding explicit encoding (in our case that would be UTF-8). The current implementation does not force file encoding on both ends. As an alternative we an URL-encode the whole lot.

I would prefer that over using a socket on windows and a pipe on unix.

**Comment by fhoeben** [comment]
Grr, unable to reproduce the problem on Windows 10. The multibyte test does cause stack traces in the console (when run from Edge), but the connection to Slim is not lost.
