### ISSUE TITLE
New wiki format, Git and line-endings

### ISSUE THREAD

**Issue by keetron** [unclebob/fitnesse#999]
When creating a new page using the latest FitNesse version, pushing said file to Git, removing the branch and pulling the branch back to local, the properties at the beginning of the file are no longer seen as properties. The result is the page is not viewed as a test but as a Static page. The Help text is also gone and in FitNesse the properties are displayed with a strike-through.

We suspect this is due to line endings changing when going to Git and back and the latest FitNesse version being somewhat intolerant to this.
Attached two files, a before and an after. I hope the zipping didn't mess up my point :-)

[wikifiles.zip](https://github.com/unclebob/fitnesse/files/638777/wikifiles.zip)

**Comment by amolenaar** [comment]
Thanks for the report. You're working on Windows?

**Comment by keetron** [comment]
We are using Windows 7 as a dev machine, the git server is a Linux machine.
The description was to specifically point out that only when pushing and pulling to remote, this happens.
For now, until this is resolved I'll set all updated projects back to the old-style wiki pages with folders so that no tests are left behind by Jenkins.

**Comment by fhoeben** [comment]
It appears a '.gitattributes' file in the FitNesseRoot directory also works, if we explicitly set all .wiki files to have only 'lf' line endings (and not Windows standard 'crlf'). 

So inside the FitNesseRoot directory we can add a '.gitattributes' file with contents:
```
*.wiki text eol=lf
```
This seems to leave the new style wiki pages in working condition. 

Is there indeed a requirement in the .wiki format for the line endings (for the entire file, or the first part of the file containing the properties)?

**Comment by keetron** [comment]
With commit d559513 this should be fixed.
